### PR TITLE
[SP-1984] Backport of PDI-12650 - GetDataFromXml Xpath loop disabled using Single Threader

### PR DESCRIPTION
**Pull request by MikhailHubanau**
@brosander @mattyb149 please review.

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please at earliest convenience. This ticket is included in the August SP, that ends this week

**Comment by brosander** [comment]
@akhayrutdinov please ensure that there are no checkstyle violations and that all unit tests pass

**Comment by brosander** [comment]
@MikhailHubanau  @akhayrutdinov  please ensure that there are no checkstyle violations and that all unit tests pass

**Comment by akhayrutdinov** [comment]
@MikhailHubanau, close this PR please

**Pull request closed without merging**
