### PR TITLE
[BACKLOG-6496] - Database lookup step with "=" comparator fails on 6.1

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- use only those fields that are needed for look-up (fix an error introduced in PDI-3314)
- add a test

@brosander, @deinspanjer, review it please

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookup.java
  engine/test-src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupUTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File engine/test-src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupUTest.java
1. Message: Using a static member import should be avoided - java.util.Collections.singletonList. at Line: 59 Column: None
2. Message: Using a static member import should be avoided - org.hamcrest.CoreMatchers.instanceOf. at Line: 60 Column: None
3. Message: Using a static member import should be avoided - org.hamcrest.CoreMatchers.is. at Line: 61 Column: None
4. Message: Using a static member import should be avoided - org.junit.Assert.assertArrayEquals. at Line: 62 Column: None
5. Message: Using a static member import should be avoided - org.junit.Assert.assertNotNull. at Line: 63 Column: None
6. Message: Using a static member import should be avoided - org.junit.Assert.assertThat. at Line: 64 Column: None
7. Message: Using a static member import should be avoided - org.mockito.Matchers.any. at Line: 65 Column: None
8. Message: Using a static member import should be avoided - org.mockito.Matchers.anyInt. at Line: 66 Column: None
9. Message: Using a static member import should be avoided - org.mockito.Matchers.anyBoolean. at Line: 67 Column: None
10. Message: Using a static member import should be avoided - org.mockito.Matchers.anyString. at Line: 68 Column: None
11. Message: Using a static member import should be avoided - org.mockito.Matchers.eq. at Line: 69 Column: None
12. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 70 Column: None









Unit test coverage change:
============
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange :**-0.17%**
    
org.pentaho.di.trans.steps.databaselookup.DatabaseLookup:
 * instructionPercentCoverageChange : +0.45%
 * branchPercentCoverageChange : +0.52%
 * linePercentCoverageChange : +0.54%
 * complexityPercentCoverageChange : +1.16%
 * methodPercentCoverageChange : +1.10%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-1.97%**
    
org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * instructionPercentCoverageChange :**-2.43%**
 * branchPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-2.95%**
 * complexityPercentCoverageChange :**-0.69%**
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange :**-0.19%**
 * linePercentCoverageChange :**-0.27%**

**Comment by akhayrutdinov** [comment]
@brosander, I see static import violations in test classes. Are they correct? IMO, for Mockito they should be suppressed. @dkincade, @lucboudreau, can you clarify it please?

**Comment by dkincade** [comment]
Is there a reason why they need to be used? If so then I would allow for test cases but I would prefer they not be used without a good reason.

Thanks,
David

On Feb 5, 2016, at 6:31 AM, Andrey Khayrutdinov <notifications@github.com<mailto:notifications@github.com>> wrote:


@brosander<https://github.com/brosander>, I see static import violations in test classes. Are they correct? IMO, for Mockito they should be suppressed. @dkincade<https://github.com/dkincade>, @lucboudreau<https://github.com/lucboudreau>, can you clarify it please?

-

**Comment by akhayrutdinov** [comment]
@dkincade, Mockito's API is based on static imports, they make it concise and easy-to-read. Compare:
```
verify(a, atLeastOnce()).call()
``` 
and
```
Mockito.verify(a, Mockito.atLeastOnce()).call()
``` 
I do think the first is better. moreover, everyone use static imports in these cases.
The same happens with JUnit's `Assert` class

**Comment by akhayrutdinov** [comment]
@brosander, review it please. I still insist Checkstyle settings should be amended to let using static imports either of several classes (Mockito, Assert, CoreMatchers, etc.) or of any class in tests

**Comment by brosander** [comment]
Hey Andrey, I'm on PTO today.  If it's urgent please contact womprats or r2d2.

On Feb 8, 2016 2:46 AM, Andrey Khayrutdinov <notifications@github.com> wrote:

@brosander<https://github.com/brosander>, review it please. I still insist Checkstyle settings should be amended to let using static imports either of several classes (Mockito, Assert, CoreMatchers, etc.) or of any class in tests

-

**Comment by akhayrutdinov** [comment]
@brosander, ok, have fun :)
That is not very urgent but should be processed before 6.1 is released

**Pull request merged**
