### PR TITLE
[PDI-13875] Update Google Analytics plugin to v3 APIs

### PR DESCRIPTION
**Pull request by mattyb149**
forward port (via cherry-pick) of 3 PRs from the 5.4 branch

### CODE REVIEW

**Comment by lucboudreau** [comment]
Should this wait before merging on the master->future merge?

**Comment by MrMauricioLeite** [comment]
Merge it, there is a lot of ppl looking fowarding for this step to work again.

**Comment by mattyb149** [comment]
@lucboudreau I think it should go before, so that the forward-port to 6.0 is automatic. I am testing now locally to make sure it will work in master, then it should port without trouble to future.

**Comment by mattyb149** [comment]
Self-merge with approval from @dkincade , dev tested successfully in master

**Pull request merged**
