### PR TITLE
[PDI-8936] JobMap - Inconsistent synchronization can lead to corruption

### PR DESCRIPTION
**Pull request by IvanNikolaychuk**
- Added synchronization of non-synchronized methods, touching common resources
- Refactored synchronization-area in some methods
- Removed unnecessary synchronization on the calls of  already-synchronized method
- Test written
- Checkstyle applied

Please, note, that test is placed in project-core test folder, where all concurrent tests (and concurrent-test executer) are located.

@brosander, review it please

### CODE REVIEW

**Comment by IvanNikolaychuk** [comment]
@brosander, review it please

**Comment by IvanNikolaychuk** [comment]
@brosander, Merry Christmas! 
Review it please

**Comment by brosander** [comment]
@IvanNikolaychuk getJob and getConfiguration look like they may have different behavior after change, what if the map changes after the sync block and before looping over the arraylist?

**Comment by IvanNikolaychuk** [comment]
@brosander, true, updated

**Comment by IvanNikolaychuk** [comment]
@brosander, could you please review it?

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -f engine/build.xml -Djunit.jvmargs=-XX:PermSize=256m clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/www/AddExportServlet.java
  engine/src/org/pentaho/di/www/AddJobServlet.java
  engine/src/org/pentaho/di/www/BaseJobServlet.java
  engine/src/org/pentaho/di/www/CarteDelegationHandler.java
  engine/src/org/pentaho/di/www/JobMap.java
  engine/src/org/pentaho/di/www/RunJobServlet.java
  engine/src/org/pentaho/di/www/StartJobServlet.java
  engine/src/org/pentaho/di/www/jaxrs/JobResource.java
  test/org/pentaho/di/concurrency/JobMapConcurrencyTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File engine/src/org/pentaho/di/www/AddExportServlet.java
1. Message: '<' is not followed by whitespace. at Line: 267 Column: 15
2. Message: '<' is not preceded with whitespace. at Line: 267 Column: 14
3. Message: '>' is not preceded with whitespace. at Line: 267 Column: 29

File engine/src/org/pentaho/di/www/AddJobServlet.java
1. Message: '<' is not followed by whitespace. at Line: 292 Column: 49
2. Message: '<' is not preceded with whitespace. at Line: 292 Column: 48
3. Message: '>' is not preceded with whitespace. at Line: 292 Column: 63

File engine/src/org/pentaho/di/www/BaseJobServlet.java
1. Message: '<' is not followed by whitespace. at Line: 181 Column: 67
2. Message: '<' is not preceded with whitespace. at Line: 181 Column: 66
3. Message: '>' is not preceded with whitespace. at Line: 181 Column: 81
4. Message: '<' is not followed by whitespace. at Line: 190 Column: 48
5. Message: '<' is not preceded with whitespace. at Line: 190 Column: 47
6. Message: '>' is not preceded with whitespace. at Line: 190 Column: 62

File engine/src/org/pentaho/di/www/JobMap.java
1. Message: '<' is not followed by whitespace. at Line: 118 Column: 28
2. Message: '<' is not preceded with whitespace. at Line: 118 Column: 27
3. Message: '>' is not preceded with whitespace. at Line: 118 Column: 44
4. Message: '<' is not followed by whitespace. at Line: 119 Column: 26
5. Message: '<' is not preceded with whitespace. at Line: 119 Column: 25
6. Message: '>' is not followed by whitespace. at Line: 119 Column: 27
7. Message: '>' is not preceded with whitespace. at Line: 119 Column: 26
8. Message: '<' is not followed by whitespace. at Line: 43 Column: 21
9. Message: '<' is not preceded with whitespace. at Line: 43 Column: 20
10. Message: '>' is not preceded with whitespace. at Line: 43 Column: 42
11. Message: '<' is not followed by whitespace. at Line: 44 Column: 21
12. Message: '<' is not preceded with whitespace. at Line: 44 Column: 20
13. Message: '>' is not preceded with whitespace. at Line: 44 Column: 55
14. Message: '<' is not followed by whitespace. at Line: 49 Column: 26
15. Message: '<' is not preceded with whitespace. at Line: 49 Column: 25
16. Message: '>' is not followed by whitespace. at Line: 49 Column: 27
17. Message: '>' is not preceded with whitespace. at Line: 49 Column: 26
18. Message: '<' is not followed by whitespace. at Line: 50 Column: 36
19. Message: '<' is not preceded with whitespace. at Line: 50 Column: 35
20. Message: '>' is not followed by whitespace. at Line: 50 Column: 37
21. Message: '>' is not preceded with whitespace. at Line: 50 Column: 36

File engine/src/org/pentaho/di/www/RunJobServlet.java
1. Message: '<' is not followed by whitespace. at Line: 179 Column: 19
2. Message: '<' is not preceded with whitespace. at Line: 179 Column: 18
3. Message: '>' is not preceded with whitespace. at Line: 179 Column: 20
4. Message: '?' is not followed by whitespace. at Line: 179 Column: 20
5. Message: '?' is not preceded with whitespace. at Line: 179 Column: 19
6. Message: '<' is not followed by whitespace. at Line: 55 Column: 24
7. Message: '<' is not preceded with whitespace. at Line: 55 Column: 23
8. Message: '>' is not preceded with whitespace. at Line: 55 Column: 25
9. Message: '?' is not followed by whitespace. at Line: 55 Column: 25
10. Message: '?' is not preceded with whitespace. at Line: 55 Column: 24

File engine/src/org/pentaho/di/www/StartJobServlet.java
1. Message: '<' is not followed by whitespace. at Line: 47 Column: 24
2. Message: '<' is not preceded with whitespace. at Line: 47 Column: 23
3. Message: '>' is not preceded with whitespace. at Line: 47 Column: 25
4. Message: '?' is not followed by whitespace. at Line: 47 Column: 25
5. Message: '?' is not preceded with whitespace. at Line: 47 Column: 24



Newly Broken Tests:
-----------------
org.pentaho.di.trans.steps.textfileinput.TextFileInputMetaLoadSaveTest.repositorySerialization: java.lang.RuntimeException
```
java.lang.RuntimeException: Error validating dateFormatLocale
	at org.pentaho.di.job.entry.loadSave.LoadSaveBase.validateLoadedMeta(LoadSaveBase.java:128)
	at org.pentaho.di.job.entry.loadSave.TransStepLoadSaveTester.testRepoRoundTrip(TransStepLoadSaveTester.java:79)
	at org.pentaho.di.trans.steps.textfileinput.TextFileInputMetaLoadSaveTest.repositorySerialization(TextFileInputMetaLoadSaveTest.java:162)
Caused by: org.pentaho.di.core.exception.KettleException: 
Attribute dateFormatLocale started with value no_NO_NY ended with value no_no_ny

	at org.pentaho.di.job.entry.loadSave.LoadSaveBase.validateLoadedMeta(LoadSaveBase.java:124)

```





Unit test coverage change:
============
org.pentaho.di.trans.Trans:
 * instructionPercentCoverageChange :**-0.09%**
 * branchPercentCoverageChange :**-0.10%**
 * linePercentCoverageChange :**-0.11%**
 * complexityPercentCoverageChange :**-0.14%**
    
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange : +0.08%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange : +0.53%
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange :**-0.28%**
 * branchPercentCoverageChange :**-3.33%**
 * complexityPercentCoverageChange :**-1.85%**
    
org.pentaho.di.core.lifecycle.KettleLifecycleSupport:
 * branchPercentCoverageChange :**-8.33%**
 * complexityPercentCoverageChange :**-9.09%**
    
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange :**-0.17%**
    
org.pentaho.di.trans.steps.randomvalue.RandomValueMeta:
 * instructionPercentCoverageChange : +0.15%
 * branchPercentCoverageChange : +2.08%
 * complexityPercentCoverageChange : +2.13%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange :**-0.19%**
 * linePercentCoverageChange :**-0.27%**
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange :**-0.18%**

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -f engine/build.xml -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/www/AddExportServlet.java
  engine/src/org/pentaho/di/www/AddJobServlet.java
  engine/src/org/pentaho/di/www/BaseJobServlet.java
  engine/src/org/pentaho/di/www/CarteDelegationHandler.java
  engine/src/org/pentaho/di/www/JobMap.java
  engine/src/org/pentaho/di/www/RunJobServlet.java
  engine/src/org/pentaho/di/www/StartJobServlet.java
  engine/src/org/pentaho/di/www/jaxrs/JobResource.java
  test/org/pentaho/di/concurrency/JobMapConcurrencyTest.java










Unit test coverage change:
============
org.pentaho.di.trans.steps.randomvalue.RandomValueMeta:
 * instructionPercentCoverageChange :**-0.15%**
 * branchPercentCoverageChange :**-2.08%**
 * complexityPercentCoverageChange :**-2.13%**
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-1.97%**
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange : +7.14%
 * complexityPercentCoverageChange : +7.69%
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange : +0.18%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +0.19%
 * linePercentCoverageChange : +0.27%

**Pull request merged**
