### PR TITLE
[PDI-18781] - Const.splitString method doesn't work properly if "spli…

### PR DESCRIPTION
**Pull request by anilsrivastava1202**
…tString" uses delimiter and "splitString" contains nested escaped enclosure within data.

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4836**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7443/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by anilsrivastava1202** [comment]
@ssamora @smmribeiro @pentaho-lmartins @ppatricio  could you please help me with whom should I ask to review it?

I have created a Jira for the same: https://jira.pentaho.com/browse/PDI-18781

**Comment by smmribeiro** [comment]
Your issue is now assigned to Triage.
They'll evaluate it and it'll enter our circuit!

**Comment by pentaho-lmartins** [comment]
This was fixed with #7538 for 9.1 GA.

**Pull request closed without merging**
