### PR TITLE
PDI-12899 Text File Input - Disabled "Allow breaks in enclosed fields"

### PR DESCRIPTION
**Pull request by KoljaTM**
- removed unused option

### CODE REVIEW

**Comment by buildguy** [comment]
### :gear: Build finished in 9m 7s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1096|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/1/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 13m 55s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1096|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/2/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 13m 26s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1096|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/3/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 15m 32s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1099|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/4/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 15m 9s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1100|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/5/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 14m 38s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1100|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/6/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 14m 33s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1100|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/7/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 16m 32s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1100|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/8/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 15m 29s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1100|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/9/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 14m 9s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1100|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/10/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 58s
Build command:
```console
mvn clean deploy -B -e -Daudit -pl ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 14m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 50 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.JsonOutputTest.testCompatibilityMode</b> (click to expand)</summary><p>

```
org/pentaho/di/core/logging/KettleLoggingEvent
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.JsonOutputTest.testNonCompatibilityMode</b> (click to expand)</summary><p>

```
org/pentaho/di/core/logging/KettleLoggingEvent
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.AttributesMapUtilTest.initializationError</b> (click to expand)</summary><p>

```
Failed to transform class with name org.pentaho.di.repository.pur.AttributesMapUtil. Reason: cannot find org.pentaho.di.core.AttributesInterface
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.DatabaseDelegateTest.org.pentaho.di.repository.pur.DatabaseDelegateTest</b> (click to expand)</summary><p>

```

Unable to find native plugins definition file: kettle-valuemeta-plugins.xml

```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.PurRepositoryConnectorTest.org.pentaho.di.repository.pur.PurRepositoryConnectorTest</b> (click to expand)</summary><p>

```

Unable to find native plugins definition file: kettle-valuemeta-plugins.xml

```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.PurRepositoryUnitTest.org.pentaho.di.repository.pur.PurRepositoryUnitTest</b> (click to expand)</summary><p>

```

Unable to find native plugins definition file: kettle-valuemeta-plugins.xml

```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.PurRepository_DatabaseNames_Test.org.pentaho.di.repository.pur.PurRepository_DatabaseNames_Test</b> (click to expand)</summary><p>

```

Unable to find native plugins definition file: kettle-valuemeta-plugins.xml

```

</p></details>

<details><summary><b>org.pentaho.di.repository.utils.RepositoryFactoryTest.org.pentaho.di.repository.utils.RepositoryFactoryTest</b> (click to expand)</summary><p>

```

Unable to find native plugins definition file: kettle-valuemeta-plugins.xml

```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.EESpoonPluginTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/core/lifecycle/LifeEventHandler
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIEEJobTest.testAcls</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIEERepositoryDirectoryTest.testAcls</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIEETransformationTest.testAcls</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclModelTest.testClear</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclModelTest.testGetAcls</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclModelTest.testSelectedUsersAndRoles</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclModelTest.testSelectedAvailableRoles</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclModelTest.testSelectedAvailableUsers</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclModelTest.testAvailableRoles</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclModelTest.testAvailableUsers</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclModelTest.testAssignRoles</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclModelTest.testAssignUsers</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclModelTest.testUserAssignmentFlags</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclModelTest.testSelectedAssignedRoles</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclModelTest.testSelectedAssignedUsers</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclTest.testRecipientType</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclTest.testToString</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclTest.testGetPermissionSet</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclTest.testEquals</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclTest.testRecipient</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclTest.testSetPermission</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclsTest.testAddAndRemoveAcl</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclsTest.testGetOwner</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclsTest.testUpdateAcl</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclsTest.testClear</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclsTest.testSetAndGetAcls</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclsTest.testGetAceIndex</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclsTest.testSetRemoveSelectedAcls</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclsTest.testBooleanFlags</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclsTest.testSetObjectAcl</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIRepositoryObjectAclsTest.testAddAndRemoveAcls</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.repositoryexplorer.UIEESecurityTest.testAddRole</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.repositoryexplorer.UIEESecurityTest.testAddUser</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ObjectRecipient$Type
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTProducerTest.initializationError</b> (click to expand)</summary><p>

```
Failed to transform class with name org.pentaho.di.trans.step.mqtt.MQTTProducerTest. Reason: [source error] no such class: org.pentaho.di.core.variables.VariableSpace
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTStreamSourceTest.mqttReadsBinary</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/RepositoryDirectoryInterface
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTStreamSourceTest.testMultipleTopics</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/RepositoryDirectoryInterface
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTStreamSourceTest.testServernameCheck</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/RepositoryDirectoryInterface
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTStreamSourceTest.testClientIdNotReused</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/RepositoryDirectoryInterface
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTStreamSourceTest.testMQTTOpenException</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/RepositoryDirectoryInterface
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTStreamSourceTest.testMqttOnlyStopsOnce</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/RepositoryDirectoryInterface
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTStreamSourceTest.testMqttStreamSingleTopic</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/RepositoryDirectoryInterface
```

</p></details>

  
Tests run: **1035**, Failures: **50**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/12/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 43s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1100**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/13/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1103**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/14/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 14m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1116**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/15/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1116**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/16/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1116**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/17/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 13m
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1121**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/18/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 17m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1122**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/19/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1125**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/20/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1125**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/22/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 15m 43s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTStreamSourceTest.mqttReadsBinary</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **1125**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/23/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1122**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/24/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1122**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/25/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1123**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/26/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1123**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/27/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1123**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/28/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1123**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/29/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1123**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/31/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1125**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/32/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1125**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/33/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1125**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6944/34/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by mbatchelor** [comment]
Awesome! Thanks for the contribution!

**Pull request merged**
