### PR TITLE
[PDI-15013] - Create zip files runs successfully with wrong Source path

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- fail on non-existing path
- in JobEntryZipFile, remove useless assignments (highlighted by Intelij)
- add a test

@brosander, review it please

### CODE REVIEW

**Comment by brosander** [comment]
@akhayrutdinov can you please test the successful path as well?

**Comment by akhayrutdinov** [comment]
@brosander, that's not so easy :smile: OK, let me work on it

**Comment by akhayrutdinov** [comment]
@brosander, I've updated the PR. Since the test now uses local temporary files, I made it integration.
Review it please

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman/5/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  engine/src/org/pentaho/di/job/entries/zipfile/JobEntryZipFile.java
  engine/test-src/org/pentaho/di/job/entries/zipfile/JobEntryZipFileIT.java



Unit test coverage change:
============
org.pentaho.di.job.entries.ftpsget.FTPSConnection:
 * Branch Change : **-1.56%**
 * Complexity Change : **-1.37%**
 * Instruction Change : **-.23%**

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.94%

org.pentaho.di.job.entries.zipfile.JobEntryZipFile:
 * Complexity Change :  + .10%
 * Instruction Change :  + .31%
 * Line Change :  + .35%
 * Method Change : **-1.57%**

org.pentaho.di.trans.step.StepMeta:
 * Instruction Change :  + .19%
 * Line Change :  + .27%

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Instruction Change : **-.08%**

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Instruction Change :  + .07%

org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * Instruction Change :  + .18%



Integration test coverage change:
============
org.pentaho.di.core.gui.JobTracker:
 * Branch Change :  + 6.25%
 * Complexity Change :  + 3.33%

org.pentaho.di.job.entries.zipfile.JobEntryZipFile:
 * Branch Change :  + 18.75%
 * Complexity Change :  + 4.66%
 * Instruction Change :  + 15.32%
 * Line Change :  + 23.18%
 * Method Change :  + 10.20%

org.pentaho.di.job.entry.JobEntryBase:
 * Complexity Change :  + .73%
 * Instruction Change :  + .71%
 * Line Change :  + .91%
 * Method Change :  + .80%

org.pentaho.di.job.Job:
 * Branch Change :  + 2.00%
 * Complexity Change :  + 2.66%
 * Instruction Change :  + 1.50%
 * Line Change :  + 1.47%
 * Method Change :  + 1.45%

org.pentaho.di.workarounds.BufferedOutputStreamWithCloseDetection:
 * Branch Change :  + 50.00%
 * Complexity Change :  + 66.67%
 * Instruction Change :  + 84.62%
 * Line Change :  + 90.91%
 * Method Change :  + 100.00%

**Pull request merged**
