### PR TITLE
[SP-1725][PDI-13502] Regression: Instance Name on Database conn SQL server not saved to repository

### PR DESCRIPTION
**Pull request by SergeyTravin**

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@mattcasters, @brosander, @mattyb149 could you review it?
Fix for master https://github.com/pentaho/pentaho-kettle/pull/1132

**Comment by SergeyTravin** [comment]
@mattyb149, I would be grateful if you could merge this backport for 5.3 also. 
It is backport for https://github.com/pentaho/pentaho-kettle/pull/1131

**Comment by mattyb149** [comment]
I'd like the master case to be set to resolved by using a CI build if possible. If time does not permit, then I will merge this PR

**Comment by SergeyTravin** [comment]
@mattyb149, 
According https://github.com/pentaho/pentaho-kettle/pull/1132#issuecomment-86508613 I verified that issue was fixed at pdi-ee-client-TRUNK-SNAPSHOT.zip build #2984 from http://ci.pentaho.com/view/Data%20Integration/job/pdi-ee-assembly/

Unfortunately, It blocks SP sprint. Could you merge this PR?

Thanks.

**Pull request merged**
