### PR TITLE
[PDI-20038] - Pentaho 9.3.0.6 - Getting java.lang.OutOfMemoryError: Java heap space when running PDI Jobs

### PR DESCRIPTION
**Pull request by renato-s**

### CODE REVIEW

**Review by smmribeiro — APPROVED** [review]
We no longer hold a reference to the original LoggingObject...
Where we were using it, we, now, make use of the 'parent' to obtain the same information.

Looks good!

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 42m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **5342**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9198/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ddiroma — APPROVED** [review]

**Comment by ddiroma** [comment]
@rmansoor Please review/approve

**Pull request merged**
