### PR TITLE
[PDI-14095] - Transformation Executor Result Rows returns data from w…

### PR DESCRIPTION
**Pull request by akhayrutdinov**
…rong step

- replace streaming from the last step with obtaining data from Result container
- add tests
- move test transformation to testfiles folder and update it with "Copy rows to result" step

@mattyb149, @brosander, review it please.

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please. This case is included into the September SP.
/cc @pamval

**Comment by pamval** [comment]
@mattyb149 tag you're it, can you review ?

**Comment by brosander** [comment]
@akhayrutdinov is the key_for_session_key attribute something that we should be storing in a public repo?

**Comment by brosander** [comment]
@akhayrutdinov please verify that unit tests pass and that there are no checkstyle violations in files you've touched

**Comment by akhayrutdinov** [comment]
@brosander, I don't know actually. I just loaded the sample into Spoon, changed the transformation and saved it - the section was added without my intention. The field was introduced within BACKLOG-2041

**Comment by brosander** [comment]
@akhayrutdinov it looks like it was probably randomly generated for you so it should be harmless, I'd still prefer you remove it from the pr when you fix the checkstyles just to be on the safe side if you don't mind

**Comment by brosander** [comment]
@akhayrutdinov and please rerun it to be sure it's not needed

**Comment by akhayrutdinov** [comment]
@brosander, I've updated the PR and confirm there are no checkstyle violations in affected files and all unit tests are passing in ```engine``` as well as ```TransformationExecutorTest```.

**Pull request merged**
