### PR TITLE
Pdi 14981

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
@brosander, @mattyb149, @mchen-len-son, please review

### CODE REVIEW

**Comment by brosander** [comment]
@stanislau-strelchanka can you add unit tests for the fix and squash the commits please?

**Comment by stanislau-strelchanka** [comment]
@brosander, @mattyb149, @mchen-len-son, updated, please review

**Comment by mchen-len-son** [comment]
@stanislau-strelchanka can you squash the commits, and name the resulting one according to convention, please?

**Comment by stanislau-strelchanka** [comment]
@brosander, @mattyb149, @mchen-len-son, updated, please review

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/job/entries/job/JobEntryJobRunner.java
  engine/test-src/org/pentaho/di/job/entries/job/JobEntryJobRunnerTest.java

Newly Broken Tests:
======================
org.pentaho.di.job.entries.checkdbconnection.JobEntryCheckDbConnectionsTest.testMillisecondWait:
-----------------------------------------------
java.lang.Exception
```
java.lang.Exception: test timed out after 5000 milliseconds
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
	at jav
```
org.pentaho.di.trans.steps.textfileinput.TextFileInputMetaLoadSaveTest.repositorySerialization:
-----------------------------------------------
java.lang.RuntimeException
```
java.lang.RuntimeException: Error validating dateFormatLocale
	at org.pentaho.di.job.entry.loadSave.LoadSaveBase.validateLoadedMeta(LoadSaveBase.java:128)
	at org.pentaho.di.job.entry.loadSave.TransStepLoadSaveTester.testRepoRoundTrip(TransStepLoadSaveTester.java:79)
	at org.pentaho.di.trans.steps.textfileinput.TextFileInputMetaLoadSaveTest.repositorySerialization(TextFileInputMetaLoadSaveTest.java:162)
Caused by: org.pentaho.di.core.exception.KettleException: 
Attribute dateFormatLocale started
```

Newly Fixed Tests:
======================
org.pentaho.di.trans.steps.textfileoutput.TextFileOutputTest.containsSeparatorOrEnclosureIsNotUnnecessaryInvoked_AllFieldsFromMeta:
-----------------------------------------------
java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: Could not initialize class org.pentaho.di.core.row.value.ValueMetaString
	at org.pentaho.di.trans.steps.textfileoutput.TextFileOutputTest.assertNotInvokedTwice(TextFileOutputTest.java:465)
	at org.pentaho.di.trans.steps.textfileoutput.TextFileOutputTest.containsSeparatorOrEnclosureIsNotUnnecessaryInvoked_AllFieldsFromMeta(TextFileOutputTest.java:445)

```
org.pentaho.di.trans.steps.textfileoutput.TextFileOutputTest.containsSeparatorOrEnclosureIsNotUnnecessaryInvoked_SomeFieldsFromMeta:
-----------------------------------------------
java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: Could not initialize class org.pentaho.di.core.row.value.ValueMetaString
	at org.pentaho.di.trans.steps.textfileoutput.TextFileOutputTest.assertNotInvokedTwice(TextFileOutputTest.java:465)
	at org.pentaho.di.trans.steps.textfileoutput.TextFileOutputTest.containsSeparatorOrEnclosureIsNotUnnecessaryInvoked_SomeFieldsFromMeta(TextFileOutputTest.java:440)

```
org.pentaho.di.trans.steps.textfileoutput.TextFileOutputTest.testsIterate:
-----------------------------------------------
java.lang.ExceptionInInitializerError
```
java.lang.ExceptionInInitializerError
	at org.pentaho.di.trans.steps.textfileoutput.TextFileOutputTest.doOutput(TextFileOutputTest.java:416)
	at org.pentaho.di.trans.steps.textfileoutput.TextFileOutputTest.helpTestInit(TextFileOutputTest.java:368)
	at org.pentaho.di.trans.steps.textfileoutput.TextFileOutputTest.testsIterate(TextFileOutputTest.java:286)
Caused by: org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at org.pentaho.di.trans.steps.text
```

Still Broken Tests:
======================
org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testGuiErrors:
-----------------------------------------------
java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: Could not initialize class org.pentaho.di.core.row.value.ValueMetaInteger
	at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.doOutput(IngresVectorwiseTest.java:270)
	at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testGuiErrors(IngresVectorwiseTest.java:134)

```
org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testGuiErrorsWithErrorsAllowed:
-----------------------------------------------
java.lang.ExceptionInInitializerError
```
java.lang.ExceptionInInitializerError
	at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.doOutput(IngresVectorwiseTest.java:270)
	at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testGuiErrorsWithErrorsAllowed(IngresVectorwiseTest.java:152)
Caused by: org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.doOutput(IngresVectorwiseTest.java:270)

E.g. thenReturn() may b
```
org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testGuiSuccess:
-----------------------------------------------
java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: Could not initialize class org.pentaho.di.core.row.value.ValueMetaInteger
	at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.doOutput(IngresVectorwiseTest.java:270)
	at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testGuiSuccess(IngresVectorwiseTest.java:170)

```
org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testWaitForFinish:
-----------------------------------------------
org.mockito.exceptions.misusing.UnfinishedStubbingException
```
org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.doOutput(IngresVectorwiseTest.java:270)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, you naughty developer!

```

Unit test coverage change:
============
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change :  + 7.14%
 * Complexity Change :  + 7.69%

org.pentaho.di.core.compress.CompressionOutputStream:
 * Complexity Change :  + 12.50%
 * Instruction Change :  + 18.92%
 * Line Change :  + 12.50%
 * Method Change :  + 12.50%

org.pentaho.di.core.util.Assert:
 * Complexity Change : **-1.75%**
 * Instruction Change : **-2.02%**
 * Line Change : **-2.33%**
 * Method Change : **-4.00%**

org.pentaho.di.job.entries.checkdbconnection.JobEntryCheckDbConnections:
 * Branch Change : **-18.52%**
 * Complexity Change : **-5.00%**
 * Instruction Change : **-10.18%**
 * Line Change : **-16.67%**

org.pentaho.di.job.entries.job.JobEntryJobRunner:
 * Instruction Change :  + 8.29%
 * Line Change :  + 2.08%

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change : **-1.64%**
 * Complexity Change : **-.69%**
 * Instruction Change : **-2.43%**
 * Line Change : **-3.70%**

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Instruction Change :  + .07%

org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * Instruction Change : **-.18%**

org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * Branch Change : **-3.33%**
 * Complexity Change : **-1.85%**
 * Instruction Change : **-.28%**

org.pentaho.di.trans.steps.textfileoutput.TextFileOutput:
 * Branch Change :  + 26.56%
 * Complexity Change :  + 15.28%
 * Instruction Change :  + 26.33%
 * Line Change :  + 27.18%
 * Method Change :  + 33.33%

org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * Instruction Change :  + .18%

org.pentaho.di.trans.Trans:
 * Branch Change :  + .10%
 * Complexity Change :  + .14%
 * Instruction Change :  + .09%
 * Line Change :  + .11%

null

**Comment by stanislau-strelchanka** [comment]
@brosander can you please run wingman again, double checked it locally, all tests are passed

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/job/entries/job/JobEntryJobRunner.java
  engine/test-src/org/pentaho/di/job/entries/job/JobEntryJobRunnerTest.java

Newly Broken Tests:
======================
org.pentaho.di.job.entries.checkdbconnection.JobEntryCheckDbConnectionsTest.testMillisecondWait:
-----------------------------------------------
java.lang.Exception
```
java.lang.Exception: test timed out after 5000 milliseconds
	at org.jacoco.agent.rt.internal_14f7ee5.asm.commons.AnalyzerAdapter.execute(AnalyzerAdapter.java:580)
	at org.jacoco.agent.rt.internal_14f7ee5.asm.commons.AnalyzerAdapter.visitJumpInsn(AnalyzerAdapter.java:388)
	at org.jacoco.agent.rt.internal_14f7ee5.asm.tree.JumpInsnNode.accept(JumpInsnNode.java:88)
	at org.jacoco.agent.rt.internal_14f7ee5.asm.tree.InsnList.accept(InsnList.java:162)
	at org.jacoco.agent.rt.internal_14f7ee5.asm.tree.M
```


Still Broken Tests:
======================
org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testGuiErrors:
-----------------------------------------------
java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: Could not initialize class org.pentaho.di.core.row.value.ValueMetaInteger
	at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.doOutput(IngresVectorwiseTest.java:270)
	at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testGuiErrors(IngresVectorwiseTest.java:134)

```
org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testGuiErrorsWithErrorsAllowed:
-----------------------------------------------
java.lang.ExceptionInInitializerError
```
java.lang.ExceptionInInitializerError
	at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.doOutput(IngresVectorwiseTest.java:270)
	at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testGuiErrorsWithErrorsAllowed(IngresVectorwiseTest.java:152)
Caused by: org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.doOutput(IngresVectorwiseTest.java:270)

E.g. thenReturn() may b
```
org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testGuiSuccess:
-----------------------------------------------
java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: Could not initialize class org.pentaho.di.core.row.value.ValueMetaInteger
	at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.doOutput(IngresVectorwiseTest.java:270)
	at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testGuiSuccess(IngresVectorwiseTest.java:170)

```
org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.testWaitForFinish:
-----------------------------------------------
org.mockito.exceptions.misusing.UnfinishedStubbingException
```
org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.doOutput(IngresVectorwiseTest.java:270)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, you naughty developer!

```

Unit test coverage change:
============
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change :  + 7.14%
 * Complexity Change :  + 7.69%

org.pentaho.di.core.util.Assert:
 * Complexity Change : **-1.75%**
 * Instruction Change : **-2.02%**
 * Line Change : **-2.33%**
 * Method Change : **-4.00%**

org.pentaho.di.job.entries.checkdbconnection.JobEntryCheckDbConnections:
 * Branch Change : **-18.52%**
 * Complexity Change : **-5.00%**
 * Instruction Change : **-10.18%**
 * Line Change : **-16.67%**

org.pentaho.di.job.entries.job.JobEntryJobRunner:
 * Instruction Change :  + 8.29%
 * Line Change :  + 2.08%

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change : **-1.64%**
 * Line Change : **-1.94%**

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change : **-1.64%**
 * Complexity Change : **-.69%**
 * Instruction Change : **-2.43%**
 * Line Change : **-3.70%**

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Instruction Change : **-.07%**

org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * Instruction Change :  + .18%

org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * Branch Change :  + 3.33%
 * Complexity Change :  + 1.85%
 * Instruction Change :  + .28%

org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * Branch Change : **-.53%**

null

**Comment by lucboudreau** [comment]
Please make sure to fix both the current failures, and those that existed before as well.

**Comment by stanislau-strelchanka** [comment]
@brosander can't reproduce JobEntryCheckDbConnectionsTest.testMillisecondWait fail on my environment. Increased timeout.

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/job/entries/job/JobEntryJobRunner.java
  engine/test-src/org/pentaho/di/job/entries/checkdbconnection/JobEntryCheckDbConnectionsTest.java
  engine/test-src/org/pentaho/di/job/entries/job/JobEntryJobRunnerTest.java

Unit test coverage change:
============
org.pentaho.di.job.entries.job.JobEntryJobRunner:
 * Instruction Change :  + 8.29%
 * Line Change :  + 2.08%

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.94%

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change : **-1.64%**
 * Complexity Change : **-.69%**
 * Instruction Change : **-2.43%**
 * Line Change : **-3.70%**

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Instruction Change : **-.08%**

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Instruction Change :  + .07%

org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * Branch Change : **-3.33%**
 * Complexity Change : **-1.85%**
 * Instruction Change : **-.28%**

Integration test coverage change:
============
org.pentaho.di.trans.step.BaseStep:
 * Branch Change :  + .30%
 * Complexity Change :  + .18%
 * Instruction Change :  + .13%
 * Line Change :  + .08%

**Comment by stanislau-strelchanka** [comment]
@brosander could please check decrease of test coverage . According to wingman it was reduced in KettleDatabaseRepositoryCreationHelper, ExcelWriterStepMeta, SymmetricCryptoTransMeta. But I've made changes only in JobEntryJobRunner.

**Comment by lucboudreau** [comment]
We think these small changes are caused by non-deterministic tests. We're aware of them. Go ahead and merge your PR when ready.

**Pull request merged**
