### PR TITLE
[SP-2649] - Backport of PDI-12460 - LOG_FIELD in Job Log Table entry doesn't capture the entire execution results. (6.1 Suite)

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
cherry picked commits from: 
https://github.com/pentaho/pentaho-kettle/pull/2384/commits
https://github.com/pentaho/pentaho-kettle/pull/2411/commits
https://github.com/pentaho/pentaho-kettle/pull/2418/commits

**Comment by stanislau-strelchanka** [comment]
@brosander, @mattyb149, @mchen-len-son, please review

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local
2. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
  core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java
  engine/test-src/org/pentaho/di/trans/steps/ivwloader/IngresVectorwiseTest.java
  engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java

Unit test coverage change:
============
org.pentaho.di.core.logging.KettleLogStore:
 * Complexity Change :  + 3.85%
 * Instruction Change :  + .88%
 * Line Change :  + 1.67%
 * Method Change :  + 5.88%

org.pentaho.di.core.logging.LogChannel:
 * Branch Change :  + 7.32%
 * Complexity Change :  + 4.84%
 * Instruction Change :  + 5.62%
 * Line Change :  + 4.83%
 * Method Change :  + 5.13%

org.pentaho.di.core.logging.LogChannelFactory:
 * Complexity Change :  + 20.00%
 * Instruction Change :  + 18.52%
 * Line Change :  + 20.00%
 * Method Change :  + 20.00%

org.pentaho.di.core.logging.LoggingBuffer:
 * Complexity Change :  + 1.72%
 * Instruction Change :  + 1.09%
 * Line Change :  + 1.57%
 * Method Change :  + 3.45%

org.pentaho.di.core.row.value.ValueMetaBase:
 * Branch Change :  + .48%
 * Complexity Change :  + .20%
 * Instruction Change :  + .55%
 * Line Change :  + .71%

org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change :  + 7.14%
 * Complexity Change :  + 7.69%

org.pentaho.di.core.lifecycle.KettleLifecycleSupport:
 * Branch Change :  + 8.33%
 * Complexity Change :  + 9.09%

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.97%

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change : **-1.64%**
 * Complexity Change : **-.69%**
 * Instruction Change : **-2.43%**
 * Line Change : **-2.95%**

org.pentaho.di.trans.step.StepMeta:
 * Instruction Change :  + .19%
 * Line Change :  + .27%

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Instruction Change : **-.08%**

org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * Branch Change :  + .53%

org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * Instruction Change : **-.18%**

License header violations:
==========================
1. Copyright year is not the current year on engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java. Found 2013. Was expecting 2016

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java

1. Message: Using a static member import should be avoided - org.pentaho.di.core.util.Assert.assertFalse. at Line: 37
2. Message: Using a static member import should be avoided - org.pentaho.di.core.util.Assert.assertTrue. at Line: 38

**Comment by lucboudreau** [comment]
Please make sure to squash your commits. Thanks!

**Comment by stanislau-strelchanka** [comment]
@brosander, @mattyb149, @mchen-len-son, updated, please review

**Comment by stanislau-strelchanka** [comment]
@brosander, @mattyb149, @mchen-len-son, please review

**Comment by stanislau-strelchanka** [comment]
@brosander, @mattyb149, @mchen-len-son, removed static imports, please review

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local
2. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
  core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java
  engine/test-src/org/pentaho/di/trans/steps/ivwloader/IngresVectorwiseTest.java
  engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java

Unit test coverage change:
============
org.pentaho.di.core.logging.KettleLogStore:
 * Complexity Change :  + 3.85%
 * Instruction Change :  + .88%
 * Line Change :  + 1.67%
 * Method Change :  + 5.88%

org.pentaho.di.core.logging.LogChannel:
 * Branch Change :  + 7.32%
 * Complexity Change :  + 4.84%
 * Instruction Change :  + 5.62%
 * Line Change :  + 4.83%
 * Method Change :  + 5.13%

org.pentaho.di.core.logging.LogChannelFactory:
 * Complexity Change :  + 20.00%
 * Instruction Change :  + 18.52%
 * Line Change :  + 20.00%
 * Method Change :  + 20.00%

org.pentaho.di.core.logging.LoggingBuffer:
 * Complexity Change :  + 1.72%
 * Instruction Change :  + 1.09%
 * Line Change :  + 1.57%
 * Method Change :  + 3.45%

org.pentaho.di.core.row.value.ValueMetaBase:
 * Branch Change :  + .48%
 * Complexity Change :  + .20%
 * Instruction Change :  + .55%
 * Line Change :  + .71%

org.pentaho.di.job.entries.ftpsget.FTPSConnection:
 * Branch Change : **-1.56%**
 * Complexity Change : **-1.37%**
 * Instruction Change : **-.23%**

org.pentaho.di.trans.step.StepMeta:
 * Instruction Change :  + .19%
 * Line Change :  + .27%

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Instruction Change : **-.08%**

org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * Instruction Change :  + .18%

**Pull request merged**
