### PR TITLE
[PDI-13227] join rows step - after changing the steps on incoming hops, step gets into undefined / not working state

### PR DESCRIPTION
**Pull request by Advent51**
- the extra restrictions were removed - now the field positions updates every time

### CODE REVIEW

**Comment by Advent51** [comment]
@mbatchelor @pamval @mchen-len-son please review

**Comment by Advent51** [comment]
@mbatchelor @pamval @mchen-len-son @mdamour1976 @duarteteixeira please review

**Comment by kolinus** [comment]
@matthewtckr  could you please review

**Comment by pamval** [comment]
@Advent51 can we add a unit test for this change, please?

**Comment by Advent51** [comment]
@pamval sure.
I will try to write a test after I finish all my SPs.

**Comment by Advent51** [comment]
Well, I don't know why these tests fails one after another.
On my local machine all tests passed successfully.
The previous failed test got fixed without any fix improvements - I just re-pushed it as is.
@pamval @mchen-len-son @matthewtckr please review.

**Pull request merged**
