### PR TITLE
[PDI-15705] Perform Undo throw an exception in Spoon console and we a…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
[PDI-15705] Perform Undo throw an exception in Spoon console and we are unable to operate on the transformation

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
@mbatchelor @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor, @matthewtckr, @pamval , @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor, @matthewtckr, @pamval , @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor, @matthewtckr, @pamval , @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor, @matthewtckr, @pamval , @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor, @matthewtckr, @pamval , @mchen-len-son please review

**Comment by pamval** [comment]
@tgf @mdamour1976 @bmorrise please review

**Pull request merged**
