### PR TITLE
[PIR-1187] Pentaho interactive reporting datetime prompt

### PR DESCRIPTION
**Pull request by SergeyTravin**
@mattcasters, @brosander, @mattyb149 
Could you review please?

### CODE REVIEW

**Comment by brosander** [comment]
Changed files:
==============
  core/src/org/pentaho/di/core/util/DateDetector.java
  core/src/org/pentaho/di/core/util/StringEvaluator.java
  core/test-src/org/pentaho/di/core/util/DateDetectorTest.java
  core/test-src/org/pentaho/di/core/util/StringEvaluatorTest.java

Checkstyle violations:
----------------------
Errors:File core/src/org/pentaho/di/core/util/StringEvaluator.java
1. Message: array initialization child at indentation level 6 not at correct indentation, 4 at Line: 65 Column: None
2. Message: array initialization child at indentation level 6 not at correct indentation, 4 at Line: 66 Column: None
3. Message: array initialization child at indentation level 6 not at correct indentation, 4 at Line: 67 Column: None
4. Message: array initialization child at indentation level 6 not at correct indentation, 4 at Line: 68 Column: None
5. Message: array initialization child at indentation level 6 not at correct indentation, 4 at Line: 69 Column: None
6. Message: array initialization child at indentation level 6 not at correct indentation, 4 at Line: 70 Column: None
7. Message: array initialization child at indentation level 6 not at correct indentation, 4 at Line: 71 Column: None
8. Message: array initialization child at indentation level 6 not at correct indentation, 4 at Line: 72 Column: None
9. Message: array initialization child at indentation level 6 not at correct indentation, 4 at Line: 73 Column: None
10. Message: array initialization child at indentation level 6 not at correct indentation, 4 at Line: 74 Column: None
11. Message: array initialization rcurly at indentation level 6 not at correct indentation, 2 at Line: 75 Column: None

Newly Broken Tests:
=================
Test Case Errors:
-----------------
  org.pentaho.di.core.util.DateDetectorTest.testGetDateFromStringByFormat: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<Thu Jan 01 00:00:00 UTC 1970> but was:<Wed Dec 31 21:00:00 UTC 1969>
	at org.pentaho.di.core.util.DateDetectorTest.testGetDateFromStringByFormat(DateDetectorTest.java:60)

```org.pentaho.di.core.util.DateDetectorTest.testGetDateFromString: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<Thu Jan 01 00:00:00 UTC 1970> but was:<Wed Dec 31 21:00:00 UTC 1969>
	at org.pentaho.di.core.util.DateDetectorTest.testGetDateFromString(DateDetectorTest.java:55)

```


Unit test coverage change:
============
org.pentaho.di.core.row.value.ValueMetaBase:
 * instructionPercentCoverageChange :**-0.02%**
 * branchPercentCoverageChange :**-0.08%**
 * linePercentCoverageChange :**-0.06%**
 * complexityPercentCoverageChange :**-0.10%**
    
org.pentaho.di.core.util.DateDetector.new DualHashBidiMap() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.core.util.DateDetector:
 * branchPercentCoverage :80.00%
 * linePercentCoverage :77.42%
 * methodPercentCoverage :90.00%
 * complexityPercentCoverage :80.00%
 * instructionPercentCoverage :85.29%
    
org.pentaho.di.core.Const:
 * instructionPercentCoverageChange :**-5.03%**
 * linePercentCoverageChange :**-1.73%**
 * complexityPercentCoverageChange :**-0.29%**
 * methodPercentCoverageChange :**-0.93%**
    
org.pentaho.di.core.util.StringEvaluator:
 * instructionPercentCoverageChange :**-0.21%**
 * branchPercentCoverageChange : +0.62%
 * linePercentCoverageChange :**-0.35%**
 * complexityPercentCoverageChange :**-0.22%**
    
org.pentaho.di.core.KettleClientEnvironment:
 * instructionPercentCoverageChange :**-6.45%**
 * branchPercentCoverageChange :**-10.00%**
 * linePercentCoverageChange :**-10.00%**
 * complexityPercentCoverageChange :**-5.00%**
    
org.pentaho.di.core.plugins.PluginRegistry:
 * instructionPercentCoverageChange : +0.14%
 * branchPercentCoverageChange : +0.48%
 * linePercentCoverageChange : +0.23%
 * complexityPercentCoverageChange : +0.70%
    
org.pentaho.di.core.database.DatabaseMeta.new PluginTypeListener() {...}:
 * instructionPercentCoverageChange : +22.22%
 * linePercentCoverageChange : +28.57%
 * complexityPercentCoverageChange : +25.00%
 * methodPercentCoverageChange : +25.00%

**Comment by brosander** [comment]
@SergeyTravin I'm suspecting the date test failure is timezone related

**Comment by SergeyTravin** [comment]
@brosander 
Thanks a lot for so quick answer!
I changed PR for ignore timezone.

**Comment by brosander** [comment]
Changed files:
==============
  core/src/org/pentaho/di/core/util/DateDetector.java
  core/src/org/pentaho/di/core/util/StringEvaluator.java
  core/test-src/org/pentaho/di/core/util/DateDetectorTest.java
  core/test-src/org/pentaho/di/core/util/StringEvaluatorTest.java

Checkstyle violations:
----------------------
No errors found




Unit test coverage change:
============
org.pentaho.di.core.row.value.ValueMetaBase:
 * instructionPercentCoverageChange :**-0.02%**
 * branchPercentCoverageChange :**-0.08%**
 * linePercentCoverageChange :**-0.06%**
 * complexityPercentCoverageChange :**-0.10%**
    
org.pentaho.di.core.util.DateDetector.new DualHashBidiMap() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.core.util.DateDetector:
 * branchPercentCoverage :80.00%
 * linePercentCoverage :77.42%
 * methodPercentCoverage :90.00%
 * complexityPercentCoverage :80.00%
 * instructionPercentCoverage :85.29%
    
org.pentaho.di.core.Const:
 * instructionPercentCoverageChange :**-5.03%**
 * linePercentCoverageChange :**-1.73%**
 * complexityPercentCoverageChange :**-0.29%**
 * methodPercentCoverageChange :**-0.93%**
    
org.pentaho.di.core.util.StringEvaluator:
 * instructionPercentCoverageChange :**-0.21%**
 * branchPercentCoverageChange : +0.62%
 * linePercentCoverageChange :**-0.35%**
 * complexityPercentCoverageChange :**-0.22%**
    
org.pentaho.di.core.KettleClientEnvironment:
 * instructionPercentCoverageChange :**-6.45%**
 * branchPercentCoverageChange :**-10.00%**
 * linePercentCoverageChange :**-10.00%**
 * complexityPercentCoverageChange :**-5.00%**
    
org.pentaho.di.core.plugins.PluginRegistry:
 * instructionPercentCoverageChange :**-0.14%**
 * branchPercentCoverageChange :**-0.48%**
 * linePercentCoverageChange :**-0.23%**
 * complexityPercentCoverageChange :**-0.70%**
    
org.pentaho.di.core.database.DatabaseMeta.new PluginTypeListener() {...}:
 * instructionPercentCoverageChange :**-22.22%**
 * linePercentCoverageChange :**-28.57%**
 * complexityPercentCoverageChange :**-25.00%**
 * methodPercentCoverageChange :**-25.00%**

**Comment by brosander** [comment]
Changed files:
==============
  core/src/org/pentaho/di/core/util/DateDetector.java
  core/src/org/pentaho/di/core/util/StringEvaluator.java
  core/test-src/org/pentaho/di/core/util/DateDetectorTest.java
  core/test-src/org/pentaho/di/core/util/StringEvaluatorTest.java

Checkstyle violations:
----------------------
No errors found




Unit test coverage change:
============
org.pentaho.di.core.util.DateDetector.new DualHashBidiMap() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.core.util.DateDetector:
 * branchPercentCoverage :80.00%
 * linePercentCoverage :77.42%
 * methodPercentCoverage :90.00%
 * complexityPercentCoverage :80.00%
 * instructionPercentCoverage :85.29%
    
org.pentaho.di.core.row.value.ValueMetaBase:
 * instructionPercentCoverageChange :**-0.02%**
 * branchPercentCoverageChange :**-0.08%**
 * linePercentCoverageChange :**-0.06%**
 * complexityPercentCoverageChange :**-0.10%**
    
org.pentaho.di.core.util.StringEvaluator:
 * instructionPercentCoverageChange :**-0.21%**
 * branchPercentCoverageChange : +0.62%
 * linePercentCoverageChange :**-0.35%**
 * complexityPercentCoverageChange :**-0.22%**

**Comment by brosander** [comment]
@SergeyTravin looks like we have a slight coverage drop in ValueMetaBase and StringEvaluator, mind covering a few more lines?

**Comment by SergeyTravin** [comment]
It should be merged before https://github.com/pentaho/data-access/pull/676

**Comment by SergeyTravin** [comment]
@brosander I added some more tests

**Comment by brosander** [comment]
Changed files:
==============
  core/src/org/pentaho/di/core/util/DateDetector.java
  core/src/org/pentaho/di/core/util/StringEvaluator.java
  core/test-src/org/pentaho/di/core/util/DateDetectorTest.java
  core/test-src/org/pentaho/di/core/util/StringEvaluatorTest.java

Checkstyle violations:
----------------------
Errors:File core/test-src/org/pentaho/di/core/util/StringEvaluatorTest.java
1. Message: Line has trailing spaces. at Line: 101 Column: None
2. Message: Line has trailing spaces. at Line: 143 Column: None
3. Message: ')' is not preceded with whitespace. at Line: 146 Column: 68
4. Message: ',' is not followed by whitespace. at Line: 146 Column: 56
5. Message: Line has trailing spaces. at Line: 153 Column: None
6. Message: '(' is not followed by whitespace. at Line: 160 Column: 53
7. Message: ')' is not preceded with whitespace. at Line: 160 Column: 108
8. Message: Line has trailing spaces. at Line: 170 Column: None
9. Message: Line has trailing spaces. at Line: 57 Column: None
10. Message: Line has trailing spaces. at Line: 67 Column: None
11. Message: Line has trailing spaces. at Line: 86 Column: None
12. Message: Line has trailing spaces. at Line: 91 Column: None
13. Message: Line has trailing spaces. at Line: 96 Column: None




Unit test coverage change:
============
org.pentaho.di.core.util.StringEvaluationResult:
 * instructionPercentCoverageChange : +6.03%
 * linePercentCoverageChange : +10.34%
 * complexityPercentCoverageChange : +10.53%
 * methodPercentCoverageChange : +11.76%
    
org.pentaho.di.core.util.DateDetector.new DualHashBidiMap() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.core.util.DateDetector:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :94.29%
 * methodPercentCoverage :90.00%
 * complexityPercentCoverage :94.44%
 * instructionPercentCoverage :97.48%
    
org.pentaho.di.core.row.value.ValueMetaBase:
 * instructionPercentCoverageChange :**-0.02%**
 * branchPercentCoverageChange :**-0.08%**
 * linePercentCoverageChange :**-0.06%**
 * complexityPercentCoverageChange :**-0.10%**
    
org.pentaho.di.core.util.StringEvaluator:
 * instructionPercentCoverageChange : +11.25%
 * branchPercentCoverageChange : +21.05%
 * linePercentCoverageChange : +12.57%
 * complexityPercentCoverageChange : +26.10%
 * methodPercentCoverageChange : +14.29%

**Comment by pamval** [comment]
@SergeyTravin @brosander, @bkemper-pentaho comments on https://github.com/pentaho/data-access/issues/676 are extremely relevant. The process of setting up the unit/integration tests before the change to reflect actual system behavior, then make the change and make sure the tests are running is necessary.

Specially here, since we've already had regressions on date handling before.

**Comment by SergeyTravin** [comment]
@brosander,  @pamval I have added commit with test before my change, commit with change and test for my change. All unit tests are successful. The classes do not have any checkstyle violation. Could you review it again, please?

**Comment by pamval** [comment]
@brosander can you review ? This looks like it should be ok.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/di/core/util/DateDetector.java
  core/src/org/pentaho/di/core/util/StringEvaluator.java
  core/test-src/org/pentaho/di/core/util/DateDetectorTest.java
  core/test-src/org/pentaho/di/core/util/StringEvaluatorTest.java

Checkstyle violations:
======================
File core/test-src/org/pentaho/di/core/util/DateDetectorTest.java
1. Message: Line has trailing spaces. at Line: 103 Column: None
2. Message: Line has trailing spaces. at Line: 162 Column: None


License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.di.core.util.StringEvaluationResult:
 * instructionPercentCoverageChange : +6.03%
 * linePercentCoverageChange : +10.34%
 * complexityPercentCoverageChange : +10.53%
 * methodPercentCoverageChange : +11.76%
    
org.pentaho.di.core.extension.ExtensionPointMap.new PluginTypeListener() {...}:
 * instructionPercentCoverageChange :**-20.69%**
 * linePercentCoverageChange :**-25.00%**
 * complexityPercentCoverageChange :**-25.00%**
 * methodPercentCoverageChange :**-25.00%**
    
org.pentaho.di.core.row.value.ValueMetaBase:
 * instructionPercentCoverageChange :**-0.02%**
 * branchPercentCoverageChange :**-0.08%**
 * linePercentCoverageChange :**-0.06%**
 * complexityPercentCoverageChange :**-0.10%**
    
org.pentaho.di.core.util.DateDetector:
 * branchPercentCoverage :92.11%
 * linePercentCoverage :96.43%
 * methodPercentCoverage :93.33%
 * complexityPercentCoverage :88.24%
 * instructionPercentCoverage :98.60%
    
org.pentaho.di.core.util.StringEvaluator:
 * instructionPercentCoverageChange : +12.36%
 * branchPercentCoverageChange : +24.27%
 * linePercentCoverageChange : +13.82%
 * complexityPercentCoverageChange : +29.61%
 * methodPercentCoverageChange : +19.05%
    
org.pentaho.di.core.util.DateDetector.new DualHashBidiMap() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.core.database.DatabaseMeta.new PluginTypeListener() {...}:
 * instructionPercentCoverageChange : +22.22%
 * linePercentCoverageChange : +28.57%
 * complexityPercentCoverageChange : +25.00%
 * methodPercentCoverageChange : +25.00%

**Comment by brosander** [comment]
@SergeyTravin still seeing checkstyle errors, think the coverage drops are unrelated to your changes (incidental coverage due to test run and kettle environment init order I would think)

**Comment by SergeyTravin** [comment]
@brosander fixed, colud you look it if you have a chance

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/di/core/util/DateDetector.java
  core/src/org/pentaho/di/core/util/StringEvaluator.java
  core/test-src/org/pentaho/di/core/util/DateDetectorTest.java
  core/test-src/org/pentaho/di/core/util/StringEvaluatorTest.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.di.core.util.StringEvaluationResult:
 * instructionPercentCoverageChange : +6.03%
 * linePercentCoverageChange : +10.34%
 * complexityPercentCoverageChange : +10.53%
 * methodPercentCoverageChange : +11.76%
    
org.pentaho.di.core.util.DateDetector.new DualHashBidiMap() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.core.util.DateDetector:
 * branchPercentCoverage :92.11%
 * linePercentCoverage :96.43%
 * methodPercentCoverage :93.33%
 * complexityPercentCoverage :88.24%
 * instructionPercentCoverage :98.60%
    
org.pentaho.di.core.row.value.ValueMetaBase:
 * instructionPercentCoverageChange :**-0.02%**
 * branchPercentCoverageChange :**-0.08%**
 * linePercentCoverageChange :**-0.06%**
 * complexityPercentCoverageChange :**-0.10%**
    
org.pentaho.di.core.util.StringEvaluator:
 * instructionPercentCoverageChange : +12.36%
 * branchPercentCoverageChange : +24.27%
 * linePercentCoverageChange : +13.82%
 * complexityPercentCoverageChange : +29.61%
 * methodPercentCoverageChange : +19.05%

**Pull request merged**
