### PR TITLE
[PDI-17024] Step name called "User Defined Java Expression 4" causes …

### PR DESCRIPTION
**Pull request by smmribeiro**
…in error

@pentaho-lmartins

### CODE REVIEW

**Comment by smmribeiro** [comment]
@mbatchelor @pamval @bmorrise please review.

**Comment by mbatchelor** [comment]
@smmribeiro - Please re-base

**Comment by smmribeiro** [comment]
@mbatchelor, during the development for this issue, I saw that the **org.pentaho.di.trans.step.StepMetaInterface#cleanAfterHopFromRemove** method, as it had no parameters, was in need of a refactoring (while debugging, I saw it clearing things that it shouldn't in org.pentaho.di.trans.steps.transexecutor.TransExecutorMeta).
As a matter of fact, I was going to create a JIRA for this. However, someone saw this behaviour and created [BACKLOG-22673](https://jira.pentaho.com/browse/BACKLOG-22673) and as its related commit was merged before mine, we've a conflict.
The approach was similar to mine, however I pass a StepMeta object:
```
default boolean cleanAfterHopToRemove( StepMeta fromStep ) {
  return false;
}
```
The other implementation uses a String (with the step name):
```
default boolean cleanAfterHopFromRemove( String toStepName ) {
  return false;
}
```

I feel that we should be homogeneous and coherent, and so, we should use the same type in both.
My feeling is that, while passing the step name is enough, passing a StepMeta object provides more flexibility for the future.
So, when I rebase my commit, should I:
1. let the two methods with their parameters
2. change my method and use “String fromStepName”
3. change the other method and use “StepMeta toStep”

**Comment by mbatchelor** [comment]
1- Leave the one with the string parameter, have it resolve the step meta, and call a new method with the step meta as a parameter.
2- Deprecate the one receiving a string

**Comment by smmribeiro** [comment]
@mbatchelor, I've talked with @ddiroma: as the method was so recently created and had no other references in code, instead of deprecating the String parameter version, I've eliminated it and made the needed changes where it was invoked.

**Pull request merged**
