### PR TITLE
[SP-2523][PDI-14413] Step Synchronize after merge - issue with mode "…

### PR DESCRIPTION
**Pull request by SergeyTravin**
…use batch update"

- return the dispose method, it is allow to free resource in unexpected situation

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@kolinus @akhayrutdinov  review its backport for https://github.com/pentaho/pentaho-kettle/pull/2295 too please

**Comment by pamval** [comment]
wingman running

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMerge.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeIT.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File engine/src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMerge.java
1. Message: 'for' have incorrect indentation level 8, expected level should be 10. at Line: 919 Column: None
2. Message: 'for' child have incorrect indentation level 10, expected level should be 12. at Line: 922 Column: None
3. Message: 'member def type' have incorrect indentation level 10, expected level should be 12. at Line: 922 Column: None
4. Message: 'if' have incorrect indentation level 10, expected level should be 12. at Line: 923 Column: None
5. Message: 'if' child have incorrect indentation level 12, expected level should be 14. at Line: 924 Column: None
6. Message: 'if rcurly' have incorrect indentation level 10, expected level should be 12. at Line: 925 Column: None
7. Message: 'for' child have incorrect indentation level 10, expected level should be 12. at Line: 927 Column: None
8. Message: 'member def type' have incorrect indentation level 10, expected level should be 12. at Line: 927 Column: None
9. Message: 'for' child have incorrect indentation level 10, expected level should be 12. at Line: 929 Column: None
10. Message: 'method call' child have incorrect indentation level 10, expected level should be 12. at Line: 929 Column: None
11. Message: 'for rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 930 Column: None
12. Message: 'for' have incorrect indentation level 8, expected level should be 10. at Line: 931 Column: None
13. Message: 'for' child have incorrect indentation level 10, expected level should be 12. at Line: 932 Column: None
14. Message: 'member def type' have incorrect indentation level 10, expected level should be 12. at Line: 932 Column: None
15. Message: 'for' child have incorrect indentation level 10, expected level should be 12. at Line: 933 Column: None
16. Message: 'method call' child have incorrect indentation level 10, expected level should be 12. at Line: 933 Column: None
17. Message: 'if' have incorrect indentation level 10, expected level should be 12. at Line: 934 Column: None
18. Message: 'if' child have incorrect indentation level 12, expected level should be 14. at Line: 935 Column: None
19. Message: 'method call' child have incorrect indentation level 12, expected level should be 14. at Line: 935 Column: None
20. Message: 'if rcurly' have incorrect indentation level 10, expected level should be 12. at Line: 936 Column: None
21. Message: 'for rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 937 Column: None
22. Message: 'if' child have incorrect indentation level 8, expected level should be 10. at Line: 939 Column: None
23. Message: 'method call' child have incorrect indentation level 8, expected level should be 10. at Line: 939 Column: None









Unit test coverage change:
============
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange :**-0.53%**
    
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange :**-0.08%**
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange :**-7.14%**
 * complexityPercentCoverageChange :**-7.69%**
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange : +0.28%
 * branchPercentCoverageChange : +3.33%
 * complexityPercentCoverageChange : +1.85%
    
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange :**-0.17%**
    
Integration test coverage change:
============
org.pentaho.di.trans.Trans:
 * instructionPercentCoverageChange : +0.70%
 * branchPercentCoverageChange : +0.40%
 * linePercentCoverageChange : +0.83%
 * complexityPercentCoverageChange : +0.28%
 * methodPercentCoverageChange : +0.48%
    
org.pentaho.di.trans.step.RunThread:
 * instructionPercentCoverageChange : +0.15%
 * branchPercentCoverageChange : +2.00%
 * linePercentCoverageChange : +1.85%
 * complexityPercentCoverageChange : +3.57%
    
org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMerge:
 * instructionPercentCoverageChange : +0.25%
 * branchPercentCoverageChange : +0.36%
 * linePercentCoverageChange : +0.35%
 * complexityPercentCoverageChange : +0.71%
 * methodPercentCoverageChange : +0.91%
    
org.pentaho.di.trans.step.BaseStep:
 * instructionPercentCoverageChange : +0.63%
 * branchPercentCoverageChange : +1.03%
 * linePercentCoverageChange : +1.15%
 * complexityPercentCoverageChange : +1.82%
 * methodPercentCoverageChange : +2.44%

**Comment by SergeyTravin** [comment]
@pamval, The checkstyle violations was fixed. COuld you merge it please?

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMerge.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeIT.java










Unit test coverage change:
============
org.pentaho.di.trans.Trans:
 * instructionPercentCoverageChange : +0.09%
 * branchPercentCoverageChange : +0.10%
 * linePercentCoverageChange : +0.10%
 * complexityPercentCoverageChange : +0.14%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange : +0.53%
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange :**-7.14%**
 * complexityPercentCoverageChange :**-7.69%**
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange : +0.28%
 * branchPercentCoverageChange : +3.33%
 * complexityPercentCoverageChange : +1.85%
    
org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * instructionPercentCoverageChange :**-2.43%**
 * branchPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-3.70%**
 * complexityPercentCoverageChange :**-0.69%**
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange :**-3.28%**
 * linePercentCoverageChange :**-3.90%**
    
Integration test coverage change:
============
org.pentaho.di.trans.Trans:
 * instructionPercentCoverageChange : +0.70%
 * branchPercentCoverageChange : +0.40%
 * linePercentCoverageChange : +0.83%
 * complexityPercentCoverageChange : +0.28%
 * methodPercentCoverageChange : +0.48%
    
org.pentaho.di.trans.step.RunThread:
 * instructionPercentCoverageChange : +0.15%
 * branchPercentCoverageChange : +2.00%
 * linePercentCoverageChange : +1.85%
 * complexityPercentCoverageChange : +3.57%
    
org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMerge:
 * instructionPercentCoverageChange : +0.25%
 * branchPercentCoverageChange : +0.36%
 * linePercentCoverageChange : +0.35%
 * complexityPercentCoverageChange : +0.71%
 * methodPercentCoverageChange : +0.91%
    
org.pentaho.di.trans.step.BaseStep:
 * instructionPercentCoverageChange : +0.68%
 * branchPercentCoverageChange : +1.33%
 * linePercentCoverageChange : +1.22%
 * complexityPercentCoverageChange : +2.00%
 * methodPercentCoverageChange : +2.44%

**Comment by lucboudreau** [comment]
This PR makes coverage go down overall.

**Pull request merged**
