### PR TITLE
[PDI-12080] PostgreSQL Bulk Loader improvements

### PR DESCRIPTION
**Pull request by evis**
Seems like @marco44 stopped activity here https://github.com/pentaho/pentaho-kettle/pull/1020

I rebased his branch and added some more improvements to bulk loader. @mbatchelor could you review and merge it please?

### CODE REVIEW

**Comment by marco44** [comment]
Yes, I sort of gave up… this pull request has been waiting for very long. And I'm not sure my latest rebase is totally correct: I'm not a Java developper, so I may have missed some implications on the changes. So evere10, if you want to take over, no problem with me, on the contrary :)

**Comment by matthewtckr** [comment]
@evere10 Thanks for your efforts on this.

Since you're in the area on one of these files, could you modify the PGBulkLoaderMetaTest class, by combining the `setUpLoadSave` and `testSerialization` methods into a single `@Test`?  The LoadSaveTester stuff isn't needed for any of the metadata injection tests, and will help limit the test failure to only where it's actually used.  Otherwise, it may be a while before I'm able to go back and cleanup that test.  Thanks!

**Comment by evere10** [comment]
@matthewtckr I modified PGBulkLoaderMetaTest as you suggested, could you validate my pull request? Or maybe, someone else could do this?

**Comment by evere10** [comment]
@mbatchelor could you invoke tests and merge it, please? maybe, someone else?

**Comment by evis** [comment]
I don't use Pentaho anymore, and I guess, this PR won't get merged soon. So, I close this PR.

**Pull request closed without merging**
