### PR TITLE
[PDI-17922] Get File Names step - Only Files filter option works inco…

### PR DESCRIPTION
**Pull request by LeonardoCoelho71950**
…rrectly

@pentaho/tatooine @pentaho-lmartins 
@mbatchelor 

File type wasn't checked if there was no wildcard.

### CODE REVIEW

**Comment by smmribeiro** [comment]
I don't think this will fix the issue.

The problem seems to be in the handling of the wildcard. I did a quick test on 8.3-QAT-180 and the same happens if one sets "Only folders" or "All files".

**Comment by LeonardoCoelho71950** [comment]
@smmribeiro Actually this bug is when you didn`t specified any wildcard. Right now we check the allowed types when we have a wildcard, but we don`t when we haven`t.

**Comment by smmribeiro** [comment]
Yes, as I said, the problem is with the wildcard handling.
And, as the change is only working with the file type, that is why I have doubts it really fixes the issue.

**Comment by LeonardoCoelho71950** [comment]
So, after talking to @smmribeiro, we realized that the bug described in https://jira.pentaho.com/browse/PDI-17922 is fixed. The question raised by him is a different one.
When we select a file in GetFileNames step, he was expecting only to be returned the folder's content, but it is returned also the select file (if the file is allowed). I wish to know if that is the expected behavior or not (@mbatchelor and @pentaho-lmartins, can you help me on that ).

**Comment by LeonardoCoelho71950** [comment]
With or without wildcard the algorithm to get the fileInputList should be the same.
When onemask is empty, the file will always be included on the list.

**Pull request merged**
