### PR TITLE
[TEST] - fixing incorrect test data after splitting was repaired in PDI-...

### PR DESCRIPTION
**Pull request by akhayrutdinov**
...12847

@mattyb149, @brosander, merge it please.
Looks like test data was incorrect from the beginning and we faced this issue after I has repaired splitting in PDI-12847

### CODE REVIEW

**Comment by brosander** [comment]
@akhayrutdinov do we have a backward compatibility flag on this? If we're changing long-standing behavior, this may break existing transformations.

**Comment by akhayrutdinov** [comment]
@brosander, what do you mean? It is just a test data. The behaviour was changed with https://github.com/pentaho/pentaho-kettle/pull/1223

**Comment by brosander** [comment]
@akhayrutdinov the need to change the test data means that behavior was changed in a way that may affect existing transformations

I'm aware that #1223 was already merged but think that we may need to bubble this up to be sure that this change won't break existing customers' transformations.

**Comment by akhayrutdinov** [comment]
@brosander, yes, if someone fitted in the incorrect behaviour (it is indeed incorrect, just check it), then #1223 indeed broke such transformations

**Pull request merged**
