### PR TITLE
[PDI-15737] File encoding setting for INI files in Property Step are ignored

### PR DESCRIPTION
**Pull request by s3b-**
File encoding has been ignored because the INI file already has been loaded when the file encoding setting was set.

### CODE REVIEW

**Comment by mbatchelor** [comment]
@s3b - Can you please fix the checkstyle issue (trailing spaces on line 449 and 452) ? I would like to process the PR, but I cannot violate wingman checkstyle fixes.

**Comment by s3b-** [comment]
Sorry, forgot about that. Fixed!

**Comment by mbatchelor** [comment]
@s3b- please rebase so we can merge.

**Comment by s3b-** [comment]
@mbatchelor Sorry - done!

**Comment by mbatchelor** [comment]
Thanks!

**Pull request merged**
