### PR TITLE
[PDI-15799] Table Input step lookup not exported to XML

### PR DESCRIPTION
**Pull request by ivanpogodin**

### CODE REVIEW

**Comment by ivanpogodin** [comment]
@mbatchelor , could you review it, please?
Checked locally for regression in PDI-14419, it looks correct

**Comment by ivanpogodin** [comment]
@mbatchelor , @pamval , @rfellows , I've updated the change, could you review it again, please?

**Comment by ivanpogodin** [comment]
@mbatchelor , @pamval , @rfellows , could you review it, please?

**Comment by mbatchelor** [comment]
@ivanpogodin - please fix newly broken test.

**Comment by ivanpogodin** [comment]
@mbatchelor , Wingman rerun shows no failed tests. Could you review it?

**Pull request merged**
