### PR TITLE
[SP-6610] Backport of PPP-5166 - Use of Vulnerable Component: Compone…

### PR DESCRIPTION
**Pull request by NJtwentyone**
…nts/jackson-databind 2.14.2 (Non OSGi upgrade) (10.2 Suite)

### CODE REVIEW

**Comment by NJtwentyone** [comment]
this will fail in wingman, this PR depends on new maven property in pentaho/maven-parent-poms#615

**Comment by buildguy** [comment]
### :x: Build failed in 1m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by soagarwal1 — APPROVED** [review]

**Comment by buildguy** [comment]
### :x: Build failed in 1m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[🚨 Frogbot scanned this pull request and found the below:](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>




---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Review by rmansoor — APPROVED** [review]

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 3h 24m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.ui.database.event.FragmentHandlerTest.org.pentaho.ui.database.event.FragmentHandlerTest</b> (click to expand)</summary><p>

```
No more handles [gtk_init_check() failed]
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTStreamSourceTest.testMQTTOpenException</b> (click to expand)</summary><p>

```
Failed to bind to server socket: mqtt://localhost:34983 due to: java.net.BindException: Address already in use
```

</p></details>

  
Tests run: **5510**, Failures: **2**, Skipped: **23** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9643/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
Failing tests look unrelated to the code changes. Merging!

**Pull request merged**
