### PR TITLE
[BACKLOG-14363,DOC] converted comment into javadoc

### PR DESCRIPTION
**Pull request by afrjorge**

### CODE REVIEW

**Comment by afrjorge** [comment]
@pentaho/bobafett please review

**Comment by annapopova1** [comment]
@afrjorge do you know how I can reproduce the case when setUrl works incorrectly and we need use another variable to store the value (lastNavigateURL)?

**Comment by afrjorge** [comment]
Revert e68db70322d3a2daab6f6de209f2b7921a66ab32, explore two steps in PDI, copy the second step URL and open in an external browser, check that the URL for the second or consecutive steps are always equal to the one of the first step.

**Comment by annapopova1** [comment]
FYI can't reproduce it on Windows. Probably OS specific behavior.

**Comment by afrjorge** [comment]
Updated comment to reflect that.

**Pull request merged**
