### PR TITLE
[PDI-14020] - Improve RowMeta: make it concurrency-correct and reduce…

### PR DESCRIPTION
**Pull request by akhayrutdinov**
… memory consumption

- re-implement RowMeta with locks to guarantee correct work in concurrent environment
- add concurrency tests

@mattyb149, @brosander, review it please.
@hudak, it can also be interesting for you

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, @deinspanjer, review it please

**Comment by akhayrutdinov** [comment]
@mattyb149, I've uploaded a screenshot with comparison of memory consumption. Take into account, that the proposal not only reduces it (it does actually, but pretty slightly), but also defends from errors in concurrent environment: run the committed test against current version to get errors.

I've updated the PR (rebased, made local class internal, verified there are no checkstyle violations and unit tests are passing). Please, review it

**Comment by akhayrutdinov** [comment]
@mattyb149, any comments on this?

**Comment by deinspanjer** [comment]
I looked at this guy last week before I went on PTO, and again yesterday afternoon.  It is a big change to a critical core area of PDI, so that makes me nervous, but it seems like a good change.

I've reached out to Casters to chat with him about it briefly.  Happy to hear feedback from @mattyb149 as well.

**Pull request merged**
