### PR TITLE
[SP-5864] Backport of PDI-18322 - KTR with MDI fails if executed on D…

### PR DESCRIPTION
**Pull request by ssamora**
…I/slave and optional target transformation specified (8.3 Suite)

cherry-pick of be2b5d0ac5e0595c583db3bcae3141e2d332c127 (from PR: https://github.com/pentaho/pentaho-kettle/pull/7847)

@bcostahitachivantara @smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/meta-inject
```
---
:ok_hand: All tests passed!
 
Tests run: **45**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7857/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PR.

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PR.

**Review by bcostahitachivantara — APPROVED** [review]
Consistent with base bug

**Pull request merged**
