### PR TITLE
PDI-8373 - Database lookup step cannot get binary data from a MySQL

### PR DESCRIPTION
**Pull request by akhayrutdinov**
@mbatchelor, review it please. I propose not to merge this PR unless all tests pass. Now, they are failing (see http://ci.pentaho.com/job/Kettle-Code_coverage/788/testReport/ for example)

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@mbatchelor, looks like all tests are passing now (http://ci.pentaho.com/view/Data%20Integration/job/kettle-code-coverage/) Review the PR please

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please. These changes were made more than a year ago - do I need to squash all commits?

**Comment by brosander** [comment]
@akhayrutdinov please squash commits and verify that unit tests, checkstyles are good and that the change still makes sense.

**Comment by akhayrutdinov** [comment]
@brosander, I've squashed the commits and introduced another test for better distinguishing two conditions: passing mySqlVariant flag and mandatoriness of ```lazyConversion``` for BINARY -> STRING conversion

**Comment by brosander** [comment]
@akhayrutdinov what about existing eoms using getLookup( boolean failOnMultipleResults )?

**Comment by akhayrutdinov** [comment]
@brosander, sorry, I do not understand - what are "eoms"?

**Comment by brosander** [comment]
it was a typo, oems

**Comment by akhayrutdinov** [comment]
@brosander, yes, you are right. I've updated the PR.
Actually, a year ago I was a comlpete newbie to the project and didn't yet know we have to keep compatibility. Since getLookup(boolean) was used in the only place, I thought I can replace it

**Comment by brosander** [comment]
@akhayrutdinov no worries, unfortunately with public methods, we have to be pretty conservative

**Comment by brosander** [comment]
seeing checkstyle errors, please ensure files you've touched are good checkstyle wise and that all unit tests are passing

**Comment by akhayrutdinov** [comment]
@brosander, done it: ran all tests (core, engine, integration) and fixed checkstyle

**Pull request merged**
