### PR TITLE
PDI-13544 - Spoon allows user to create duplicate connection and slave s...

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
...erver x

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@brosander 
Please review.

**Comment by Aliaksandr-Kastenka** [comment]
@mattyb149 
Please review.

**Comment by mattyb149** [comment]
Can you add unit tests for the changes?

**Comment by Aliaksandr-Kastenka** [comment]
@mattyb149 
Pull-request updated.

**Pull request merged**
