### PR TITLE
[PDI-14983] Schedule/run Salesforce Insert and Input steps on DI Serv…

### PR DESCRIPTION
**Pull request by ivanpogodin**
…er - java.lang.ExceptionInInitializerError
@mattcasters , @brosander , could you review it, please?

### CODE REVIEW

**Comment by brosander** [comment]
[wingman](http://10.100.11.222:8080/job/wingman-ant/425/console)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/salesforce/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/salesforce/src/org/pentaho/di/trans/steps/salesforcedelete/SalesforceDeleteMeta.java
  plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceinput/SalesforceInputMeta.java
  plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceinsert/SalesforceInsertMeta.java
  plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceupdate/SalesforceUpdateMeta.java
  plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceupsert/SalesforceUpsertMeta.java

**Comment by brosander** [comment]
@ivanpogodin I'd really prefer to remove duplicate jars if that's an option.  This is a classloader workaround which keeps unneeded code in the plugin's lib folder and could cause other issues if there are conflicts.

**Comment by brosander** [comment]
@ivanpogodin I think the right place for the fix is in the assembly, it doesn't make sense to ship multiple copies of the same jars

**Comment by ivanpogodin** [comment]
This is an assembly fix now.
pdi-client works fine, but I'm not absolutely sure about pdi-server
I've been checking...

**Comment by ivanpogodin** [comment]
@mattcasters , @brosander , could you review it, please?
This is an assembly fix.
pdi-client is configured to provide the required .jars like pdi-server
axis-saaj is left in the plugin/lib since it's not provided by pdi-server

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
ignoring wingman output as this isn't a code change, wingman doesn't deal well with top level kettle or assembly changes in ant projects atm

**Pull request merged**
