### PR TITLE
SP-2165 - Backport of PDI-13028 - Export repository with rule: Job/Transformation with Note is not exported (6.0 Suite)

### PR DESCRIPTION
**Pull request by YuryBY**
@mattcasters, @brosander, @mattyb149, @mbatchelor, here is backport of https://github.com/pentaho/pentaho-kettle/pull/1787 to 6.0 branch. Thanks.

### CODE REVIEW

**Comment by dkincade** [comment]
@pamval @brosander @mattyb149 please review...

**Comment by brosander** [comment]
@YuryBY I'm picking up checkstyle errors in PurRepositoryExporter

**Comment by YuryBY** [comment]
@brosander, thanks. Were two checkstyle errors. Already updated.

**Comment by YuryBY** [comment]
@pamval, @brosander, @mattyb149, PR is updated.Thanks.

**Pull request merged**
