### PR TITLE
[PPP-4815] - Vulnerable Component: Ini4j 0.5.1

### PR DESCRIPTION
**Pull request by renato-s**
@andreramos89 
@bcostahitachivantara 
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 32m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransTest.testPDI12424ParametersFromMetaAreCopiedToTrans</b> (click to expand)</summary><p>

```

Transformation was unable to open [null]

The transformation path ram:///parameters_775132e1-8d0b-11ed-849b-57ca45154a3e.ktr is invalid, and will not run successfully.


```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.avro.input.AvroInputMetaTest.testGetFields_unknownPluginForFieldType</b> (click to expand)</summary><p>

```
Expected exception: org.pentaho.di.core.exception.KettleStepException
```

</p></details>

  
Tests run: **4030**, Failures: **2**, Skipped: **8** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8769/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 3s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good!

**Comment by buildguy** [comment]
### :warning: Build finished in 32m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransTest.testPDI12424ParametersFromMetaAreCopiedToTrans</b> (click to expand)</summary><p>

```

Transformation was unable to open [null]

The transformation path ram:///parameters_8eb64806-902a-11ed-bcc9-51e484ebb2ad.ktr is invalid, and will not run successfully.


```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.avro.input.AvroInputMetaTest.testGetFields_unknownPluginForFieldType</b> (click to expand)</summary><p>

```
Expected exception: org.pentaho.di.core.exception.KettleStepException
```

</p></details>

  
Tests run: **4030**, Failures: **2**, Skipped: **8** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8769/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 50m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransTest.testPDI12424ParametersFromMetaAreCopiedToTrans</b> (click to expand)</summary><p>

```

Transformation was unable to open [null]

The transformation path ram:///parameters_637dcf62-9031-11ed-a69d-a5d662aeafd0.ktr is invalid, and will not run successfully.


```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.avro.input.AvroInputMetaTest.testGetFields_unknownPluginForFieldType</b> (click to expand)</summary><p>

```
Expected exception: org.pentaho.di.core.exception.KettleStepException
```

</p></details>

  
Tests run: **5265**, Failures: **2**, Skipped: **9** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8769/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
The 2 failing unit tests seem to be not related with this change (may be one of those build random failures or for wingman not building with the complete set of dependencies).
I'm merge this and will follow the official build for these tests.

**Pull request merged**
