### PR TITLE
[PDI-16790]-Miscalculation with big number data type in calculator step

### PR DESCRIPTION
**Pull request by denisprotopopov**
-fixed

### CODE REVIEW

**Comment by denisprotopopov** [comment]
@pamval @mbatchelor @bmorrise please review the changes

**Comment by denisprotopopov** [comment]
@pamval @mbatchelor @bmorrise please review the changes

**Comment by pamval** [comment]
The unit tests were wrong to start with?

**Comment by denisprotopopov** [comment]
yes, unit tests were wrong

**Pull request merged**
