### PR TITLE
[PDI-13570] - Regression: Shared DB-connections without .kdb file not sh...

### PR DESCRIPTION
**Pull request by akhayrutdinov**
...owing in Spoon 5.3

@mattyb149, @brosander review it please

### CODE REVIEW

**Comment by mattyb149** [comment]
The class and methods should be public not package-protected

**Comment by akhayrutdinov** [comment]
@mattyb149 why do you think so? The collector is a class to be used inside a procedure, I don't really believe it makes any sense to reveal it to the whole world

**Comment by mattyb149** [comment]
Our coding standards discourage package protection in favor of explicit protected access. This is usually to make the access level clear. If package-protected is the best choice, then the class and each method must be documented as such (Javadoc)

**Comment by mattyb149** [comment]
I recommended public access because it appears generally useful. Even if we only call it once from the same package, other people who embed PDI would be able to use it as they see fit :)

**Comment by akhayrutdinov** [comment]
@mattyb149, I've updated the PR

**Comment by mattyb149** [comment]
Cool, thanks!

**Pull request merged**
