### PR TITLE
[TEST] - Updated spring-security  in pdi-pure-plugin's tests in order to fix their failings

### PR DESCRIPTION
**Pull request by ArtsiomYurhevich**
The problem was that the tests used 2.0.8 spring-security while the pentaho-platform's modules are referenced by this plugin had been already updated to 4 version and 2.0.8 spring-core tried to load defined in pentaho-platform configs intended for 4 spring-security

### CODE REVIEW

**Comment by dkincade** [comment]
@ArtsiomYurhevich  Please provide JIRA case information on this PR...

**Comment by lucboudreau** [comment]
@pedrofvteixeira Hi Pedro. Please have someone review this PR. Did you guys miss this plugin when upgrading Spring? :)

**Comment by ArtsiomYurhevich** [comment]
@dkincade, This pr fixes IT tests for pdi-pur-plugin. The cause of the tests' failings was leaving the plugin with non updated spring-security while the modules are referenced by this plugin were already updated to 4 version.

**Comment by lucboudreau** [comment]
@ArtsiomYurhevich Please update this PR to use a commit message which starts with the prefix "[TEST]". Thanks!

**Comment by ArtsiomYurhevich** [comment]
fixed checkstyle

**Comment by pedrofvteixeira** [comment]
@lucboudreau @dkincade looks like this fell through the cracks.. @ArtsiomYurhevich thank you for tackling this! 👍 

PR looks good to me and Wingman is happy. Merging.

**Comment by dkincade** [comment]
If @pedrofvteixeira says it is good ... oh wait ... he already jumped in and said it was. Hurray! 🍾

**Pull request merged**
