### PR TITLE
[PDI-17007] Issues with Carte Jobs API startJob endpoint in Pentaho R…

### PR DESCRIPTION
**Pull request by smmribeiro**
…EST API

It now returns the following codes:
- 200 (OK) when all goes well
- 404 (NOT_FOUND) when the job is not found
- 400 (BAD_REQUEST) when there're problems with parameters
- 500 (SERVER_ERROR) when an unexpected error occurs

@pentaho-lmartins @ssamora @ppatricio @bcostahitachivantara

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 48m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 20 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testJsonInputExternalResourceConsumer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetUsedFields_isNotAcceptingFilenames</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testCloneAnalyzer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetUsedFields_fileNameFromField</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetSupportedSteps</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testIsOutput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetResourceOutputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testNewInstance</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetResourceInputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testIsInput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testCloneAnalyzer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testJsonOutputExternalResourceConsumer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testGetSupportedSteps</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testIsOutput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testGetResourceOutputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testNewInstance</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testGetResourceInputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testIsInput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.getxmldata.GetXMLDataStepAnalyzerTest.testCreateResourceNode</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.metaverse.api.analyzer.kettle.KettleAnalyzerUtil
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.xmloutput.XMLOutputStepAnalyzerTest.testCreateResourceNode</b> (click to expand)</summary><p>

```
org/osgi/framework/ServiceFactory
```

</p></details>

  
Tests run: **3754**, Failures: **20**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7547/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 33m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 20 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testJsonInputExternalResourceConsumer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetUsedFields_isNotAcceptingFilenames</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testCloneAnalyzer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetUsedFields_fileNameFromField</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetSupportedSteps</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testIsOutput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetResourceOutputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testNewInstance</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetResourceInputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testIsInput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testCloneAnalyzer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testJsonOutputExternalResourceConsumer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testGetSupportedSteps</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testIsOutput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testGetResourceOutputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testNewInstance</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testGetResourceInputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testIsInput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.getxmldata.GetXMLDataStepAnalyzerTest.testCreateResourceNode</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.metaverse.api.analyzer.kettle.KettleAnalyzerUtil
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.xmloutput.XMLOutputStepAnalyzerTest.testCreateResourceNode</b> (click to expand)</summary><p>

```
org/osgi/framework/ServiceFactory
```

</p></details>

  
Tests run: **3754**, Failures: **20**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7547/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 3m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **585**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7547/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 31m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 20 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testJsonInputExternalResourceConsumer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetUsedFields_isNotAcceptingFilenames</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testCloneAnalyzer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetUsedFields_fileNameFromField</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetSupportedSteps</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testIsOutput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetResourceOutputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testNewInstance</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetResourceInputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testIsInput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testCloneAnalyzer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testJsonOutputExternalResourceConsumer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testGetSupportedSteps</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testIsOutput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testGetResourceOutputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testNewInstance</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testGetResourceInputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testIsInput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.getxmldata.GetXMLDataStepAnalyzerTest.testCreateResourceNode</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.metaverse.api.analyzer.kettle.KettleAnalyzerUtil
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.xmloutput.XMLOutputStepAnalyzerTest.testCreateResourceNode</b> (click to expand)</summary><p>

```
org/osgi/framework/ServiceFactory
```

</p></details>

  
Tests run: **3754**, Failures: **20**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7547/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 38m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 20 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testJsonInputExternalResourceConsumer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetUsedFields_isNotAcceptingFilenames</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testCloneAnalyzer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetUsedFields_fileNameFromField</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetSupportedSteps</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testIsOutput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetResourceOutputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testNewInstance</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testGetResourceInputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.analyzer.JsonInputAnalyzerTest.testIsInput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testCloneAnalyzer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testJsonOutputExternalResourceConsumer</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testGetSupportedSteps</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testIsOutput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testGetResourceOutputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testNewInstance</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testGetResourceInputNodeType</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsonoutput.analyzer.JsonOutputAnalyzerTest.testIsInput</b> (click to expand)</summary><p>

```
org/springframework/security/core/Authentication
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.getxmldata.GetXMLDataStepAnalyzerTest.testCreateResourceNode</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.metaverse.api.analyzer.kettle.KettleAnalyzerUtil
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.xmloutput.XMLOutputStepAnalyzerTest.testCreateResourceNode</b> (click to expand)</summary><p>

```
org/osgi/framework/InvalidSyntaxException
```

</p></details>

  
Tests run: **4922**, Failures: **20**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7547/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 32m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3759**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7547/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Comment by pentaho-lmartins** [comment]
Closing in favor of #7585.

**Pull request closed without merging**
