### PR TITLE
[SP-6599]- Backport of Vulnerable Avro component changes.

### PR DESCRIPTION
**Pull request by nawaz34-hitachivantara**

### CODE REVIEW

**Review by smmribeiro — APPROVED** [review]
Consistent with the original code.

**Comment by buildguy** [comment]
### :x: Build failed in 1m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
plugins/avro-format/core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
plugins/avro-format/core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 49s
Build command:
```console
mvn deploy -B -e -Daudit -U -Drelease -pl plugins/avro-format/core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 9m 13s
Build command:
```console
mvn deploy -B -e -Daudit -U -Drelease -pl plugins/avro-format/core
```
---
:ok_hand: All tests passed!
 
Tests run: **41**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9597/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by smmribeiro** [comment]
As this PR was inadvertently closed, I've recreated it: [pentaho-kettle#9603](https://github.com/pentaho/pentaho-kettle/pull/9603)

**Pull request closed without merging**
