### PR TITLE
[PDI-17350] Row denormaliser : Specifying Internet Address as the data type causes an error.

### PR DESCRIPTION
**Pull request by smmribeiro**
@renato-s @andreramos89

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4512**, Failures: **0**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/vc-pdi/job/PR-9211/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 22m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl core
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 44m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **5367**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9211/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by renato-s — APPROVED** [review]

**Review by andreramos89 — APPROVED** [review]
Looks good.

**Pull request merged**
