### PR TITLE
PDI-19750: Database lookup step fetches incorrect data from the database

### PR DESCRIPTION
**Pull request by hv-shiva**
Due to thread concurrency issue, Database::getRow is fetching incorrect data. This method is being called by both Table Input step and Database Lookup step.

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 40m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 10 test(s) failed:

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_LowResourceMaxIdleTimeSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_LowResourceMaxIdleTimeSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptQueueSizeSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptQueueSizeSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptorsSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptorsSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsEmpty</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsEmpty</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsInvalidValue</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsInvalidValue</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **5320**, Failures: **10**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9077/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 33m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 10 test(s) failed:

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_LowResourceMaxIdleTimeSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_LowResourceMaxIdleTimeSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptQueueSizeSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptQueueSizeSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptorsSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptorsSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsEmpty</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsEmpty</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsInvalidValue</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsInvalidValue</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **5320**, Failures: **10**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9077/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 27m 27s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 10 test(s) failed:

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_LowResourceMaxIdleTimeSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_LowResourceMaxIdleTimeSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptQueueSizeSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptQueueSizeSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptorsSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptorsSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsEmpty</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsEmpty</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsInvalidValue</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsInvalidValue</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **5320**, Failures: **10**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9077/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 58m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 10 test(s) failed:

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_LowResourceMaxIdleTimeSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_LowResourceMaxIdleTimeSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptQueueSizeSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptQueueSizeSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptorsSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptorsSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsEmpty</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsEmpty</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsInvalidValue</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsInvalidValue</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **5320**, Failures: **10**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9077/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 56m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 10 test(s) failed:

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_LowResourceMaxIdleTimeSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_LowResourceMaxIdleTimeSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptQueueSizeSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptQueueSizeSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptorsSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptorsSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsEmpty</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsEmpty</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsInvalidValue</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsInvalidValue</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **5320**, Failures: **10**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9077/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 45m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.core.util.AsyncDatabaseActionTest.getSchemas</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.core.util.AsyncDatabaseActionTest.executeAction</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **5315**, Failures: **2**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9077/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 32m
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **5315**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9077/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by hv-shiva** [comment]
> There are two commits here, there should only be one. Please squash them together. Also, the commit message should start with [PDI-19750] including the square brackets; they are important. You can use git rebase to squash the commits together and git commit --amend to update the commit message, then push to either a different branch and open a new PR or force push to this branch.

Raised a new PR - https://github.com/pentaho/pentaho-kettle/pull/9089
Hence Closing this PR

**Pull request closed without merging**
