### PR TITLE
[SP-2204][PDI-14375] - Incorrect time displayed in Version History af…

### PR DESCRIPTION
**Pull request by SergeyTravin**
…ter some operations with transformation/jobs in the DI repository

- clear "createdDate" on renaming to force the repository to inject current time
- update tests to check this condition

Conflicts:
	plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_MoveAndRename_IT.java

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@brosander could you review its backport for https://github.com/pentaho/pentaho-kettle/pull/1883
when you have a chance?

Thanks!

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found






Still Broken Tests:
-----------------
com.pentaho.pdi.ws.RepositorySyncWebServiceClientIT: java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: org/pentaho/platform/api/engine/IPentahoObjectFactory
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
Caused by: java.lang.ClassNotFoundException: org.pentaho.platform.api.engine.IPentahoObjectFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

```
org.pentaho.di.repository.pur.PurRepositoryIT: java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: org/pentaho/platform/api/repository2/unified/RepositoryFilePermission
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
Caused by: java.lang.ClassNotFoundException: org.pentaho.platform.api.repository2.unified.RepositoryFilePermission
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

```

Unit test coverage change:
============
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange :**-0.00%**

**Comment by SergeyTravin** [comment]
The Still broken Tests should be fixed with https://github.com/SergeyTravin/pentaho-kettle/commit/ba962993924f3dadc288825e0b55361ab24077b8 from 
https://github.com/pentaho/pentaho-kettle/pull/1894

**Comment by akhayrutdinov** [comment]
@brosander, review it after #1894 please

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found






Still Broken Tests:
-----------------
com.pentaho.pdi.ws.RepositorySyncWebServiceClientIT: java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: org/pentaho/platform/api/engine/IPentahoObjectFactory
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
Caused by: java.lang.ClassNotFoundException: org.pentaho.platform.api.engine.IPentahoObjectFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

```
org.pentaho.di.repository.pur.PurRepositoryIT: java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: org/pentaho/platform/api/repository2/unified/RepositoryFilePermission
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
Caused by: java.lang.ClassNotFoundException: org.pentaho.platform.api.repository2.unified.RepositoryFilePermission
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

```

Unit test coverage change:
============
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange :**-0.00%**

**Comment by brosander** [comment]
reviewed, will run wingman after #1894

**Comment by brosander** [comment]
Rebased in https://github.com/pentaho/pentaho-kettle/pull/1901

**Pull request closed without merging**
