### PR TITLE
[BACKLOG-21008] Yarn job hangs in Transformation step set with run

### PR DESCRIPTION
**Pull request by mchen-len-son**
configuration Clusterd & never ends
 - replaced LinkedBlockingDeque with a plain ArrayList defended by
   ReadWriteLock, as LBD is not fully thread-safe due to bug in JDK.
   Also, LBD does not seem to be the right collection for LoggingBuffer
   (for exmaple, even though it is backed by linked list, iterator.remove
   runs in a linear time).
 - added concurrent test for logging buffer
 - moved ConcurrentTestRunner utility to the core module
 - added test jar to core module to be used by engine module, since it still needs
   ConcurrentTestRunner

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@mbatchelor @pamval please review

**Comment by mchen-len-son** [comment]
@mbatchelor @pamval please review

**Comment by mchen-len-son** [comment]
@mbatchelor @pamval @bmorrise please review

**Comment by mchen-len-son** [comment]
@VasilinaTerehova can you please have a look?

**Comment by VasilinaTerehova** [comment]
Looks ok

**Pull request merged**
