### PR TITLE
[SP-4018][PDI-16819]-Copying a Timestamp to result cannot be de-serialized whe…

### PR DESCRIPTION
**Pull request by SergeyTravin**
…n running on Slave Server

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@mchen-len-son, @mbatchelor  Could you please review. It is backport for https://github.com/pentaho/pentaho-kettle/pull/4704

**Comment by mchen-len-son** [comment]
@SergeyTravin please fix checkstyle issues

**Comment by mchen-len-son** [comment]
@SergeyTravin also, please specify SP case number in the commit message

**Comment by SergeyTravin** [comment]
@mchen-len-son The checkstyle was fixed.  Could you please review. It is backport for #4704

**Pull request merged**
