### PR TITLE
[BACKLOG-9100] Pluginize the Metadata Injection step

### PR DESCRIPTION
**Pull request by bmorrise**

### CODE REVIEW

**Comment by bmorrise** [comment]
This pull request removes the metadata inject step from kettle and creates a plugin. There is a pull request which adds the new osgi-based plugin to the assembly here: https://github.com/pentaho/pentaho-karaf-assembly/pull/204

**Comment by bmorrise** [comment]
@mdamour1976

**Comment by lucboudreau** [comment]
@bmorrise Are you sure this PR is good to go? Seems like an enormous drop of coverage across the board. Is this intended?

**Comment by bmorrise** [comment]
A bunch of tests were moved into the new plugin, which are being run and really, very little new code was added, so I'm wondering if the metrics are being calculated properly.

**Comment by lucboudreau** [comment]
I think you're right. Wingman built core and engine, but not plugin, so the coverage has not been calculated correctly.

**Comment by matthewtckr** [comment]
@bmorrise Was the dialog class (MetaInjectDialog) also supposed to be moved to the plugin?  It appears to still be in the UI module

**Comment by bmorrise** [comment]
@matthewtckr It is in the plugin, but yeah, it looks like it wasn't removed from ui when this work was done. I'll pull it out of there.

**Comment by lucboudreau** [comment]
@bmorrise @mdamour1976 Seems that this change broke the master branch.

https://github.com/pentaho/pentaho-kettle/pull/2717#issuecomment-235363987
https://github.com/pentaho/pentaho-kettle/pull/2710#issuecomment-235364363

**Pull request merged**
