### PR TITLE
  [PDI-11018] getXMLData - Variables are overwritten

### PR DESCRIPTION
**Pull request by e-cuellar**
@bmorrise Please Sir!

### CODE REVIEW

**Comment by lucboudreau** [comment]
Probably needs a test.

**Comment by e-cuellar** [comment]
@lucboudreau Should be easy to write... I am on it!

**Comment by e-cuellar** [comment]
@bmorrise Test done... Please Sir!

**Comment by bmorrise** [comment]
Running wingman: http://10.100.11.222:8080/job/wingman-ant/433/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-xml-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/getxmldata/GetXMLData.java
  plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/getxmldata/GetXMLDataTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/getxmldata/GetXMLDataTest.java
1. Message: 'array initialization lcurly' have incorrect indentation level 8, expected level should be 4. at Line: 111 Column: None









Unit test coverage change:
============
org.pentaho.di.trans.steps.getxmldata.GetXMLData:
 * instructionPercentCoverageChange : +0.59%
 * branchPercentCoverageChange : +0.12%
 * linePercentCoverageChange : +1.03%
 * complexityPercentCoverageChange : +0.05%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-xml-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/getxmldata/GetXMLData.java
  plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/getxmldata/GetXMLDataTest.java










Unit test coverage change:
============
org.pentaho.di.trans.steps.getxmldata.GetXMLData:
 * instructionPercentCoverageChange : +0.59%
 * branchPercentCoverageChange : +0.12%
 * linePercentCoverageChange : +1.03%
 * complexityPercentCoverageChange : +0.05%

**Pull request merged**
