### PR TITLE
[PDI-19759] Authentication methods are showing information on clear text when using Redshift connection type

### PR DESCRIPTION
**Pull request by Mandakini111**

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 45m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,dbdialog
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.core.database.DatabaseMetaTest.supportsOptionalExtraOptions</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.core.database.RedshiftDatabaseMetaTest.testGetURL</b> (click to expand)</summary><p>

```
expected:<[myid]> but was:<[]>
```

</p></details>

  
Tests run: **5329**, Failures: **2**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9138/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by peterrinehart — CHANGES_REQUESTED** [review]
Please update the copyright headers in these files.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 47m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,dbdialog
```
---
:ok_hand: All tests passed!
 
Tests run: **5329**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9138/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 43m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,dbdialog
```
---
:ok_hand: All tests passed!
 
Tests run: **5329**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9138/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
