### PR TITLE
[TEST] - Added missing spring dependencies into the pdi-pur-plugin's test scope

### PR DESCRIPTION
**Pull request by ArtsiomYurhevich**

### CODE REVIEW

**Comment by mbatchelor** [comment]
@ArtsiomYurhevich  - the new dependency was not found:
org.springframework.security#spring-security-core;3.2.14.RELEASE: not found

**Comment by ArtsiomYurhevich** [comment]
@mbatchelor , Fixed the version

**Comment by ArtsiomYurhevich** [comment]
@pamval Review, please

**Comment by mchen-len-son** [comment]
Tested locally. Merging.

**Comment by pamval** [comment]
thanks, @ArtsiomYurhevich !

**Pull request merged**
