### PR TITLE
[BACKLOG-35866] VariableSubstitution for pvfs

### PR DESCRIPTION
**Pull request by tkafalas**

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 6m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,plugins/connections/ui,plugins/file-open-save-new/api,plugins/file-open-save-new/core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 9m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,plugins/connections/ui,plugins/file-open-save-new/api,plugins/file-open-save-new/core,ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 9m 27s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,plugins/connections/ui,plugins/file-open-save-new/api,plugins/file-open-save-new/core,ui
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by ddiroma — APPROVED** [review]

**Pull request merged**
