### PR TITLE
[SP-1849] Backport of PDI-12593 - JobEntrySFTP (Get a File with SFTP)…

### PR DESCRIPTION
**Pull request by ivanpogodin**
… fails (5.4 Suite)
@brosander, @mattyb149, could you review it?

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please

**Comment by brosander** [comment]
@ivanpogodin  please rebase and run checkstyles, unit tests

**Comment by ivanpogodin** [comment]
@mattyb149, @brosander, review it please
rebased, resolved conflicts, checked style

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, @deinspanjer, review it please

**Pull request merged**
