### PR TITLE
[PDI-12749] - PMR: Bad Results in Group-By if an entire key is filtered earlier

### PR DESCRIPTION
**Pull request by akhayrutdinov**
@mattyb149, @brosander, review it please

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, @mattcasters, review it please

**Comment by brosander** [comment]
@akhayrutdinov I'm seeing 4 checkstyle errors in GroupByMeta

**Comment by akhayrutdinov** [comment]
@brosander, I've eliminated all warnings. Take a look again, please

**Comment by brosander** [comment]
@akhayrutdinov I'm still seeing the 4 checkstyle warnings (albeit at different indentation levels)

**Comment by akhayrutdinov** [comment]
@brosander, what  ruleset are you using? I doublechecked GroupByMeta.java with the latest version (https://github.com/pentaho/pentaho-coding-standards/blob/master/pentaho_checkStyle.xml) and it showed no errors

**Comment by brosander** [comment]
@akhayrutdinov I'm running the ant task:
ant clean-checkstyle checkstyle

It appears to be using:
http://ci.pentaho.com/job/pentaho-coding-standards/lastSuccessfulBuild/artifact/pentaho_checkStyle.xml

**Comment by akhayrutdinov** [comment]
@brosander, I've update this PR. Review it please
Dunno why it happened so: the output of inspection run from Intelij differs from the output produced by Ant task

**Comment by mdamour1976** [comment]
@brosander @akhayrutdinov @mattyb149 This pull request seems to be breaking downstream big-data-plugin unit tests.

**Pull request merged**
