### PR TITLE
[PDI-13967] adding sampling level to Google Analytics Input Step

### PR DESCRIPTION
**Pull request by DavidStanitzki**

### CODE REVIEW

**Comment by mbatchelor** [comment]
Without tests covering the new contribution, I cannot merge it in lest it regress in functionality without being detectable. Please create new tests for this in the existing test-src/org/pentaho/di/trans/steps/googleanalytics/GaInputStepTest and GaInputStepMetaTest.

**Comment by DavidStanitzki** [comment]
Thank you for your feedback. At first I have to read something about JUnit. At the moment I'm not qualified to create Unit Tests.
Maybe this will take some days.

**Comment by DavidStanitzki** [comment]
I've resolved the merge conflict to the actual master.
I added a small snippet to test-src/org/pentaho/di/trans/steps/googleanalytics/GaInputStepMetaTest but still no new test cases. I'm still looking for some free time.

**Comment by DavidStanitzki** [comment]
I added a new test case in GaInputStepTest. Please give me a hint if it is not worth and/or s.th. else is required.

**Comment by MrMauricioLeite** [comment]
+1
This feature is really useful, can someone help @DavidStanitzki with the unit tests?

**Comment by thijsvdanker** [comment]
Good job @DavidStanitzki, wish I could help out but my JUnit skills are below par.

**Comment by matthewtckr** [comment]
Rebased and submitted as #2628

**Comment by mbatchelor** [comment]
Thank-you so much for your contribution. Worked this through to completion with Matt Tucker on #2628 . Closing this PR.

**Pull request closed without merging**
