### PR TITLE
[PDI-14413] Step Synchronize after merge - issue with mode "use batch…

### PR DESCRIPTION
**Pull request by SergeyTravin**
… update"

- return the dispose method, it is allow to free resource in unexpected situation

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@kolinus, please review it.

**Comment by SergeyTravin** [comment]
@tgf, @pamval could you start wingman on this please?

**Comment by pamval** [comment]
running

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMerge.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeIT.java










Unit test coverage change:
============
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange : +0.18%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange :**-0.53%**
    
org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * instructionPercentCoverageChange : +0.07%
    
org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * instructionPercentCoverageChange :**-2.43%**
 * branchPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-3.70%**
 * complexityPercentCoverageChange :**-0.69%**
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +0.19%
 * linePercentCoverageChange : +0.27%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +1.94%
    
Integration test coverage change:
============
org.pentaho.di.trans.Trans:
 * instructionPercentCoverageChange : +0.70%
 * branchPercentCoverageChange : +0.40%
 * linePercentCoverageChange : +0.86%
 * complexityPercentCoverageChange : +0.28%
 * methodPercentCoverageChange : +0.48%
    
org.pentaho.di.trans.step.RunThread:
 * instructionPercentCoverageChange : +0.15%
 * branchPercentCoverageChange : +2.00%
 * linePercentCoverageChange : +1.85%
 * complexityPercentCoverageChange : +3.57%
    
org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMerge:
 * instructionPercentCoverageChange : +0.25%
 * branchPercentCoverageChange : +0.36%
 * linePercentCoverageChange : +0.35%
 * complexityPercentCoverageChange : +0.71%
 * methodPercentCoverageChange : +0.91%
    
org.pentaho.di.trans.step.BaseStep:
 * instructionPercentCoverageChange : +0.68%
 * branchPercentCoverageChange : +1.33%
 * linePercentCoverageChange : +1.22%
 * complexityPercentCoverageChange : +2.00%
 * methodPercentCoverageChange : +2.44%

**Comment by SergeyTravin** [comment]
@kolinus, the wingman result are presented below. The checkstyle violations does not exist. All the test are passed. Could you review it?

**Pull request merged**
