### PR TITLE
[PDI-20172] - Avoid trans from finishing more than once

### PR DESCRIPTION
**Pull request by rparaujo**

### CODE REVIEW

**Comment by buildguy** [comment]
<div align='center'>

[🚨 Frogbot scanned this pull request and found the below:](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>




---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

```
classLoader.getResource( filename )
```
at `core/src/main/java/org/pentaho/di/laf/OverlayProperties.java` (line 65)


[comment]: <> (FrogbotReviewComment)


## 🎯 Static Application Security Testing (SAST) Vulnerability
<div align='center'>

| Severity                | Finding                  |
| :---------------------: | :-----------------------------------: |
| <br>  Medium | Stored Path Traversal |

</div>

<details>
<summary> <b>Full description</b> </summary>
<br>


### Overview
Path traversal, also known as directory traversal, is a type of
vulnerability that allows an attacker to access files or directories on a
computer or device that are outside of the intended directory.
Allowing arbitrary read access can allow the attacker to read sensitive
files, such as configuration files or sensitive data, potentially leading
data loss or even system compromise. Allowing arbitrary write access is
more severe and in most cases leads to arbitrary code execution, via
editing important system files or sensitive data.

### Vulnerable example
```java
public class path_traversaLvuln {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String DOCS_FOLDER = "/srv/www/docs";
        String docName = statement.executeQuery(query);  // Reading from DB
        Path docPath = Paths.get(DOCS_FOLDER, docName);
        File docFile = docPath.toFile();
        FileUtils.copyFile(docFile, response.getOutputStream());
    }
}
```
In this example, an attacker can, via a stored parameter, inject a back-path,
that will get anywhere in the system, using "../../".

### Remediation
```diff
public class path_traversal_safe {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String DOCS_FOLDER = "/srv/www/docs";
        String docName = statement.executeQuery(query);  // Reading from DB
        Path docPath = Paths.get(DOCS_FOLDER, docName);
        + Path normDocPath = docPath.normalize();
        + // Make sure the canonical path resides in the desired dir
        + if (normDocPath.startsWith(DOCS_FOLDER)) {
            File docFile = docPath.toFile();
            FileUtils.copyFile(docFile, response.getOutputStream());
        + }
    }
}
```
By checking that the folder name still starts with the predefined prefix, we
make sure that the attacker is not able to back-path outside of the allowed
folder.


</details>

<details>
<summary> <b>Code Flows</b> </summary>
<br>


<details>
<summary> <b>Vulnerable data flow analysis result</b> </summary>
<br>


↘️ `System.getProperty( variable, deflt )` (at core/src/main/java/org/pentaho/di/core/Const.java line 2634)

↘️ `return System.getProperty( variable, deflt );` (at core/src/main/java/org/pentaho/di/core/Const.java line 2634)

↘️ `Const.getEnvironmentVariable( "org.pentaho.di.laf.alt", null )` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 54)

↘️ `altFile` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 54)

↘️ `loadProps( altFile )` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 56)

↘️ `String filename` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 86)

↘️ `new OverlayProperties( filename )` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 88)

↘️ `public class OverlayProperties extends Properties implements PropertyHandler {

  private static final long serialVersionUID = 1L;
  private String name = null;

  public OverlayProperties( String file ) throws IOException {
    load( file );
  }

  @Override
  public boolean exists( String filename ) {
    try {
      return ( getURL( filename ) != null );
    } catch ( MalformedURLException e ) {
      return false;
    }
  }

  @Override
  public boolean loadProps( String filename ) {
    try {
      return load( filename );
    } catch ( IOException e ) {
      return false;
    }
  }

  private URL getURL( String filename ) throws MalformedURLException {
    URL url;
    File file = new File( filename );
    if ( file.exists() ) {
      url = file.toURI().toURL();
    } else {
      ClassLoader classLoader = getClass().getClassLoader();
      url = classLoader.getResource( filename );
    }
    return url;
  }

  /**
   * cleanse and reload the property file
   *
   * @param filename
   * @return
   * @throws IOException
   */
  public boolean load( String filename ) throws IOException {
    URL url = getURL( filename );
    if ( url == null ) {
      return false;
    }
    clear();
    load( url.openStream() );
    return true;
  }

  public String getName() {
    return name;
  }
}` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 31)

↘️ `String file` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 36)

↘️ `load( file )` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 37)

↘️ `String filename` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 77)

↘️ `getURL( filename )` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 78)

↘️ `String filename` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 58)

↘️ `classLoader.getResource( filename )` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 65)


</details>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

```
new File( filename )
```
at `core/src/main/java/org/pentaho/di/laf/OverlayProperties.java` (line 60)


[comment]: <> (FrogbotReviewComment)


## 🎯 Static Application Security Testing (SAST) Vulnerability
<div align='center'>

| Severity                | Finding                  |
| :---------------------: | :-----------------------------------: |
| <br>  Medium | Stored Path Traversal |

</div>

<details>
<summary> <b>Full description</b> </summary>
<br>


### Overview
Path traversal, also known as directory traversal, is a type of
vulnerability that allows an attacker to access files or directories on a
computer or device that are outside of the intended directory.
Allowing arbitrary read access can allow the attacker to read sensitive
files, such as configuration files or sensitive data, potentially leading
data loss or even system compromise. Allowing arbitrary write access is
more severe and in most cases leads to arbitrary code execution, via
editing important system files or sensitive data.

### Vulnerable example
```java
public class path_traversaLvuln {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String DOCS_FOLDER = "/srv/www/docs";
        String docName = statement.executeQuery(query);  // Reading from DB
        Path docPath = Paths.get(DOCS_FOLDER, docName);
        File docFile = docPath.toFile();
        FileUtils.copyFile(docFile, response.getOutputStream());
    }
}
```
In this example, an attacker can, via a stored parameter, inject a back-path,
that will get anywhere in the system, using "../../".

### Remediation
```diff
public class path_traversal_safe {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String DOCS_FOLDER = "/srv/www/docs";
        String docName = statement.executeQuery(query);  // Reading from DB
        Path docPath = Paths.get(DOCS_FOLDER, docName);
        + Path normDocPath = docPath.normalize();
        + // Make sure the canonical path resides in the desired dir
        + if (normDocPath.startsWith(DOCS_FOLDER)) {
            File docFile = docPath.toFile();
            FileUtils.copyFile(docFile, response.getOutputStream());
        + }
    }
}
```
By checking that the folder name still starts with the predefined prefix, we
make sure that the attacker is not able to back-path outside of the allowed
folder.


</details>

<details>
<summary> <b>Code Flows</b> </summary>
<br>


<details>
<summary> <b>Vulnerable data flow analysis result</b> </summary>
<br>


↘️ `System.getProperty( variable, deflt )` (at core/src/main/java/org/pentaho/di/core/Const.java line 2634)

↘️ `return System.getProperty( variable, deflt );` (at core/src/main/java/org/pentaho/di/core/Const.java line 2634)

↘️ `Const.getEnvironmentVariable( "org.pentaho.di.laf.alt", null )` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 54)

↘️ `altFile` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 54)

↘️ `loadProps( altFile )` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 56)

↘️ `String filename` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 86)

↘️ `new OverlayProperties( filename )` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 88)

↘️ `public class OverlayProperties extends Properties implements PropertyHandler {

  private static final long serialVersionUID = 1L;
  private String name = null;

  public OverlayProperties( String file ) throws IOException {
    load( file );
  }

  @Override
  public boolean exists( String filename ) {
    try {
      return ( getURL( filename ) != null );
    } catch ( MalformedURLException e ) {
      return false;
    }
  }

  @Override
  public boolean loadProps( String filename ) {
    try {
      return load( filename );
    } catch ( IOException e ) {
      return false;
    }
  }

  private URL getURL( String filename ) throws MalformedURLException {
    URL url;
    File file = new File( filename );
    if ( file.exists() ) {
      url = file.toURI().toURL();
    } else {
      ClassLoader classLoader = getClass().getClassLoader();
      url = classLoader.getResource( filename );
    }
    return url;
  }

  /**
   * cleanse and reload the property file
   *
   * @param filename
   * @return
   * @throws IOException
   */
  public boolean load( String filename ) throws IOException {
    URL url = getURL( filename );
    if ( url == null ) {
      return false;
    }
    clear();
    load( url.openStream() );
    return true;
  }

  public String getName() {
    return name;
  }
}` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 31)

↘️ `String file` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 36)

↘️ `load( file )` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 37)

↘️ `String filename` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 77)

↘️ `getURL( filename )` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 78)

↘️ `String filename` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 58)

↘️ `new File( filename )` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 60)


</details>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3h 16m 41s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **2325**, Failures: **0**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9550/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ssamora — APPROVED** [review]

**Pull request merged**
