### PR TITLE
PDI-14055 - 5.3 Transformation cannot be read from repository after import

### PR DESCRIPTION
**Pull request by YuryBY**
@mattcasters, @brosander, @mattyb149, would you mind of reviewing/merging

### CODE REVIEW

**Comment by mattyb149** [comment]
MetaInjectMeta implements StepMetaChangeListenerInterface. How does the added test check the new condition (index != -1)? Also there are no assert statements in the new test, is an exception expected if for some reason the code changes in the future?

**Comment by brosander** [comment]
@YuryBY also seeing checkstyle violations in TransMeta and TransMetaTest

**Comment by YuryBY** [comment]
@mattcasters, @brosander, @mattyb149, PR already updated.
1) @mattyb149, assertions is added in order to show method running succesfully. 
2) @brosander, the code was changed according to checkstyle.
@mattyb149, idea here https://github.com/pentaho/pentaho-kettle/pull/1607/files#diff-fce300191b26a16dd436b81a05baf840R140 is to ensure that we entered to https://github.com/YuryBY/pentaho-kettle/blob/PDI-14055/engine/src/org/pentaho/di/trans/TransMeta.java#L856 before fix.

**Comment by pamval** [comment]
@mattyb149 can you review the altered pr and merge ?

**Comment by pamval** [comment]
@YuryBY this has merge conflicts now.. Please rebase and reissue

**Comment by mattyb149** [comment]
Please rebase against the latest master branch. Also when I ran the engine's unit tests I got a failure in TransMetaTest.testAddOrReplaceStep() that might be related to this change, please investigate. Thanks!

**Pull request closed without merging**
