### PR TITLE
[PDI-14999] - ‘Split Field to Rows’ step fails with NullPointerException after import into repository

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- manually handle `null` value of `delimiter` property

@pamval, @pedrofvteixeira, start WM for this PR please

### CODE REVIEW

**Comment by pedrofvteixeira** [comment]
[wingman](http://10.100.11.222:8080/job/wingman-ant/402)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/splitfieldtorows/SplitFieldToRows.java
  engine/test-src/org/pentaho/di/trans/steps/splitfieldtorows/SplitFieldToRowsTest.java










Unit test coverage change:
============
org.pentaho.di.trans.steps.splitfieldtorows.SplitFieldToRows:
 * branchPercentCoverage :5.26%
 * linePercentCoverage :16.67%
 * methodPercentCoverage :60.00%
 * complexityPercentCoverage :12.50%
 * instructionPercentCoverage :13.99%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange : +0.53%
    
org.pentaho.di.trans.steps.splitfieldtorows.SplitFieldToRowsData:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * instructionPercentCoverageChange : +2.43%
 * branchPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +2.95%
 * complexityPercentCoverageChange : +0.69%

**Comment by akhayrutdinov** [comment]
@mtseu, @PavelSakoun, @brosander, review it please

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/splitfieldtorows/SplitFieldToRows.java
  engine/test-src/org/pentaho/di/trans/steps/splitfieldtorows/SplitFieldToRowsTest.java










Unit test coverage change:
============
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange : +0.08%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange :**-0.53%**
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange : +7.14%
 * complexityPercentCoverageChange : +7.69%
    
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange :**-0.17%**
    
org.pentaho.di.trans.steps.splitfieldtorows.SplitFieldToRows:
 * branchPercentCoverage :5.26%
 * linePercentCoverage :16.67%
 * methodPercentCoverage :60.00%
 * complexityPercentCoverage :12.50%
 * instructionPercentCoverage :13.99%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange :**-3.28%**
 * linePercentCoverageChange :**-3.95%**
    
org.pentaho.di.trans.steps.splitfieldtorows.SplitFieldToRowsData:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%

**Pull request merged**
