### PR TITLE
[BACKLOG-5396] Additional file input steps tests

### PR DESCRIPTION
**Pull request by AlexanderBuloichik**

### CODE REVIEW

**Comment by mdamour1976** [comment]
Changed files:
==============
  engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputContentParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/csvinput/files/default.csv
  engine/test-src/org/pentaho/di/trans/steps/csvinput/files/semicolon.csv
  engine/test-src/org/pentaho/di/trans/steps/excelinput/BaseExcelParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputContentParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/excelinput/ods/.gitattributes
  engine/test-src/org/pentaho/di/trans/steps/excelinput/ods/sample.xls
  engine/test-src/org/pentaho/di/trans/steps/excelinput/ods/sample.xlsx
  engine/test-src/org/pentaho/di/trans/steps/fixedinput/BaseFixedParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/fixedinput/FixedInputContentParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/fixedinput/files/.gitignore
  engine/test-src/org/pentaho/di/trans/steps/fixedinput/files/default.txt
  engine/test-src/org/pentaho/di/trans/steps/xbaseinput/BaseXBaseParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/xbaseinput/XBaseInputContentParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/xbaseinput/files/.gitattributes
  engine/test-src/org/pentaho/di/trans/steps/xbaseinput/files/test.dbf

Checkstyle violations:
----------------------
Errors:File engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputContentParsingTest.java
1. Message: array initialization child at indentation level 6 not at correct indentation, [8, 30] at Line: 51 Column: None
2. Message: array initialization child at indentation level 6 not at correct indentation, [8, 30] at Line: 64 Column: NoneFile engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputContentParsingTest.java
1. Message: array initialization child at indentation level 6 not at correct indentation, [8, 30] at Line: 37 Column: NoneFile engine/test-src/org/pentaho/di/trans/steps/fixedinput/FixedInputContentParsingTest.java
1. Message: array initialization child at indentation level 6 not at correct indentation, [8, 30] at Line: 44 Column: None

Newly Broken Tests:
=================
Test Case Errors:
-----------------
  org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testDefaultOptions: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: Wrong rows count expected:<3> but was:<2>
	at org.pentaho.di.trans.steps.fileinput.BaseParsingTest.check(BaseParsingTest.java:110)
	at org.pentaho.di.trans.steps.excelinput.BaseExcelParsingTest.check(BaseExcelParsingTest.java:92)
	at org.pentaho.di.trans.steps.excelinput.ExcelInputContentParsingTest.testDefaultOptions(ExcelInputContentParsingTest.java:36)

```


Unit test coverage change:
============
org.pentaho.di.trans.steps.randomvalue.RandomValueMeta:
 * instructionPercentCoverageChange : +0.15%
 * branchPercentCoverageChange : +2.08%
 * complexityPercentCoverageChange : +2.13%
    
org.pentaho.di.trans.steps.excelinput.jxl.XLSWorkbook:
 * instructionPercentCoverageChange : +36.44%
 * branchPercentCoverageChange : +20.00%
 * linePercentCoverageChange : +35.90%
 * complexityPercentCoverageChange : +26.67%
 * methodPercentCoverageChange : +40.00%
    
org.pentaho.di.trans.steps.excelinput.ExcelInputData:
 * instructionPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +100.00%
 * complexityPercentCoverageChange : +100.00%
 * methodPercentCoverageChange : +100.00%
    
org.pentaho.di.trans.steps.fixedinput.FixedInputData:
 * instructionPercentCoverageChange : +100.00%
 * branchPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +100.00%
 * complexityPercentCoverageChange : +100.00%
 * methodPercentCoverageChange : +100.00%
    
org.pentaho.di.trans.steps.excelinput.jxl.XLSCell:
 * instructionPercentCoverageChange : +45.19%
 * branchPercentCoverageChange : +26.09%
 * linePercentCoverageChange : +41.94%
 * complexityPercentCoverageChange : +22.22%
 * methodPercentCoverageChange : +80.00%
    
org.pentaho.di.trans.steps.excelinput.ExcelInput:
 * instructionPercentCoverageChange : +33.99%
 * branchPercentCoverageChange : +30.00%
 * linePercentCoverageChange : +44.12%
 * complexityPercentCoverageChange : +15.66%
 * methodPercentCoverageChange : +92.31%
    
org.pentaho.di.trans.steps.fixedinput.FixedInput:
 * instructionPercentCoverageChange : +57.49%
 * branchPercentCoverageChange : +53.57%
 * linePercentCoverageChange : +61.54%
 * complexityPercentCoverageChange : +40.00%
 * methodPercentCoverageChange : +85.71%
    
org.pentaho.di.trans.steps.xbaseinput.XBase:
 * instructionPercentCoverageChange : +35.59%
 * branchPercentCoverageChange : +42.11%
 * linePercentCoverageChange : +47.83%
 * complexityPercentCoverageChange : +33.33%
 * methodPercentCoverageChange : +58.33%
    
org.pentaho.di.trans.steps.fixedinput.FixedInputMeta:
 * instructionPercentCoverageChange : +18.33%
 * branchPercentCoverageChange : +9.38%
 * linePercentCoverageChange : +24.29%
 * complexityPercentCoverageChange : +29.03%
 * methodPercentCoverageChange : +37.78%
    
org.pentaho.di.trans.steps.xbaseinput.XBaseInput:
 * instructionPercentCoverageChange : +46.40%
 * branchPercentCoverageChange : +35.42%
 * linePercentCoverageChange : +44.66%
 * complexityPercentCoverageChange : +25.81%
 * methodPercentCoverageChange : +71.43%
    
org.pentaho.di.trans.steps.xbaseinput.XBaseInputData:
 * instructionPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +100.00%
 * complexityPercentCoverageChange : +100.00%
 * methodPercentCoverageChange : +100.00%
    
org.pentaho.di.trans.steps.fixedinput.FixedFileInputField:
 * instructionPercentCoverageChange : +15.16%
 * linePercentCoverageChange : +9.80%
 * complexityPercentCoverageChange : +16.05%
 * methodPercentCoverageChange : +43.33%
    
org.pentaho.di.trans.steps.excelinput.jxl.XLSCell.new Object() {...}:
 * instructionPercentCoverageChange : +86.76%
 * linePercentCoverageChange : +100.00%
 * complexityPercentCoverageChange : +100.00%
 * methodPercentCoverageChange : +100.00%
    
org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * instructionPercentCoverageChange : +2.43%
 * branchPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +2.95%
 * complexityPercentCoverageChange : +0.69%
    
org.pentaho.di.trans.steps.excelinput.ExcelInputField:
 * instructionPercentCoverageChange : +40.49%
 * linePercentCoverageChange : +42.59%
 * complexityPercentCoverageChange : +37.93%
 * methodPercentCoverageChange : +39.29%
    
org.pentaho.di.trans.steps.excelinput.ExcelInputRow:
 * instructionPercentCoverageChange : +100.00%
 * linePercentCoverageChange : +100.00%
 * complexityPercentCoverageChange : +100.00%
 * methodPercentCoverageChange : +100.00%
    
org.pentaho.di.trans.steps.excelinput.WorkbookFactory:
 * instructionPercentCoverageChange : +6.59%
 * branchPercentCoverageChange : +10.00%
 * linePercentCoverageChange : +7.69%
 * complexityPercentCoverageChange : +9.09%
    
org.pentaho.di.trans.steps.excelinput.ExcelInputMeta:
 * instructionPercentCoverageChange : +7.92%
 * branchPercentCoverageChange : +13.95%
 * linePercentCoverageChange : +11.18%
 * complexityPercentCoverageChange : +9.50%
 * methodPercentCoverageChange : +14.04%
    
org.pentaho.di.trans.steps.excelinput.jxl.XLSSheet:
 * instructionPercentCoverageChange : +75.41%
 * branchPercentCoverageChange : +50.00%
 * linePercentCoverageChange : +73.33%
 * complexityPercentCoverageChange : +62.50%
 * methodPercentCoverageChange : +80.00%
    
org.pentaho.di.trans.steps.xbaseinput.XBaseInputMeta:
 * instructionPercentCoverageChange : +13.15%
 * branchPercentCoverageChange : +11.90%
 * linePercentCoverageChange : +17.82%
 * complexityPercentCoverageChange : +18.75%
 * methodPercentCoverageChange : +25.58%

**Comment by AlexanderBuloichik** [comment]
@mdamour1976 : I fixed broken test (added more tests for Excel also), but I don't have idea how to fix checkstyle, because checkstyle's message doesn't contain correct place, and Pentaho's Eclipse formatter doesn't format file correctly.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputContentParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/csvinput/files/default.csv
  engine/test-src/org/pentaho/di/trans/steps/csvinput/files/semicolon.csv
  engine/test-src/org/pentaho/di/trans/steps/excelinput/BaseExcelParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputContentParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/excelinput/OdfSheetTest.java
  engine/test-src/org/pentaho/di/trans/steps/excelinput/files/.gitattributes
  engine/test-src/org/pentaho/di/trans/steps/excelinput/files/sample-2.4.ods
  engine/test-src/org/pentaho/di/trans/steps/excelinput/files/sample-3.4.1.ods
  engine/test-src/org/pentaho/di/trans/steps/excelinput/files/sample.xls
  engine/test-src/org/pentaho/di/trans/steps/excelinput/files/sample.xlsx
  engine/test-src/org/pentaho/di/trans/steps/excelinput/ods/OdfSheetTest.java
  engine/test-src/org/pentaho/di/trans/steps/excelinput/ods/sample-2.4.ods
  engine/test-src/org/pentaho/di/trans/steps/excelinput/ods/sample-3.4.1.ods
  engine/test-src/org/pentaho/di/trans/steps/fixedinput/BaseFixedParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/fixedinput/FixedInputContentParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/fixedinput/files/.gitignore
  engine/test-src/org/pentaho/di/trans/steps/fixedinput/files/default.txt
  engine/test-src/org/pentaho/di/trans/steps/xbaseinput/BaseXBaseParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/xbaseinput/XBaseInputContentParsingTest.java
  engine/test-src/org/pentaho/di/trans/steps/xbaseinput/files/.gitattributes
  engine/test-src/org/pentaho/di/trans/steps/xbaseinput/files/test.dbf

Checkstyle violations:
======================
File engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputContentParsingTest.java
1. Message: array initialization child at indentation level 6 not at correct indentation, [8, 30] at Line: 51 Column: None
2. Message: array initialization child at indentation level 6 not at correct indentation, [8, 30] at Line: 64 Column: None

File engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputContentParsingTest.java
1. Message: array initialization child at indentation level 6 not at correct indentation, [8, 30, 102] at Line: 86 Column: None

File engine/test-src/org/pentaho/di/trans/steps/excelinput/OdfSheetTest.java
1. Message: Redundant import from the same package - org.pentaho.di.trans.steps.excelinput.SpreadSheetType. at Line: 28 Column: 1
2. Message: Redundant import from the same package - org.pentaho.di.trans.steps.excelinput.WorkbookFactory. at Line: 29 Column: 1

File engine/test-src/org/pentaho/di/trans/steps/fixedinput/FixedInputContentParsingTest.java
1. Message: array initialization child at indentation level 6 not at correct indentation, [8, 30] at Line: 44 Column: None


License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.di.trans.steps.fixedinput.FixedInputData:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheet.new Object() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :86.76%
    
org.pentaho.di.trans.steps.fixedinput.FixedInput:
 * branchPercentCoverage :53.57%
 * linePercentCoverage :61.54%
 * methodPercentCoverage :85.71%
 * complexityPercentCoverage :40.00%
 * instructionPercentCoverage :57.49%
    
org.pentaho.di.trans.steps.excelinput.poi.PoiCell.new Object() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :86.76%
    
org.pentaho.di.trans.steps.fixedinput.FixedFileInputField:
 * linePercentCoverage :9.80%
 * methodPercentCoverage :43.33%
 * complexityPercentCoverage :16.05%
 * instructionPercentCoverage :15.16%
    
org.pentaho.di.trans.steps.xbaseinput.XBaseInput:
 * branchPercentCoverage :35.42%
 * linePercentCoverage :44.66%
 * methodPercentCoverage :71.43%
 * complexityPercentCoverage :25.81%
 * instructionPercentCoverage :46.40%
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange :**-7.14%**
 * complexityPercentCoverageChange :**-7.69%**
    
org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiSheet:
 * branchPercentCoverage :48.06%
 * linePercentCoverage :65.69%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :27.50%
 * instructionPercentCoverage :70.54%
    
org.pentaho.di.trans.steps.excelinput.ods.OdfWorkbook:
 * instructionPercentCoverageChange : +19.05%
 * branchPercentCoverageChange : +20.00%
 * linePercentCoverageChange : +16.67%
 * complexityPercentCoverageChange : +20.00%
 * methodPercentCoverageChange : +20.00%
    
org.pentaho.di.trans.steps.excelinput.staxpoi.StaxUtil:
 * branchPercentCoverage :80.00%
 * linePercentCoverage :94.12%
 * methodPercentCoverage :75.00%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :96.51%
    
org.pentaho.di.trans.steps.excelinput.jxl.XLSWorkbook:
 * branchPercentCoverage :20.00%
 * linePercentCoverage :35.90%
 * methodPercentCoverage :40.00%
 * complexityPercentCoverage :26.67%
 * instructionPercentCoverage :36.44%
    
org.pentaho.di.trans.steps.excelinput.ExcelInputData:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.steps.excelinput.ExcelInput:
 * branchPercentCoverage :31.67%
 * linePercentCoverage :45.19%
 * methodPercentCoverage :92.31%
 * complexityPercentCoverage :17.47%
 * instructionPercentCoverage :35.03%
    
org.pentaho.di.trans.steps.excelinput.ExcelInputMeta:
 * instructionPercentCoverageChange : +7.92%
 * branchPercentCoverageChange : +13.95%
 * linePercentCoverageChange : +11.18%
 * complexityPercentCoverageChange : +9.50%
 * methodPercentCoverageChange : +14.04%
    
org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiCell:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :57.14%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :57.14%
 * instructionPercentCoverage :59.52%
    
org.pentaho.di.trans.steps.xbaseinput.XBaseInputData:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.steps.excelinput.ods.OdfSheet:
 * instructionPercentCoverageChange : +8.04%
 * branchPercentCoverageChange : +9.38%
 * linePercentCoverageChange : +4.00%
 * complexityPercentCoverageChange : +16.67%
 * methodPercentCoverageChange : +12.50%
    
org.pentaho.di.trans.steps.excelinput.ExcelInputField:
 * linePercentCoverage :42.59%
 * methodPercentCoverage :39.29%
 * complexityPercentCoverage :37.93%
 * instructionPercentCoverage :40.49%
    
org.pentaho.di.trans.steps.excelinput.ExcelInputRow:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.steps.excelinput.WorkbookFactory:
 * instructionPercentCoverageChange : +19.78%
 * branchPercentCoverageChange : +30.00%
 * linePercentCoverageChange : +23.08%
 * complexityPercentCoverageChange : +27.27%
    
org.pentaho.di.trans.steps.fixedinput.FixedInputMeta:
 * branchPercentCoverage :9.38%
 * linePercentCoverage :24.29%
 * methodPercentCoverage :37.78%
 * complexityPercentCoverage :29.03%
 * instructionPercentCoverage :18.33%
    
org.pentaho.di.trans.steps.excelinput.poi.PoiWorkbook:
 * branchPercentCoverage :43.75%
 * linePercentCoverage :47.54%
 * methodPercentCoverage :40.00%
 * complexityPercentCoverage :27.78%
 * instructionPercentCoverage :47.62%
    
org.pentaho.di.trans.steps.xbaseinput.XBase:
 * branchPercentCoverage :42.11%
 * linePercentCoverage :47.83%
 * methodPercentCoverage :58.33%
 * complexityPercentCoverage :33.33%
 * instructionPercentCoverage :35.59%
    
org.pentaho.di.trans.steps.excelinput.poi.PoiCell:
 * branchPercentCoverage :17.86%
 * linePercentCoverage :31.71%
 * methodPercentCoverage :80.00%
 * complexityPercentCoverage :18.18%
 * instructionPercentCoverage :23.03%
    
org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * instructionPercentCoverageChange : +0.07%
    
org.pentaho.di.trans.steps.excelinput.jxl.XLSCell.new Object() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :86.76%
    
org.pentaho.di.trans.steps.excelinput.jxl.XLSSheet:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :73.33%
 * methodPercentCoverage :80.00%
 * complexityPercentCoverage :62.50%
 * instructionPercentCoverage :75.41%
    
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange :**-0.08%**
    
org.pentaho.di.trans.steps.excelinput.staxpoi.StaxPoiWorkbook:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :63.75%
 * methodPercentCoverage :60.00%
 * complexityPercentCoverage :46.15%
 * instructionPercentCoverage :60.19%
    
org.pentaho.di.trans.steps.excelinput.jxl.XLSCell:
 * branchPercentCoverage :26.09%
 * linePercentCoverage :41.94%
 * methodPercentCoverage :80.00%
 * complexityPercentCoverage :22.22%
 * instructionPercentCoverage :45.19%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange : +0.53%
    
org.pentaho.di.trans.steps.xbaseinput.XBaseInputMeta:
 * branchPercentCoverage :11.90%
 * linePercentCoverage :17.82%
 * methodPercentCoverage :25.58%
 * complexityPercentCoverage :18.75%
 * instructionPercentCoverage :13.15%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +1.97%
    
org.pentaho.di.trans.steps.excelinput.poi.PoiSheet:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :60.71%
 * methodPercentCoverage :60.00%
 * complexityPercentCoverage :38.46%
 * instructionPercentCoverage :65.09%
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange : +0.18%

**Comment by lucboudreau** [comment]
@AlexanderBuloichik https://github.com/pentaho/pentaho-coding-standards

**Comment by AlexanderBuloichik** [comment]
@lucboudreau: fixed

**Comment by mdamour1976** [comment]
@AlexanderBuloichik @lucboudreau checkstyle violations are gone.  Pull request is looking good

**Pull request merged**
