### PR TITLE
[BACKLOG-19168] Introduce FileMetaCache to cache meta of sub-job/tran…

### PR DESCRIPTION
**Pull request by tkafalas**
…sformations to enhance performance when Connected to Repository

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 42m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 17 test(s) failed:

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForStepAsJobFromRepoTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForEntryAsJobFromFileSystemTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForStepAsJobFromFileSystemTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForEntryAsJobFromRepoTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.TransMetaTest.testLoadXml</b> (click to expand)</summary><p>

```
javassist.CannotCompileException: by java.util.zip.ZipException: invalid stored block lengths
```

</p></details>

<details><summary><b>org.pentaho.di.trans.TransMetaTest.testSetInternalEntryCurrentDirectoryWithRepository</b> (click to expand)</summary><p>

```
javassist.CannotCompileException: by java.util.zip.ZipException: invalid stored block lengths
```

</p></details>

<details><summary><b>org.pentaho.di.trans.TransMetaTest.testTransWithOneStepIsConsideredUsed</b> (click to expand)</summary><p>

```
javassist.CannotCompileException: by java.util.zip.ZipException: invalid stored block lengths
```

</p></details>

<details><summary><b>org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTest</b> (click to expand)</summary><p>

```
javassist.CannotCompileException: by java.util.zip.ZipException: invalid stored block lengths
```

</p></details>

<details><summary><b>org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTestCantFindDirectory</b> (click to expand)</summary><p>

```
javassist.CannotCompileException: by java.util.zip.ZipException: invalid stored block lengths
```

</p></details>

<details><summary><b>org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTestJobNotFoundInDirectory</b> (click to expand)</summary><p>

```
javassist.CannotCompileException: by java.util.zip.ZipException: invalid stored block lengths
```

</p></details>

<details><summary><b>org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTestCantFindRepository</b> (click to expand)</summary><p>

```
javassist.CannotCompileException: by java.util.zip.ZipException: invalid stored block lengths
```

</p></details>

<details><summary><b>org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTestWithUnauthorizedUser</b> (click to expand)</summary><p>

```
javassist.CannotCompileException: by java.util.zip.ZipException: invalid stored block lengths
```

</p></details>

<details><summary><b>org.pentaho.di.www.ExecuteTransServletTest.doGetRepositoryAuthenticationFailTest</b> (click to expand)</summary><p>

```
javassist.CannotCompileException: by java.util.zip.ZipException: invalid stored block lengths
```

</p></details>

<details><summary><b>org.pentaho.di.www.ExecuteTransServletTest.doGetTransformationNotFoundTest</b> (click to expand)</summary><p>

```
javassist.CannotCompileException: by java.util.zip.ZipException: invalid stored block lengths
```

</p></details>

<details><summary><b>org.pentaho.di.www.ExecuteTransServletTest.doGetTransformationFailsTest</b> (click to expand)</summary><p>

```
javassist.CannotCompileException: by java.util.zip.ZipException: invalid stored block lengths
```

</p></details>

<details><summary><b>org.pentaho.di.www.ExecuteTransServletTest.doGetTransformationSucceedsTest</b> (click to expand)</summary><p>

```
javassist.CannotCompileException: by java.util.zip.ZipException: invalid stored block lengths
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.metainject.MetaInjectTest.testMetastoreIsSet</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **3952**, Failures: **17**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-8066/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 36m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 5 test(s) failed:

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForStepAsJobFromRepoTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForEntryAsJobFromFileSystemTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForStepAsJobFromFileSystemTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForEntryAsJobFromRepoTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.metainject.MetaInjectTest.testMetastoreIsSet</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **3952**, Failures: **5**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-8066/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 33m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForStepAsJobFromRepoTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForEntryAsJobFromFileSystemTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForStepAsJobFromFileSystemTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForEntryAsJobFromRepoTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **3952**, Failures: **4**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-8066/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 32m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForStepAsJobFromRepoTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForEntryAsJobFromFileSystemTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForStepAsJobFromFileSystemTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.base.MetaFileLoaderImplTest.getMetaForEntryAsJobFromRepoTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **3952**, Failures: **4**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-8066/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 36m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3952**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-8066/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
**Please note that this PR's message is wrong: this is not related with BACKLOG-19168, it's related with PDI-19168!**

**Pull request merged**
