### PR TITLE
[PDI-14983] (part 2) Schedule/run Salesforce Insert and Input steps o…

### PR DESCRIPTION
**Pull request by ivanpogodin**
…n DI Server - java.lang.ExceptionInInitializerError
@mattcasters , @brosander , could you review it, please?

### CODE REVIEW

**Comment by ivanpogodin** [comment]
@mattcasters , @brosander , could you review it, please?

**Comment by ivanpogodin** [comment]
@mattcasters , @brosander , could you review it, please?

**Comment by ivanpogodin** [comment]
@mattcasters , @brosander , could you review it, please?

**Comment by MrMauricioLeite** [comment]
someone give this man a review please! :cookie: :wink:

**Comment by ivanpogodin** [comment]
@brosander , @mdamour1976 , @pamval , @bmorrise , could you review it, please?

**Pull request merged**
