### PR TITLE
[PDI-15328] PDI needs to error out and log an error when a plugin is missing at run time

### PR DESCRIPTION
**Pull request by mchen-len-son**
these are rebased and fixed changes from #3108.

- reworked integration tests. moved them to engine module, as they unlikely would've been executed in the near future (those tests in root folder have compilation errors and seem to be abandoned).
- fixed checkstyle violations

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@e-cuellar @bmorrise @mbatchelor please review.
thanks.

**Comment by mchen-len-son** [comment]
+ @AndreyBurikhin

**Comment by pamval** [comment]
@mdamour1976 @tkafalas @tgf please review

**Comment by mchen-len-son** [comment]
@mdamour1976 @tkafalas @mbatchelor please take a look. 
thanks.

**Pull request merged**
