### PR TITLE
[PDI-13723] - PluginRegistry doesn't create a proper classloader if s…

### PR DESCRIPTION
**Pull request by akhayrutdinov**
…everal plugins are shipped within one jar

- fix class loader factory method so, that it respects directory class name patterns of plugins from the same directories
- introduce a test

@mattyb149, @brosander, review it please

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, take a look at it please

**Comment by brosander** [comment]
@akhayrutdinov I believe @mattcasters added classloader groups for this purpose:
https://github.com/pentaho/pentaho-kettle/commit/e38ad4db6aeb64ebb4400cd7fc0d5a5463f2746f

In the normal case this is intended behavior as far as I'm aware

**Comment by akhayrutdinov** [comment]
@brosander, thanks for replying.

Actually, I don't think this fix contradicts with groups.
This fix is about what type of classloader (CL) to create, ```createClassLoader``` is invoked both for ordinal and group CLs.

Assume, we have two plugins of the same group. One needs a parent-first CL, the other declares nothing about it. If the second is touched earlier, than the first, then the described problem occures. It is a rare case? I thought so, but I've faced with it.

**Comment by brosander** [comment]
@akhayrutdinov is parentClassloaderPatternMap fully populated before the first createClassloader call?

**Comment by akhayrutdinov** [comment]
@brosander, patterns are put in the map via ``BasePluginType.handlePluginAnnotation```. So, before a CL will be created for the particular plugin, its patterns (if they exist) will have been gathered. If several plugins are located in the same jar, then all of them will be processed before any call of ```loadClass()``` (this call forces creating the proper CL instance).

Asking to your question: I suppose we can rely on an assumption, that pattern map has been properly defined before any CL is created for a plugin.

**Comment by brosander** [comment]
@akhayrutdinov what if two plugins in different directories are part of the same classloader group?

**Comment by akhayrutdinov** [comment]
@brosander, then the CL will be created for that one, who is proceeded first. This CL instance will be stored in the internal map and used for each next action

**Comment by akhayrutdinov** [comment]
@brosander, any thoughts? If you hesitate, let's ask @mattcasters, @deinspanjer or someone else. I don't insist on this fix is undoubtedly needed, but I believe clear decision is much better than uncertain silence :)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/di/core/plugins/PluginRegistry.java
  core/test-src/org/pentaho/di/core/plugins/PluginRegistryClassloadingTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File core/src/org/pentaho/di/core/plugins/PluginRegistry.java
1. Message: 'if rcurly' have incorrect indentation level 14, expected level should be 16. at Line: 1000 Column: None
2. Message: 'else' child have incorrect indentation level 16, expected level should be 18. at Line: 1001 Column: None
3. Message: 'if' have incorrect indentation level 16, expected level should be 18. at Line: 1002 Column: None
4. Message: 'if' have incorrect indentation level 18, expected level should be 20. at Line: 1003 Column: None
5. Message: 'if' have incorrect indentation level 20, expected level should be 22. at Line: 1004 Column: None
6. Message: 'if' child have incorrect indentation level 22, expected level should be 24. at Line: 1005 Column: None
7. Message: 'if rcurly' have incorrect indentation level 20, expected level should be 22. at Line: 1006 Column: None
8. Message: 'if rcurly' have incorrect indentation level 18, expected level should be 20. at Line: 1007 Column: None
9. Message: 'if' child have incorrect indentation level 18, expected level should be 20. at Line: 1008 Column: None
10. Message: 'if' child have incorrect indentation level 18, expected level should be 20. at Line: 1009 Column: None
11. Message: 'method call' child have incorrect indentation level 18, expected level should be 20. at Line: 1009 Column: None
12. Message: 'if rcurly' have incorrect indentation level 16, expected level should be 18. at Line: 1010 Column: None
13. Message: 'else rcurly' have incorrect indentation level 14, expected level should be 16. at Line: 1011 Column: None
14. Message: 'else rcurly' have incorrect indentation level 12, expected level should be 14. at Line: 1012 Column: None
15. Message: 'if rcurly' have incorrect indentation level 10, expected level should be 12. at Line: 1013 Column: None
16. Message: 'else rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 1014 Column: None
17. Message: 'member def type' have incorrect indentation level 4, expected level should be 6. at Line: 1042 Column: None
18. Message: 'try' child have incorrect indentation level 4, expected level should be 6. at Line: 1042 Column: None
19. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 1043 Column: None
20. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 1044 Column: None
21. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 1045 Column: None
22. Message: 'method call' child have incorrect indentation level 6, expected level should be 8. at Line: 1045 Column: None
23. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 1046 Column: None
24. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 1048 Column: None
25. Message: 'method call' child have incorrect indentation level 6, expected level should be 8. at Line: 1048 Column: None
26. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 1049 Column: None
27. Message: 'finally rcurly' have incorrect indentation level 2, expected level should be 4. at Line: 1052 Column: None
28. Message: 'member def type' have incorrect indentation level 4, expected level should be 6. at Line: 1058 Column: None
29. Message: 'try' child have incorrect indentation level 4, expected level should be 6. at Line: 1058 Column: None
30. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 1059 Column: None
31. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 1060 Column: None
32. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 1061 Column: None
33. Message: 'method call' child have incorrect indentation level 6, expected level should be 8. at Line: 1061 Column: None
34. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 1062 Column: None
35. Message: 'method call' child have incorrect indentation level 4, expected level should be 6. at Line: 1063 Column: None
36. Message: 'try' child have incorrect indentation level 4, expected level should be 6. at Line: 1063 Column: None
37. Message: 'finally rcurly' have incorrect indentation level 2, expected level should be 4. at Line: 1066 Column: None
38. Message: 'for' have incorrect indentation level 4, expected level should be 6. at Line: 1097 Column: None
39. Message: 'for' have incorrect indentation level 6, expected level should be 8. at Line: 1098 Column: None
40. Message: 'for' child have incorrect indentation level 8, expected level should be 10. at Line: 1099 Column: None
41. Message: 'member def type' have incorrect indentation level 8, expected level should be 10. at Line: 1099 Column: None
42. Message: 'try' have incorrect indentation level 8, expected level should be 10. at Line: 1100 Column: None
43. Message: 'if' have incorrect indentation level 10, expected level should be 12. at Line: 1101 Column: None
44. Message: 'if' child have incorrect indentation level 12, expected level should be 14. at Line: 1102 Column: None
45. Message: 'method call' child have incorrect indentation level 12, expected level should be 14. at Line: 1102 Column: None
46. Message: 'if rcurly' have incorrect indentation level 10, expected level should be 12. at Line: 1103 Column: None
47. Message: 'try rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 1104 Column: None
48. Message: 'catch' child have incorrect indentation level 10, expected level should be 12. at Line: 1105 Column: None
49. Message: 'method call' child have incorrect indentation level 10, expected level should be 12. at Line: 1105 Column: None
50. Message: 'catch rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 1106 Column: None
51. Message: 'for rcurly' have incorrect indentation level 6, expected level should be 8. at Line: 1107 Column: None
52. Message: 'for rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 1108 Column: None
53. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 113 Column: None
54. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 114 Column: None
55. Message: 'method call' child have incorrect indentation level 6, expected level should be 8. at Line: 114 Column: None
56. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 115 Column: None
57. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 119 Column: None
58. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 121 Column: None
59. Message: 'finally rcurly' have incorrect indentation level 2, expected level should be 4. at Line: 124 Column: None
60. Message: 'member def type' have incorrect indentation level 4, expected level should be 6. at Line: 130 Column: None
61. Message: 'try' child have incorrect indentation level 4, expected level should be 6. at Line: 130 Column: None
62. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 131 Column: None
63. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 132 Column: None
64. Message: 'method call' child have incorrect indentation level 6, expected level should be 8. at Line: 132 Column: None
65. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 133 Column: None
66. Message: 'member def type' have incorrect indentation level 4, expected level should be 6. at Line: 135 Column: None
67. Message: 'try' child have incorrect indentation level 4, expected level should be 6. at Line: 135 Column: None
68. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 136 Column: None
69. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 137 Column: None
70. Message: 'method call' child have incorrect indentation level 6, expected level should be 8. at Line: 137 Column: None
71. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 138 Column: None
72. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 140 Column: None
73. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 143 Column: None
74. Message: 'method call' child have incorrect indentation level 6, expected level should be 8. at Line: 143 Column: None
75. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 144 Column: None
76. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 147 Column: None
77. Message: 'for' have incorrect indentation level 6, expected level should be 8. at Line: 148 Column: None
78. Message: 'for' child have incorrect indentation level 8, expected level should be 10. at Line: 149 Column: None
79. Message: 'method call' child have incorrect indentation level 8, expected level should be 10. at Line: 149 Column: None
80. Message: 'for rcurly' have incorrect indentation level 6, expected level should be 8. at Line: 150 Column: None
81. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 151 Column: None
82. Message: 'method call' child have incorrect indentation level 4, expected level should be 6. at Line: 163 Column: None
83. Message: 'try' child have incorrect indentation level 4, expected level should be 6. at Line: 163 Column: None
84. Message: 'member def type' have incorrect indentation level 4, expected level should be 6. at Line: 185 Column: None
85. Message: 'try' child have incorrect indentation level 4, expected level should be 6. at Line: 185 Column: None
86. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 187 Column: None
87. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 188 Column: None
88. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 189 Column: None
89. Message: 'member def type' have incorrect indentation level 4, expected level should be 6. at Line: 191 Column: None
90. Message: 'try' child have incorrect indentation level 4, expected level should be 6. at Line: 191 Column: None
91. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 192 Column: None
92. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 193 Column: None
93. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 194 Column: None
94. Message: 'method call' child have incorrect indentation level 6, expected level should be 8. at Line: 194 Column: None
95. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 195 Column: None
96. Message: 'member def type' have incorrect indentation level 4, expected level should be 6. at Line: 197 Column: None
97. Message: 'try' child have incorrect indentation level 4, expected level should be 6. at Line: 197 Column: None
98. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 198 Column: None
99. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 199 Column: None
100. Message: 'method call' child have incorrect indentation level 6, expected level should be 8. at Line: 199 Column: None
101. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 200 Column: None
102. Message: 'else' child have incorrect indentation level 6, expected level should be 8. at Line: 201 Column: None
103. Message: 'method call' child have incorrect indentation level 6, expected level should be 8. at Line: 201 Column: None
104. Message: 'else' child have incorrect indentation level 6, expected level should be 8. at Line: 202 Column: None
105. Message: 'else rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 203 Column: None
106. Message: 'method call' child have incorrect indentation level 4, expected level should be 6. at Line: 207 Column: None
107. Message: 'try' child have incorrect indentation level 4, expected level should be 6. at Line: 207 Column: None
108. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 214 Column: None
109. Message: 'if' child have incorrect indentation level 6, expected level should be 8. at Line: 215 Column: None
110. Message: 'member def type' have incorrect indentation level 6, expected level should be 8. at Line: 215 Column: None
111. Message: 'if' have incorrect indentation level 6, expected level should be 8. at Line: 216 Column: None
112. Message: 'if' child have incorrect indentation level 8, expected level should be 10. at Line: 217 Column: None
113. Message: 'if' child have incorrect indentation level 8, expected level should be 10. at Line: 218 Column: None
114. Message: 'method call' child have incorrect indentation level 8, expected level should be 10. at Line: 218 Column: None
115. Message: 'if rcurly' have incorrect indentation level 6, expected level should be 8. at Line: 219 Column: None
116. Message: 'if' have incorrect indentation level 6, expected level should be 8. at Line: 220 Column: None
117. Message: 'if' child have incorrect indentation level 8, expected level should be 10. at Line: 221 Column: None
118. Message: 'method call' child have incorrect indentation level 8, expected level should be 10. at Line: 221 Column: None
119. Message: 'if' child have incorrect indentation level 8, expected level should be 10. at Line: 227 Column: None
120. Message: 'member def type' have incorrect indentation level 8, expected level should be 10. at Line: 227 Column: None
121. Message: 'if' child have incorrect indentation level 8, expected level should be 10. at Line: 229 Column: None
122. Message: 'member def type' have incorrect indentation level 8, expected level should be 10. at Line: 229 Column: None
123. Message: 'if' have incorrect indentation level 8, expected level should be 10. at Line: 231 Column: None
124. Message: 'if' child have incorrect indentation level 10, expected level should be 12. at Line: 232 Column: None
125. Message: 'member def type' have incorrect indentation level 10, expected level should be 12. at Line: 232 Column: None
126. Message: 'if' child have incorrect indentation level 10, expected level should be 12. at Line: 233 Column: None
127. Message: 'member def type' have incorrect indentation level 10, expected level should be 12. at Line: 233 Column: None
128. Message: 'if' child have incorrect indentation level 10, expected level should be 12. at Line: 234 Column: None
129. Message: 'for' have incorrect indentation level 10, expected level should be 12. at Line: 235 Column: None
130. Message: 'for' child have incorrect indentation level 12, expected level should be 14. at Line: 236 Column: None
131. Message: 'for rcurly' have incorrect indentation level 10, expected level should be 12. at Line: 237 Column: None
132. Message: 'if rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 238 Column: None
133. Message: 'if' have incorrect indentation level 8, expected level should be 10. at Line: 239 Column: None
134. Message: 'if' child have incorrect indentation level 10, expected level should be 12. at Line: 240 Column: None
135. Message: 'member def modifier' have incorrect indentation level 10, expected level should be 12. at Line: 240 Column: None
136. Message: 'if' child have incorrect indentation level 10, expected level should be 12. at Line: 241 Column: None
137. Message: 'method call' child have incorrect indentation level 10, expected level should be 12. at Line: 241 Column: None
138. Message: 'if rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 250 Column: None
139. Message: 'if rcurly' have incorrect indentation level 6, expected level should be 8. at Line: 251 Column: None
140. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 252 Column: None
141. Message: 'if' have incorrect indentation level 4, expected level should be 6. at Line: 254 Column: None
142. Message: 'for' have incorrect indentation level 6, expected level should be 8. at Line: 255 Column: None
143. Message: 'if' have incorrect indentation level 8, expected level should be 10. at Line: 257 Column: None
144. Message: 'if' child have incorrect indentation level 10, expected level should be 12. at Line: 258 Column: None
145. Message: 'method call' child have incorrect indentation level 10, expected level should be 12. at Line: 258 Column: None
146. Message: 'if rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 259 Column: None
147. Message: 'else' child have incorrect indentation level 10, expected level should be 12. at Line: 260 Column: None
148. Message: 'method call' child have incorrect indentation level 10, expected level should be 12. at Line: 260 Column: None
149. Message: 'else rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 261 Column: None
150. Message: 'for rcurly' have incorrect indentation level 6, expected level should be 8. at Line: 262 Column: None
151. Message: 'if rcurly' have incorrect indentation level 4, expected level should be 6. at Line: 263 Column: None
152. Message: 'try' child have incorrect indentation level 4, expected level should be 6. at Line: 278 Column: None
153. Message: 'finally rcurly' have incorrect indentation level 2, expected level should be 4. at Line: 282 Column: None
154. Message: 'for' have incorrect indentation level 4, expected level should be 6. at Line: 295 Column: None
155. Message: 'if' have incorrect indentation level 6, expected level should be 8. at Line: 296 Column: None
156. Message: 'if' child have incorrect indentation level 8, expected level should be 10. at Line: 297 Column: None
157. Message: 'member def type' have incorrect indentation level 8, expected level should be 10. at Line: 297 Column: None
158. Message: 'if' have incorrect indentation level 8, expected level should be 10. at Line: 298 Column: None
159. Message: 'for' have incorrect indentation level 10, expected level should be 12. at Line: 299 Column: None
160. Message: 'for' child have incorrect indentation level 12, expected level should be 14. at Line: 300 Column: None
161. Message: 'member def type' have incorrect indentation level 12, expected level should be 14. at Line: 300 Column: None
162. Message: 'finally rcurly' have incorrect indentation level 2, expected level should be 4. at Line: 368 Column: None
163. Message: 'if' have incorrect indentation level 10, expected level should be 12. at Line: 485 Column: None
164. Message: 'if' child have incorrect indentation level 12, expected level should be 14. at Line: 487 Column: None
165. Message: 'if rcurly' have incorrect indentation level 10, expected level should be 12. at Line: 488 Column: None
166. Message: 'else' child have incorrect indentation level 12, expected level should be 14. at Line: 490 Column: None
167. Message: 'member def type' have incorrect indentation level 12, expected level should be 14. at Line: 490 Column: None
168. Message: 'if' have incorrect indentation level 12, expected level should be 14. at Line: 491 Column: None
169. Message: 'if' child have incorrect indentation level 14, expected level should be 16. at Line: 492 Column: None
170. Message: 'if' child have incorrect indentation level 14, expected level should be 16. at Line: 493 Column: None
171. Message: 'method call' child have incorrect indentation level 14, expected level should be 16. at Line: 493 Column: None
172. Message: 'if rcurly' have incorrect indentation level 12, expected level should be 14. at Line: 494 Column: None
173. Message: 'else' child have incorrect indentation level 14, expected level should be 16. at Line: 495 Column: None
174. Message: 'else rcurly' have incorrect indentation level 12, expected level should be 14. at Line: 496 Column: None
175. Message: 'if' have incorrect indentation level 12, expected level should be 14. at Line: 497 Column: None
176. Message: 'if' have incorrect indentation level 14, expected level should be 16. at Line: 499 Column: None
177. Message: 'if' child have incorrect indentation level 16, expected level should be 18. at Line: 500 Column: None
178. Message: 'if' have incorrect indentation level 16, expected level should be 18. at Line: 501 Column: None
179. Message: 'if' child have incorrect indentation level 18, expected level should be 20. at Line: 502 Column: None
180. Message: 'if' child have incorrect indentation level 18, expected level should be 20. at Line: 503 Column: None
181. Message: 'method call' child have incorrect indentation level 18, expected level should be 20. at Line: 503 Column: None
182. Message: 'if' child have incorrect indentation level 18, expected level should be 20. at Line: 504 Column: None
183. Message: 'method call' child have incorrect indentation level 18, expected level should be 20. at Line: 504 Column: None
184. Message: 'if rcurly' have incorrect indentation level 16, expected level should be 18. at Line: 505 Column: None
185. Message: 'if rcurly' have incorrect indentation level 14, expected level should be 16. at Line: 506 Column: None
186. Message: 'else' child have incorrect indentation level 16, expected level should be 18. at Line: 507 Column: None
187. Message: 'if' have incorrect indentation level 16, expected level should be 18. at Line: 508 Column: None
188. Message: 'if' child have incorrect indentation level 18, expected level should be 20. at Line: 509 Column: None
189. Message: 'if' child have incorrect indentation level 18, expected level should be 20. at Line: 510 Column: None
190. Message: 'method call' child have incorrect indentation level 18, expected level should be 20. at Line: 510 Column: None
191. Message: 'if rcurly' have incorrect indentation level 16, expected level should be 18. at Line: 511 Column: None
192. Message: 'else rcurly' have incorrect indentation level 14, expected level should be 16. at Line: 512 Column: None
193. Message: 'if rcurly' have incorrect indentation level 12, expected level should be 14. at Line: 513 Column: None
194. Message: 'else rcurly' have incorrect indentation level 10, expected level should be 12. at Line: 514 Column: None
195. Message: 'if' child have incorrect indentation level 4, expected level should be 6. at Line: 683 Column: None
196. Message: 'method call' child have incorrect indentation level 4, expected level should be 6. at Line: 683 Column: None
197. Message: 'method call' child have incorrect indentation level 6, expected level should be 8. at Line: 684 Column: None
198. Message: 'method call' child have incorrect indentation level 6, expected level should be 8. at Line: 685 Column: None
199. Message: 'member def type' have incorrect indentation level 8, expected level should be 10. at Line: 896 Column: None
200. Message: 'try' child have incorrect indentation level 8, expected level should be 10. at Line: 896 Column: None
201. Message: 'if' have incorrect indentation level 8, expected level should be 10. at Line: 897 Column: None
202. Message: 'if' child have incorrect indentation level 10, expected level should be 12. at Line: 898 Column: None
203. Message: 'if' child have incorrect indentation level 10, expected level should be 12. at Line: 899 Column: None
204. Message: 'method call' child have incorrect indentation level 10, expected level should be 12. at Line: 899 Column: None
205. Message: 'if rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 900 Column: None
206. Message: 'else' child have incorrect indentation level 10, expected level should be 12. at Line: 901 Column: None
207. Message: 'else rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 902 Column: None
208. Message: 'if' have incorrect indentation level 8, expected level should be 10. at Line: 903 Column: None
209. Message: 'if' have incorrect indentation level 10, expected level should be 12. at Line: 905 Column: None
210. Message: 'if' child have incorrect indentation level 12, expected level should be 14. at Line: 906 Column: None
211. Message: 'if' child have incorrect indentation level 12, expected level should be 14. at Line: 908 Column: None
212. Message: 'method call' child have incorrect indentation level 12, expected level should be 14. at Line: 908 Column: None
213. Message: 'if rcurly' have incorrect indentation level 10, expected level should be 12. at Line: 910 Column: None
214. Message: 'if rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 912 Column: None
215. Message: 'if' have incorrect indentation level 8, expected level should be 10. at Line: 972 Column: None
216. Message: 'if' child have incorrect indentation level 10, expected level should be 12. at Line: 974 Column: None
217. Message: 'if rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 975 Column: None
218. Message: 'else' child have incorrect indentation level 10, expected level should be 12. at Line: 977 Column: None
219. Message: 'member def type' have incorrect indentation level 10, expected level should be 12. at Line: 977 Column: None
220. Message: 'if' have incorrect indentation level 10, expected level should be 12. at Line: 978 Column: None
221. Message: 'if' child have incorrect indentation level 12, expected level should be 14. at Line: 979 Column: None
222. Message: 'if' child have incorrect indentation level 12, expected level should be 14. at Line: 980 Column: None
223. Message: 'method call' child have incorrect indentation level 12, expected level should be 14. at Line: 980 Column: None
224. Message: 'if rcurly' have incorrect indentation level 10, expected level should be 12. at Line: 981 Column: None
225. Message: 'else' child have incorrect indentation level 12, expected level should be 14. at Line: 982 Column: None
226. Message: 'else rcurly' have incorrect indentation level 10, expected level should be 12. at Line: 983 Column: None
227. Message: 'if' have incorrect indentation level 10, expected level should be 12. at Line: 984 Column: None
228. Message: 'if' have incorrect indentation level 12, expected level should be 14. at Line: 985 Column: None
229. Message: 'if' child have incorrect indentation level 14, expected level should be 16. at Line: 986 Column: None
230. Message: 'if' have incorrect indentation level 14, expected level should be 16. at Line: 987 Column: None
231. Message: 'if' child have incorrect indentation level 16, expected level should be 18. at Line: 988 Column: None
232. Message: 'if' child have incorrect indentation level 16, expected level should be 18. at Line: 989 Column: None
233. Message: 'method call' child have incorrect indentation level 16, expected level should be 18. at Line: 989 Column: None
234. Message: 'if' child have incorrect indentation level 16, expected level should be 18. at Line: 990 Column: None
235. Message: 'method call' child have incorrect indentation level 16, expected level should be 18. at Line: 990 Column: None
236. Message: 'if rcurly' have incorrect indentation level 14, expected level should be 16. at Line: 991 Column: None
237. Message: 'if rcurly' have incorrect indentation level 12, expected level should be 14. at Line: 992 Column: None
238. Message: 'if' have incorrect indentation level 14, expected level should be 16. at Line: 993 Column: None
239. Message: 'if' child have incorrect indentation level 16, expected level should be 18. at Line: 994 Column: None
240. Message: 'if' have incorrect indentation level 16, expected level should be 18. at Line: 995 Column: None
241. Message: 'if' child have incorrect indentation level 18, expected level should be 20. at Line: 996 Column: None
242. Message: 'if' child have incorrect indentation level 18, expected level should be 20. at Line: 997 Column: None
243. Message: 'method call' child have incorrect indentation level 18, expected level should be 20. at Line: 997 Column: None
244. Message: 'if' child have incorrect indentation level 18, expected level should be 20. at Line: 998 Column: None
245. Message: 'method call' child have incorrect indentation level 18, expected level should be 20. at Line: 998 Column: None
246. Message: 'if rcurly' have incorrect indentation level 16, expected level should be 18. at Line: 999 Column: None



Newly Broken Tests:
-----------------
org.pentaho.di.core.extension.ExtensionPointIntegrationTest.test: java.lang.NullPointerException
```
java.lang.NullPointerException
	at org.pentaho.di.core.extension.ExtensionPointIntegrationTest.test(ExtensionPointIntegrationTest.java:65)

```





Unit test coverage change:
============
org.pentaho.di.core.logging.LogChannel:
 * instructionPercentCoverageChange : +7.87%
 * branchPercentCoverageChange : +2.44%
 * linePercentCoverageChange : +7.59%
 * complexityPercentCoverageChange : +3.23%
 * methodPercentCoverageChange : +5.13%
    
org.pentaho.di.core.plugins.Plugin:
 * instructionPercentCoverageChange : +4.21%
 * branchPercentCoverageChange :**-16.67%**
 * complexityPercentCoverageChange :**-4.44%**
    
org.pentaho.di.core.logging.KettleLogLayout:
 * instructionPercentCoverageChange : +30.85%
 * branchPercentCoverageChange : +23.08%
 * linePercentCoverageChange : +31.25%
 * complexityPercentCoverageChange : +14.29%
    
org.pentaho.di.core.exception.KettlePluginException:
 * instructionPercentCoverageChange : +31.25%
 * linePercentCoverageChange : +25.00%
 * complexityPercentCoverageChange : +25.00%
 * methodPercentCoverageChange : +25.00%
    
org.pentaho.di.core.logging.ConsoleLoggingEventListener:
 * branchPercentCoverage :50.00%
 * instructionPercentCoverageChange : +53.85%
 * linePercentCoverageChange : +50.00%
 * complexityPercentCoverageChange : +33.33%
 * methodPercentCoverageChange : +50.00%
    
org.pentaho.di.core.plugins.KettleSelectiveParentFirstClassLoader:
 * branchPercentCoverage :37.50%
 * linePercentCoverage :38.10%
 * methodPercentCoverage :40.00%
 * complexityPercentCoverage :33.33%
 * instructionPercentCoverage :44.44%
    
org.pentaho.di.core.Const:
 * instructionPercentCoverageChange : +0.71%
 * linePercentCoverageChange : +1.15%
 * complexityPercentCoverageChange : +0.58%
 * methodPercentCoverageChange : +1.85%
    
org.pentaho.di.core.extension.ExtensionPointMap.ExtensionPointLoader:
 * branchPercentCoverage :50.00%
 * instructionPercentCoverageChange : +53.66%
 * linePercentCoverageChange : +42.86%
    
org.pentaho.di.core.plugins.KettleURLClassLoader:
 * instructionPercentCoverageChange :**-3.93%**
 * linePercentCoverageChange :**-4.51%**
 * complexityPercentCoverageChange :**-5.13%**
 * methodPercentCoverageChange :**-14.29%**
    
org.pentaho.di.core.plugins.PluginRegistry:
 * instructionPercentCoverageChange : +1.59%
 * branchPercentCoverageChange :**-1.14%**
 * linePercentCoverageChange : +1.13%
 * complexityPercentCoverageChange : +0.75%
 * methodPercentCoverageChange : +3.78%
    
org.pentaho.di.core.extension.ExtensionPointMap:
 * instructionPercentCoverageChange : +2.60%
 * branchPercentCoverageChange : +10.00%
 * linePercentCoverageChange : +6.45%
 * complexityPercentCoverageChange : +6.67%
 * methodPercentCoverageChange : +10.00%
    
org.pentaho.di.core.exception.KettleException:
 * instructionPercentCoverageChange : +37.96%
 * branchPercentCoverageChange : +16.67%
 * linePercentCoverageChange : +5.00%
 * complexityPercentCoverageChange : +11.11%

**Comment by brosander** [comment]
@akhayrutdinov do you still think this PR is relevant? If so we can process after unit test, checkstyle issues are addressed.

**Comment by akhayrutdinov** [comment]
@brosander, although I faced rather rare scenariol, the bug exists. I'll close this PR and re-assign the case to Triage. If it is decided the problem is worth being fixed, I'll send another PR. Thanks for concerning!

**Pull request closed without merging**
