### PR TITLE
[PDI-17065] - Kafka Consumer step doesn't find sub transformation in …

### PR DESCRIPTION
**Pull request by SergeyTravin**
…some

cases. Fix for localhost resolve

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@mbatchelor, @kolinus, @mchen-len-son please review

**Comment by SergeyTravin** [comment]
@pentaho-lmartins, please review

**Comment by mbatchelor** [comment]
Re-running wingman - this has been open for 13 days, and there could be new conflicts

**Comment by SergeyTravin** [comment]
@pentaho-lmartins, @mbatchelor please merge it. The restarted wingman was successful.

**Comment by SergeyTravin** [comment]
@mbatchelor please review

**Pull request merged**
