### PR TITLE
[BACKLOG-7091] Default json leaf nodes to null

### PR DESCRIPTION
**Pull request by bmorrise**

### CODE REVIEW

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
  plugins/kettle-json-plugin/src/org/pentaho/di/ui/trans/steps/jsoninput/JsonInputDialog.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.jsoninput.JsonInput:
 * Branch Change : **-2.28%**
 * Complexity Change : **-1.23%**
 * Instruction Change : **-.81%**
 * Line Change :  + .48%

org.pentaho.di.trans.steps.jsoninput.JsonInputMeta:
 * Complexity Change : **-.94%**
 * Instruction Change : **-.11%**
 * Line Change : **-.44%**
 * Method Change : **-1.02%**

org.pentaho.di.trans.steps.jsoninput.reader.FastJsonReader:
 * Branch Change : **-1.10%**
 * Complexity Change : **-6.90%**
 * Instruction Change : **-2.82%**
 * Line Change : **-3.03%**
 * Method Change : **-7.50%**

null

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

1. Message: Unused import - org.pentaho.di.job.entries.syslog.SyslogException. at Line: 73 Column: 8
2. Message: Unused import - org.pentaho.di.trans.step.RowListener. at Line: 75 Column: 8

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
  plugins/kettle-json-plugin/src/org/pentaho/di/ui/trans/steps/jsoninput/JsonInputDialog.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.jsoninput.JsonInput:
 * Branch Change : **-2.28%**
 * Complexity Change : **-1.23%**
 * Instruction Change : **-.81%**
 * Line Change :  + .48%

org.pentaho.di.trans.steps.jsoninput.JsonInputMeta:
 * Complexity Change : **-.94%**
 * Instruction Change : **-.11%**
 * Line Change : **-.44%**
 * Method Change : **-1.02%**

org.pentaho.di.trans.steps.jsoninput.reader.FastJsonReader:
 * Branch Change : **-1.10%**
 * Complexity Change : **-6.90%**
 * Instruction Change : **-2.82%**
 * Line Change : **-3.03%**
 * Method Change : **-7.50%**

null

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
  plugins/kettle-json-plugin/src/org/pentaho/di/ui/trans/steps/jsoninput/JsonInputDialog.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.jsoninput.JsonInput:
 * Branch Change : **-2.28%**
 * Complexity Change : **-1.23%**
 * Instruction Change : **-.81%**
 * Line Change :  + .48%

org.pentaho.di.trans.steps.jsoninput.JsonInputMeta:
 * Complexity Change : **-.94%**
 * Instruction Change : **-.11%**
 * Line Change : **-.44%**
 * Method Change : **-1.02%**

org.pentaho.di.trans.steps.jsoninput.reader.FastJsonReader:
 * Branch Change : **-1.10%**
 * Complexity Change : **-6.90%**
 * Instruction Change : **-2.82%**
 * Line Change : **-3.03%**
 * Method Change : **-7.50%**

null

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
  plugins/kettle-json-plugin/src/org/pentaho/di/ui/trans/steps/jsoninput/JsonInputDialog.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/reader/FastJsonReaderTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.jsoninput.JsonInput:
 * Branch Change : **-2.28%**
 * Complexity Change : **-1.23%**
 * Instruction Change : **-.81%**
 * Line Change :  + .48%

org.pentaho.di.trans.steps.jsoninput.JsonInputMeta:
 * Complexity Change : **-.94%**
 * Instruction Change : **-.11%**
 * Line Change : **-.44%**
 * Method Change : **-1.02%**

org.pentaho.di.trans.steps.jsoninput.reader.FastJsonReader:
 * Branch Change : **-1.10%**
 * Complexity Change : **-6.90%**
 * Instruction Change : **-2.82%**
 * Line Change : **-3.03%**
 * Method Change : **-7.50%**

null

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
  plugins/kettle-json-plugin/src/org/pentaho/di/ui/trans/steps/jsoninput/JsonInputDialog.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/reader/FastJsonReaderTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.jsoninput.JsonInput:
 * Branch Change : **-2.28%**
 * Complexity Change : **-1.23%**
 * Instruction Change : **-.81%**
 * Line Change :  + .48%

org.pentaho.di.trans.steps.jsoninput.JsonInputMeta:
 * Complexity Change : **-.94%**
 * Instruction Change : **-.11%**
 * Line Change : **-.44%**
 * Method Change : **-1.02%**

org.pentaho.di.trans.steps.jsoninput.reader.FastJsonReader:
 * Branch Change : **-1.10%**
 * Complexity Change : **-6.90%**
 * Instruction Change : **-2.82%**
 * Line Change : **-3.03%**
 * Method Change : **-7.50%**

null

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
  plugins/kettle-json-plugin/src/org/pentaho/di/ui/trans/steps/jsoninput/JsonInputDialog.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.jsoninput.JsonInput:
 * Branch Change : **-1.60%**
 * Complexity Change : **-.20%**
 * Instruction Change :  + 2.16%
 * Line Change :  + 4.71%
 * Method Change :  + 4.35%

org.pentaho.di.trans.steps.jsoninput.JsonInputMeta:
 * Complexity Change : **-.94%**
 * Instruction Change : **-.11%**
 * Line Change : **-.44%**
 * Method Change : **-1.02%**

org.pentaho.di.trans.steps.jsoninput.reader.FastJsonReader:
 * Branch Change : **-1.10%**
 * Complexity Change : **-6.90%**
 * Instruction Change : **-2.82%**
 * Line Change : **-3.03%**
 * Method Change : **-7.50%**

null

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
  plugins/kettle-json-plugin/src/org/pentaho/di/ui/trans/steps/jsoninput/JsonInputDialog.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.jsoninput.JsonInput:
 * Branch Change : **-1.60%**
 * Complexity Change : **-.20%**
 * Instruction Change :  + 2.16%
 * Line Change :  + 4.71%
 * Method Change :  + 4.35%

org.pentaho.di.trans.steps.jsoninput.JsonInputMeta:
 * Complexity Change : **-.94%**
 * Instruction Change : **-.11%**
 * Line Change : **-.44%**
 * Method Change : **-1.02%**

org.pentaho.di.trans.steps.jsoninput.reader.FastJsonReader:
 * Branch Change :  + 9.62%
 * Complexity Change :  + 3.59%
 * Instruction Change :  + 10.18%
 * Line Change :  + 8.13%
 * Method Change :  + 4.81%

null

**Comment by bmorrise** [comment]
@e-cuellar

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
  plugins/kettle-json-plugin/src/org/pentaho/di/ui/trans/steps/jsoninput/JsonInputDialog.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.jsoninput.JsonInput:
 * Branch Change : **-1.60%**
 * Complexity Change : **-.20%**
 * Instruction Change :  + 2.16%
 * Line Change :  + 4.71%
 * Method Change :  + 4.35%

org.pentaho.di.trans.steps.jsoninput.JsonInputMeta:
 * Complexity Change : **-.94%**
 * Instruction Change : **-.11%**
 * Line Change : **-.44%**
 * Method Change : **-1.02%**

org.pentaho.di.trans.steps.jsoninput.reader.FastJsonReader:
 * Branch Change :  + 9.62%
 * Complexity Change :  + 3.59%
 * Instruction Change :  + 10.18%
 * Line Change :  + 8.13%
 * Method Change :  + 4.81%

null

**Comment by lucboudreau** [comment]
Good effort. You got to 0.6% short of green status. :)

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
  plugins/kettle-json-plugin/src/org/pentaho/di/ui/trans/steps/jsoninput/JsonInputDialog.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputMetaTest.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.jsoninput.JsonInput:
 * Branch Change :  + 1.10%
 * Complexity Change :  + 2.89%
 * Instruction Change :  + 4.65%
 * Line Change :  + 7.53%
 * Method Change :  + 4.35%

org.pentaho.di.trans.steps.jsoninput.JsonInputMeta:
 * Branch Change :  + 16.67%
 * Complexity Change :  + 17.32%
 * Instruction Change :  + 21.99%
 * Line Change :  + 17.49%
 * Method Change :  + 18.50%

org.pentaho.di.trans.steps.jsoninput.reader.FastJsonReader:
 * Branch Change :  + 9.62%
 * Complexity Change :  + 3.59%
 * Instruction Change :  + 10.18%
 * Line Change :  + 8.13%
 * Method Change :  + 4.81%

null

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-json-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties
  plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
  plugins/kettle-json-plugin/src/org/pentaho/di/ui/trans/steps/jsoninput/JsonInputDialog.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputMetaTest.java
  plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.jsoninput.JsonInput:
 * Branch Change :  + 1.10%
 * Complexity Change :  + 2.89%
 * Instruction Change :  + 4.65%
 * Line Change :  + 7.53%
 * Method Change :  + 4.35%

org.pentaho.di.trans.steps.jsoninput.JsonInputMeta:
 * Branch Change :  + 16.67%
 * Complexity Change :  + 17.32%
 * Instruction Change :  + 21.99%
 * Line Change :  + 17.49%
 * Method Change :  + 18.50%

org.pentaho.di.trans.steps.jsoninput.reader.FastJsonReader:
 * Branch Change :  + 9.62%
 * Complexity Change :  + 3.59%
 * Instruction Change :  + 10.18%
 * Line Change :  + 8.13%
 * Method Change :  + 4.81%

null

**Pull request merged**
