### PR TITLE
PDI-18335 or PDI-7869

### PR DESCRIPTION
**Pull request by mattcasters**

### CODE REVIEW

**Comment by buildguy** [comment]
### :gear: Build finished in 1m 19s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl plugins/shapefilereader/core
```
:exclamation: No tests found!


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 5s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl plugins/shapefilereader/core
```
:exclamation: No tests found!


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 15s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl plugins/shapefilereader/core
```
:exclamation: No tests found!


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 4m 15s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl plugins/shapefilereader/core
```
:exclamation: No tests found!


:information_source:  _This is an automatic message_

**Comment by pentaho-lmartins** [comment]
Closing in favor of #6959 which includes unit tests. The commit in this PR was cherry-picked into #6959. Thank you @mattcasters for fixing this.

**Comment by mattcasters** [comment]
But of-course. You're welcome!

**Comment by buildguy** [comment]
### :gear: Build finished in 3m 14s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl plugins/shapefilereader/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6945/5/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 4m 4s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl plugins/shapefilereader/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|1|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6945/6/testReport)|
|----|


:information_source:  _This is an automatic message_

**Pull request closed without merging**
