### PR TITLE
[PDI-11365] Create lazy conversion test data and test transformations for QA and include them in the QA process

### PR DESCRIPTION
**Pull request by stepanovdg**
- Added storage-type column to Datagrid step
- Added index name column to Datagrid step (to be used if storagetype = indexed)
- Added functionality to create data with different storage types (include inject meta support)
- Fixed a couple of issues related to preview tab and binary/indexed storage types
- Added integration test

rebased from https://github.com/pentaho/pentaho-kettle/pull/512

### CODE REVIEW

**Comment by mbatchelor** [comment]
@stepanovdg - can you re-base this please? Send me an e-mail when complete and when Wingman has run on it. Thanks!

**Comment by stepanovdg** [comment]
@mbatchelor  Rebased.

**Comment by stepanovdg** [comment]
@mbatchelor Mark, could you please provide wingman logs? We have no access.

**Comment by mbatchelor** [comment]
Could you please re-base?

**Pull request closed without merging**
