### PR TITLE
[PDI-18678] In rare situation's getStatusServlet down with NPE error

### PR DESCRIPTION
**Pull request by rusxakep**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 32m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3642**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7278/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by rusxakep** [comment]
I got NPE on /kettle/status page. I can send some screenshots to your email, if you want.

**Comment by mkambol** [comment]
Sure, send a screenshot.  Was there a specific condition in which you got the NPE on the status page, though?  E.g. were you running unusual ktrs, or something?  Typically the logDate should be sent, so curious why it wasn't, and how we can reproduce the issue on our end.

**Comment by rusxakep** [comment]
> Sure, send a screenshot. Was there a specific condition in which you got the NPE on the status page, though? E.g. were you running unusual ktrs, or something? Typically the logDate should be sent, so curious why it wasn't, and how we can reproduce the issue on our end.

Matt, do you have any news? When this pull request will be accept?

**Comment by mkambol** [comment]
Sorry for the delay, @ruscakep, missed the github notification.

Can put some info in the JIRA ticket to help QA validate?  That is, how to reproduce one of the "rare situations"?

Thanks!

**Comment by rusxakep** [comment]
> Sorry for the delay, @ruscakep, missed the github notification.
> 
> Can put some info in the JIRA ticket to help QA validate? That is, how to reproduce one of the "rare situations"?
> 
> Thanks!

@mkambol 
Sure, if I get this error again, I will try to write my steps more carefully.

**Comment by rusxakep** [comment]
@mkambol 
[(https://github.com/pentaho/pentaho-kettle/pull/7314/checks?check_run_id=479316030)]

What's wrong? I haven't Pentaho VPN to access to sonar.

**Comment by mkambol** [comment]
There were a handful of places with style violations-- there should be a space between the ( and ).
E.g. `Encode.forHtml("'" + jobName + "'")` -> `Encode.forHtml( "'" + jobName + "'" )`

For future reference, Pentaho's checkstyle config is here:  https://github.com/pentaho/pentaho-coding-standards/tree/master/checkstyle

**Pull request merged**
