### PR TITLE
[PMD-1037] - NPE error appears when user uses "Data Profile" feature …

### PR DESCRIPTION
**Pull request by vasilina-terehova-epam**
When calculating statistics factor - standard deviation - npe happens on final calculation phase when we divide by quantity of rows, and take square root from this value.
According to issue http://jira.pentaho.com/browse/PDI-10250 for null data aggregation data should return null

### CODE REVIEW

**Comment by vasilina-terehova-epam** [comment]
But for string data statistics factor TYPE_GROUP_CONCAT_STRING on null input data not null but "" empty string is returned, when we do the same sql queries the result concat for null input data is also null, perhaps that should be updated.

**Comment by vasilina-terehova-epam** [comment]
@brosander Could you please take a view?

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/groupby/GroupBy.java
  engine/test-src/org/pentaho/di/trans/steps/groupby/GroupByNullInputTest.java

Unit test coverage change:
============
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.94%

org.pentaho.di.trans.steps.groupby.GroupBy:
 * Branch Change :  + 15.49%
 * Complexity Change :  + 15.25%
 * Instruction Change :  + 6.40%
 * Line Change :  + 8.54%

org.pentaho.di.trans.steps.groupby.GroupByMeta:
 * Complexity Change :  + 2.15%
 * Instruction Change :  + .51%
 * Line Change :  + 1.17%
 * Method Change :  + 4.44%

org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * Instruction Change : **-.18%**

org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * Branch Change : **-.53%**

Integration test coverage change:
============
org.pentaho.di.trans.steps.groupby.GroupBy:
 * Branch Change : **-.00%**
 * Complexity Change : **-.01%**
 * Instruction Change : **-.00%**
 * Line Change : **-.02%**

License header violations:
==========================
1. Copyright year is not the current year on engine/src/org/pentaho/di/trans/steps/groupby/GroupBy.java. Found 2013. Was expecting 2016

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/engine/src/org/pentaho/di/trans/steps/groupby/GroupBy.java

1. Message: '(' is not followed by whitespace. at Line: 725 Column: 17

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/groupby/GroupBy.java
  engine/test-src/org/pentaho/di/trans/steps/groupby/GroupByNullInputTest.java

Unit test coverage change:
============
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.94%

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Instruction Change :  + .08%

org.pentaho.di.trans.steps.groupby.GroupBy:
 * Branch Change :  + 15.90%
 * Complexity Change :  + 15.89%
 * Instruction Change :  + 6.86%
 * Line Change :  + 9.02%

org.pentaho.di.trans.steps.groupby.GroupByMeta:
 * Complexity Change :  + 2.15%
 * Instruction Change :  + .51%
 * Line Change :  + 1.17%
 * Method Change :  + 4.44%

org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * Instruction Change :  + .18%

org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * Branch Change :  + 3.33%
 * Complexity Change :  + 1.85%
 * Instruction Change :  + .28%

org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * Branch Change : **-.53%**

org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * Instruction Change :  + .18%

Integration test coverage change:
============
org.pentaho.di.trans.steps.groupby.GroupBy:
 * Branch Change : **-.00%**
 * Complexity Change : **-.01%**
 * Instruction Change : **-.00%**
 * Line Change : **-.02%**

**Comment by vasilina-terehova-epam** [comment]
@brosander checks are passed, could you take a view?

**Pull request merged**
