### PR TITLE
[PDI-19254] - XML Output "Null" under fields tab is not working as expected

### PR DESCRIPTION
**Pull request by hv-shiva**
For backward compatibility, new kettle property - KETTLE_COMPATIBILITY_XML_OUTPUT_NULL_IF_FIELD_VALUES is added in XmlOutput step.

By default, value will be KETTLE_COMPATIBILITY_XML_OUTPUT_NULL_IF_FIELD_VALUES = N indicating existing functionality
and KETTLE_COMPATIBILITY_XML_OUTPUT_NULL_IF_FIELD_VALUES = Y which populates Null If data when stream value is null

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 57m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,plugins/xml/core
```
---
:ok_hand: All tests passed!
 
Tests run: **5317**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9103/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 41m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,plugins/xml/core
```
---
:ok_hand: All tests passed!
 
Tests run: **5317**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9103/2/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 33m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,plugins/xml/core
```
---
:ok_hand: All tests passed!
 
Tests run: **5317**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9103/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 46m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,plugins/xml/core
```
---
:ok_hand: All tests passed!
 
Tests run: **5318**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9103/4/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 35m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,plugins/xml/core
```
---
:ok_hand: All tests passed!
 
Tests run: **5318**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9103/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by NJtwentyone — APPROVED** [review]
Very good PR. You documented variables and functions. As well as you created a new unit tests.

**Pull request merged**
