### PR TITLE
[SP-5919] Backport of PDI-19140 - Problems in Delete Files and Get Su…

### PR DESCRIPTION
**Pull request by ssamora**
…bfolder Names steps when using S3 (9.1 Suite)

@bcostahitachivantara @smmribeiro 

cherry-pick of https://github.com/pentaho/pentaho-kettle/pull/7864 and https://github.com/pentaho/pentaho-kettle/pull/7921

### CODE REVIEW

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PRs.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 33m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **4964**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7925/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **4964**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7925/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Sonar approved this last change!

**Review by bcostahitachivantara — APPROVED** [review]
Consistent with base bug

**Pull request merged**
