### PR TITLE
[PDI-20256] - better handling of vfs paths in open-save

### PR DESCRIPTION
**Pull request by abryant-hv**

### CODE REVIEW

**Review by niehusa — APPROVED** [review]

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[👍 Frogbot scanned this pull request and did not find any new security issues.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 18m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
plugins/file-open-save-new/core
```
---
:ok_hand: All tests passed!
 
Tests run: **61**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9764/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by dcleao — CHANGES_REQUESTED** [review]
There are other places in the code where `VFSFile#setPath(.)` is being called with an Apache VFS URI, obtained from `FileName#getURI()`. At this point, I am not sure what's the best approach, but there's at least the consistency aspect which needs to be looked at further.

**Comment by abryant-hv** [comment]
Closing this PR. This changes behavior with paths that we don't want to change. Will dig a bit more and make a more targeted fix.

**Pull request closed without merging**
