### PR TITLE
[PDI-2607] - Text File Input - 1 extra line read when using wrapped l…

### PR DESCRIPTION
**Pull request by akhayrutdinov**
…ines and 1 header line

- force reading from input when breaks' buffer is empty
- add a test for scenario of wrapped input with no headers

@mattyb149, @brosander, review it please

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, @deinspanjer, review it please

**Comment by brosander** [comment]
@akhayrutdinov please verify that unit tests pass and there are no checkstyle violations in files you've touched

**Comment by akhayrutdinov** [comment]
@brosander, I confirm there is no checkstyle violations.
As for tests, I ran those in modules (no problems), but it is impossible ti verify integration tests now, as after master had been merged with future-develop, kettle hangs on startup. You can see it here: http://ci.pentaho.com/view/Data%20Integration/job/Kettle-integration-tests/ 
(the job has been executing for 2 days). I wrote a letter to @pentaho-nbaker indicating the problem with osgi-bridge, but haven't got any feedback yet.

Before I sent this PR I had run integration tests and they were passing at that moment

**Pull request merged**
