### PR TITLE
[TEST] - Splitting PurRepositoryTest

### PR DESCRIPTION
**Pull request by akhayrutdinov**
@mattyb149, @brosander, review it please.
Actually, I don't like ```PurRepositoryTest``` as it is a monstrous class with lots of tests that hardly relate to each other. Thus I decided to create a "lightweight" version of the test thereby alleviating future testing.

Now, it is much easier to create a brand new test class just by extending ```PurRepositoryBaseTest```. It has extension points for injecting additional code in handling ```ApplicationContext``` and ```MicroPlatform```, though I believe such cases are really rare.

And last but no least, I replaced hardcoded /tmp/ path with a SpEL expression that utilizes the system property. This is useful for Windows users. Also it creates a new directory for each re-initialisation, hence there is no need to manually clean the repo's folder anymore.

- create PurRepositoryBaseTest as a parent for PurRepository-related tests and copy all necessary actions for installing establishing environment from PurRepositoryTest
- introduce PurRepositoryTestingUtils and move some common actions there
- override JCR factory bean with new spring configuration and use SpEL to locate test repository in temporary folder (picked up from the system variable)
- create PurRepository_GetObjectInformation_Test as a child of PurRepositoryBaseTest and move there related tests from PurRepositoryTest
- create PurRepository_MoveAndRename_Test as a child of PurRepositoryBaseTest and move there related tests from PurRepositoryTest

### CODE REVIEW

**Comment by brosander** [comment]
@akhayrutdinov I like the idea, I think we should probably wait until after the 6.0 branch is created

**Comment by akhayrutdinov** [comment]
@brosander, the branches has been diverged. Can you please take a look at this once again?

**Comment by akhayrutdinov** [comment]
@brosander, review it please

**Comment by akhayrutdinov** [comment]
@pminutillo, @brosander, review it please

**Comment by brosander** [comment]
@akhayrutdinov  When I run ant clean-all resolve test, I get an error that PurRepositoryBaseTest has no runnable methods.  If you intend it to have tests, it doesn't seem to, if you didn't want it to be directly run, maybe rename to PurRepositoryTestBase

**Comment by akhayrutdinov** [comment]
@brosander, cannot believe I missed it!
Anyway, I updated the PR and had checked with an Ant build all tests are passing now.

**Comment by brosander** [comment]
@akhayrutdinov 

test/org/pentaho/di/repository/pur/PurRepositoryTest.java
  line: 30 column: None message: Using the '.*' form of import should be avoided - java.util.*.
  line: 59 column: None message: Using the '.*' form of import should be avoided - org.pentaho.di.repository.*.

test/org/pentaho/di/repository/pur/PurRepositoryTestBase.java
  line: 77 column: None message: assign child at indentation level 0 not at correct indentation, 4

**Comment by akhayrutdinov** [comment]
@brosander, I've fixed it

**Pull request merged**
