### PR TITLE
[SP-2592] Backport of PDI-14606 - Salesforce Input default field format (yyyy-MM-dd'T'HH:mm:ss'.000'Z) fails for Date/Time fields (6.1 Suite)

### PR DESCRIPTION
**Pull request by IvanNikolaychuk**
- Changing date time format to java 7 style (it would be parsed with SimpleDateFormat class, that supports ISO - 8601 from java 7)

@akhayrutdinov , could you please review it? It's a backport of  https://github.com/pentaho/pentaho-kettle/pull/2272

@pamval , @pedrofvteixeira , could you please run WM?

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@pamval, @pedrofvteixeira, run WM for this PR please

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/79/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/salesforce/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/salesforce/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceinput/SalesforceInputDialog.java

**Comment by IvanNikolaychuk** [comment]
@akhayrutdinov, ready for merging

**Comment by akhayrutdinov** [comment]
No problems with Checkstyle, tests are passing, same as #2272. Merged

**Pull request merged**
