### PR TITLE
5.4 sp 2353

### PR DESCRIPTION
**Pull request by lgrill-pentaho**
See notes on SP-2353 ticket for additional details.

### CODE REVIEW

**Comment by pamval** [comment]
@mdamour1976 can you please review this backport ? Adding S3 CSV input step code to 5.4 branch.

thanks!

**Comment by mdamour1976** [comment]
Unfortunately, this doesn't result in code which compiles:

compile.compile:
    [javac] /home/mdamour/local-data/git/pentaho-kettle/plugins/kettle5-log4j-plugin/build-res/subfloor.xml:1328: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 10 source files to /home/mdamour/local-data/git/pentaho-kettle/plugins/kettle5-log4j-plugin/bin/classes
    [javac] warning: [path] bad path element "/home/mdamour/local-data/git/pentaho-kettle/plugins/kettle5-log4j-plugin/dev-lib/xercesImpl.jar": no such file or directory
    [javac] warning: [path] bad path element "/home/mdamour/local-data/git/pentaho-kettle/plugins/kettle5-log4j-plugin/dev-lib/xml-apis.jar": no such file or directory
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /home/mdamour/local-data/git/pentaho-kettle/plugins/kettle5-log4j-plugin/src/org/pentaho/di/core/logging/CentralLogStore.java:88: error: no suitable constructor found for LoggingEvent(String,Logger,long,Level,Object,<null>,<null>,<null>,<null>,<null>)
    [javac]       LoggingEvent loggingEvent = new LoggingEvent(
    [javac]                                   ^
    [javac]     constructor LoggingEvent.LoggingEvent(String,Category,Priority,Object,Throwable) is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac]     constructor LoggingEvent.LoggingEvent(String,Category,long,Priority,Object,Throwable) is not applicable
    [javac]       (actual and formal argument lists differ in length)
    [javac] 1 error
    [javac] 3 warnings

I can attempt to fix the compile issue and then push the commit to the branch if you guys are interested.

**Comment by pamval** [comment]
that's weird. There are no changes for that folder. Isn't that error already there when you compile the 5.4 branch without these changes ?

**Comment by mdamour1976** [comment]
Wiping everything (ivy/m2) and retrying now..

**Comment by mdamour1976** [comment]
Ok, so this code all compiles and produces the desired effect of having a kettle-s3csvinput-plugin in the plugins of the distribution.

Unfortunately, the plugin is not registered because of one of the following:
1.  no plugin.xml
2.  S3CsvInputMeta.java has no step annotations

In order to be a valid plugin, it will need one of the above.

For example, in master:
https://github.com/pentaho/pentaho-kettle/blob/master/plugins/kettle-s3csvinput-plugin/src/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputMeta.java#L75

But do not include the @InjectionSupported annotations, as these are 6.1+ only.

**Comment by mr9d** [comment]
@mdamour1976, can I do it or you wait it to be done by someone else?

**Comment by mdamour1976** [comment]
@mr9d you can, that would be great, thank you.

**Comment by mr9d** [comment]
@mdamour1976 no problem, I've added Step annotation: https://github.com/mr9d/pentaho-kettle/commit/651435c9c6beea0330682c914a458ec0d9b57a72

**Comment by mdamour1976** [comment]
I think so thank you.

**Pull request merged**
