### PR TITLE
[PDI-17423] - PDI REST Client Not Sending Content-Length(setting chunked)

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@pentaho-lmartins 
@pentaho/tatooine 

The problem reported is related with a bug in Jersey and Apache Client Implementation.

When a ClientRequest is converted to a HttpUriRequest a private method getHttpEntity() is called that returns a HttpEntity. Unfortunately, this returns a HttpEntity whose getContentLength() always returns a -1.

When the Apache http client creates the request it will consult the HttpEntity object for a length and since it returns -1 no Content-Length header will be set.

The solution was add an implementation of Apache Http Client 3.5 for Jersey instead of 4.x.

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 17m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3624**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7148/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 18m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3624**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7148/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3624**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7148/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by pentaho-lmartins** [comment]
Can't downgrade Jersey.

**Pull request closed without merging**
