### PR TITLE
[PDI-15821] java.lang.ArrayIndexOutOfBoundsException with metadata injection and microsoft excel input step

### PR DESCRIPTION
**Pull request by Advent51**
- NPE and OutOfBounds were fixed
- added tests
- checkstyle improvements

### CODE REVIEW

**Comment by Advent51** [comment]
@mbatchelor @pamval please review

**Comment by Advent51** [comment]
These changes were locally verified and tested.
@mbatchelor @pamval please review.

**Comment by mbatchelor** [comment]
Restarted wingman

**Comment by lucboudreau** [comment]
@mbatchelor Larry is looking into removing the overrides within build.xml which point to Sourceforge. I don't have an ETA, but it will fix this problem for good soon-ish.

**Pull request merged**
