### PR TITLE
[PDI-12727] - Change ROWNUM<1 to 1=0 in OracleDatabaseMeta.java for b…

### PR DESCRIPTION
**Pull request by mbatchelor**
…etter

performance

### CODE REVIEW

**Comment by mbatchelor** [comment]
@kurtwalker, @lucboudreau - please review and merge. Thanks!

**Comment by kurtwalker** [comment]
Any specific reason you removed the first_rows comment?  seems like someone probably put it there purposefully.

**Comment by matthewtckr** [comment]
Oracle optimizes on the `1=0` option before trying to scan the table rows for matches, so the `FIRST_ROWS` hint would have negligible impact in later stages of Oracle's query planning.

**Comment by kurtwalker** [comment]
Got it.  :+1:

**Pull request merged**
