### PR TITLE
[PDI-5537] MemoryGroupBy Aggregation Return Types

### PR DESCRIPTION
**Pull request by matthewtckr**
SUM and Average should return the same type as they are aggregating, instead of always Numeric (w/ decimal) values.

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByMeta.java
  engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByMetaTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByMetaTest.java
1. Message: Line has trailing spaces at Line: 101 Column: None
2. Message: Line has trailing spaces at Line: 106 Column: None
3. Message: Line has trailing spaces at Line: 111 Column: None
4. Message: Line has trailing spaces at Line: 116 Column: None
5. Message: Line has trailing spaces at Line: 121 Column: None
6. Message: Line has trailing spaces at Line: 126 Column: None
7. Message: Line has trailing spaces at Line: 131 Column: None
8. Message: Line has trailing spaces at Line: 136 Column: None
9. Message: Line has trailing spaces at Line: 141 Column: None
10. Message: Line has trailing spaces at Line: 146 Column: None
11. Message: Line has trailing spaces at Line: 151 Column: None
12. Message: Line has trailing spaces at Line: 156 Column: None
13. Message: Line has trailing spaces at Line: 161 Column: None
14. Message: Line has trailing spaces at Line: 166 Column: None
15. Message: Line has trailing spaces at Line: 171 Column: None
16. Message: Line has trailing spaces at Line: 176 Column: None
17. Message: Line has trailing spaces at Line: 181 Column: None
18. Message: Line has trailing spaces at Line: 186 Column: None
19. Message: Line has trailing spaces at Line: 191 Column: None
20. Message: Line has trailing spaces at Line: 196 Column: None
21. Message: Line has trailing spaces at Line: 201 Column: None
22. Message: Line has trailing spaces at Line: 206 Column: None
23. Message: Line has trailing spaces at Line: 211 Column: None
24. Message: Using a static member import should be avoided - org.junit.Assert.assertEquals. at Line: 25 Column: None
25. Message: Using a static member import should be avoided - org.junit.Assert.assertNotNull. at Line: 26 Column: None
26. Message: Using a static member import should be avoided - org.junit.Assert.assertTrue. at Line: 27 Column: None
27. Message: Line has trailing spaces at Line: 96 Column: None









Unit test coverage change:
============
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange :**-0.17%**
    
org.pentaho.di.core.lifecycle.KettleLifecycleSupport:
 * branchPercentCoverageChange :**-8.33%**
 * complexityPercentCoverageChange :**-9.09%**
    
org.pentaho.di.job.entries.ftpsget.FTPSConnection:
 * instructionPercentCoverageChange : +0.23%
 * branchPercentCoverageChange : +1.56%
 * complexityPercentCoverageChange : +1.37%
    
org.pentaho.di.trans.steps.memgroupby.MemoryGroupByMeta:
 * branchPercentCoverage :63.75%
 * instructionPercentCoverageChange : +64.51%
 * linePercentCoverageChange : +77.65%
 * complexityPercentCoverageChange : +52.11%
 * methodPercentCoverageChange : +62.07%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +0.19%
 * linePercentCoverageChange : +0.27%
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange :**-0.18%**

**Comment by deinspanjer** [comment]
I agree with the argument for SUM, but if you were averaging a set of integers, you might want those decimals for precision.

**Comment by matthewtckr** [comment]
The proposed implementation is more consistent with the standard [Group By step](https://github.com/pentaho/pentaho-kettle/blob/6.0.1.0-R/engine/src/org/pentaho/di/trans/steps/groupby/GroupByMeta.java#L449) for Average.

**Comment by deinspanjer** [comment]
Fair enough.

**Comment by matthewtckr** [comment]
Added additional tests and a backwards-compatibility flag.

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/62/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local
2. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  core/src/org/pentaho/di/core/Const.java
  engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupBy.java
  engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByMeta.java
  engine/src/org/pentaho/di/trans/steps/memgroupby/messages/messages_en_US.properties
  engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByAggregationTest.java
  engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByMetaTest.java

Newly Broken Tests:
======================
org.pentaho.di.trans.steps.memgroupby.MemoryGroupByMetaTest.testGetFields: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<3> but was:<1>
	at org.pentaho.di.trans.steps.memgroupby.MemoryGroupByMetaTest.testGetFields(MemoryGroupByMetaTest.java:277)

```


Still Broken Tests:
======================
org.pentaho.di.core.row.value.ValueMetaStringTest.testCompare_emptyIsNull: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<0> but was:<-1>
	at org.pentaho.di.core.row.value.ValueMetaStringTest.assertSignum(ValueMetaStringTest.java:831)
	at org.pentaho.di.core.row.value.ValueMetaStringTest.assertSignum(ValueMetaStringTest.java:818)
	at org.pentaho.di.core.row.value.ValueMetaStringTest.testCompare_emptyIsNull(ValueMetaStringTest.java:518)

```
org.pentaho.di.core.row.value.ValueMetaStringTest.testIsNull_emptyIsNull: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<true> but was:<false>
	at org.pentaho.di.core.row.value.ValueMetaStringTest.testIsNull_emptyIsNull(ValueMetaStringTest.java:180)

```

Unit test coverage change:
============
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change :  + 7.14%
 * Complexity Change :  + 7.69%

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.94%

org.pentaho.di.trans.step.StepMeta:
 * Instruction Change : **-.19%**
 * Line Change : **-.27%**

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Instruction Change :  + .08%

org.pentaho.di.trans.steps.memgroupby.MemoryGroupBy:
 * Branch Change :  + .66%
 * Complexity Change :  + .37%
 * Instruction Change :  + .86%
 * Line Change :  + .85%

org.pentaho.di.trans.steps.memgroupby.MemoryGroupByMeta:
 * Branch Change :  + 41.03%
 * Complexity Change :  + 39.57%
 * Instruction Change :  + 45.51%
 * Line Change :  + 47.37%
 * Method Change :  + 48.28%

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Instruction Change : **-.07%**

**Pull request merged**
