### PR TITLE
[PDI-13274] - Data Validator Validation Fails if Data Type is not String and Only Numeric data expected is checked

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- fix the missed ! operator
- add tests

@mattyb149, @brosander, review it please

### CODE REVIEW

**Comment by brosander** [comment]
Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/validator/Validator.java
  engine/test-src/org/pentaho/di/trans/steps/validator/ValidatorTest.java

Checkstyle violations:
----------------------
No errors found



Still Broken Tests:
===================
Test Case Errors:
-----------------
  org.pentaho.di.base.AbstractMetaTest.testGetSetSharedObjects: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: 
	at org.pentaho.di.base.AbstractMetaTest.testGetSetSharedObjects(AbstractMetaTest.java:521)

```
Unit test coverage change:
============
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange : +0.17%
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange : +0.28%
 * branchPercentCoverageChange : +3.33%
 * complexityPercentCoverageChange : +1.85%
    
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange :**-0.08%**
    
org.pentaho.di.trans.steps.randomvalue.RandomValueMeta:
 * instructionPercentCoverageChange :**-0.15%**
 * branchPercentCoverageChange :**-2.08%**
 * complexityPercentCoverageChange :**-2.13%**
    
org.pentaho.di.trans.steps.validator.Validator:
 * instructionPercentCoverageChange : +2.73%
 * branchPercentCoverageChange : +4.24%
 * linePercentCoverageChange : +2.32%
 * complexityPercentCoverageChange : +5.16%
 * methodPercentCoverageChange : +16.67%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +0.19%
 * linePercentCoverageChange : +0.27%
    
org.pentaho.di.trans.steps.validator.KettleValidatorException:
 * instructionPercentCoverageChange : +60.43%
 * linePercentCoverageChange : +30.43%
 * complexityPercentCoverageChange : +16.67%
 * methodPercentCoverageChange : +20.00%

**Comment by akhayrutdinov** [comment]
@brosander, do you have any comments?

**Comment by brosander** [comment]
Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/validator/Validator.java
  engine/test-src/org/pentaho/di/trans/steps/validator/ValidatorTest.java

Checkstyle violations:
----------------------
No errors found



Still Broken Tests:
===================
Test Case Errors:
-----------------
  org.pentaho.di.base.AbstractMetaTest.testGetSetSharedObjects: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: 
	at org.pentaho.di.base.AbstractMetaTest.testGetSetSharedObjects(AbstractMetaTest.java:521)

```
Unit test coverage change:
============
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange : +0.17%
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange : +0.18%
    
org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * instructionPercentCoverageChange : +0.07%
    
org.pentaho.di.trans.steps.validator.Validator:
 * instructionPercentCoverageChange : +2.73%
 * branchPercentCoverageChange : +4.24%
 * linePercentCoverageChange : +2.32%
 * complexityPercentCoverageChange : +5.16%
 * methodPercentCoverageChange : +16.67%
    
org.pentaho.di.trans.steps.validator.KettleValidatorException:
 * instructionPercentCoverageChange : +60.43%
 * linePercentCoverageChange : +30.43%
 * complexityPercentCoverageChange : +16.67%
 * methodPercentCoverageChange : +20.00%
    
org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * instructionPercentCoverageChange : +2.43%
 * branchPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +2.95%
 * complexityPercentCoverageChange : +0.69%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +0.19%
 * linePercentCoverageChange : +0.27%
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange :**-7.14%**
 * complexityPercentCoverageChange :**-7.69%**

**Comment by brosander** [comment]
@akhayrutdinov I think the negative coverage on DefaultAuthenticationConsumerFactory is due to some different code paths on second run, I'm good with pr

**Comment by brosander** [comment]
The still broken test is being worked on by @mattyb149 as part of https://github.com/pentaho/pentaho-kettle/pull/1872

**Pull request merged**
