### PR TITLE
[PDI-13206] - The Kettle5-log4j plugin doesn't work because init never gets called on the plugin

### PR DESCRIPTION
**Pull request by AndreyBurikhin**
@e-cuellar , @mdamour1976 same as https://github.com/pentaho/pentaho-kettle/pull/1768

### CODE REVIEW

**Comment by mdamour1976** [comment]
@dkincade just looping you in here

**Comment by dkincade** [comment]
thanks - @dkincade or @pamval are the only two that should include this item

**Comment by dkincade** [comment]
@AndreyBurikhin @mdamour1976 - where is this included in master? I haven't been able to find it yet...

**Comment by mdamour1976** [comment]
I didn't merge it yet, I believe it had been previously reviewed by Ezequiel.  There should be a PR.

**Comment by dkincade** [comment]
I don't want to merge this yet into the 6.0.0.0 until it has been merged in Master (and proved that it does cause compilation problems).

**Comment by mdamour1976** [comment]
@dkincade FYI merged into master yesterday (no issues on 6.0-snapshot)

**Pull request merged**
