### PR TITLE
[PDI-5153] Cannot log LOG_FIELD for transformation logging to MySQL -…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
… add logging only message exception strategy and unit tests

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
@brosander @mchen-len-son

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman/28/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  core/src/org/pentaho/di/core/database/BaseDatabaseMeta.java
  core/src/org/pentaho/di/core/database/Database.java
  core/src/org/pentaho/di/core/database/DatabaseInterfaceExtended.java
  core/src/org/pentaho/di/core/database/MySQLDatabaseMeta.java
  core/src/org/pentaho/di/core/database/util/DatabaseLogExceptionFactory.java
  core/test-src/com/mysql/jdbc/PacketTooBigException.java
  core/test-src/org/pentaho/di/core/database/util/DatabaseLogExceptionFactoryTest.java

Newly Fixed Tests:
======================
org.pentaho.di.core.logging.LoggingBufferTest.testRaceCondition:
-----------------------------------------------
junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: Failed expected:<true> but was:<false>
	at org.pentaho.di.core.logging.LoggingBufferTest.testRaceCondition(LoggingBufferTest.java:101)

```

Unit test coverage change:
============
org.pentaho.di.compatibility.ValueString:
 * Branch Change :  + 5.00%
 * Complexity Change :  + 2.70%
 * Instruction Change :  + .89%

org.pentaho.di.core.database.BaseDatabaseMeta:
 * Complexity Change : **-.06%**
 * Instruction Change : **-.02%**
 * Line Change : **-.04%**
 * Method Change : **-.13%**

org.pentaho.di.core.database.Database:
 * Instruction Change : **-.00%**

org.pentaho.di.core.database.MySQLDatabaseMeta:
 * Branch Change :  + 4.69%
 * Complexity Change :  + 1.16%
 * Instruction Change :  + .99%
 * Line Change :  + 1.77%
 * Method Change :  + 2.48%

org.pentaho.di.core.database.util.DatabaseLogExceptionFactory:
 * Branch Change :  + 71.43%
 * Complexity Change :  + 58.33%
 * Instruction Change :  + 93.42%
 * Line Change :  + 94.74%
 * Method Change :  + 80.00%

org.pentaho.di.core.database.util.DatabaseLogExceptionFactory.SuppressableWithShortMessage:
 * Complexity New Coverage : 50.00%
 * Instruction New Coverage : 26.67%
 * Line New Coverage : 25.00%
 * Method New Coverage : 50.00%

org.pentaho.di.core.database.util.DatabaseLogExceptionFactory.SuppressBehaviour:
 * Complexity Change :  + 33.33%
 * Instruction Change :  + 16.67%
 * Line Change :  + 20.00%
 * Method Change :  + 33.33%

org.pentaho.di.core.database.util.DatabaseLogExceptionFactory.ThrowableBehaviour:
 * Complexity Change :  + 33.33%
 * Instruction Change :  + 15.00%
 * Line Change :  + 33.33%
 * Method Change :  + 33.33%

org.pentaho.di.core.exception.KettleDatabaseException:
 * Complexity Change :  + 25.00%
 * Instruction Change :  + 25.00%
 * Line Change :  + 25.00%
 * Method Change :  + 25.00%

License header violations:
==========================
1. core/test-src/com/mysql/jdbc/PacketTooBigException.java
2. core/test-src/org/pentaho/di/core/database/util/DatabaseLogExceptionFactoryTest.java

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/core/test-src/org/pentaho/di/core/database/util/DatabaseLogExceptionFactoryTest.java

1. Message: Using a static member import should be avoided - org.pentaho.di.core.database.util.DatabaseLogExceptionFactory.KETTLE_GLOBAL_PROP_NAME. at Line: 18

**Comment by stanislau-strelchanka** [comment]
@pamval, please update wingman

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/9/

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  core/src/org/pentaho/di/core/database/BaseDatabaseMeta.java
  core/src/org/pentaho/di/core/database/Database.java
  core/src/org/pentaho/di/core/database/DatabaseInterfaceExtended.java
  core/src/org/pentaho/di/core/database/MySQLDatabaseMeta.java
  core/src/org/pentaho/di/core/database/util/DatabaseLogExceptionFactory.java
  core/test-src/com/mysql/jdbc/MysqlDataTruncation.java
  core/test-src/com/mysql/jdbc/PacketTooBigException.java
  core/test-src/org/pentaho/di/core/database/util/DatabaseLogExceptionFactoryTest.java



Unit test coverage change:
============
org.pentaho.di.compatibility.ValueString:
 * Branch Change :  + 5.00%
 * Complexity Change :  + 2.70%
 * Instruction Change :  + .89%

org.pentaho.di.core.database.BaseDatabaseMeta:
 * Complexity Change : **-.06%**
 * Instruction Change : **-.02%**
 * Line Change : **-.04%**
 * Method Change : **-.13%**

org.pentaho.di.core.database.Database:
 * Instruction Change : **-.00%**

org.pentaho.di.core.database.MySQLDatabaseMeta:
 * Branch Change :  + 4.69%
 * Complexity Change :  + 2.47%
 * Instruction Change :  + 1.83%
 * Line Change :  + 3.47%
 * Method Change :  + 4.82%

org.pentaho.di.core.database.util.DatabaseLogExceptionFactory:
 * Branch Change :  + 71.43%
 * Complexity Change :  + 58.33%
 * Instruction Change :  + 93.42%
 * Line Change :  + 94.74%
 * Method Change :  + 80.00%

org.pentaho.di.core.database.util.DatabaseLogExceptionFactory.SuppressableWithShortMessage:
 * Complexity New Coverage : 50.00%
 * Instruction New Coverage : 26.67%
 * Line New Coverage : 25.00%
 * Method New Coverage : 50.00%

org.pentaho.di.core.database.util.DatabaseLogExceptionFactory.SuppressBehaviour:
 * Complexity Change :  + 33.33%
 * Instruction Change :  + 16.67%
 * Line Change :  + 20.00%
 * Method Change :  + 33.33%

org.pentaho.di.core.database.util.DatabaseLogExceptionFactory.ThrowableBehaviour:
 * Complexity Change :  + 33.33%
 * Instruction Change :  + 15.00%
 * Line Change :  + 33.33%
 * Method Change :  + 33.33%

org.pentaho.di.core.exception.KettleDatabaseException:
 * Complexity Change :  + 25.00%
 * Instruction Change :  + 25.00%
 * Line Change :  + 25.00%
 * Method Change :  + 25.00%



Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/core/test-src/org/pentaho/di/core/database/util/DatabaseLogExceptionFactoryTest.java

1. Message: Using a static member import should be avoided - org.pentaho.di.core.database.util.DatabaseLogExceptionFactory.KETTLE_GLOBAL_PROP_NAME. at Line: 40

**Comment by stanislau-strelchanka** [comment]
@pamval, fixed styles, please update wingman

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/10/

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  core/src/org/pentaho/di/core/database/BaseDatabaseMeta.java
  core/src/org/pentaho/di/core/database/Database.java
  core/src/org/pentaho/di/core/database/DatabaseInterfaceExtended.java
  core/src/org/pentaho/di/core/database/MySQLDatabaseMeta.java
  core/src/org/pentaho/di/core/database/util/DatabaseLogExceptionFactory.java
  core/test-src/com/mysql/jdbc/MysqlDataTruncation.java
  core/test-src/com/mysql/jdbc/PacketTooBigException.java
  core/test-src/org/pentaho/di/core/database/util/DatabaseLogExceptionFactoryTest.java



Unit test coverage change:
============
org.pentaho.di.compatibility.ValueString:
 * Branch Change :  + 5.00%
 * Complexity Change :  + 2.70%
 * Instruction Change :  + .89%

org.pentaho.di.core.database.BaseDatabaseMeta:
 * Complexity Change : **-.06%**
 * Instruction Change : **-.02%**
 * Line Change : **-.04%**
 * Method Change : **-.13%**

org.pentaho.di.core.database.Database:
 * Instruction Change : **-.00%**

org.pentaho.di.core.database.MySQLDatabaseMeta:
 * Branch Change :  + 4.69%
 * Complexity Change :  + 2.47%
 * Instruction Change :  + 1.83%
 * Line Change :  + 3.47%
 * Method Change :  + 4.82%

org.pentaho.di.core.database.util.DatabaseLogExceptionFactory:
 * Branch Change :  + 71.43%
 * Complexity Change :  + 58.33%
 * Instruction Change :  + 93.42%
 * Line Change :  + 94.74%
 * Method Change :  + 80.00%

org.pentaho.di.core.database.util.DatabaseLogExceptionFactory.SuppressableWithShortMessage:
 * Complexity New Coverage : 50.00%
 * Instruction New Coverage : 26.67%
 * Line New Coverage : 25.00%
 * Method New Coverage : 50.00%

org.pentaho.di.core.database.util.DatabaseLogExceptionFactory.SuppressBehaviour:
 * Complexity Change :  + 33.33%
 * Instruction Change :  + 16.67%
 * Line Change :  + 20.00%
 * Method Change :  + 33.33%

org.pentaho.di.core.database.util.DatabaseLogExceptionFactory.ThrowableBehaviour:
 * Complexity Change :  + 33.33%
 * Instruction Change :  + 15.00%
 * Line Change :  + 33.33%
 * Method Change :  + 33.33%

org.pentaho.di.core.exception.KettleDatabaseException:
 * Complexity Change :  + 25.00%
 * Instruction Change :  + 25.00%
 * Line Change :  + 25.00%
 * Method Change :  + 25.00%

**Comment by stanislau-strelchanka** [comment]
@brosander, @mattyb149, @mchen-len-son  updated styles, please review

**Pull request merged**
