### PR TITLE
[BACKLOG-6843] Change indexed setters in MDI into custom converter implementation

### PR DESCRIPTION
**Pull request by AlexanderBuloichik**

### CODE REVIEW

**Comment by bmorrise** [comment]
Running Wingman: http://10.100.11.222:8080/job/wingman-ant/452/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local
3. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local
4. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/googleanalytics/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/di/core/RowMetaAndData.java
  core/src/org/pentaho/di/core/injection/DefaultInjectionTypeConverter.java
  core/src/org/pentaho/di/core/injection/InjectionTypeConverter.java
  core/test-src/org/pentaho/di/core/RowMetaAndDataTest.java
  engine/src/org/pentaho/di/core/annotations/Inject.java
  engine/src/org/pentaho/di/core/injection/Injection.java
  engine/src/org/pentaho/di/core/injection/bean/BeanInjector.java
  engine/src/org/pentaho/di/core/injection/bean/BeanLevelInfo.java
  engine/src/org/pentaho/di/trans/steps/fieldsplitter/DataTypeConverter.java
  engine/src/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitterMeta.java
  engine/src/org/pentaho/di/trans/steps/fieldsplitter/TrimTypeConverter.java
  plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStepMeta.java
  plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/OutputTypeConverter.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File engine/src/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitterMeta.java
1. Message: Unused import - java.util.Arrays. at Line: 25 Column: 8

File plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStepMeta.java
1. Message: Unused import - java.util.Arrays. at Line: 26 Column: 8
2. Message: ')' have incorrect indentation level 0, expected level should be 2. at Line: 66 Column: None









Unit test coverage change:
============
org.pentaho.di.core.injection.DefaultInjectionTypeConverter:
 * branchPercentCoverage :76.92%
 * linePercentCoverage :75.00%
 * methodPercentCoverage :76.67%
 * complexityPercentCoverage :75.00%
 * instructionPercentCoverage :73.02%
    
org.pentaho.di.core.row.value.ValueMetaBase:
 * instructionPercentCoverageChange :**-0.02%**
 * branchPercentCoverageChange :**-0.08%**
 * linePercentCoverageChange :**-0.05%**
 * complexityPercentCoverageChange :**-0.10%**
    
org.pentaho.di.core.RowMetaAndData:
 * instructionPercentCoverageChange :**-5.31%**
 * branchPercentCoverageChange :**-14.01%**
 * linePercentCoverageChange :**-0.71%**
 * complexityPercentCoverageChange :**-9.69%**
 * methodPercentCoverageChange :**-0.53%**
    
org.pentaho.di.core.injection.InjectionTypeConverter:
 * linePercentCoverage :3.03%
 * methodPercentCoverage :3.03%
 * complexityPercentCoverage :3.03%
 * instructionPercentCoverage :1.84%
    
org.pentaho.di.trans.Trans:
 * instructionPercentCoverageChange : +0.09%
 * branchPercentCoverageChange : +0.10%
 * linePercentCoverageChange : +0.11%
 * complexityPercentCoverageChange : +0.14%
    
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange : +0.08%
    
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange :**-0.18%**
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange : +0.28%
 * branchPercentCoverageChange : +3.33%
 * complexityPercentCoverageChange : +1.85%
    
org.pentaho.di.trans.steps.fieldsplitter.FieldSplitterMeta:
 * instructionPercentCoverageChange : +1.56%
 * branchPercentCoverageChange : +4.75%
 * linePercentCoverageChange : +1.48%
 * complexityPercentCoverageChange : +4.24%
 * methodPercentCoverageChange : +1.61%
    
org.pentaho.di.trans.steps.fieldsplitter.TrimTypeConverter:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.core.injection.bean.BeanLevelInfo:
 * instructionPercentCoverageChange :**-17.36%**
 * branchPercentCoverageChange :**-6.80%**
 * linePercentCoverageChange :**-9.08%**
 * complexityPercentCoverageChange :**-12.50%**
 * methodPercentCoverageChange :**-12.50%**
    
org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * instructionPercentCoverageChange : +2.43%
 * branchPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +3.70%
 * complexityPercentCoverageChange : +0.69%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +0.19%
 * linePercentCoverageChange : +0.27%
    
org.pentaho.di.trans.steps.fieldsplitter.DataTypeConverter:
 * linePercentCoverage :50.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :50.00%
    
org.pentaho.di.core.injection.bean.BeanInjector:
 * instructionPercentCoverageChange :**-3.22%**
 * branchPercentCoverageChange :**-3.55%**
 * linePercentCoverageChange :**-3.40%**
 * complexityPercentCoverageChange :**-0.54%**
    
org.pentaho.di.trans.steps.googleanalytics.OutputTypeConverter:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.steps.googleanalytics.GaInputStepMeta:
 * instructionPercentCoverageChange :**-0.49%**
 * branchPercentCoverageChange :**-3.48%**
 * linePercentCoverageChange :**-0.59%**
 * complexityPercentCoverageChange :**-0.10%**
 * methodPercentCoverageChange :**-0.23%**
    
Integration test coverage change:
============
org.pentaho.di.core.injection.bean.BeanLevelInfo:
 * instructionPercentCoverageChange :**-13.28%**
 * branchPercentCoverageChange :**-1.97%**
 * linePercentCoverageChange :**-5.29%**
 * complexityPercentCoverageChange :**-7.50%**
 * methodPercentCoverageChange :**-12.50%**
    
org.pentaho.di.core.injection.bean.BeanInjector:
 * instructionPercentCoverageChange : +2.18%
 * branchPercentCoverageChange : +3.92%
 * linePercentCoverageChange : +1.41%
 * complexityPercentCoverageChange : +1.73%

**Comment by AlexanderBuloichik** [comment]
Unused imports removed, some tests added

**Comment by bmorrise** [comment]
Running Wingman: http://10.100.11.222:8080/job/wingman-ant/459/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local
3. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local
4. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/googleanalytics/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/di/core/RowMetaAndData.java
  core/src/org/pentaho/di/core/injection/DefaultInjectionTypeConverter.java
  core/src/org/pentaho/di/core/injection/InjectionTypeConverter.java
  core/test-src/org/pentaho/di/core/RowMetaAndDataTest.java
  engine/src/org/pentaho/di/core/annotations/Inject.java
  engine/src/org/pentaho/di/core/injection/Injection.java
  engine/src/org/pentaho/di/core/injection/bean/BeanInjector.java
  engine/src/org/pentaho/di/core/injection/bean/BeanLevelInfo.java
  engine/src/org/pentaho/di/trans/steps/fieldsplitter/DataTypeConverter.java
  engine/src/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitterMeta.java
  engine/src/org/pentaho/di/trans/steps/fieldsplitter/TrimTypeConverter.java
  engine/test-src/org/pentaho/di/core/injection/MetaAnnotationInjectionTest.java
  engine/test-src/org/pentaho/di/core/injection/MetaBeanWrong1.java
  engine/test-src/org/pentaho/di/core/injection/MetaBeanWrong2.java
  engine/test-src/org/pentaho/di/core/injection/MetaBeanWrong3.java
  engine/test-src/org/pentaho/di/core/injection/MetaBeanWrong4.java
  engine/test-src/org/pentaho/di/core/injection/MetaBeanWrong5.java
  plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStepMeta.java
  plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/OutputTypeConverter.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStepMeta.java
1. Message: ')' have incorrect indentation level 0, expected level should be 2. at Line: 65 Column: None









Unit test coverage change:
============
org.pentaho.di.core.injection.DefaultInjectionTypeConverter:
 * branchPercentCoverage :76.92%
 * linePercentCoverage :75.00%
 * methodPercentCoverage :76.67%
 * complexityPercentCoverage :75.00%
 * instructionPercentCoverage :73.02%
    
org.pentaho.di.core.RowMetaAndData:
 * instructionPercentCoverageChange :**-5.31%**
 * branchPercentCoverageChange :**-14.01%**
 * linePercentCoverageChange :**-0.71%**
 * complexityPercentCoverageChange :**-9.69%**
 * methodPercentCoverageChange :**-0.53%**
    
org.pentaho.di.core.injection.InjectionTypeConverter:
 * linePercentCoverage :3.03%
 * methodPercentCoverage :3.03%
 * complexityPercentCoverage :3.03%
 * instructionPercentCoverage :1.84%
    
org.pentaho.di.trans.Trans:
 * instructionPercentCoverageChange : +0.09%
 * branchPercentCoverageChange : +0.10%
 * linePercentCoverageChange : +0.11%
 * complexityPercentCoverageChange : +0.14%
    
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange :**-0.08%**
    
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange : +0.18%
    
org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * instructionPercentCoverageChange : +0.07%
    
org.pentaho.di.trans.steps.fieldsplitter.FieldSplitterMeta:
 * instructionPercentCoverageChange : +1.56%
 * branchPercentCoverageChange : +4.75%
 * linePercentCoverageChange : +1.48%
 * complexityPercentCoverageChange : +4.24%
 * methodPercentCoverageChange : +1.61%
    
org.pentaho.di.trans.steps.fieldsplitter.TrimTypeConverter:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.core.injection.bean.BeanLevelInfo:
 * instructionPercentCoverageChange :**-3.39%**
 * branchPercentCoverageChange : +7.26%
 * linePercentCoverageChange : +0.81%
 * complexityPercentCoverageChange : +7.50%
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange : +0.18%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +0.19%
 * linePercentCoverageChange : +0.27%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +1.94%
    
org.pentaho.di.trans.steps.fieldsplitter.DataTypeConverter:
 * linePercentCoverage :50.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :50.00%
    
org.pentaho.di.core.injection.bean.BeanInjector:
 * instructionPercentCoverageChange :**-3.22%**
 * branchPercentCoverageChange :**-3.55%**
 * linePercentCoverageChange :**-3.40%**
 * complexityPercentCoverageChange :**-0.54%**
    
org.pentaho.di.trans.steps.googleanalytics.OutputTypeConverter:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.steps.googleanalytics.GaInputStepMeta:
 * instructionPercentCoverageChange :**-0.49%**
 * branchPercentCoverageChange :**-3.48%**
 * linePercentCoverageChange :**-0.59%**
 * complexityPercentCoverageChange :**-0.10%**
 * methodPercentCoverageChange :**-0.23%**
    
Integration test coverage change:
============
org.pentaho.di.core.injection.bean.BeanLevelInfo:
 * instructionPercentCoverageChange :**-13.15%**
 * branchPercentCoverageChange :**-1.97%**
 * linePercentCoverageChange :**-5.29%**
 * complexityPercentCoverageChange :**-7.50%**
 * methodPercentCoverageChange :**-12.50%**
    
org.pentaho.di.core.injection.bean.BeanInjector:
 * instructionPercentCoverageChange : +2.18%
 * branchPercentCoverageChange : +3.92%
 * linePercentCoverageChange : +1.41%
 * complexityPercentCoverageChange : +1.73%

**Comment by AlexanderBuloichik** [comment]
Fixed, sorry

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local
3. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local
4. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/googleanalytics/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/di/core/RowMetaAndData.java
  core/src/org/pentaho/di/core/injection/DefaultInjectionTypeConverter.java
  core/src/org/pentaho/di/core/injection/InjectionTypeConverter.java
  core/test-src/org/pentaho/di/core/RowMetaAndDataTest.java
  engine/src/org/pentaho/di/core/annotations/Inject.java
  engine/src/org/pentaho/di/core/injection/Injection.java
  engine/src/org/pentaho/di/core/injection/bean/BeanInjector.java
  engine/src/org/pentaho/di/core/injection/bean/BeanLevelInfo.java
  engine/src/org/pentaho/di/trans/steps/fieldsplitter/DataTypeConverter.java
  engine/src/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitterMeta.java
  engine/src/org/pentaho/di/trans/steps/fieldsplitter/TrimTypeConverter.java
  engine/test-src/org/pentaho/di/core/injection/MetaAnnotationInjectionTest.java
  engine/test-src/org/pentaho/di/core/injection/MetaBeanWrong1.java
  engine/test-src/org/pentaho/di/core/injection/MetaBeanWrong2.java
  engine/test-src/org/pentaho/di/core/injection/MetaBeanWrong3.java
  engine/test-src/org/pentaho/di/core/injection/MetaBeanWrong4.java
  engine/test-src/org/pentaho/di/core/injection/MetaBeanWrong5.java
  plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStepMeta.java
  plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/OutputTypeConverter.java










Unit test coverage change:
============
org.pentaho.di.core.injection.DefaultInjectionTypeConverter:
 * branchPercentCoverage :76.92%
 * linePercentCoverage :75.00%
 * methodPercentCoverage :76.67%
 * complexityPercentCoverage :75.00%
 * instructionPercentCoverage :73.02%
    
org.pentaho.di.core.RowMetaAndData:
 * instructionPercentCoverageChange :**-5.31%**
 * branchPercentCoverageChange :**-14.01%**
 * linePercentCoverageChange :**-0.71%**
 * complexityPercentCoverageChange :**-9.69%**
 * methodPercentCoverageChange :**-0.53%**
    
org.pentaho.di.core.injection.InjectionTypeConverter:
 * linePercentCoverage :3.03%
 * methodPercentCoverage :3.03%
 * complexityPercentCoverage :3.03%
 * instructionPercentCoverage :1.84%
    
org.pentaho.di.trans.Trans:
 * instructionPercentCoverageChange : +0.09%
 * branchPercentCoverageChange : +0.10%
 * linePercentCoverageChange : +0.11%
 * complexityPercentCoverageChange : +0.14%
    
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange :**-0.08%**
    
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange : +0.18%
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange :**-0.18%**
    
org.pentaho.di.trans.steps.fieldsplitter.FieldSplitterMeta:
 * instructionPercentCoverageChange : +1.56%
 * branchPercentCoverageChange : +4.75%
 * linePercentCoverageChange : +1.48%
 * complexityPercentCoverageChange : +4.24%
 * methodPercentCoverageChange : +1.61%
    
org.pentaho.di.trans.steps.fieldsplitter.TrimTypeConverter:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.steps.randomvalue.RandomValueMeta:
 * instructionPercentCoverageChange :**-0.15%**
 * branchPercentCoverageChange :**-2.17%**
 * complexityPercentCoverageChange :**-2.17%**
    
org.pentaho.di.core.injection.bean.BeanLevelInfo:
 * instructionPercentCoverageChange :**-3.39%**
 * branchPercentCoverageChange : +7.26%
 * linePercentCoverageChange : +0.81%
 * complexityPercentCoverageChange : +7.50%
    
org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * instructionPercentCoverageChange :**-2.43%**
 * branchPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-3.70%**
 * complexityPercentCoverageChange :**-0.69%**
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-1.94%**
    
org.pentaho.di.trans.steps.fieldsplitter.DataTypeConverter:
 * linePercentCoverage :50.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :50.00%
    
org.pentaho.di.core.injection.bean.BeanInjector:
 * instructionPercentCoverageChange :**-3.22%**
 * branchPercentCoverageChange :**-3.55%**
 * linePercentCoverageChange :**-3.40%**
 * complexityPercentCoverageChange :**-0.54%**
    
org.pentaho.di.trans.steps.googleanalytics.OutputTypeConverter:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.steps.googleanalytics.GaInputStepMeta:
 * instructionPercentCoverageChange :**-0.49%**
 * branchPercentCoverageChange :**-3.48%**
 * linePercentCoverageChange :**-0.59%**
 * complexityPercentCoverageChange :**-0.10%**
 * methodPercentCoverageChange :**-0.23%**
    
Integration test coverage change:
============
org.pentaho.di.core.injection.bean.BeanLevelInfo:
 * instructionPercentCoverageChange :**-13.15%**
 * branchPercentCoverageChange :**-1.97%**
 * linePercentCoverageChange :**-5.29%**
 * complexityPercentCoverageChange :**-7.50%**
 * methodPercentCoverageChange :**-12.50%**
    
org.pentaho.di.core.injection.bean.BeanInjector:
 * instructionPercentCoverageChange : +2.18%
 * branchPercentCoverageChange : +3.92%
 * linePercentCoverageChange : +1.41%
 * complexityPercentCoverageChange : +1.73%

**Pull request merged**
