### PR TITLE
[PDI-15928] - Get Repository Names step hangs when working with the

### PR DESCRIPTION
**Pull request by SergeyTravin**
Pentaho Repository

### CODE REVIEW

**Comment by SergeyTravin** [comment]
I have changed the method in interface because it was introduced one month ago https://github.com/pentaho/pentaho-kettle/pull/3368 and the changed method have more powerful functionality. From my perspective the chaanged method is more useful for major release instead of the method definied before my changes because it allows to get more accurate information from server side.

**Comment by bmorrise** [comment]
@tgf Can you take a look at this?

**Comment by rmansoor** [comment]
@tgf please review this as well. I have reviewed it. If you find anything that is wrong, please let @SergeyTravin know

**Comment by tgf** [comment]
looks good to me

**Pull request merged**
