### PR TITLE
[PDI-13927] - Checking type before casting, adding null handling in g…

### PR DESCRIPTION
**Pull request by brosander**
…etDataSourceFromJndi

### CODE REVIEW

**Comment by brosander** [comment]
@dkincade is 5.4 the right branch?
@e-cuellar Mind pulling this down and testing on your box, mysql generic seems to be working with this fix

**Comment by e-cuellar** [comment]
@brosander @dkincade Brian... I bet this will work! But as you might have found the "dsName" is getting passed as an empty String causing the InitialContext to return an instance of a MemoryContext, which in my opinion... if the dsName is empty or null then this method should not even be called.....  or simply throw a NamingException on a empty dsName and let the flow do the rest....  However I'd be ok with your fix if advised!

**Comment by brosander** [comment]
@e-cuellar the if check at the top should throw the correct exception if dsName is null now

**Comment by e-cuellar** [comment]
@brosander Gotcha!... I like it! :) let me check it!

**Comment by e-cuellar** [comment]
@brosander Sorry Brian... the dsName is not getting passed as null but as an empty string.... thus it will fail the if check.... I suggest using the Const.isEmpty method instead....

**Comment by brosander** [comment]
@e-cuellar good catch!  The get sql button was passing null in.  I guess we could run into an issue if there was a jndi connectio with an empty name that was matched.

**Comment by e-cuellar** [comment]
@brosander Awesome!... Checking the fix locally... I will merge in a bit!

**Comment by brosander** [comment]
@e-cuellar added String.valueOf( dsName ) to ensure we won't get a NPE there either

**Comment by dkincade** [comment]
5.4 is the correct branch - once validated please ensure this is included in master as well.

**Pull request merged**
