### PR TITLE
[PDI-19013] - Get data from XML: "Size field" value not saved when the transformation is saved in repository

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@pentaho-lmartins 
@ssamora 
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 5m 41s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/xml/core
```
---
:ok_hand: All tests passed!
 
Tests run: **79**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7820/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ssamora** [comment]
Well spotted. Changes seem fine. Can you address the multiple literals Sonar issue ?

**Comment by buildguy** [comment]
### :warning: Build finished in 6m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/xml/core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.getxmldata.GetXMLDataMetaTest.testSaveRepOfAdditionalOutputFields</b> (click to expand)</summary><p>

```

Argument(s) are different! Wanted:
repository.saveStepAttribute(
    Mock for ObjectId, hashCode: 1510813400,
    Mock for ObjectId, hashCode: 1839610003,
    "sizeFieldName",
    null
);
-> at org.pentaho.di.trans.steps.getxmldata.GetXMLDataMetaTest.testSaveRepOfAdditionalOutputFields(GetXMLDataMetaTest.java:60)
Actual invocation has different arguments:
repository.saveStepAttribute(
    Mock for ObjectId, hashCode: 1510813400,
    Mock for ObjectId, hashCode: 1839610003,
    "include_field",
    null
);
-> at org.pentaho.di.trans.steps.getxmldata.GetXMLDataMeta.saveRep(GetXMLDataMeta.java:1104)

```

</p></details>

  
Tests run: **79**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7820/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/xml/core
```
---
:ok_hand: All tests passed!
 
Tests run: **79**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7820/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/xml/core
```
---
:ok_hand: All tests passed!
 
Tests run: **79**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7820/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ssamora — APPROVED** [review]

**Pull request merged**
