### PR TITLE
[CLEANUP] Checkstyle

### PR DESCRIPTION
**Pull request by matthewtckr**

### CODE REVIEW

**Comment by lucboudreau** [comment]
I could never figure out why this happens every now and then. I had it output all commands like this, tried them locally, but it does not cause the same problem.

```
Git clone: [git, clone, --depth=10, --branch, master, https://[GITHUB TOKEN]@github.com/pentaho/pentaho-kettle.git, pentaho-kettle-base-2834-b7f06154-8bb8-4039-b6e3-487ccec3d1e4]
Git fetch: [git, fetch, --depth=11, origin, pull/2834/head:pullRequest]
Git merge: [git, merge, --no-edit, --no-ff, -X, theirs, pullRequest]
```

**Comment by matthewtckr** [comment]
@lucboudreau I'll just try backing out those 4 files for now, and re-submit them if Wingman responds better after they're gone.

**Comment by matthewtckr** [comment]
See #2839.  More fallout from removing the kettle-engine-test artifact as a dependency in the UI module.

**Comment by matthewtckr** [comment]
The copyright statements on those files are a bit more complicated (multiple copyright claims, but the Pentaho copyright claim does say 2016.

I'd like to grandfather the DummyPlugin empty statement violation for now, as the statement is simply calling processRow() repeatedly.

**Pull request merged**
