### PR TITLE
[BACKLOG-12003]Persist Filter step output when target is renamed

### PR DESCRIPTION
**Pull request by hudak**
Reverts previous fixes that caused this regression
2fa882af41b0baaee72d4cc0faa7fa44921326aa
3c46aa03c8f54ecb00995aa01388c5cd61b15222

### CODE REVIEW

**Comment by hudak** [comment]
@dkincade @kcruzada

**Comment by dkincade** [comment]
Would love a code review from @bmorrise or @mkambol  or anyone on R2D2 / BB8

**Comment by ccaspanello** [comment]
I'm reviewing it right now.

**Comment by ccaspanello** [comment]
Code looks good.  Built and ran locally.

**Pull request merged**
