### PR TITLE
[PDI-19054] Fixed for - Logging Registry is unable to purge LogChanne…

### PR DESCRIPTION
**Pull request by gkuntsevich**
…ls error

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **5034**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7852/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 22m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 7 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.pentahoreporting.PentahoReportingOutputTest.testProcessRowWithoutUsingValuesFromFields</b> (click to expand)</summary><p>

```
org/pentaho/reporting/libraries/base/boot/AbstractBoot
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.pentahoreporting.PentahoReportingOutputTest.testProcessRowWitUsingValuesFromFields</b> (click to expand)</summary><p>

```
org/pentaho/reporting/libraries/resourceloader/LibLoaderBoot
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.pentahoreporting.PentahoReportingOutputTest.testLoadLocalReport</b> (click to expand)</summary><p>

```
org/pentaho/reporting/libraries/resourceloader/LibLoaderBoot
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.pentahoreporting.PentahoReportingOutputTest.testLocalFile</b> (click to expand)</summary><p>

```
org/pentaho/reporting/libraries/resourceloader/LibLoaderBoot
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.pentahoreporting.ReportExportTaskTest.testExportReportWithUnsupportedLocale</b> (click to expand)</summary><p>

```
org/pentaho/reporting/libraries/base/config/Configuration
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.pentahoreporting.ReportExportTaskTest.testExportReportWithNullReport</b> (click to expand)</summary><p>

```
org/pentaho/reporting/libraries/base/config/Configuration
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.pentahoreporting.ReportExportTaskTest.testExportReportWithSupportedLocale</b> (click to expand)</summary><p>

```
org/pentaho/reporting/libraries/base/config/Configuration
```

</p></details>

  
Tests run: **5034**, Failures: **7**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7852/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 24m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **5034**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7852/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by cdeptula** [comment]
Should this log message be logged at the warning level instead of the error level? It really is not an error and the server will continue to work.

**Pull request merged**
