### PR TITLE
[PDI-13696] - Text File Input: deteriorated performance for compressed i...

### PR DESCRIPTION
**Pull request by akhayrutdinov**
...nput

@mattyb149, @brosander review it please

### CODE REVIEW

**Comment by mattyb149** [comment]
Unit tests please

**Comment by akhayrutdinov** [comment]
@mattyb149 do you really think this should be tested?)
In contrary with the previous PR (related to FileTextOutput), there's no refactoring - just introducing two public methods from standard API. Of course, I can test, for instance, the usage of read([]), but does it make sense to verify classes from JRE?

**Comment by brosander** [comment]
@akhayrutdinov you could mock the input stream you pass into the constructor and just verify that the delegate is invoked with the correct arguments and that the return is the same as from your mock

**Comment by mattyb149** [comment]
Agreed that the test is not heavyweight and perhaps a bit silly in this case, but we're committed to getting the highest code coverage and quality possible. Adding the test Bryan suggests above will help

**Comment by akhayrutdinov** [comment]
@brosander, @mattyb149, ok if you insist on it.
In fact none of step's classes works directly with the stream. Instead, they utilize a Reader above the BufferedInputStream - https://github.com/pentaho/pentaho-kettle/blob/master/engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java#L1413, therefore it turns the test to verify the buffered reader reads by filling its buffer, but not by hoisting separate ints

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander done it. Review it please

**Pull request merged**
