### PR TITLE
[PDI-17271] Give the user the ability to filter GTK Warnings

### PR DESCRIPTION
**Pull request by DFieldFL**

### CODE REVIEW

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 48s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl assemblies/core/static,assemblies/static
```
:exclamation: No tests found!


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 10s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl assemblies/core/static,assemblies/static
```
:exclamation: No tests found!


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 32s
Build command:
```console
mvn clean deploy -B -e -Daudit -pl \
assemblies/core/static,assemblies/static
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by DFieldFL** [comment]
Hold on merging this commit. Having some more discussions on the fix.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 5m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/core/static,assemblies/static
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/core/static,assemblies/static
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
