### PR TITLE
[PDI-19604] - Connection related issues when Connection Pooling is enabled in transformations.

### PR DESCRIPTION
**Pull request by renato-s**
@andreramos89 
@bcostahitachivantara 
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 37m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui,plugins/lucid-db-streaming-loader/core,plugins/pur/core,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **4866**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8754/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 38m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui,plugins/lucid-db-streaming-loader/core,plugins/pur/core,ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeTest.initWithCommitSizeVariable</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.tableoutput.TableOutputTest.testInit_unsupportedConnection</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **4499**, Failures: **2**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8754/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 43m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui,plugins/lucid-db-streaming-loader/core,plugins/pur/core,ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransTest.testPDI12424ParametersFromMetaAreCopiedToTrans</b> (click to expand)</summary><p>

```

Transformation was unable to open [null]

The transformation path ram:///parameters_1c82bdb2-8b53-11ed-9309-d5095920c69a.ktr is invalid, and will not run successfully.


```

</p></details>

  
Tests run: **5243**, Failures: **1**, Skipped: **9** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8754/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 43m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui,plugins/lucid-db-streaming-loader/core,plugins/pur/core,ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransTest.testPDI12424ParametersFromMetaAreCopiedToTrans</b> (click to expand)</summary><p>

```

Transformation was unable to open [null]

The transformation path ram:///parameters_d1dfc6c6-8b88-11ed-84cc-a18612c1ddab.ktr is invalid, and will not run successfully.


```

</p></details>

  
Tests run: **5243**, Failures: **1**, Skipped: **9** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8754/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 36m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/avro-format/core,plugins/core/impl,plugins/lucid-db-streaming-loader/core
```
---
:ok_hand: All tests passed!
 
Tests run: **5253**, Failures: **0**, Skipped: **9** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8754/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 36m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/avro-format/core,plugins/core/impl,plugins/lucid-db-streaming-loader/core
```
---
:ok_hand: All tests passed!
 
Tests run: **5253**, Failures: **0**, Skipped: **9** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8754/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 4m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui,plugins/lucid-db-streaming-loader/core,plugins/pur/core,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1223**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8754/7/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 45m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui,plugins/lucid-db-streaming-loader/core,plugins/pur/core,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **5253**, Failures: **0**, Skipped: **9** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8754/8/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 43m 47s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui,plugins/lucid-db-streaming-loader/core,plugins/pur/core,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **5253**, Failures: **0**, Skipped: **9** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-11/job/PR-8754/9/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by bcostahitachivantara — APPROVED** [review]

**Pull request merged**
