### PR TITLE
[PDI-203] XML Formatting

### PR DESCRIPTION
**Pull request by matthewtckr**

### CODE REVIEW

**Comment by deinspanjer** [comment]
I understand how this is advantageous for a developer looking at these serialized files, but we need to make sure we have a commit that covers as much of the tests that might fail after this change as possible.  I'm not sure what parts of the platform might do a strict string comparison of "known good xml", but those would be things that would blow up after this change happens, so we'd have to validate and update those known good snippets wherever they are stored.

**Comment by mdamour1976** [comment]
While what you are saying does make a good deal of sense, I do not think that the platform parses XML by way of pure string/snipet manipulation (or "known good xml").  We're using parsers.  Even Kettle, despite generating XML with StringBuffer, uses something of an XML parser to read in the XML and that would remain functioning with or without the changes to the XML output.  It's why Matt only has changed the "getXML" side of each of the persisted objects.

Is it your suggestion that we have a test for each of these objects, like SlaveServer, to be certain that before/after changes there are no issues?  I'm not against that, but it could turn into something we have to maintain, rather than something that provides value.

**Comment by deinspanjer** [comment]
In this case, I'm not looking to add more tests, but rather, I'm worried some of our existing tests, or maybe some other part of our system, is relying on some statically stored serializations of XML and using them as "known good" items to compare against when exercising the code to generate new serializations.  This is something that Mondrian does in a lot of its tests, and it causes a lot of issues if you make changes to a dialect.

Maybe there isn't anything as bad as that in the PDI parts of the stack, but I'm not sure one way or the other, and hence my caution and desire for us to do our best to make sure the commit won't cause a bunch of failures in other parts of the build once it is merged.

**Comment by mdamour1976** [comment]
Well if I run wingman on it, it would pickup any new failures within any of the kettle projects.  I haven't been able to do that because of some artifact changes causing massive compile failures (unrelated to this commit).  I'll dig into that a little bit, it would at least provide some assurance.

**Comment by mdamour1976** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local
3. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/di/core/xml/XMLHandler.java
  core/test-src/org/pentaho/di/core/xml/XMLHandlerUnitTest.java
  engine/src/org/pentaho/di/cluster/ClusterSchema.java
  engine/src/org/pentaho/di/cluster/SlaveServer.java
  engine/src/org/pentaho/di/core/logging/BaseLogTable.java
  engine/src/org/pentaho/di/core/logging/ChannelLogTable.java
  engine/src/org/pentaho/di/core/logging/JobEntryLogTable.java
  engine/src/org/pentaho/di/core/logging/JobLogTable.java
  engine/src/org/pentaho/di/core/logging/MetricsLogTable.java
  engine/src/org/pentaho/di/core/logging/PerformanceLogTable.java
  engine/src/org/pentaho/di/core/logging/StepLogTable.java
  engine/src/org/pentaho/di/core/logging/TransLogTable.java
  engine/src/org/pentaho/di/job/JobMeta.java
  engine/src/org/pentaho/di/job/entries/trans/JobEntryTrans.java
  engine/src/org/pentaho/di/job/entry/JobEntryCopy.java
  engine/src/org/pentaho/di/partition/PartitionSchema.java
  engine/src/org/pentaho/di/trans/SlaveStepCopyPartitionDistribution.java
  engine/src/org/pentaho/di/trans/TransHopMeta.java
  engine/src/org/pentaho/di/trans/TransMeta.java
  engine/src/org/pentaho/di/trans/step/StepMeta.java
  engine/src/org/pentaho/di/trans/step/StepPartitioningMeta.java
  engine/src/org/pentaho/di/www/SslConfiguration.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File core/src/org/pentaho/di/core/xml/XMLHandler.java
1. Message: '{' at column 5 should be on the previous line. at Line: 458 Column: 5
2. Message: '{' at column 7 should be on the previous line. at Line: 461 Column: 7

File core/test-src/org/pentaho/di/core/xml/XMLHandlerUnitTest.java
1. Message: ',' is preceded with whitespace. at Line: 129 Column: 32

File engine/src/org/pentaho/di/cluster/SlaveServer.java
1. Message: '(' is not followed by whitespace. at Line: 126 Column: 31
2. Message: '(' is not followed by whitespace. at Line: 126 Column: 41
3. Message: '(' is not followed by whitespace. at Line: 134 Column: 31
4. Message: '(' is not followed by whitespace. at Line: 134 Column: 41

File engine/src/org/pentaho/di/job/entries/trans/JobEntryTrans.java
1. Message: 'switch' is not followed by whitespace. at Line: 1180 Column: 13
2. Message: 'switch' is not followed by whitespace. at Line: 623 Column: 11
3. Message: '{' at column 5 should be on the previous line. at Line: 664 Column: 5

File engine/src/org/pentaho/di/job/entry/JobEntryCopy.java
1. Message: Line has trailing spaces. at Line: 356 Column: None

File engine/src/org/pentaho/di/trans/TransMeta.java
1. Message: '{' at column 7 should be on the previous line. at Line: 1123 Column: 7
2. Message: '{' at column 7 should be on the previous line. at Line: 1190 Column: 7
3. Message: '{' at column 5 should be on the previous line. at Line: 1669 Column: 5
4. Message: '{' at column 7 should be on the previous line. at Line: 1672 Column: 7
5. Message: '{' at column 13 should be on the previous line. at Line: 2961 Column: 13









Unit test coverage change:
============
org.pentaho.di.core.xml.XMLHandler:
 * instructionPercentCoverageChange : +6.49%
 * branchPercentCoverageChange : +1.37%
 * linePercentCoverageChange : +5.38%
 * complexityPercentCoverageChange : +7.19%
 * methodPercentCoverageChange : +13.64%
    
org.pentaho.di.core.logging.ChannelLogTable:
 * instructionPercentCoverageChange : +0.77%
    
org.pentaho.di.core.lifecycle.KettleLifecycleSupport:
 * branchPercentCoverageChange :**-8.33%**
 * complexityPercentCoverageChange :**-9.09%**
    
org.pentaho.di.cluster.ClusterSchema:
 * instructionPercentCoverageChange :**-0.11%**
    
org.pentaho.di.core.logging.TransLogTable:
 * instructionPercentCoverageChange : +0.59%
    
org.pentaho.di.cluster.SlaveServer:
 * instructionPercentCoverageChange : +0.03%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange :**-0.74%**
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +1.97%
    
org.pentaho.di.core.logging.PerformanceLogTable:
 * instructionPercentCoverageChange : +0.68%
    
org.pentaho.di.trans.step.StepPartitioningMeta:
 * instructionPercentCoverageChange :**-0.46%**
    
org.pentaho.di.partition.PartitionSchema:
 * instructionPercentCoverageChange :**-0.52%**
    
org.pentaho.di.job.entries.trans.JobEntryTrans:
 * instructionPercentCoverageChange :**-0.04%**
    
org.pentaho.di.core.logging.JobLogTable:
 * instructionPercentCoverageChange : +0.61%
    
org.pentaho.di.core.logging.MetricsLogTable:
 * instructionPercentCoverageChange : +0.95%
    
org.pentaho.di.core.logging.StepLogTable:
 * instructionPercentCoverageChange : +0.63%
    
org.pentaho.di.job.JobMeta:
 * instructionPercentCoverageChange : +0.19%
    
org.pentaho.di.trans.TransMeta:
 * instructionPercentCoverageChange : +0.07%
    
org.pentaho.di.trans.SlaveStepCopyPartitionDistribution:
 * instructionPercentCoverageChange : +0.98%
    
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange : +0.08%
    
org.pentaho.di.core.logging.BaseLogTable:
 * instructionPercentCoverageChange : +0.36%
    
org.pentaho.di.trans.TransHopMeta:
 * instructionPercentCoverageChange :**-1.00%**
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange :**-0.53%**
    
org.pentaho.di.core.logging.JobEntryLogTable:
 * instructionPercentCoverageChange : +0.59%
    
Integration test coverage change:
============
org.pentaho.di.trans.step.StepPartitioningMeta:
 * instructionPercentCoverageChange :**-0.11%**
    
org.pentaho.di.core.logging.ChannelLogTable:
 * instructionPercentCoverageChange :**-1.21%**
    
org.pentaho.di.core.logging.StepLogTable:
 * instructionPercentCoverageChange :**-1.11%**
    
org.pentaho.di.core.logging.BaseLogTable:
 * instructionPercentCoverageChange :**-0.07%**
    
org.pentaho.di.partition.PartitionSchema:
 * instructionPercentCoverageChange :**-0.09%**
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange :**-0.24%**
    
org.pentaho.di.trans.TransMeta:
 * instructionPercentCoverageChange :**-0.00%**
    
org.pentaho.di.core.logging.TransLogTable:
 * instructionPercentCoverageChange :**-0.60%**
    
org.pentaho.di.trans.SlaveStepCopyPartitionDistribution:
 * instructionPercentCoverageChange :**-0.03%**
    
org.pentaho.di.core.logging.MetricsLogTable:
 * instructionPercentCoverageChange :**-1.36%**
    
org.pentaho.di.core.logging.PerformanceLogTable:
 * instructionPercentCoverageChange :**-1.09%**

**Comment by matthewtckr** [comment]
Fixed checkstyle issues.  There is a lot of noise in the checkstyle reports regarding `engine/test-src/...` classes

**Comment by matthewtckr** [comment]
Updated copyright years

**Pull request merged**
