### PR TITLE
[PDI-19803] Update JSch for ssh rfc compliance

### PR DESCRIPTION
**Pull request by tgf**

### CODE REVIEW

**Comment by tgf** [comment]
@smmribeiro @mladenmilev @bcostahitachivantara please review

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 24m 2s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **5308**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8933/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **5320**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8933/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 44m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **5339**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8933/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good!

**Pull request merged**
