### PR TITLE
[PDI-18453] Enhance SQLite database input to correctly return BLOB field

### PR DESCRIPTION
**Pull request by cgrimm01**
Removes restrictions that forces an SQLite BLOB field to only be returned to PDI as a String.   NOTE: This change is dependent on PDI-18456.

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 14m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4709**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7040/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 55s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4714**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7040/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4715**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7040/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 20m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4718**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7040/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4727**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7040/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by jbleuel** [comment]
assertArrayEquals( new String[] { "sqlite-jdbc-3.7.2.jar" }, nativeMeta.getUsedLibraries() );
--> Shouldn't we change the test to the changed version by PR 7039?

**Comment by rmansoor** [comment]
@mkambol can you please reivew the PR

**Comment by cgrimm01** [comment]
This is taken care of in PDI-18456.  
    On Monday, November 18, 2019, 10:43:33 AM EST, Jens Bleuel <notifications@github.com> wrote:  
 
 
assertArrayEquals( new String[] { "sqlite-jdbc-3.7.2.jar" }, nativeMeta.getUsedLibraries() );
--> Shouldn't we change the test to the changed version by PR 7039?

**Comment by cgrimm01** [comment]
Please keep in mind for this to work completely, PDI-18456 must also be applied.  This one is where the JDBC driver is updated.
    On Monday, November 18, 2019, 11:13:29 AM EST, Ramaiz Mansoor <notifications@github.com> wrote:  
 
 
@mkambol can you please reivew the PR

**Comment by mkambol** [comment]
Sorry @cgrimm01 -  just merged 7039, which introduced the conflict.  Can you resolve?

**Comment by cgrimm01** [comment]
Can you give me a hint on what I need to do with this?  This is the first time I have tried to submit.a change for Pentaho.
Thanks!

    On Monday, November 18, 2019, 11:42:34 AM EST, Matt Campbell <notifications@github.com> wrote:  
 
 
Sorry @cgrimm01 - just merged 7039, which introduced the conflict. Can you resolve?

**Comment by cgrimm01** [comment]
I don't have write access, so please let me know how I can resolve.

**Comment by cgrimm01** [comment]
I believe this is now correct.

**Comment by cgrimm01** [comment]
I think I managed to resolve the conflict. Please verify.
    On Monday, November 18, 2019, 11:50:54 AM EST, Clifford Grimm <clifford.grimm@yahoo.com> wrote:  
 
  Can you give me a hint on what I need to do with this?  This is the first time I have tried to submit.a change for Pentaho.
Thanks!

    On Monday, November 18, 2019, 11:42:34 AM EST, Matt Campbell <notifications@github.com> wrote:  
 
 
Sorry @cgrimm01 - just merged 7039, which introduced the conflict. Can you resolve?

**Comment by cgrimm01** [comment]
I believe this has been correctly resolved.

**Comment by mkambol** [comment]
@cgrimm01 -  that works :) .   I typically squash commits locally and force push when I make changes to a PR just to make sure it goes in as a single commit, but I can squash on merge.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 17m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,plugins/connections/ui,plugins/file-open-save-new/core,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **4727**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7040/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
