### PR TITLE
[SP-2644] - Backport of PDI-14910 - UDJC Cannot Read fields from Tabl…

### PR DESCRIPTION
**Pull request by andrei-viaryshka**
…e Input Info Step (6.1 Suite)

Backport of https://github.com/pentaho/pentaho-kettle/commit/8109f7d9f8ddb0fca3a0db5e541749cf1c0dbe7b.

### CODE REVIEW

**Comment by andrei-viaryshka** [comment]
@mbatchelor Could you please take a look?

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/TransMeta.java
  engine/test-src/org/pentaho/di/trans/TransMetaTest.java

Unit test coverage change:
============
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change :  + 7.14%
 * Complexity Change :  + 7.69%

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change :  + 1.64%
 * Complexity Change :  + .69%
 * Instruction Change :  + 2.43%
 * Line Change :  + 2.95%

org.pentaho.di.trans.step.BaseStepMeta:
 * Branch Change :  + 2.50%
 * Complexity Change :  + 2.70%
 * Instruction Change :  + 3.18%
 * Line Change :  + 2.72%
 * Method Change :  + 3.30%

org.pentaho.di.trans.step.StepIOMeta:
 * Branch Change :  + 7.14%
 * Complexity Change :  + 4.88%
 * Instruction Change :  + 7.23%
 * Line Change :  + 5.62%
 * Method Change :  + 3.70%

org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * Instruction Change :  + .18%

org.pentaho.di.trans.steps.userdefinedjavaclass.TransformClassBase:
 * Branch Change :  + 5.00%
 * Complexity Change :  + 2.08%
 * Instruction Change :  + 4.38%
 * Line Change :  + 2.78%
 * Method Change :  + 1.77%

org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClassDef:
 * Branch Change :  + 50.00%
 * Complexity Change :  + 46.67%
 * Instruction Change :  + 71.95%
 * Line Change :  + 60.00%
 * Method Change :  + 53.85%

org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClassDef.ClassType:
 * Complexity Change :  + 50.00%
 * Instruction Change :  + 76.32%
 * Line Change :  + 100.00%
 * Method Change :  + 50.00%

org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClassMeta:
 * Branch Change :  + 13.39%
 * Complexity Change :  + 14.61%
 * Instruction Change :  + 10.41%
 * Line Change :  + 15.56%
 * Method Change :  + 30.30%

org.pentaho.di.trans.TransMeta:
 * Branch Change :  + 2.09%
 * Complexity Change :  + 1.30%
 * Instruction Change :  + 1.53%
 * Line Change :  + 1.73%
 * Method Change :  + 1.86%

Integration test coverage change:
============
org.pentaho.di.trans.TransMeta:
 * Instruction Change :  + .01%
 * Line Change :  + .03%

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/engine/src/org/pentaho/di/trans/TransMeta.java

1. Message: '{' at column 7 should be on the previous line. at Line: 1,123 Column: 7
2. Message: '{' at column 7 should be on the previous line. at Line: 1,190 Column: 7
3. Message: '{' at column 5 should be on the previous line. at Line: 1,666 Column: 5
4. Message: '{' at column 7 should be on the previous line. at Line: 1,669 Column: 7
5. Message: '{' at column 13 should be on the previous line. at Line: 2,958 Column: 13

**Comment by pamval** [comment]
@andrei-viaryshka please review code style on this pull request.

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/TransMeta.java
  engine/test-src/org/pentaho/di/trans/TransMetaTest.java

Unit test coverage change:
============
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change : **-7.14%**
 * Complexity Change : **-7.69%**

org.pentaho.di.core.lifecycle.KettleLifecycleSupport:
 * Branch Change :  + 8.33%
 * Complexity Change :  + 9.09%

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change : **-1.64%**
 * Line Change : **-1.97%**

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change : **-1.64%**
 * Complexity Change : **-.69%**
 * Instruction Change : **-2.43%**
 * Line Change : **-2.95%**

org.pentaho.di.trans.step.BaseStepMeta:
 * Branch Change :  + 2.50%
 * Complexity Change :  + 2.70%
 * Instruction Change :  + 3.18%
 * Line Change :  + 2.72%
 * Method Change :  + 3.30%

org.pentaho.di.trans.step.StepIOMeta:
 * Branch Change :  + 7.14%
 * Complexity Change :  + 4.88%
 * Instruction Change :  + 7.23%
 * Line Change :  + 5.62%
 * Method Change :  + 3.70%

org.pentaho.di.trans.step.StepMeta:
 * Instruction Change :  + .19%
 * Line Change :  + .27%

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Instruction Change : **-.08%**

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Instruction Change :  + .07%

org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * Instruction Change :  + .18%

org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * Branch Change : **-.53%**

org.pentaho.di.trans.steps.userdefinedjavaclass.TransformClassBase:
 * Branch Change :  + 5.00%
 * Complexity Change :  + 2.08%
 * Instruction Change :  + 4.38%
 * Line Change :  + 2.78%
 * Method Change :  + 1.77%

org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClassDef:
 * Branch Change :  + 50.00%
 * Complexity Change :  + 46.67%
 * Instruction Change :  + 71.95%
 * Line Change :  + 60.00%
 * Method Change :  + 53.85%

org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClassDef.ClassType:
 * Complexity Change :  + 50.00%
 * Instruction Change :  + 76.32%
 * Line Change :  + 100.00%
 * Method Change :  + 50.00%

org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClassMeta:
 * Branch Change :  + 13.39%
 * Complexity Change :  + 14.61%
 * Instruction Change :  + 10.41%
 * Line Change :  + 15.56%
 * Method Change :  + 30.30%

org.pentaho.di.trans.TransMeta:
 * Branch Change :  + 2.09%
 * Complexity Change :  + 1.30%
 * Instruction Change :  + 1.53%
 * Line Change :  + 1.73%
 * Method Change :  + 1.86%

Integration test coverage change:
============
org.pentaho.di.trans.TransMeta:
 * Instruction Change :  + .01%
 * Line Change :  + .03%

**Comment by andrei-viaryshka** [comment]
@pamval updated

**Pull request merged**
