### PR TITLE
[PDI-19721] Text File Output - use the correct encoded newline charac…

### PR DESCRIPTION
**Pull request by bconlon-hv**
…ters for strings injected into the NEW_LINE field

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 20m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
Error fetching remote repo 'origin'
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1h 39m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **4042**, Failures: **0**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8863/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ddiroma** [comment]
Please do not merge this until we get approval from Tammy to adding this to 9.5 since this is a product bug and we are past feature code freeze deadline.

**Review by ddiroma — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 42m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **4042**, Failures: **0**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8863/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ddiroma — APPROVED** [review]

**Pull request merged**
