### PR TITLE
SP-1745 - Backport of PDI-13544 - Spoon allows user to create duplicate ...

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
...connection and slave server x (5.0 Suite)
Backport of https://github.com/pentaho/pentaho-kettle/pull/1099

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@mattyb149 
Please review.

**Comment by mattyb149** [comment]
Can we add a unit test for this method? Not sure what would need to be mocked for the SlaveServer static method call inside the new method...

**Comment by Aliaksandr-Kastenka** [comment]
@mattyb149 
Pull-request updated.

**Comment by mattyb149** [comment]
Thank you. Please forward-port the test to master, I will merge this PR in the meantime

**Comment by Aliaksandr-Kastenka** [comment]
@mattyb149 
It is already there, https://github.com/pentaho/pentaho-kettle/pull/1099

**Pull request merged**
