### PR TITLE
[SP-2606] Backport of PDI-14413 - Step Synchronize after merge - issue with mode "use batch update" (6.1 Suite)

### PR DESCRIPTION
**Pull request by SergeyTravin**
It is backport for https://github.com/pentaho/pentaho-kettle/pull/2225 and https://github.com/pentaho/pentaho-kettle/pull/2295

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@pamval, @pedrofvteixeira , could you run WM on this PR?

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/95/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMerge.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchMockDriver.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeIT.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeTest.java



Unit test coverage change:
============
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change : **-7.14%**
 * Complexity Change : **-7.69%**

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.97%

org.pentaho.di.trans.step.BaseStep:
 * Branch Change : **-1.77%**
 * Complexity Change : **-1.28%**
 * Instruction Change : **-1.23%**
 * Line Change : **-1.39%**

org.pentaho.di.trans.step.StepErrorMeta:
 * Complexity Change : **-17.95%**
 * Instruction Change : **-8.48%**
 * Line Change : **-10.66%**
 * Method Change : **-24.14%**

org.pentaho.di.trans.step.StepInitThread:
 * Branch Change : **-25.00%**
 * Complexity Change : **-8.33%**
 * Instruction Change : **-13.07%**
 * Line Change : **-6.25%**

org.pentaho.di.trans.step.StepMeta:
 * Branch Change : **-2.74%**
 * Complexity Change : **-1.75%**
 * Instruction Change : **-1.29%**
 * Line Change : **-.81%**
 * Method Change : **-2.04%**

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Instruction Change : **-.08%**

org.pentaho.di.trans.steps.injector.Injector:
 * Complexity Change : **-40.00%**
 * Instruction Change : **-23.40%**
 * Line Change : **-27.27%**
 * Method Change : **-66.67%**

org.pentaho.di.trans.steps.injector.InjectorData:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.injector.InjectorMeta:
 * Complexity Change : **-16.13%**
 * Instruction Change : **-8.61%**
 * Line Change : **-12.94%**
 * Method Change : **-20.83%**

org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * Branch Change : **-3.33%**
 * Complexity Change : **-1.85%**
 * Instruction Change : **-.28%**

org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMerge:
 * Branch Change : **-4.29%**
 * Complexity Change : **-2.16%**
 * Instruction Change : **-5.48%**
 * Line Change : **-7.03%**
 * Method Change : **-40.00%**

org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeData:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeMeta:
 * Complexity Change : **-21.48%**
 * Instruction Change : **-4.32%**
 * Line Change : **-10.84%**
 * Method Change : **-51.79%**

org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * Instruction Change : **-.18%**

org.pentaho.di.trans.Trans:
 * Branch Change : **-1.21%**
 * Complexity Change : **-1.27%**
 * Instruction Change : **-1.21%**
 * Line Change : **-1.15%**

org.pentaho.di.trans.TransMeta:
 * Branch Change : **-1.30%**
 * Complexity Change : **-.83%**
 * Instruction Change : **-.66%**
 * Line Change : **-.57%**
 * Method Change : **-.37%**



Integration test coverage change:
============
org.pentaho.di.core.KettleEnvironment:
 * Complexity Change :  + 5.26%
 * Instruction Change :  + 1.78%
 * Line Change :  + 3.23%
 * Method Change :  + 10.00%

org.pentaho.di.trans.RowProducer:
 * Branch Change :  + 75.00%
 * Complexity Change :  + 45.45%
 * Instruction Change :  + 56.92%
 * Line Change :  + 61.90%
 * Method Change :  + 44.44%

org.pentaho.di.trans.step.BaseStep:
 * Branch Change :  + 5.02%
 * Complexity Change :  + 4.92%
 * Instruction Change :  + 3.76%
 * Line Change :  + 4.49%
 * Method Change :  + 5.85%

org.pentaho.di.trans.step.BaseStepData:
 * Complexity Change :  + 5.56%
 * Instruction Change :  + 4.17%
 * Line Change :  + 7.14%
 * Method Change :  + 9.09%

org.pentaho.di.trans.step.BaseStepMeta:
 * Complexity Change :  + .90%
 * Instruction Change :  + .16%
 * Line Change :  + .54%
 * Method Change :  + 1.10%

org.pentaho.di.trans.step.RunThread:
 * Branch Change :  + 4.00%
 * Complexity Change :  + 7.14%
 * Instruction Change :  + .15%
 * Line Change :  + 2.04%

org.pentaho.di.trans.step.StepErrorMeta:
 * Complexity Change :  + 17.95%
 * Instruction Change :  + 8.48%
 * Line Change :  + 13.11%
 * Method Change :  + 24.14%

org.pentaho.di.trans.step.StepMeta:
 * Branch Change :  + 2.05%
 * Complexity Change :  + 1.17%
 * Instruction Change :  + .90%
 * Line Change :  + .54%
 * Method Change :  + 1.02%

org.pentaho.di.trans.steps.dummytrans.DummyTrans:
 * Branch Change :  + 50.00%
 * Complexity Change :  + 66.67%
 * Instruction Change :  + 62.75%
 * Line Change :  + 83.33%
 * Method Change :  + 100.00%

org.pentaho.di.trans.steps.dummytrans.DummyTransData:
 * Complexity Change :  + 100.00%
 * Instruction Change :  + 100.00%
 * Line Change :  + 100.00%
 * Method Change :  + 100.00%

org.pentaho.di.trans.steps.dummytrans.DummyTransMeta:
 * Complexity Change :  + 26.67%
 * Instruction Change :  + 16.38%
 * Line Change :  + 20.00%
 * Method Change :  + 33.33%

org.pentaho.di.trans.steps.injector.Injector:
 * Branch Change :  + 75.00%
 * Complexity Change :  + 80.00%
 * Instruction Change :  + 68.09%
 * Line Change :  + 90.91%
 * Method Change :  + 100.00%

org.pentaho.di.trans.steps.injector.InjectorData:
 * Complexity Change :  + 100.00%
 * Instruction Change :  + 100.00%
 * Line Change :  + 100.00%
 * Method Change :  + 100.00%

org.pentaho.di.trans.steps.injector.InjectorMeta:
 * Complexity Change :  + 16.13%
 * Instruction Change :  + 8.61%
 * Line Change :  + 12.94%
 * Method Change :  + 20.83%

org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMerge:
 * Branch Change :  + 43.22%
 * Complexity Change :  + 22.87%
 * Instruction Change :  + 50.32%
 * Line Change :  + 54.78%
 * Method Change :  + 90.91%

org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeData:
 * Complexity Change :  + 100.00%
 * Instruction Change :  + 100.00%
 * Line Change :  + 100.00%
 * Method Change :  + 100.00%

org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeMeta:
 * Complexity Change :  + 30.37%
 * Instruction Change :  + 5.68%
 * Line Change :  + 13.27%
 * Method Change :  + 73.21%

org.pentaho.di.trans.Trans:
 * Branch Change :  + 1.31%
 * Complexity Change :  + 1.13%
 * Instruction Change :  + 1.46%
 * Line Change :  + 1.72%
 * Method Change :  + 1.91%

org.pentaho.di.trans.TransHopMeta:
 * Complexity Change :  + 2.78%
 * Instruction Change :  + 5.05%
 * Line Change :  + 6.76%
 * Method Change :  + 4.17%

org.pentaho.di.trans.TransMeta:
 * Branch Change :  + .09%
 * Complexity Change :  + .24%
 * Instruction Change :  + .04%
 * Line Change :  + .10%
 * Method Change :  + .37%



Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/engine/src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMerge.java

1. Message: 'for' have incorrect indentation level 8, expected level should be 10. at Line: 919
2. Message: 'for' child have incorrect indentation level 10, expected level should be 12. at Line: 922
3. Message: 'member def type' have incorrect indentation level 10, expected level should be 12. at Line: 922
4. Message: 'if' have incorrect indentation level 10, expected level should be 12. at Line: 923
5. Message: 'if' child have incorrect indentation level 12, expected level should be 14. at Line: 924
6. Message: 'if rcurly' have incorrect indentation level 10, expected level should be 12. at Line: 925
7. Message: 'for' child have incorrect indentation level 10, expected level should be 12. at Line: 927
8. Message: 'member def type' have incorrect indentation level 10, expected level should be 12. at Line: 927
9. Message: 'for' child have incorrect indentation level 10, expected level should be 12. at Line: 929
10. Message: 'method call' child have incorrect indentation level 10, expected level should be 12. at Line: 929
11. Message: 'for rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 930
12. Message: 'for' have incorrect indentation level 8, expected level should be 10. at Line: 931
13. Message: 'for' child have incorrect indentation level 10, expected level should be 12. at Line: 932
14. Message: 'member def type' have incorrect indentation level 10, expected level should be 12. at Line: 932
15. Message: 'for' child have incorrect indentation level 10, expected level should be 12. at Line: 933
16. Message: 'method call' child have incorrect indentation level 10, expected level should be 12. at Line: 933
17. Message: 'if' have incorrect indentation level 10, expected level should be 12. at Line: 934
18. Message: 'if' child have incorrect indentation level 12, expected level should be 14. at Line: 935
19. Message: 'method call' child have incorrect indentation level 12, expected level should be 14. at Line: 935
20. Message: 'if rcurly' have incorrect indentation level 10, expected level should be 12. at Line: 936
21. Message: 'for rcurly' have incorrect indentation level 8, expected level should be 10. at Line: 937
22. Message: 'if' child have incorrect indentation level 8, expected level should be 10. at Line: 939
23. Message: 'method call' child have incorrect indentation level 8, expected level should be 10. at Line: 939

**Comment by SergeyTravin** [comment]
@pamval, @pedrofvteixeira , could you rerun WM on this PR?

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/96/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMerge.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchMockDriver.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeIT.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeTest.java



Unit test coverage change:
============
org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change :  + 1.64%
 * Complexity Change :  + .69%
 * Instruction Change :  + 2.43%
 * Line Change :  + 2.95%

org.pentaho.di.trans.step.BaseStep:
 * Branch Change : **-1.77%**
 * Complexity Change : **-1.28%**
 * Instruction Change : **-1.23%**
 * Line Change : **-1.39%**

org.pentaho.di.trans.step.StepErrorMeta:
 * Complexity Change : **-17.95%**
 * Instruction Change : **-8.48%**
 * Line Change : **-10.66%**
 * Method Change : **-24.14%**

org.pentaho.di.trans.step.StepInitThread:
 * Branch Change : **-25.00%**
 * Complexity Change : **-8.33%**
 * Instruction Change : **-13.07%**
 * Line Change : **-6.25%**

org.pentaho.di.trans.step.StepMeta:
 * Branch Change : **-2.74%**
 * Complexity Change : **-1.75%**
 * Instruction Change : **-1.29%**
 * Line Change : **-.81%**
 * Method Change : **-2.04%**

org.pentaho.di.trans.steps.injector.Injector:
 * Complexity Change : **-40.00%**
 * Instruction Change : **-23.40%**
 * Line Change : **-27.27%**
 * Method Change : **-66.67%**

org.pentaho.di.trans.steps.injector.InjectorData:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.injector.InjectorMeta:
 * Complexity Change : **-16.13%**
 * Instruction Change : **-8.61%**
 * Line Change : **-12.94%**
 * Method Change : **-20.83%**

org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMerge:
 * Branch Change : **-4.29%**
 * Complexity Change : **-2.16%**
 * Instruction Change : **-5.48%**
 * Line Change : **-7.03%**
 * Method Change : **-40.00%**

org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeData:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeMeta:
 * Complexity Change : **-21.48%**
 * Instruction Change : **-4.32%**
 * Line Change : **-10.84%**
 * Method Change : **-51.79%**

org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * Branch Change : **-.53%**

org.pentaho.di.trans.Trans:
 * Branch Change : **-1.21%**
 * Complexity Change : **-1.27%**
 * Instruction Change : **-1.21%**
 * Line Change : **-1.15%**

org.pentaho.di.trans.TransMeta:
 * Branch Change : **-1.30%**
 * Complexity Change : **-.83%**
 * Instruction Change : **-.66%**
 * Line Change : **-.57%**
 * Method Change : **-.37%**



Integration test coverage change:
============
org.pentaho.di.core.KettleEnvironment:
 * Complexity Change :  + 5.26%
 * Instruction Change :  + 1.78%
 * Line Change :  + 3.23%
 * Method Change :  + 10.00%

org.pentaho.di.trans.RowProducer:
 * Branch Change :  + 75.00%
 * Complexity Change :  + 45.45%
 * Instruction Change :  + 56.92%
 * Line Change :  + 61.90%
 * Method Change :  + 44.44%

org.pentaho.di.trans.step.BaseStep:
 * Branch Change :  + 5.02%
 * Complexity Change :  + 4.92%
 * Instruction Change :  + 3.76%
 * Line Change :  + 4.49%
 * Method Change :  + 5.85%

org.pentaho.di.trans.step.BaseStepData:
 * Complexity Change :  + 5.56%
 * Instruction Change :  + 4.17%
 * Line Change :  + 7.14%
 * Method Change :  + 9.09%

org.pentaho.di.trans.step.BaseStepMeta:
 * Complexity Change :  + .90%
 * Instruction Change :  + .16%
 * Line Change :  + .54%
 * Method Change :  + 1.10%

org.pentaho.di.trans.step.RunThread:
 * Branch Change :  + 4.00%
 * Complexity Change :  + 7.14%
 * Instruction Change :  + .15%
 * Line Change :  + 2.04%

org.pentaho.di.trans.step.StepErrorMeta:
 * Complexity Change :  + 17.95%
 * Instruction Change :  + 8.48%
 * Line Change :  + 13.11%
 * Method Change :  + 24.14%

org.pentaho.di.trans.step.StepMeta:
 * Branch Change :  + 2.05%
 * Complexity Change :  + 1.17%
 * Instruction Change :  + .90%
 * Line Change :  + .54%
 * Method Change :  + 1.02%

org.pentaho.di.trans.steps.dummytrans.DummyTrans:
 * Branch Change :  + 50.00%
 * Complexity Change :  + 66.67%
 * Instruction Change :  + 62.75%
 * Line Change :  + 83.33%
 * Method Change :  + 100.00%

org.pentaho.di.trans.steps.dummytrans.DummyTransData:
 * Complexity Change :  + 100.00%
 * Instruction Change :  + 100.00%
 * Line Change :  + 100.00%
 * Method Change :  + 100.00%

org.pentaho.di.trans.steps.dummytrans.DummyTransMeta:
 * Complexity Change :  + 26.67%
 * Instruction Change :  + 16.38%
 * Line Change :  + 20.00%
 * Method Change :  + 33.33%

org.pentaho.di.trans.steps.injector.Injector:
 * Branch Change :  + 75.00%
 * Complexity Change :  + 80.00%
 * Instruction Change :  + 68.09%
 * Line Change :  + 90.91%
 * Method Change :  + 100.00%

org.pentaho.di.trans.steps.injector.InjectorData:
 * Complexity Change :  + 100.00%
 * Instruction Change :  + 100.00%
 * Line Change :  + 100.00%
 * Method Change :  + 100.00%

org.pentaho.di.trans.steps.injector.InjectorMeta:
 * Complexity Change :  + 16.13%
 * Instruction Change :  + 8.61%
 * Line Change :  + 12.94%
 * Method Change :  + 20.83%

org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMerge:
 * Branch Change :  + 43.22%
 * Complexity Change :  + 22.87%
 * Instruction Change :  + 50.32%
 * Line Change :  + 54.78%
 * Method Change :  + 90.91%

org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeData:
 * Complexity Change :  + 100.00%
 * Instruction Change :  + 100.00%
 * Line Change :  + 100.00%
 * Method Change :  + 100.00%

org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeMeta:
 * Complexity Change :  + 30.37%
 * Instruction Change :  + 5.68%
 * Line Change :  + 13.27%
 * Method Change :  + 73.21%

org.pentaho.di.trans.Trans:
 * Branch Change :  + 1.31%
 * Complexity Change :  + 1.13%
 * Instruction Change :  + 1.46%
 * Line Change :  + 1.72%
 * Method Change :  + 1.91%

org.pentaho.di.trans.TransHopMeta:
 * Complexity Change :  + 2.78%
 * Instruction Change :  + 5.05%
 * Line Change :  + 6.76%
 * Method Change :  + 4.17%

org.pentaho.di.trans.TransMeta:
 * Branch Change :  + .09%
 * Complexity Change :  + .24%
 * Instruction Change :  + .04%
 * Line Change :  + .10%
 * Method Change :  + .37%

**Comment by SergeyTravin** [comment]
@brosander The wingman does not found any problems. It is backport of #2225 and #2295 Could you please review?

**Pull request merged**
