### PR TITLE
[SP-2524][PDI-14413] Step Synchronize after merge - issue with mode "…

### PR DESCRIPTION
**Pull request by SergeyTravin**
…use batch update"

- batch will be executed after last row readed, independet from batch size.

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@akhayrutdinov, @pamval  could you review its backport for https://github.com/pentaho/pentaho-kettle/pull/2225 
thanks!

**Comment by pamval** [comment]
@akhayrutdinov please review

**Comment by akhayrutdinov** [comment]
@SergeyTravin,

1. Please, reword the message: `Conflicts: engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeTest.java` should not be there
2. `IT` suffix is used only since 6.0. Please keep old convention and rename the file to `...Test`
3. I'm getting a compile error:
```
compile-tests:
    [javac] Compiling 329 source files to ...
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] ...SynchronizeAfterMergeIT.java:97: error: cannot find symbol
    [javac]     KettleEnvironment.shutdown();
    [javac]                      ^
    [javac]   symbol:   method shutdown()
    [javac]   location: class KettleEnvironment
```
Please, re-check it.

**Comment by akhayrutdinov** [comment]
Compiles, test passes, similar to #2225. Merged

**Pull request merged**
