### PR TITLE
[PDI-16678]-database connection > option section - can't add more than 4 parameters

### PR DESCRIPTION
**Pull request by denisprotopopov**
-changed from 5 empty patameters to 15 by default

### CODE REVIEW

**Comment by denisprotopopov** [comment]
@bmorrise @pamval @mbatchelor please review the changes

**Comment by denisprotopopov** [comment]
@bmorrise @pamval @mbatchelor please review the changes

**Comment by denisprotopopov** [comment]
@bmorrise @pamval @mbatchelor please review the changes

**Comment by mchen-len-son** [comment]
@mbatchelor, @pamval can you please take a look?
the changes have been approved by Jens.

**Comment by mchen-len-son** [comment]
@mbatchelor, @pamval can you please take a look?
the changes have been approved by Jens.

**Comment by mchen-len-son** [comment]
@mbatchelor, @pamval can you please take a look?
the changes have been approved by Jens.

**Pull request merged**
