### PR TITLE
[PDI-14618] - Creating a connection from an open KTR or KJB when connected to repository allows to create connections with the same names (identical) or with the same names but with differ case

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- add trimming to the changes from 59d8e73
- apply the same for JobEntryDialog

@brosander, review it please. I don't like that awful copy-paste, and addressed it in http://jira.pentaho.com/browse/PDI-14228

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@brosander, review it please

**Comment by akhayrutdinov** [comment]
@rpbouman, @deinspanjer, @hudak, can you please review it?
/cc @pamval

**Comment by rpbouman** [comment]
Hi @akhayrutdinov! Thanks for picking this up. I'm no longer at Pentaho so a review from me won't do much good. Best regards, Roland.

**Comment by akhayrutdinov** [comment]
@rpbouman, oh, I didn't know it. Sorry for disturbing you :)

**Comment by rpbouman** [comment]
No worries :)

**Comment by akhayrutdinov** [comment]
@brosander, @deinspanjer, @hudak, review it please

**Comment by akhayrutdinov** [comment]
@brosander, @deinspanjer, @hudak, review it please

**Comment by akhayrutdinov** [comment]
@brosander, @deinspanjer, @hudak, review it please

**Comment by akhayrutdinov** [comment]
@brosander, @deinspanjer, @hudak, review it please

**Comment by deinspanjer** [comment]
In general the refactoring looks fine, but I didn't see any fix or test for the described issue of creating an entry with the same letters but differing capitalization.  I was scanning for some code that called toLower or similar.  Is that covered here?

I'm on vacation this week, and not reviewing from my work computer, so I can't easily run code coverage or wingman tests.  I believe Bryan and Nick are out as well.  Maybe @mkambol could do those tests?

**Comment by akhayrutdinov** [comment]
@deinspanjer, thanks for the response!
Isn't it the case you are talking about: http://jira.pentaho.com/browse/PDI-13353 ? (https://github.com/pentaho/pentaho-kettle/pull/1887)

**Comment by deinspanjer** [comment]
That one is similar, and maybe it already fixed the underlying issue, but this issue, PDI-14618 discusses creating or editing a connection to have an identical name or the same letters but different case (capitalization).  If the capitalization issue has already been fixed and there is a test for it, then nothing needs to change in this PR, but I just expected to see a toLower() or similar in the code or a test that covered that issue.  Again, it could just be that I overlooked it because I'm reviewing from my tablet.

**Comment by akhayrutdinov** [comment]
@deinspanjer, here is what you are looking for: https://github.com/akhayrutdinov/pentaho-kettle/commit/48cb06a422fc2667df434887ff0af11dd7e5c39e#diff-c7a9ecf9e27932908b835e184798a470R363 - `AbstractMeta.findDatabase()` internally uses `equalsIgnoreCase()`

**Comment by brosander** [comment]
@akhayrutdinov can we add a test case covering what should happen when a case insensitive match is made? (e.g. https://github.com/akhayrutdinov/pentaho-kettle/commit/48cb06a422fc2667df434887ff0af11dd7e5c39e#diff-b2f47d4b3399d2dce2b462909a07ff2dR90 with INITIAL_NAME.toUpperCase())

**Comment by akhayrutdinov** [comment]
@brosander, I've updated the PR -- review it please.

1. Added `@VisibleForTesting`
2. Added tests demonstrating the behaviour on different input: identical, with spaces, in upper case, on cancelling

Once again -- I really dislike copy-pasting, but unifying is too significant change. Hope, http://jira.pentaho.com/browse/PDI-14228 will eventually be done someday.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f ui/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  ui/src/org/pentaho/di/ui/core/database/dialog/DatabaseDialog.java
  ui/src/org/pentaho/di/ui/job/entry/JobEntryDialog.java
  ui/src/org/pentaho/di/ui/trans/step/BaseStepDialog.java
  ui/test-src/org/pentaho/di/ui/job/entry/JobEntryDialog_ConnectionLine_Test.java
  ui/test-src/org/pentaho/di/ui/trans/step/BaseStepDialog_ConnectionLine_Test.java










Unit test coverage change:
============
org.pentaho.di.ui.job.entry.JobEntryDialog.EditConnectionListener:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :75.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.ui.trans.step.BaseStepDialog:
 * instructionPercentCoverageChange : +3.30%
 * branchPercentCoverageChange : +6.00%
 * linePercentCoverageChange : +5.14%
 * complexityPercentCoverageChange : +4.30%
 * methodPercentCoverageChange : +3.07%
    
org.pentaho.di.ui.job.entry.JobEntryDialog:
 * branchPercentCoverage :37.50%
 * linePercentCoverage :26.88%
 * methodPercentCoverage :30.77%
 * complexityPercentCoverage :32.00%
 * instructionPercentCoverage :17.99%
    
org.pentaho.di.ui.job.entry.JobEntryDialog.AddConnectionListener:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%

**Pull request merged**
