### PR TITLE
[TEST] - run pur tests with Lazy and non-Lazy flag

### PR DESCRIPTION
**Pull request by aliakseihaidukou**
@pentaho-nbaker @rmansoor please take a look at these changes - it will run all PUR tests that work with Repository 2 times with *LAZY_REPOSITORY* flag set to *true* and *false*.

### CODE REVIEW

**Comment by rmansoor** [comment]
@pedrovtexeira can you please review and run wingman on this

**Comment by pedrofvteixeira** [comment]
[wingman](http://10.100.11.222:8080/job/wingman-ant/374)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/RepositoryPerformanceApp.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/RepositoryTestBase.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/RepositoryTestLazySupport.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryTestBase.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryUnitTest.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_Test.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_GetObjectInformation_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_MoveAndRename_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_RepositoryDirectory_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_Revisions_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_Links_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/ui/repository/pur/repositoryexplorer/model/UIEERepositoryDirectoryIT.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java
1. Message: Using a static member import should be avoided - java.util.Arrays.asList. at Line: 19 Column: None
2. Message: Using the '.*' form of import should be avoided - org.junit.Assert.*. at Line: 20 Column: None
3. Message: Using a static member import should be avoided - org.pentaho.di.repository.pur.PurRepositoryTestingUtils.*. at Line: 24 Column: None
4. Message: Using the '.*' form of import should be avoided - org.pentaho.di.repository.pur.PurRepositoryTestingUtils.*. at Line: 24 Column: None

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryTestBase.java
1. Message: Using a static member import should be avoided - org.pentaho.di.repository.pur.PurRepositoryTestingUtils.*. at Line: 67 Column: None
2. Message: Using the '.*' form of import should be avoided - org.pentaho.di.repository.pur.PurRepositoryTestingUtils.*. at Line: 67 Column: None
3. Message: Using a static member import should be avoided - org.pentaho.platform.engine.core.system.PentahoSessionHolder.MODE_GLOBAL. at Line: 68 Column: None
4. Message: Using a static member import should be avoided - org.pentaho.platform.engine.core.system.PentahoSessionHolder.MODE_INHERITABLETHREADLOCAL. at Line: 69 Column: None
5. Message: Using a static member import should be avoided - org.pentaho.platform.security.userroledao.DefaultTenantedPrincipleNameResolver.ALTERNATE_DELIMETER. at Line: 70 Column: None

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryUnitTest.java
1. Message: Using a static member import should be avoided - org.hamcrest.MatcherAssert.assertThat. at Line: 48 Column: None
2. Message: Using a static member import should be avoided - org.hamcrest.Matchers.equalTo. at Line: 49 Column: None
3. Message: Using a static member import should be avoided - org.hamcrest.Matchers.instanceOf. at Line: 50 Column: None
4. Message: Using a static member import should be avoided - org.hamcrest.collection.IsEmptyCollection.empty. at Line: 51 Column: None
5. Message: Using a static member import should be avoided - org.hamcrest.core.Is.is. at Line: 52 Column: None
6. Message: Using the '.*' form of import should be avoided - org.mockito.Mockito.*. at Line: 60 Column: None

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_IT.java
1. Message: Using a static member import should be avoided - org.pentaho.di.repository.pur.PurRepository.checkAndSanitize. at Line: 31 Column: None
2. Message: Using a static member import should be avoided - org.pentaho.platform.repository.RepositoryFilenameUtils.escape. at Line: 32 Column: None

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_Test.java
1. Message: Using a static member import should be avoided - java.util.Arrays.asList. at Line: 29 Column: None
2. Message: Using the '.*' form of import should be avoided - org.mockito.Mockito.*. at Line: 32 Column: None
3. Message: Using a static member import should be avoided - org.pentaho.di.repository.RepositoryObjectType.DATABASE. at Line: 33 Column: None

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_GetObjectInformation_IT.java
1. Message: Using the '.*' form of import should be avoided - org.junit.Assert.*. at Line: 32 Column: None
2. Message: Using a static member import should be avoided - org.pentaho.di.repository.RepositoryObjectType.JOB. at Line: 37 Column: None

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_MoveAndRename_IT.java
1. Message: Using a static member import should be avoided - java.util.Arrays.asList. at Line: 29 Column: None
2. Message: Using the '.*' form of import should be avoided - org.junit.Assert.*. at Line: 30 Column: None
3. Message: Using a static member import should be avoided - org.junit.matchers.JUnitMatchers.hasItem. at Line: 31 Column: None

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_RepositoryDirectory_IT.java
1. Message: Using a static member import should be avoided - junit.framework.TestCase.assertEquals. at Line: 28 Column: None

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_Revisions_IT.java
1. Message: Using the '.*' form of import should be avoided - org.junit.Assert.*. at Line: 31 Column: None

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_IT.java
1. Message: Using a static member import should be avoided - org.pentaho.di.repository.RepositoryObjectType.*. at Line: 37 Column: None
2. Message: Using the '.*' form of import should be avoided - org.pentaho.di.repository.RepositoryObjectType.*. at Line: 37 Column: None



Newly Broken Tests:
-----------------
org.pentaho.di.repository.pur.PurRepository_SharedObjects_IT.initializationError: java.lang.Exception
```
java.lang.Exception: org.pentaho.di.repository.pur.PurRepository_SharedObjects_IT.primeNumbers() must return an Iterable of arrays.
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

```
org.pentaho.di.repository.pur.PurRepository_MoveAndRename_IT.initializationError: java.lang.Exception
```
java.lang.Exception: org.pentaho.di.repository.pur.PurRepository_MoveAndRename_IT.primeNumbers() must return an Iterable of arrays.
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

```
org.pentaho.di.repository.pur.PurRepository_GetObjectInformation_IT.initializationError: java.lang.Exception
```
java.lang.Exception: org.pentaho.di.repository.pur.PurRepository_GetObjectInformation_IT.primeNumbers() must return an Iterable of arrays.
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

```
org.pentaho.di.repository.pur.PurRepository_DatabaseNames_IT.initializationError: java.lang.Exception
```
java.lang.Exception: org.pentaho.di.repository.pur.PurRepository_DatabaseNames_IT.primeNumbers() must return an Iterable of arrays.
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

```
org.pentaho.di.repository.pur.PurRepository_Revisions_IT.initializationError: java.lang.Exception
```
java.lang.Exception: org.pentaho.di.repository.pur.PurRepository_Revisions_IT.primeNumbers() must return an Iterable of arrays.
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

```
org.pentaho.di.repository.pur.PurRepository_RepositoryDirectory_IT.initializationError: java.lang.Exception
```
java.lang.Exception: org.pentaho.di.repository.pur.PurRepository_RepositoryDirectory_IT.primeNumbers() must return an Iterable of arrays.
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

```





Unit test coverage change:
============
org.pentaho.di.repository.pur.model.EERepositoryObject:
 * instructionPercentCoverageChange : +13.87%
 * linePercentCoverageChange : +14.81%
 * complexityPercentCoverageChange : +6.67%
 * methodPercentCoverageChange : +7.69%
    
org.pentaho.di.repository.pur.LazyUnifiedRepositoryDirectory:
 * instructionPercentCoverageChange : +8.14%
 * branchPercentCoverageChange : +10.81%
 * linePercentCoverageChange : +6.16%
 * complexityPercentCoverageChange : +3.12%
 * methodPercentCoverageChange : +3.70%
    
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange : +2.39%
 * branchPercentCoverageChange : +2.16%
 * linePercentCoverageChange : +2.97%
 * complexityPercentCoverageChange : +2.00%
 * methodPercentCoverageChange : +1.69%
    
Integration test coverage change:
============
org.pentaho.di.repository.pur.LazyUnifiedRepositoryDirectory:
 * instructionPercentCoverageChange :**-1.52%**
 * branchPercentCoverageChange :**-2.70%**
 * linePercentCoverageChange :**-1.37%**
 * complexityPercentCoverageChange :**-3.12%**
    
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange :**-6.43%**
 * branchPercentCoverageChange :**-6.09%**
 * linePercentCoverageChange :**-6.60%**
 * complexityPercentCoverageChange :**-6.87%**
 * methodPercentCoverageChange :**-9.04%**
    
org.pentaho.di.repository.pur.JobDelegate:
 * instructionPercentCoverageChange :**-0.14%**
 * branchPercentCoverageChange :**-0.91%**
 * complexityPercentCoverageChange :**-1.45%**
    
org.pentaho.di.repository.pur.PurObjectRevision:
 * instructionPercentCoverageChange :**-14.67%**
 * branchPercentCoverageChange :**-12.50%**
 * linePercentCoverageChange :**-6.25%**
 * complexityPercentCoverageChange :**-10.00%**
 * methodPercentCoverageChange :**-16.67%**
    
org.pentaho.di.repository.pur.model.EERepositoryObject:
 * instructionPercentCoverageChange : +13.87%
 * linePercentCoverageChange : +14.81%
 * complexityPercentCoverageChange : +6.67%
 * methodPercentCoverageChange : +7.69%
    
org.pentaho.di.repository.pur.TransDelegate:
 * instructionPercentCoverageChange :**-0.09%**
 * branchPercentCoverageChange :**-0.99%**
 * complexityPercentCoverageChange :**-1.72%**

**Comment by aliakseihaidukou** [comment]
@lucboudreau you asked to notify you if there are checkstyle violations with static import for test sources.

**Comment by lucboudreau** [comment]
@aliakseihaidukou Thanks. we will add the ones below to our list, but all others should be fixed.

> 1. Message: Using a static member import should be avoided - org.hamcrest.MatcherAssert.assertThat. at Line: 48 Column: None
> 2. Message: Using a static member import should be avoided - org.hamcrest.Matchers.equalTo. at Line: 49 Column: None
> 3. Message: Using a static member import should be avoided - org.hamcrest.Matchers.instanceOf. at Line: 50 Column: None
> 4. Message: Using a static member import should be avoided - org.hamcrest.collection.IsEmptyCollection.empty. at Line: 51 Column: None
> 5. Message: Using a static member import should be avoided - org.hamcrest.core.Is.is. at Line: 52 Column: None

**Comment by aliakseihaidukou** [comment]
@lucboudreau everything there is static import violations, which ones should I fix? Maybe "Using the '.' form of import should be avoided"?
BTW unit tests are fixed.

**Comment by lucboudreau** [comment]
We only should allow static imports of testing frameworks. Those I've quoted above are OK not to fix, but the others should be fixed.

The warnings about using the '.' form should be fixed as well.

**Comment by aliakseihaidukou** [comment]
@lucboudreau what about *org.junit.matchers.JUnitMatchers.hasItem*?

**Comment by aliakseihaidukou** [comment]
@lucboudreau never mind, I switched to *org.hamcrest.CoreMatchers.hasItem* in this case.

Can you start Wingman again please?

**Comment by lucboudreau** [comment]
[In progress](http://10.100.11.222:8080/job/wingman-ant/375/console)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/RepositoryPerformanceApp.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/RepositoryTestBase.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/RepositoryTestLazySupport.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryTestBase.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryUnitTest.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_Test.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_GetObjectInformation_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_MoveAndRename_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_RepositoryDirectory_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_Revisions_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_Links_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/ui/repository/pur/repositoryexplorer/model/UIEERepositoryDirectoryIT.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryUnitTest.java
1. Message: Using a static member import should be avoided - org.hamcrest.MatcherAssert.assertThat. at Line: 48 Column: None
2. Message: Using a static member import should be avoided - org.hamcrest.Matchers.equalTo. at Line: 49 Column: None
3. Message: Using a static member import should be avoided - org.hamcrest.Matchers.instanceOf. at Line: 50 Column: None
4. Message: Using a static member import should be avoided - org.hamcrest.collection.IsEmptyCollection.empty. at Line: 51 Column: None
5. Message: Using a static member import should be avoided - org.hamcrest.core.Is.is. at Line: 52 Column: None



Newly Broken Tests:
-----------------
org.pentaho.di.repository.pur.PurRepository_RepositoryDirectory_IT.testGetChildrenFirst[1]: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<2> but was:<1>
	at org.pentaho.di.repository.pur.PurRepository_RepositoryDirectory_IT.testGetChildrenFirst(PurRepository_RepositoryDirectory_IT.java:71)

```
org.pentaho.di.repository.pur.PurRepository_RepositoryDirectory_IT.testGetRepositoryObjectsFirst[1]: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<2> but was:<1>
	at org.pentaho.di.repository.pur.PurRepository_RepositoryDirectory_IT.testGetRepositoryObjectsFirst(PurRepository_RepositoryDirectory_IT.java:62)

```





Unit test coverage change:
============
org.pentaho.di.repository.pur.model.EERepositoryObject:
 * instructionPercentCoverageChange : +13.87%
 * linePercentCoverageChange : +14.81%
 * complexityPercentCoverageChange : +6.67%
 * methodPercentCoverageChange : +7.69%
    
org.pentaho.di.repository.pur.LazyUnifiedRepositoryDirectory:
 * instructionPercentCoverageChange : +8.14%
 * branchPercentCoverageChange : +10.81%
 * linePercentCoverageChange : +6.16%
 * complexityPercentCoverageChange : +3.12%
 * methodPercentCoverageChange : +3.70%
    
org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UISecurityRole:
 * instructionPercentCoverageChange :**-0.16%**
 * branchPercentCoverageChange :**-1.79%**
 * linePercentCoverageChange :**-0.58%**
 * complexityPercentCoverageChange :**-1.54%**
    
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange : +2.39%
 * branchPercentCoverageChange : +2.16%
 * linePercentCoverageChange : +2.97%
 * complexityPercentCoverageChange : +2.00%
 * methodPercentCoverageChange : +1.69%
    
Integration test coverage change:
============
org.pentaho.di.repository.pur.model.EERepositoryObject:
 * instructionPercentCoverageChange : +13.87%
 * linePercentCoverageChange : +14.81%
 * complexityPercentCoverageChange : +6.67%
 * methodPercentCoverageChange : +7.69%
    
org.pentaho.di.repository.pur.LazyUnifiedRepositoryDirectory:
 * instructionPercentCoverageChange :**-1.24%**
 * branchPercentCoverageChange :**-1.35%**
 * linePercentCoverageChange :**-0.68%**
 * complexityPercentCoverageChange :**-1.56%**
    
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange : +0.40%
 * branchPercentCoverageChange : +0.39%
 * linePercentCoverageChange : +0.25%
 * complexityPercentCoverageChange : +0.44%

**Comment by aliakseihaidukou** [comment]
@lucboudreau sorry, ran ant with *test* task, not *integration-test* and didn't notice the issue. Fixed it now. If everything other is fine, it is ok to be merged.

**Comment by aliakseihaidukou** [comment]
@pedrofvteixeira can you review, please?

**Comment by pedrofvteixeira** [comment]
reviewing and running [wingman](http://10.100.11.222:8080/job/wingman-ant/379)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/LazyUnifiedRepositoryDirectory.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/RepositoryPerformanceApp.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/RepositoryTestBase.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/RepositoryTestLazySupport.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryTestBase.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryUnitTest.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_Test.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_GetObjectInformation_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_MoveAndRename_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_RepositoryDirectory_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_Revisions_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_Links_IT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/ui/repository/pur/repositoryexplorer/model/UIEERepositoryDirectoryIT.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryUnitTest.java
1. Message: Using a static member import should be avoided - org.hamcrest.MatcherAssert.assertThat. at Line: 48 Column: None
2. Message: Using a static member import should be avoided - org.hamcrest.Matchers.equalTo. at Line: 49 Column: None
3. Message: Using a static member import should be avoided - org.hamcrest.Matchers.instanceOf. at Line: 50 Column: None
4. Message: Using a static member import should be avoided - org.hamcrest.collection.IsEmptyCollection.empty. at Line: 51 Column: None
5. Message: Using a static member import should be avoided - org.hamcrest.core.Is.is. at Line: 52 Column: None









Unit test coverage change:
============
org.pentaho.di.repository.pur.model.EERepositoryObject:
 * instructionPercentCoverageChange : +13.87%
 * linePercentCoverageChange : +14.81%
 * complexityPercentCoverageChange : +6.67%
 * methodPercentCoverageChange : +7.69%
    
org.pentaho.di.repository.pur.LazyUnifiedRepositoryDirectory:
 * instructionPercentCoverageChange : +8.37%
 * branchPercentCoverageChange : +11.17%
 * linePercentCoverageChange : +6.52%
 * complexityPercentCoverageChange : +2.79%
 * methodPercentCoverageChange : +3.70%
    
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange : +2.39%
 * branchPercentCoverageChange : +2.16%
 * linePercentCoverageChange : +2.97%
 * complexityPercentCoverageChange : +2.00%
 * methodPercentCoverageChange : +1.69%
    
Integration test coverage change:
============
org.pentaho.di.repository.pur.model.EERepositoryObject:
 * instructionPercentCoverageChange : +13.87%
 * linePercentCoverageChange : +14.81%
 * complexityPercentCoverageChange : +6.67%
 * methodPercentCoverageChange : +7.69%
    
org.pentaho.di.repository.pur.LazyUnifiedRepositoryDirectory:
 * instructionPercentCoverageChange :**-1.11%**
 * branchPercentCoverageChange :**-0.50%**
 * linePercentCoverageChange :**-0.49%**
 * complexityPercentCoverageChange :**-0.91%**
    
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange : +0.35%
 * linePercentCoverageChange : +0.16%

**Comment by pedrofvteixeira** [comment]
PR looks good, same with wingman.

Over to you @rmansoor , @pentaho-nbaker.

**Pull request merged**
