### PR TITLE
[BACKLOG-31099] Improve UX for adding parameters to the Transformatio…

### PR DESCRIPTION
**Pull request by ddiroma**
…n executor step

### CODE REVIEW

**Comment by buildguy** [comment]
### :gear: Build finished in 21m 19s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl engine,ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3577|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6974/1/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by ddiroma** [comment]
@bmorrise @cseverino789

**Comment by buildguy** [comment]
### :gear: Build finished in 23m 16s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl core,engine,ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|4685|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6974/2/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by ddiroma** [comment]
@cseverino789 @bmorrise

**Pull request merged**
