### PR TITLE
[SP-6180] [PDI-19444] : ExecuteTrans API issue for Carte for non-repo…

### PR DESCRIPTION
**Pull request by PawanPonugupati**
…sitory transformation files

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 9m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by PawanPonugupati** [comment]
Build Failed due to Sonar server not reachable issue. Reopening Pr

**Comment by buildguy** [comment]
### :x: Build failed in 11m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by ddiroma — APPROVED** [review]
Changes match original from PDI-19444

**Pull request merged**
