### PR TITLE
[PDI-15401] - Extend the date format parsing to include milliseconds …

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
…(CSV & Text File Input)

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@kurtwalker @DFieldFL 
Please review.

**Comment by DFieldFL** [comment]
Any tests need to be created/modified for this changed?

**Comment by DFieldFL** [comment]
Any tests need to be created/modified for this changed?

**Comment by Aliaksandr-Kastenka** [comment]
@DFieldFL @kurtwalker 
We have a test for a Const.getDataFromat method(https://github.com/pentaho/pentaho-kettle/blob/28b55c0782886baa8043b77684feb9ab21b520b2/core/src/main/java/org/pentaho/di/core/Const.java#L2880-L2889)
Id checks only the size of date list:
https://github.com/pentaho/pentaho-kettle/blob/5099e34abeee5a604a3715078d8ff75fe3e11269/core/src/test/java/org/pentaho/di/core/ConstTest.java#L2048-L2055

**Comment by DFieldFL** [comment]
@pentaho/ackbar merely a test.

**Comment by DFieldFL** [comment]
@pentaho/ackbar one more test.

**Comment by DFieldFL** [comment]
@pentaho/ackbar not the last one :)

**Comment by DFieldFL** [comment]
check this out @pentaho/ackbar . How cool is this?

**Pull request merged**
