### PR TITLE
[SP-2204][PDI-14375] - Incorrect time displayed in Version History af…

### PR DESCRIPTION
**Pull request by brosander**
…ter some operations with transformation/jobs in the DI repository

- clear "createdDate" on renaming to force the repository to inject current time
- update tests to check this condition

Conflicts:
	plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_MoveAndRename_IT.java

### CODE REVIEW

**Comment by brosander** [comment]
Rebased on top of 6.0, moved test logic updates to correct file (PurRepository_MoveAndRename_Test)

**Comment by brosander** [comment]
wingman running

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_MoveAndRename_Test.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange : +0.02%
    
Integration test coverage change:
============
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange :**-0.02%**

**Comment by brosander** [comment]
@lucboudreau @mattyb149 please review, should be equivalent to https://github.com/pentaho/pentaho-kettle/issues/1891

**Comment by lucboudreau** [comment]
Aren't there two tests in the other PR and only one being changed in this one?

**Comment by brosander** [comment]
@lucboudreau if you expand upwards in the test change, you'll see two test methods that call the method I added the changes to

**Pull request merged**
