### PR TITLE
[PDI-20085] - KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL produces opposite display for NULLS - fixing unit tests

### PR DESCRIPTION
**Pull request by smmribeiro**
This is a squash and rebase of [pentaho-kettle#9324](https://github.com/pentaho/pentaho-kettle/pull/9324) but with the fix for the "unreachable statement" error (due to a return on line 3605)!

@pentaho/tatooine_dev

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 4m 17s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,engine,ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 37m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 102 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.aggregaterows.AggregateRowsTest.testProcessRow</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.abort.AbortTest.testAbortDoesntAbortWithoutInputRow</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.abort.AbortTest.testSafeStop</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.abort.AbortTest.testAbortWithError</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.abort.AbortTest.testAbortAbortsWithInputRow</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.clonerow.CloneRowTest.nullNrCloneField</b> (click to expand)</summary><p>

```
Unexpected exception, expected<org.pentaho.di.core.exception.KettleException> but was<java.lang.NoClassDefFoundError>
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.concatfields.ConcatFieldsTest.testPrepareOutputRowWithSplitRows</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.concatfields.ConcatFieldsTest.testPrepareOutputRowWithSplitRowsAndHeaderOffsetForSplitRowsAllowed</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStep_FormulaRecalculationTest.forcesToRecalculate_Sxssf_PropertyIsCleared</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStep_FormulaRecalculationTest.forcesToRecalculate_Sxssf_PropertyIsCleared</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStep_FormulaRecalculationTest.forcesToRecalculate_Hssf</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStep_FormulaRecalculationTest.forcesToRecalculate_Hssf</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStep_FormulaRecalculationTest.forcesToRecalculate_Sxssf_PropertyIsSet</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStep_FormulaRecalculationTest.forcesToRecalculate_Sxssf_PropertyIsSet</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStep_FormulaRecalculationTest.forcesToRecalculate_Sxssf_PropertyIsNotSet</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStep_FormulaRecalculationTest.forcesToRecalculate_Sxssf_PropertyIsNotSet</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStep_StyleFormatTest.testStyleFormatHssf</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStep_StyleFormatTest.testStyleFormatHssf</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStep_StyleFormatTest.testStyleFormatXssf</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.excelwriter.ExcelWriterStep_StyleFormatTest.testStyleFormatXssf</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest.org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testDefaultLeafToNullChangedToFalse_NoNullInOutput</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testSingleObjPred</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testExpressionWithLegacyModeEnable</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testChildDot</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testChildBracketsNDots</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testDualExpMismatchError</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testBfsMatchOrder</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testDefaultLeafToNullTrue_NullsInOutput</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testExpressionWithLegacyModeDisable</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testBadInput</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testAttrFilter</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testIndex</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testNullProp</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testJsonInputPathResolutionSuccess</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testObjectOut</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testSmallDoubles</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testChildBrackets</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testArrayOut</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testRemoveSourceField</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testRepeatFieldSingleObj</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testZeroSizeFile</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testUrlInput</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testBicycleAsterisk</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testIndexList</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testFileList</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testExtraFileFields</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testIndexFirst</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testZipFileInput</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testNoFilesInListError</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testNullFileList</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testErrorRedirect</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testIncludeNulls_N</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testIncludeNulls_Y</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testDefaultLeafToNull</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testLargeDoubles</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testJgdArray</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testParsingWithNullFinding</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testRowLimit</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testDualExpMismatchPathLeafToNull</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testNullInputs</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testBadExp</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testIndexLastObj</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testJsonInputPathResolution</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testDualExp</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testIfIgnorePathDoNotSkipRowIfInputIsNullOrFieldNotFound</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testSingleField</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testJsonInputMetaInputFieldsNotOverwritten</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testPathMissingIgnore</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.jsoninput.JsonInputTest.testBracketEscape</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.mail.MailTest.testSendMailWithPlainPassword</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.mail.MailTest.testSendMailWithEncryptedPassword</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.metainject.MetaInjectTest.initializationError</b> (click to expand)</summary><p>

```
Failed to transform class with name org.pentaho.di.trans.steps.metainject.MetaInjectTest. Reason: [source error] the called constructor is private in org.pentaho.di.trans.steps.metainject.MetaInjectTest$InjectableTestStepMeta
```

</p></details>

<details><summary><b>org.pentaho.metastore.locator.api.impl.MetastoreLocatorBeforeJobExtensionPointTest.testCallExtensionPoint</b> (click to expand)</summary><p>

```

The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks

Mockito's inline mock maker supports static mocks based on the Instrumentation API.
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
Note that Mockito's inline mock maker is not supported on Android.
```

</p></details>

<details><summary><b>org.pentaho.metastore.locator.api.impl.MetastoreLocatorBeforeJobSaveExtensionPointTest.testCallExtensionPoint</b> (click to expand)</summary><p>

```

The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks

Mockito's inline mock maker supports static mocks based on the Instrumentation API.
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
Note that Mockito's inline mock maker is not supported on Android.
```

</p></details>

<details><summary><b>org.pentaho.metastore.locator.api.impl.MetastoreLocatorExtensionPointTest.testCallExtensionPointWithTrans</b> (click to expand)</summary><p>

```

The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks

Mockito's inline mock maker supports static mocks based on the Instrumentation API.
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
Note that Mockito's inline mock maker is not supported on Android.
```

</p></details>

<details><summary><b>org.pentaho.metastore.locator.api.impl.MetastoreLocatorExtensionPointTest.testCallExtensionPointWithTransMeta</b> (click to expand)</summary><p>

```

The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks

Mockito's inline mock maker supports static mocks based on the Instrumentation API.
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
Note that Mockito's inline mock maker is not supported on Android.
```

</p></details>

<details><summary><b>org.pentaho.metastore.locator.api.impl.MetastoreLocatorImplTest.testGetMetastoreTest</b> (click to expand)</summary><p>

```

The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks

Mockito's inline mock maker supports static mocks based on the Instrumentation API.
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
Note that Mockito's inline mock maker is not supported on Android.
```

</p></details>

<details><summary><b>org.pentaho.metastore.locator.api.impl.MetastoreLocatorImplTest.testGetMetastoreSingleNull</b> (click to expand)</summary><p>

```

The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks

Mockito's inline mock maker supports static mocks based on the Instrumentation API.
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
Note that Mockito's inline mock maker is not supported on Android.
```

</p></details>

<details><summary><b>org.pentaho.metastore.locator.api.impl.MetastoreLocatorNewTransExtensionPointTest.testCallExtensionPoint</b> (click to expand)</summary><p>

```

The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks

Mockito's inline mock maker supports static mocks based on the Instrumentation API.
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
Note that Mockito's inline mock maker is not supported on Android.
```

</p></details>

<details><summary><b>org.pentaho.metastore.locator.api.impl.MetastoreLocatorPrepareTransExtensionPointTest.testCallExtensionPoint</b> (click to expand)</summary><p>

```

The used MockMaker SubclassByteBuddyMockMaker does not support the creation of static mocks

Mockito's inline mock maker supports static mocks based on the Instrumentation API.
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
Note that Mockito's inline mock maker is not supported on Android.
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.checkRemoteFoldernameField_NameIsSet_NotFound</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.checkSourceFileField_NameIsSet_Found</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.checkDestinationFolderField_NameIsSet_NotFound</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.remoteFilenameFieldIsMandatoryWhenStreamingFromInputField</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.checkSourceFileField_NameIsBlank</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.checkRemoteFoldernameField_NameIsSet_Found</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.checkRemoteFilenameField_FieldNameIsBlank</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.checkRemoteFilenameField_FieldNameIsSet_Found</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.checkSourceFileField_NameIsSet_NotFound</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.checkRemoteFoldernameField_NameIsBlank</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.checkDestinationFolderField_NameIsSet_Found</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.checkRemoteFilenameField_FieldNameIsSet_NotFound</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.sftpput.SFTPPutTest.checkDestinationFolderField_NameIsBlank</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.shapefilereader.ShapeFileReaderTest.processRowPolyLineCloneRowTest</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.shapefilereader.ShapeFileReaderTest.processRowPolyLineCloneRowTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.addxml.AddXMLTest.testProcessRow</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.xmljoin.XmlJoinOmitNullValuesTest.testRemoveEmptyNodes</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.xmloutput.XMLOutputTest.testFlow</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.xmloutput.XMLOutputTest.testFlowWithKettlePropertyNullIfValueAllowed</b> (click to expand)</summary><p>

```
org/mockito/ArgumentMatchers
```

</p></details>

<details><summary><b>org.pentaho.di.core.xml.XMLHandlerUnitTest.addTagValueBinary</b> (click to expand)</summary><p>

```
expected:<...ytedata>H4sIAAAAAAAA[/w]tJLS5RcEksSQQAL4PL8Q...> but was:<...ytedata>H4sIAAAAAAAA[AA]tJLS5RcEksSQQAL4PL8Q...>
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.fieldsplitter.FieldSplitterTest.testSplitFields</b> (click to expand)</summary><p>

```
Output row is of an unexpected length expected:<4> but was:<3>
```

</p></details>

  
Tests run: **5380**, Failures: **102**, Skipped: **22** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9347/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 22m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,engine,ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.core.xml.XMLHandlerUnitTest.addTagValueBinary</b> (click to expand)</summary><p>

```
expected:<...ytedata>H4sIAAAAAAAA[/w]tJLS5RcEksSQQAL4PL8Q...> but was:<...ytedata>H4sIAAAAAAAA[AA]tJLS5RcEksSQQAL4PL8Q...>
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.fieldsplitter.FieldSplitterTest.testSplitFields</b> (click to expand)</summary><p>

```
Output row is of an unexpected length expected:<4> but was:<3>
```

</p></details>

  
Tests run: **3959**, Failures: **2**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9347/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by renato-s — APPROVED** [review]

**Pull request merged**
