### PR TITLE
[BACKLOG-35209] JSON input: Add boolean field to allow user to includ…

### PR DESCRIPTION
**Pull request by ddiroma**
…e NULL values in result set

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 8m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **87**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-8034/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **87**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-8034/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ddiroma** [comment]
The 2 code smells are:
1. I added a second constructor (same as the 1st) with a throws Exception. This will not compile without this and it is exactly how the 1st constructor is built
2. Nobody can decrease the complexity of the step dialogs...ever!

**Pull request merged**
