### PR TITLE
[PDI-19160] - Set variables(job entry): When "Variable substitution" …

### PR DESCRIPTION
**Pull request by krishnaalluhitachi**
Code is added to respect Variable Substitution flag so that variables declared in the Set Variables step operated as below
1. Variable will be overridden if the same variable is available in the property file and Variable Substitution flag is true
2. Variable will not be overridden if the Variable Substitution flag is false
3. Variable will be added if the variable is not available in the property file and  Variable Substitution flag is true/false.

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 9m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 8m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by peterrinehart — CHANGES_REQUESTED** [review]
Looks good, please update the copyright date in the header.

**Comment by buildguy** [comment]
### :x: Build failed in 10m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by krishnaalluhitachi** [comment]
Have some merge conflicts so creating new PR

**Comment by krishnaalluhitachi** [comment]
Squash issue

**Pull request closed without merging**
