### PR TITLE
[PDI-11421] - Moving MySQL data via Bulk Loader with DECIMAL Data Type from one MySQL Table to another has precision errors

### PR DESCRIPTION
**Pull request by mr9d**
- Reset default conversion mask for Number type and make it to be calculated according to field length and precision.
- Unit test.

### CODE REVIEW

**Comment by mr9d** [comment]
@brosander please review.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoader.java
  engine/test-src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File engine/src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoader.java
1. Message: 'if' is not followed by whitespace. at Line: 393 Column: 19

File engine/test-src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderTest.java
1. Message: Line has trailing spaces. at Line: 101 Column: None
2. Message: Line has trailing spaces. at Line: 103 Column: None
3. Message: Line has trailing spaces. at Line: 104 Column: None
4. Message: '(' is not followed by whitespace. at Line: 217 Column: 47
5. Message: ')' is not preceded with whitespace. at Line: 217 Column: 53
6. Message: '(' is not followed by whitespace. at Line: 218 Column: 19
7. Message: ')' is not preceded with whitespace. at Line: 218 Column: 22
8. Message: ',' is not followed by whitespace. at Line: 218 Column: 21
9. Message: '(' is not followed by whitespace. at Line: 232 Column: 25
10. Message: ')' is not preceded with whitespace. at Line: 232 Column: 82
11. Message: Line has trailing spaces. at Line: 63 Column: None
12. Message: ')' is not preceded with whitespace. at Line: 96 Column: 59
13. Message: '(' is preceded with whitespace. at Line: 97 Column: 29









Unit test coverage change:
============
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange :**-0.53%**
    
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange :**-0.08%**
    
org.pentaho.di.trans.steps.mysqlbulkloader.MySQLBulkLoader:
 * instructionPercentCoverageChange : +2.51%
 * branchPercentCoverageChange : +3.58%
 * linePercentCoverageChange : +2.94%
 * complexityPercentCoverageChange : +2.45%
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange : +7.14%
 * complexityPercentCoverageChange : +7.69%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +0.19%
 * linePercentCoverageChange : +0.27%

**Comment by akhayrutdinov** [comment]
@brosander, mind reviewing it please?

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoader.java
  engine/test-src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderTest.java










Unit test coverage change:
============
org.pentaho.di.trans.steps.randomvalue.RandomValueMeta:
 * instructionPercentCoverageChange :**-0.15%**
 * branchPercentCoverageChange :**-2.08%**
 * complexityPercentCoverageChange :**-2.13%**
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange :**-0.18%**
    
org.pentaho.di.trans.steps.mysqlbulkloader.MySQLBulkLoader:
 * instructionPercentCoverageChange : +2.51%
 * branchPercentCoverageChange : +3.58%
 * linePercentCoverageChange : +2.94%
 * complexityPercentCoverageChange : +2.45%

**Pull request merged**
