### PR TITLE
[BACKLOG-6046] Revamp the Transformation Dialog

### PR DESCRIPTION
**Pull request by e-cuellar**
@mdamour1976 Please Sir!

### CODE REVIEW

**Comment by mdamour1976** [comment]
@e-cuellar the reason you are seeing such large diffs is because the line endings changed since you are on windows and must have touched some of the files.  Anyway, I applied a fix to the line endings.  Here is the diff with the line endings fixed:  https://github.com/pentaho/pentaho-kettle/compare/master...mdamour1976:BACKLOG-6046?expand=1

Maybe you can use my commit or I can close this pull request and issue a new one with my changes.  Your name is still on the commit I pushed.

**Comment by e-cuellar** [comment]
@mdamour1976 Mike... please go ahead and close this pull request and issue a new one with your changes...

**Comment by e-cuellar** [comment]
@mdamour1976 Done Mike. I cherry picked your commit and pushed it to my branch. The pull request now looks good for review!

**Comment by mdamour1976** [comment]
Going to create a branch in pentaho/pentaho-kettle.

**Pull request closed without merging**
