### PR TITLE
[BACKLOG-28035] View recently opened files in new file browser

### PR DESCRIPTION
**Pull request by bmorrise**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 10m 19s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
plugins/file-open-save-new/api,plugins/file-open-save-new/core,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1130**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7150/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 10m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
plugins/file-open-save-new/api,plugins/file-open-save-new/core,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1130**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7150/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bmorrise** [comment]
@cseverino789

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 11m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
plugins/file-open-save-new/api,plugins/file-open-save-new/core,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1130**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7150/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request closed without merging**
