### PR TITLE
[PDI-17006] Issues with Carte Jobs API runJob endpoint in Pentaho REST API

### PR DESCRIPTION
**Pull request by ssamora**
@pentaho-lmartins

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 34m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3728**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7592/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 32m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3728**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7592/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ssamora** [comment]
PR recreated in https://github.com/pentaho/pentaho-kettle/pull/7637 due to merging conflicts after 9.1 code freeze

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 41s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3728**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7592/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 30m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 18 test(s) failed:

<details><summary><b>org.pentaho.di.cluster.SlaveServerTest.org.pentaho.di.cluster.SlaveServerTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.concurrency.ActiveSubTransformationsConcurrencyTest.getAndCreateConcurrently</b> (click to expand)</summary><p>

```
org/pentaho/di/concurrency/StopOnErrorCallable
```

</p></details>

<details><summary><b>org.pentaho.di.concurrency.BaseRowSetConcurrentTest.test</b> (click to expand)</summary><p>

```
org/pentaho/di/concurrency/StopOnErrorCallable
```

</p></details>

<details><summary><b>org.pentaho.di.concurrency.BaseStepConcurrencyTest.testRowListeners</b> (click to expand)</summary><p>

```
org/pentaho/di/concurrency/StopOnErrorCallable
```

</p></details>

<details><summary><b>org.pentaho.di.concurrency.BaseStepConcurrencyTest.testInputOutputRowSets</b> (click to expand)</summary><p>

```
org/pentaho/di/concurrency/StopOnErrorCallable
```

</p></details>

<details><summary><b>org.pentaho.di.concurrency.ConcurrentFileSystemManagerTest.org.pentaho.di.concurrency.ConcurrentFileSystemManagerTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.concurrency.JobMapConcurrencyTest.updateGetAndReplaceConcurrently</b> (click to expand)</summary><p>

```
org/pentaho/di/concurrency/StopOnErrorCallable
```

</p></details>

<details><summary><b>org.pentaho.di.concurrency.RowMetaConcurrencyTest.fiveAddersAgainstTenReaders</b> (click to expand)</summary><p>

```
org/pentaho/di/concurrency/StopOnErrorCallable
```

</p></details>

<details><summary><b>org.pentaho.di.concurrency.RowMetaConcurrencyTest.addRemoveSearch</b> (click to expand)</summary><p>

```
org/pentaho/di/concurrency/StopOnErrorCallable
```

</p></details>

<details><summary><b>org.pentaho.di.concurrency.RowMetaConcurrencyTest.fiveShufflersAgainstTenSearchers</b> (click to expand)</summary><p>

```
org/pentaho/di/concurrency/StopOnErrorCallable
```

</p></details>

<details><summary><b>org.pentaho.di.concurrency.SlaveServerConcurrentTest.getAndReplaceConcurrently</b> (click to expand)</summary><p>

```
org/pentaho/di/concurrency/StopOnErrorCallable
```

</p></details>

<details><summary><b>org.pentaho.di.concurrency.TransformationMapConcurrentTest.testConcurrentAllocateAndDeallocateServerSocketPort</b> (click to expand)</summary><p>

```
org/pentaho/di/concurrency/ConcurrencyTestRunner
```

</p></details>

<details><summary><b>org.pentaho.di.concurrency.TransformationMapConcurrentTest.testConcurrentAllocateServerSocketPort</b> (click to expand)</summary><p>

```
org/pentaho/di/concurrency/ConcurrencyTestRunner
```

</p></details>

<details><summary><b>org.pentaho.di.shared.SharedObjectsTest.org.pentaho.di.shared.SharedObjectsTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.www.CarteTest.callStopCarteRestService</b> (click to expand)</summary><p>

```
"No Carte Server found at localhost:8080
```

</p></details>

<details><summary><b>org.pentaho.di.www.GetPropertiesServletTest.org.pentaho.di.www.GetPropertiesServletTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.www.SlaveServerJobStatusTest.org.pentaho.di.www.SlaveServerJobStatusTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.www.SlaveServerTransStatusTest.org.pentaho.di.www.SlaveServerTransStatusTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

  
Tests run: **3714**, Failures: **18**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7592/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1h 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3496**, Failures: **0**, Skipped: **3** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7592/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3733**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7592/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]

**Review by ppatricio — APPROVED** [review]

**Pull request merged**
