### PR TITLE
[SP-2594] Backport of PDI-15018 - DI Server security not behaving properly. (5.4 Suite)

### PR DESCRIPTION
**Pull request by IvanNikolaychuk**
- Adding SCHEDULE_TRANSFORMATION and SCHEDULE_JOB enums

@akhayrutdinov , review it please. It's a part of a backport of  https://github.com/pentaho/pentaho-kettle/pull/2326 and  for 5.4

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@pamval, @pedrofvteixeira, run WM for this PR please

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/80/

**Comment by lucboudreau** [comment]
Base build failed with return code 1

**Comment by mbatchelor** [comment]
I don't see any test cases - shouldn't there be a new test case for this?

**Comment by IvanNikolaychuk** [comment]
@mbatchelor, the only thig changed here - is adding two elements to enum.
Later they will be used in [here] (https://github.com/pentaho/pdi-ee-plugin/pull/316). Tests in that PR are written.

**Comment by IvanNikolaychuk** [comment]
@akhayrutdinov, could you review it please?

**Comment by akhayrutdinov** [comment]
Same as #2326, no backward-compatibility problems. Merged

**Pull request merged**
