### PR TITLE
[SP-6103] Backport of PDI-19379 - CSV file input step does not save t…

### PR DESCRIPTION
**Pull request by ddiroma**
…he chosen file if the ktr is not saved first (9.2 Suite)

### CODE REVIEW

**Comment by ddiroma** [comment]
@pentaho/tatooine Please approve

**Comment by buildguy** [comment]
### :x: Build failed in 7m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 1h 24m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 34 test(s) failed:

<details><summary><b>com.pentaho.repository.importexport.StreamToJobNodeConverterTest.com.pentaho.repository.importexport.StreamToJobNodeConverterTest</b> (click to expand)</summary><p>

```

Unable to find native plugins definition file: kettle-steps.xml

```

</p></details>

<details><summary><b>com.pentaho.repository.importexport.StreamToNodeConvertersPrivateDatabasesTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/core/logging/JobLogTable
```

</p></details>

<details><summary><b>com.pentaho.repository.importexport.StreamToTransNodeConverterTest.testConvertTransWithMissingPlugins</b> (click to expand)</summary><p>

```
org/pentaho/di/trans/step/StepIOMetaInterface
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.AbsSecurityProviderTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/BaseRepositorySecurityProvider
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.AttributesMapUtilTest.initializationError</b> (click to expand)</summary><p>

```
Failed to transform class with name org.pentaho.di.repository.pur.AttributesMapUtilTest. Reason: cannot find org.pentaho.di.job.entry.JobEntryCopy
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.DatabaseDelegateTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ReconnectableRepository
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.DelegatesPrivateDatabasesTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/core/logging/JobLogTable
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.JobDelegateTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/job/entry/JobEntryBase
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.PurRepositoryConnectorTest.org.pentaho.di.repository.pur.PurRepositoryConnectorTest</b> (click to expand)</summary><p>

```

Unable to find native plugins definition file: kettle-steps.xml

```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.PurRepositoryMetaTest.initializationError</b> (click to expand)</summary><p>

```
Lorg/pentaho/di/repository/RepositoriesMeta;
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.PurRepositorySecurityManagerTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/RepositorySecurityUserValidator
```

</p></details>

<details><summary><b>org.apache.maven.surefire.junit4.JUnit4Provider.org.pentaho.di.repository.pur.PurRepositoryStressTest</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ReconnectableRepository
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.PurRepositoryUnitTest.org.pentaho.di.repository.pur.PurRepositoryUnitTest</b> (click to expand)</summary><p>

```

Unable to find native plugins definition file: kettle-steps.xml

```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.PurRepository_DatabaseNames_Test.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ReconnectableRepository
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.SlaveDelegateTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ReconnectableRepository
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.UserRoleDelegateTest.createUser_ProhibitsToCreate_WhenNameCollides</b> (click to expand)</summary><p>

```
Unexpected exception, expected<org.pentaho.di.core.exception.KettleException> but was<java.lang.NoClassDefFoundError>
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.UserRoleDelegateTest.createUser_CreatesSuccessfully_WhenNameIsUnique</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/UserInfo
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.UserRoleDelegateTest.createUser_CreatesSuccessfully_WhenNameDiffersInCase</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/UserInfo
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.UserRoleHelperTest.convertFromProxyPentahoUser_CopiesRolesForEeUser</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/UserInfo
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.UserRoleHelperTest.convertFromProxyPentahoUsers_CopiesEachUser</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/UserInfo
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.UserRoleHelperTest.convertFromProxyPentahoUser_CopiesDataFromInput</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/UserInfo
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.metastore.PurRepositoryMetaStoreTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ReconnectableRepository
```

</p></details>

<details><summary><b>org.pentaho.di.repository.utils.RepositoryFactoryTest.org.pentaho.di.repository.utils.RepositoryFactoryTest</b> (click to expand)</summary><p>

```

Unable to find native plugins definition file: kettle-steps.xml

```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.EESpoonPluginTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/core/AddUndoPositionInterface
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.controller.RepositoryLockControllerTest.testBlockLock</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/BaseRepositoryMeta
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.pur.repositoryexplorer.model.UIEERepositoryDirectoryTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/ReconnectableRepository
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.repositoryexplorer.UIEESecurityTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/UserInfo
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.repositoryexplorer.UIEESecurityUserTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/UserInfo
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.repositoryexplorer.UISecurityRoleTest.initializationError</b> (click to expand)</summary><p>

```
Lorg/pentaho/di/repository/UserInfo;
```

</p></details>

<details><summary><b>org.pentaho.di.ui.repository.repositoryexplorer.abs.model.UIAbsSecurityTest.testUIAbsSecurity</b> (click to expand)</summary><p>

```
org/pentaho/di/repository/UserInfo
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTConsumerMetaTest.org.pentaho.di.trans.step.mqtt.MQTTConsumerMetaTest</b> (click to expand)</summary><p>

```

Unable to read plugin xml file: {0}:
Type org.pentaho.di.core.encryption.TwoWayPasswordEncoderInterface not present

```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTConsumerTest.org.pentaho.di.trans.step.mqtt.MQTTConsumerTest</b> (click to expand)</summary><p>

```

Unable to read plugin xml file: {0}:
Type org.pentaho.di.core.encryption.TwoWayPasswordEncoderInterface not present

```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTProducerMetaTest.org.pentaho.di.trans.step.mqtt.MQTTProducerMetaTest</b> (click to expand)</summary><p>

```

Unable to read plugin xml file: {0}:
Type org.pentaho.di.core.encryption.TwoWayPasswordEncoderInterface not present

```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTProducerTest.org.pentaho.di.trans.step.mqtt.MQTTProducerTest</b> (click to expand)</summary><p>

```

Unable to read plugin xml file: {0}:
Type org.pentaho.di.core.encryption.TwoWayPasswordEncoderInterface not present

```

</p></details>

  
Tests run: **1061**, Failures: **34**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.pentaho.net/job/projects/job/pdi-8/job/PR-8174/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
I'm closing this PR as the issue is still not assigned a specific SP.

**Comment by buildguy** [comment]
### :x: Build failed in 1m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by ddiroma** [comment]
Master PR: https://github.com/pentaho/pentaho-kettle/pull/8098
9.2 PR: https://github.com/pentaho/pentaho-kettle/pull/8174
9.2.0.4 PR: https://github.com/pentaho/pentaho-kettle/pull/8321

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PR.

**Pull request merged**
