### PR TITLE
[PDI-17738] Row Denormaliser doesn't honor formats

### PR DESCRIPTION
**Pull request by jonjarvis**
Fixed and added unit test. The Denormaliser also did not honor:
-Grouping Symbol
-Decimal Symbol
-Currency Symbol

### CODE REVIEW

**Comment by buildguy** [comment]
### :gear: Build finished in 19m 28s with command:
```
mvn clean verify -B -e -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3533|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/5/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 19m 1s with command:
```
mvn clean verify -B -e -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3533|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/6/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 18m 47s with command:
```
mvn clean verify -B -e -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3533|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/7/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 20m 13s with command:
```
mvn clean verify -B -e -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3531|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/8/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 23m 53s with command:
```
mvn clean verify -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl engine
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 11 test(s) failed:
- **org.pentaho.di.trans.StepWithMappingMetaTest.loadMappingMeta**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.trans.StepWithMappingMetaTest.loadMappingMetaTest**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.trans.StepWithMappingMetaTest.testFileNameAsVariable**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.trans.TransMetaTest.testLoadXml**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.trans.TransMetaTest.testSetInternalEntryCurrentDirectoryWithRepository**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.trans.TransMetaTest.testTransWithOneStepIsConsideredUsed**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTest**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTestCantFindDirectory**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTestJobNotFoundInDirectory**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTestCantFindRepository**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTestWithUnauthorizedUser**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|3540|11|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/10/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 21m 11s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3540|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/11/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 22m 14s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3540|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/13/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 21m 46s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3539|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/14/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 21m 22s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3541|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/15/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 21m 30s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3542|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/16/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 21m 40s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3545|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/18/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 20m 46s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3558|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/19/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 23m with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3558|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/20/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 22m 46s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3558|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/21/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 43s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl engine
```
:exclamation: No tests found!


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 21m 50s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3558|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/23/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 23m 26s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3558|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/24/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 22m 49s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3566|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/25/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 23m 58s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3572|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/26/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 23m 55s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3573|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/27/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 23m 25s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3573|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/28/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 24m 51s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3580|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/30/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 24m 37s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3580|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/31/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 22m 37s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3580|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/32/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
error=11, Resource temporarily unavailable
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 24m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3580**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/35/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3589**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/36/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 22m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3602**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/37/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3602**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/38/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 25m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3602**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/39/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 27m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3608**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/41/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 25m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3611**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/42/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 24m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3620**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/44/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 24m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3620**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/45/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 20m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3617**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/46/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 26m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3617**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/47/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 24m 3s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3618**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/48/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3618**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/49/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 25m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3618**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/50/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 29m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3618**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/51/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 21m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3618**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/52/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3618**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/53/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 24m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3620**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/54/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 24m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 14 test(s) failed:

<details><summary><b>org.pentaho.di.trans.step.jms.JmsConsumerMetaTest.org.pentaho.di.trans.step.jms.JmsConsumerMetaTest</b> (click to expand)</summary><p>

```

Unable to find native plugins definition file: kettle-valuemeta-plugins.xml

```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.jms.JmsProducerMetaTest.testCheck</b> (click to expand)</summary><p>

```
org/pentaho/di/core/CheckResult
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.jms.JmsProducerTest.testProperties</b> (click to expand)</summary><p>

```
org/pentaho/di/core/ResultFile
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.jms.JmsProducerTest.testInit</b> (click to expand)</summary><p>

```
org/pentaho/di/core/ResultFile
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.jms.JmsProducerTest.testUserDrivenSetOptions</b> (click to expand)</summary><p>

```
org/pentaho/di/core/ResultFile
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.jms.JmsProducerTest.jmsContextClosedOnStop</b> (click to expand)</summary><p>

```
org/pentaho/di/core/ResultFile
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.jms.JmsProducerTest.testSetOptions</b> (click to expand)</summary><p>

```
org/pentaho/di/core/ResultFile
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.jms.JmsStreamSourceTest.org.pentaho.di.trans.step.jms.JmsStreamSourceTest</b> (click to expand)</summary><p>

```
org/pentaho/di/core/ResultFile
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTClientBuilderTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/core/gui/GUIPositionInterface
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTConsumerMetaTest.org.pentaho.di.trans.step.mqtt.MQTTConsumerMetaTest</b> (click to expand)</summary><p>

```
org/pentaho/di/core/xml/XMLHandlerCacheEntry
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTConsumerTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/core/ExtensionDataInterface
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTProducerMetaTest.org.pentaho.di.trans.step.mqtt.MQTTProducerMetaTest</b> (click to expand)</summary><p>

```

java.lang.NoClassDefFoundError: org/pentaho/di/core/xml/XMLHandlerCacheEntry
org/pentaho/di/core/xml/XMLHandlerCacheEntry

```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTProducerTest.initializationError</b> (click to expand)</summary><p>

```
Failed to transform class with name org.pentaho.di.trans.step.mqtt.MQTTProducerTest. Reason: [source error] no such class: org.pentaho.di.core.variables.VariableSpace
```

</p></details>

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTStreamSourceTest.initializationError</b> (click to expand)</summary><p>

```
Failed to transform class with name org.pentaho.di.trans.step.mqtt.MQTTClientBuilder. Reason: cannot find org.pentaho.di.core.variables.VariableSpace
```

</p></details>

  
Tests run: **3585**, Failures: **14**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/55/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3620**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6671/56/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by mbatchelor** [comment]
Awesome! Thanks so much for the fix.

**Pull request merged**
