### PR TITLE
PDI-12123 - Field quoting of reserved database words can cause SQL fa…

### PR DESCRIPTION
**Pull request by SergeyTravin**
…ilures

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@mattcasters, @brosander, @mattyb149  Could you review it, please? Thanks!

**Comment by SergeyTravin** [comment]
@hudak, @mattcasters, @brosander, @mattyb149, Could you review it, please? Thanks!

**Comment by SergeyTravin** [comment]
@hudak, @mattcasters, @brosander, @mattyb149, Could you merge it, please? It is a really simple changes.
The PR was sent more than years ago and included in 6.0 goals

**Comment by SergeyTravin** [comment]
@hudak, @mattcasters, @brosander, @mattyb149, Could you merge it, please? It is a really simple changes. The PR was sent about 1 year ago.
/cc @dkincade

**Comment by SergeyTravin** [comment]
@hudak, @mattcasters, @brosander, @mattyb149
I would be grateful if you could look at the PR.

**Comment by hudak** [comment]
@SergeyTravin I apologize for this taking so long. It is a simple fix, but changing the default behavior of a core Kettle base class is concerning. I'll work with management on how to proceed here and get back to you. Thanks!

**Pull request merged**
