### PR TITLE
[SP-6084] Backport of PDI-19292 - ERROR messages related to LoggingRe…

### PR DESCRIPTION
**Pull request by ddiroma**
…gistry Purge keeps getting logged. (9.2 Suite)

### CODE REVIEW

**Comment by ddiroma** [comment]
@pentaho/tatooine Please approve

**Comment by buildguy** [comment]
### :x: Build failed in 2m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 1h 30m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 21 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransMetaTest.org.pentaho.di.trans.TransMetaTest</b> (click to expand)</summary><p>

```

Unable to read plugin xml file: {0}:
Type org.pentaho.di.core.encryption.TwoWayPasswordEncoderInterface not present

```

</p></details>

<details><summary><b>org.pentaho.di.www.CarteTest.callStopCarteRestService</b> (click to expand)</summary><p>

```
"No Carte Server found at localhost:8080
```

</p></details>

<details><summary><b>org.pentaho.di.connections.ui.ConnectionEndpointsTest.createConnection</b> (click to expand)</summary><p>

```

Unable to read plugin xml file: {0}:
Type org.pentaho.di.core.encryption.TwoWayPasswordEncoderInterface not present

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.metainject.MetaInjectMetaInjectionTest.org.pentaho.di.trans.steps.metainject.MetaInjectMetaInjectionTest</b> (click to expand)</summary><p>

```

Unable to read plugin xml file: {0}:
Type org.pentaho.di.core.encryption.TwoWayPasswordEncoderInterface not present

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.metainject.MetaInjectMetaLoadSaveTest.testSerialization</b> (click to expand)</summary><p>

```

Unable to read plugin xml file: {0}:
Type org.pentaho.di.core.encryption.TwoWayPasswordEncoderInterface not present

```

</p></details>

<details><summary><b>com.pentaho.di.messages.MessagesTest.testEncoding</b> (click to expand)</summary><p>

```
org/pentaho/platform/util/messages/MessagesBase
```

</p></details>

<details><summary><b>com.pentaho.di.messages.MessagesTest.testMessages</b> (click to expand)</summary><p>

```
org/pentaho/platform/util/messages/MessagesBase
```

</p></details>

<details><summary><b>com.pentaho.di.messages.MessagesTest.testErrorMessages</b> (click to expand)</summary><p>

```
org/pentaho/platform/util/messages/MessagesBase
```

</p></details>

<details><summary><b>com.pentaho.di.messages.MessagesTest.testBadKey</b> (click to expand)</summary><p>

```
org/pentaho/platform/util/messages/MessagesBase
```

</p></details>

<details><summary><b>com.pentaho.di.revision.RevisionResourceTest.testDummy</b> (click to expand)</summary><p>

```
org/pentaho/platform/util/RepositoryPathEncoder
```

</p></details>

<details><summary><b>com.pentaho.di.revision.RevisionResourceTest.testDoGetVersions</b> (click to expand)</summary><p>

```
org/pentaho/platform/util/RepositoryPathEncoder
```

</p></details>

<details><summary><b>com.pentaho.di.revision.RevisionResourceTest.testGetVersioningEnabled</b> (click to expand)</summary><p>

```
org/pentaho/platform/util/RepositoryPathEncoder
```

</p></details>

<details><summary><b>com.pentaho.repository.importexport.PDIImportUtilTest.testConnectToRepository</b> (click to expand)</summary><p>

```
org/pentaho/platform/engine/core/system/PentahoSystem
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.UserRoleDelegateTest.createRole_CreatesSuccessfully_WhenNameDiffersInCase</b> (click to expand)</summary><p>

```
org/pentaho/platform/core/mt/Tenant
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.UserRoleDelegateTest.createUser_ProhibitsToCreate_WhenNameCollides</b> (click to expand)</summary><p>

```
org/pentaho/platform/core/mt/Tenant
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.UserRoleDelegateTest.createRole_CreatesSuccessfully_WhenNameIsUnique</b> (click to expand)</summary><p>

```
org/pentaho/platform/core/mt/Tenant
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.UserRoleDelegateTest.createUser_CreatesSuccessfully_WhenNameIsUnique</b> (click to expand)</summary><p>

```
org/pentaho/platform/core/mt/Tenant
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.UserRoleDelegateTest.createRole_ProhibitsToCreate_WhenNameCollides</b> (click to expand)</summary><p>

```
org/pentaho/platform/core/mt/Tenant
```

</p></details>

<details><summary><b>org.pentaho.di.repository.pur.UserRoleDelegateTest.createUser_CreatesSuccessfully_WhenNameDiffersInCase</b> (click to expand)</summary><p>

```
org/pentaho/platform/core/mt/Tenant
```

</p></details>

<details><summary><b>org.pentaho.di.repository.utils.RepositoryFactoryTest.org.pentaho.di.repository.utils.RepositoryFactoryTest</b> (click to expand)</summary><p>

```
org/pentaho/platform/engine/core/system/StandaloneApplicationContext
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.s3csvinput.S3CsvInputMetaTest.testSerialization</b> (click to expand)</summary><p>

```
org/pentaho/support/utils/StringUtil
```

</p></details>

  
Tests run: **5119**, Failures: **21**, Skipped: **7** &nbsp;&nbsp; [Test Results](https://wingman.pentaho.net/job/projects/job/pdi-8/job/PR-8176/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
I'm closing this PR as the issue is still not assigned a specific SP.

**Comment by buildguy** [comment]
### :x: Build failed in 1m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by ddiroma** [comment]
Master PR: https://github.com/pentaho/pentaho-kettle/pull/8144

8.3 PR: https://github.com/pentaho/pentaho-kettle/pull/8175

9.2 PR: https://github.com/pentaho/pentaho-kettle/pull/8176

9.2.0.4 PR: https://github.com/pentaho/pentaho-kettle/pull/8320

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PR.

**Pull request merged**
