### PR TITLE
[PDI-14618] - Creating a connection from an open KTR or KJB when connected to repository allows to create connections with the same names (identical) or with the same names but with differ case

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- check uniqueness of name when adding and editing connection from step dialog
- add tests
- fix Checkstyle violations

@brosander, @mdamour1976, review it please. This is a worked version of #1970

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@brosander, review it please

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f ui/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  ui/src/org/pentaho/di/ui/trans/step/BaseStepDialog.java
  ui/test-src/org/pentaho/di/ui/trans/step/BaseStepDialog_ConnectionLine_Test.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File ui/src/org/pentaho/di/ui/trans/step/BaseStepDialog.java
1. Message: '<' is not followed by whitespace. at Line: 1016 Column: 10
2. Message: '<' is not followed by whitespace. at Line: 1016 Column: 39
3. Message: '<' is not preceded with whitespace. at Line: 1016 Column: 38
4. Message: '<' is not preceded with whitespace. at Line: 1016 Column: 9
5. Message: '>' is not followed by whitespace. at Line: 1016 Column: 46
6. Message: '>' is not preceded with whitespace. at Line: 1016 Column: 16
7. Message: '>' is not preceded with whitespace. at Line: 1016 Column: 45
8. Message: '<' is not followed by whitespace. at Line: 1145 Column: 55
9. Message: '<' is not preceded with whitespace. at Line: 1145 Column: 54
10. Message: '>' is not preceded with whitespace. at Line: 1145 Column: 76
11. Message: '<' is not followed by whitespace. at Line: 1155 Column: 10
12. Message: '<' is not preceded with whitespace. at Line: 1155 Column: 9
13. Message: '>' is not preceded with whitespace. at Line: 1155 Column: 31
14. Message: '<' is not followed by whitespace. at Line: 383 Column: 18
15. Message: '<' is not followed by whitespace. at Line: 383 Column: 56
16. Message: '<' is not preceded with whitespace. at Line: 383 Column: 17
17. Message: '<' is not preceded with whitespace. at Line: 383 Column: 55
18. Message: '>' is not followed by whitespace. at Line: 383 Column: 66
19. Message: '>' is not preceded with whitespace. at Line: 383 Column: 27
20. Message: '>' is not preceded with whitespace. at Line: 383 Column: 65
21. Message: '<' is not followed by whitespace. at Line: 409 Column: 72
22. Message: '<' is not preceded with whitespace. at Line: 409 Column: 71
23. Message: '>' is not preceded with whitespace. at Line: 409 Column: 81
24. Message: '<' is not followed by whitespace. at Line: 592 Column: 55
25. Message: '<' is not preceded with whitespace. at Line: 592 Column: 54
26. Message: '>' is not preceded with whitespace. at Line: 592 Column: 82
27. Message: '?' is not preceded with whitespace. at Line: 592 Column: 55
28. Message: '<' is not followed by whitespace. at Line: 638 Column: 42
29. Message: '<' is not preceded with whitespace. at Line: 638 Column: 41
30. Message: '>' is not preceded with whitespace. at Line: 638 Column: 69
31. Message: '?' is not preceded with whitespace. at Line: 638 Column: 42
32. Message: '<' is not followed by whitespace. at Line: 677 Column: 76
33. Message: '<' is not preceded with whitespace. at Line: 677 Column: 75
34. Message: '>' is not preceded with whitespace. at Line: 677 Column: 103
35. Message: '?' is not preceded with whitespace. at Line: 677 Column: 76
36. Message: '<' is not followed by whitespace. at Line: 98 Column: 24
37. Message: '<' is not preceded with whitespace. at Line: 98 Column: 23
38. Message: '>' is not preceded with whitespace. at Line: 98 Column: 25
39. Message: '?' is not followed by whitespace. at Line: 98 Column: 25
40. Message: '?' is not preceded with whitespace. at Line: 98 Column: 24

File ui/test-src/org/pentaho/di/ui/trans/step/BaseStepDialog_ConnectionLine_Test.java
1. Message: '<' is not followed by whitespace. at Line: 142 Column: 61
2. Message: '<' is not preceded with whitespace. at Line: 142 Column: 60
3. Message: '>' is not preceded with whitespace. at Line: 142 Column: 67









Unit test coverage change:
============
org.pentaho.di.ui.trans.step.BaseStepDialog.AddConnectionListener:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.ui.trans.step.BaseStepDialog:
 * instructionPercentCoverageChange : +0.46%
 * branchPercentCoverageChange :**-0.04%**
 * linePercentCoverageChange : +0.81%
 * complexityPercentCoverageChange : +0.63%
 * methodPercentCoverageChange : +1.45%
    
org.pentaho.di.ui.trans.step.BaseStepDialog.EditConnectionListener:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :75.00%
 * instructionPercentCoverage :100.00%

**Comment by akhayrutdinov** [comment]
@brosander, review it please.
/cc @pamval

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f ui/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  ui/src/org/pentaho/di/ui/trans/step/BaseStepDialog.java
  ui/test-src/org/pentaho/di/ui/trans/step/BaseStepDialog_ConnectionLine_Test.java










Unit test coverage change:
============
org.pentaho.di.ui.trans.step.BaseStepDialog.AddConnectionListener:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.ui.trans.step.BaseStepDialog:
 * instructionPercentCoverageChange : +0.46%
 * branchPercentCoverageChange :**-0.04%**
 * linePercentCoverageChange : +0.81%
 * complexityPercentCoverageChange : +0.63%
 * methodPercentCoverageChange : +1.45%
    
org.pentaho.di.ui.trans.step.BaseStepDialog.EditConnectionListener:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :75.00%
 * instructionPercentCoverage :100.00%

**Pull request merged**
