### PR TITLE
[BACKLOG-35992][BACKLOG-35993] Changing some BaseStepDialog methods t…

### PR DESCRIPTION
**Pull request by ddiroma**
…o public for use in JDBC MetadataDiscovery new step in PDI

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 9m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 6m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 3m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by peterrinehart — APPROVED** [review]

**Pull request merged**
