### PR TITLE
fix: DET pivot table will not render data [BACKLOG-39840]

### PR DESCRIPTION
**Pull request by davidmsantos90**
By default SWT will launch internet explorer 11 on Windows, that is no longer supported by Windows and also Pentaho, and on top of that it  doesn't support ES6+ javascript sintax that was introduced in the Analyzer code, used by DET. This was fixed by forcing SWT to use Edge (the default browser in Windows)

@pentaho/millenniumfalcon please review

 - Edge version was taken from [here](https://help.hitachivantara.com/Documentation/Pentaho/Data_Integration_and_Analytics/10.0/Setup/Components_Reference#Web_browsers)
 - a follow up improvement to this story should be created, to update the SWT version used by kettle and its plugins.

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 5m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/static,ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 4m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/static,ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 30m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/static,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1429**, Failures: **0**, Skipped: **6** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9182/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 26m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/core/static,assemblies/static,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1429**, Failures: **0**, Skipped: **6** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9182/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by mbrasil — APPROVED** [review]

**Review by afrjorge — APPROVED** [review]

**Pull request merged**
