### PR TITLE
[PDI-14250] SFTP Put step corrupts file data when "Input is a stream" option is used

### PR DESCRIPTION
**Pull request by Advent51**
- SFTPPut step was modified in order to work with input stream as with binary array

### CODE REVIEW

**Comment by Advent51** [comment]
@pamval @mchen-len-son @mbatchelor @bmorrise please review

**Comment by Advent51** [comment]
@pamval @mchen-len-son @mbatchelor @bmorrise please review

**Comment by Advent51** [comment]
@pamval @mbatchelor @duarteteixeira @smaring please review

**Comment by mchen-len-son** [comment]
@pamval @mbatchelor can you please take a look?

**Comment by Advent51** [comment]
@bmorrise @pamval please review

**Comment by Advent51** [comment]
@pamval @bmorrise @duarteteixeira @mbatchelor please review

**Pull request merged**
