### PR TITLE
[BISERVER-14442] - Database connections using connection pooling will not adhere to changes in the connection details

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@pentaho-lmartins 
@ssamora 
@ppatricio 
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 26m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.combinationlookup.CombinationLookupTest.testCombiInsert</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **4891**, Failures: **1**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7621/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ssamora — APPROVED** [review]

**Comment by buildguy** [comment]
### :warning: Build finished in 24m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.combinationlookup.CombinationLookupTest.testCombiInsert</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **4891**, Failures: **1**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7621/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 27m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.combinationlookup.CombinationLookupTest.testCombiInsert</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **4891**, Failures: **1**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7621/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 26m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.combinationlookup.CombinationLookupTest.testCombiInsert</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **4891**, Failures: **1**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7621/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 26m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.combinationlookup.CombinationLookupTest.testCombiInsert</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **4891**, Failures: **1**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7621/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bcostahitachivantara** [comment]
Problems with current branch

**Pull request closed without merging**
