### PR TITLE
[BACKLOG-5676] Update the toolbar UI/Actions Menu with a Run/Run Opti…

### PR DESCRIPTION
**Pull request by ddiroma**
…ons menu AND ran checkstyle @mdamour1976

### CODE REVIEW

**Comment by lucboudreau** [comment]
A couple comments on this PR. 

 - The cosmetic changes are included with the actual code changes. This makes it hard to see what changed. Please decouple them, or provide clear indications as to what the changes are.

 - I think (might be wrong) some of these changes are cosmetic and caused by an auto formatter in your IDE. We prefer not to make changes unless checkstyle was complaining about the formatting, since it wipes out the original commit associated to these lines.

 - We do not leave commented out code behind. I see a couple places where the code was commented out. Please remove altogether the code that is not is use.

**Comment by ddiroma** [comment]
After I make these corrections, can I just create a new pull request and we can cancel this one?

**Comment by lucboudreau** [comment]
Whichever you prefer.

**Comment by ddiroma** [comment]
I'll create a new PR, thx.

**Pull request closed without merging**
