### PR TITLE
[BACKLOG-2176]

### PR DESCRIPTION
**Pull request by diogofscmariano**
- Reviewed the dialect extension added in the context of the SAP Hana dialect implementation.
- Added new DatabaseInterfaceExtended, marked as deprecated, adding the new methods and extended from DatabaseInterface
- Reviewed steps
- Reviewed unit tests

### CODE REVIEW

**Comment by diogofscmariano** [comment]
@mattyb149 @dkincade @pentaho-nbaker @pamval please review. I updated the pull request with the last suggestions

**Comment by brosander** [comment]
@diogofscmariano @dkincade removing those methods from BaseDatabaseMeta and DatabaseInterface will break any 3rd party implementors, do we have the green light to do this?

**Comment by diogofscmariano** [comment]
@brosander these methods were added by me in the same story and they need to be removed and added as a Deprecated Extended class because we can't change it in this release

**Comment by dkincade** [comment]
@pentaho-nbaker @mattyb149 please review....

**Comment by mattyb149** [comment]
Unit tests don't pass due to the missing class. I believe that was added in another PR so maybe rebase this one?

**Comment by diogofscmariano** [comment]
@mattyb149 pr rebased

**Comment by pamval** [comment]
@mattyb149 can you please review this pr. We need to get this in in order to run 5.4 validations

**Comment by mattyb149** [comment]
@brosander @pentaho-baker can one of you guys take this one? I'm on PTO and will be AFK until Monday

**Comment by brosander** [comment]
@mattyb149 looking at it

**Comment by brosander** [comment]
@diogofscmariano core/src/org/pentaho/di/core/database/DatabaseInterfaceExtended.java has checkstyle errors

**Comment by diogofscmariano** [comment]
@brosander pr updated. Can you please recheck?

**Comment by brosander** [comment]
@diogofscmariano please run checkstyle on your changes in engine, ui also
so far I've seen errors in
engine/src/org/pentaho/di/trans/steps/combinationlookup/CombinationLookup.java
engine/src/org/pentaho/di/trans/steps/dimensionlookup/DimensionLookup.java

**Comment by diogofscmariano** [comment]
@brosander pr updated. Check style applied to the changed lines

**Pull request merged**
