### PR TITLE
[PDI-19073] Checksum for Date and BigNumber in PDI 8.x and 9.x differ…

### PR DESCRIPTION
**Pull request by smmribeiro**
…ent despite same value and format

@ssamora @bcostahitachivantara @moraesvc

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 35m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.checksum.CheckSumMetaTest.testSerialization</b> (click to expand)</summary><p>

```
Error validating oldChecksumBehaviour
```

</p></details>

  
Tests run: **5075**, Failures: **1**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7945/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 34m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui
```
---
:ok_hand: All tests passed!
 
Tests run: **5087**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7945/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 35m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.checksum.CheckSumMetaTest.testGetEvaluationMethodDesc</b> (click to expand)</summary><p>

```
expected:<B[YTES]> but was:<B[yte Representation of fields (default behavior 8.1 forward)]>
```

</p></details>

  
Tests run: **5091**, Failures: **1**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7945/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 3m 2s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui
```
---
:ok_hand: All tests passed!
 
Tests run: **1755**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7945/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 34m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui
```
---
:ok_hand: All tests passed!
 
Tests run: **5091**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7945/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 32m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,engine,plugins/core/impl,plugins/core/ui
```
---
:ok_hand: All tests passed!
 
Tests run: **5094**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7945/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ssamora — APPROVED** [review]

**Pull request merged**
