### PR TITLE
PDI-19457 "PDI - Microsoft Excel Output Step Using Template Errors Regression

### PR DESCRIPTION
**Pull request by SreejaSridhar**
PDI-19457 "PDI - Microsoft Excel Output Step Using Template Errors - Regression": Correct Error message is displayed when different worksheet name is used in Template and output file.

### CODE REVIEW

**Comment by ddiroma** [comment]
@SreejaSridhar Was there already a different PR to fix the problem? https://jira.pentaho.com/browse/PDI-19457 is a regression bug where the functionality stopped working as it previously did. But this code change is only to log the error and not to change the functionality to behave as it did before the regression was introduced.

**Comment by SreejaSridhar** [comment]
Yes, this PR is only to log the right error message and not change functionality. 
The other sub-issues of the ticket have been dealt with by updating the documentation by raising another ticket for the same as mentioned in the comments section of the ticket.
Kindly review the PR.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 20m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 19m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request closed without merging**
