### PR TITLE
[PDI-13637] NPE when running looping transformation - at org.pentaho.di.core.gui.JobTracker.getJobTracker(JobTracker.java:125)

### PR DESCRIPTION
**Pull request by akhayrutdinov**
@mattyb149, @brosander, review it please.

I've put two commits into this PR. The first is the fix itself with several tests.
The second is a kind of refactoring in tests. I noticed, that both concurrent tests have similar runners. Thus it makes sense to generalise it, separating runner from tests logic.

### CODE REVIEW

**Comment by brosander** [comment]
@akhayrutdinov if we're going to leave getJobTrackers() in the class, we should make it possible to synchronize access to the list

Before you could synchronize on the JobTracker object.  We may want to add a getter for the lock and deprecate it with a javadoc in getJobTrackers to make sure you use the lock for access.

**Comment by akhayrutdinov** [comment]
@brosander, I would better remove the method at all, than reveal the lock outside. In Kettle, it is used only in tests now. Do you think it is acceptable to replace its behaviour to returning a defensive copy?

**Comment by brosander** [comment]
@akhayrutdinov I think that's a good option, leave signature the same as before but return a defensive copy when called, if someone really needs to modify the returned list, they can do so with the set method

**Comment by akhayrutdinov** [comment]
@brosander, I've updated the PR

**Pull request merged**
