### PR TITLE
[BACKLOG-9351] Ensure default values for publishing to a server fall …

### PR DESCRIPTION
**Pull request by pdesai16**
…in line with Pentaho Server's hostname and port

- Changed the default-url in pdi from http://localhost:9080/pentaho-di to http://localhost:8080/pentaho
- Made the similar changes in sample transformation

### CODE REVIEW

**Comment by pdesai16** [comment]
@pentaho/rogueone  Please review

**Comment by pedrofvteixeira** [comment]
@pdesai16 this PR and https://github.com/pentaho/pentaho-kettle/pull/2818 will tackle all of the pdi-client needs as far as updating it to mention the new Pentaho Server, correct ?

PR looks good to me and wingman gave us its 👍

**Comment by pdesai16** [comment]
Yes, the other commit updates the default-url in repositories-plugin, so the new repository connection dialog in Spoon display the default url that points to pentaho server

**Comment by pedrofvteixeira** [comment]
PR is good. Merging.

**Pull request merged**
