### PR TITLE
[PDI-17469] add xugu database @date   : 06-June-2018

### PR DESCRIPTION
**Pull request by ouguan**
adding the new metadata of xugu database and the test class

### CODE REVIEW

**Comment by mbatchelor** [comment]
Hey Ouguan,

Thanks for the contribution. Before I can merge this in, please point me to the "xugu" database main page so I can have a look at their documentation. Thanks!

**Comment by ouguan** [comment]
Hey mbatchelor,

I'm from xugu, if you want any documents or references, Please provide a mail address that I could give you some stuff!
PS: All our stuff are write in chinese. :)
Thanks!

**Comment by mbatchelor** [comment]
Hey Ouguan,
Sorry for the delay. Could you please create an Improvement case at https://jira.pentaho.com in the PDI project for this? Please attach some documents and provide your web page so we can evaluate it for inclusion. No problem with Chinese information as we have plenty of people on staff that can read and interpret the information.

**Comment by ouguan** [comment]
I have created an improved case on https://jira.pentaho.com in the PDI project and gave the page of xugu where you can download our products and documentation. I hope these pages can help you understand us,thank you for your reply

**Comment by ouguan** [comment]
[xugu website](http://xuguweiye.d19.3eok.com/)

**Comment by mdamour1976** [comment]
I believe this is the JIRA case logged for this.

https://jira.pentaho.com/browse/PDI-17469

**Comment by ouguan** [comment]
yes

**Comment by jbleuel** [comment]
Can we get this database added to the marketplace (instead of into core)? see https://github.com/pentaho/marketplace-metadata

**Comment by ouguan** [comment]
Of course, you can. If we have updates in the future, what do we need to do?

**Comment by buildguy** [comment]
### :gear: Build finished in 16m 4s with command:
```
mvn clean verify -B -e -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|4637|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-5441/6/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by jbleuel** [comment]
We have no immediate plans to add this database to our core. Please add this database to the marketplace (instead of into core), see https://github.com/pentaho/marketplace-metadata . You can maintain it on your own and also provide updates when needed.

**Pull request closed without merging**
