### PR TITLE
[PDI-11014] - Error Fields not passed from Select Values step (when erro...

### PR DESCRIPTION
**Pull request by akhayrutdinov**
...r handling is enabled)

- pass field's name to the error row
- add a test
- apply formatting

@mattyb149, @brosander, review it please

### CODE REVIEW

**Comment by mattyb149** [comment]
The unit tests should include the KettleConversionException path(s) as these are new, and also it looks like the binary-to-normal storage logic was inverted/changed a bit, we should have unit tests for that path as well.

**Comment by akhayrutdinov** [comment]
Thanks, Matt!
As for the exception - I'll add such case.
As for logic - the behaviour is keeped, but the code is slightly changed.
It was:
```
if (cond1) {
  rowData[index] = something
}
if (cond2) {
  rowData[index] = yet another something
}
```

So, I introduced an else branch to avoid extra operations.
```
if (cond2) {
  rowData[index] = yet another something
} else if (cond1) {
  rowData[index] = something
}
```
I inverted the order to keep copatibility with the previous behaviour: if it somehow both conditions were truth, then the second assignment overwrote the first; thus it preceedes the first now

**Comment by akhayrutdinov** [comment]
@mattyb149,
I've update the PR. Could you please take a look?

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please :)

**Pull request merged**
