### PR TITLE
[PDI-14413] Step Synchronize after merge - issue with mode "use batch…

### PR DESCRIPTION
**Pull request by SergeyTravin**
… update"

- batch will be executed after last row readed, independet from batch size.

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@tgf, @pamval, could you please start WM?

**Comment by pamval** [comment]
started wingman

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMerge.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchMockDriver.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeTest.java










Unit test coverage change:
============
org.pentaho.di.trans.Trans:
 * instructionPercentCoverageChange : +0.96%
 * branchPercentCoverageChange : +0.91%
 * linePercentCoverageChange : +1.03%
 * complexityPercentCoverageChange : +0.71%
 * methodPercentCoverageChange : +2.39%
    
org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeMeta:
 * instructionPercentCoverageChange : +1.34%
 * linePercentCoverageChange : +2.42%
 * complexityPercentCoverageChange : +8.76%
 * methodPercentCoverageChange : +21.43%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange : +0.53%
    
org.pentaho.di.trans.Trans.new StepAdapter() {...}:
 * linePercentCoverage :66.67%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :73.08%
    
org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMerge:
 * instructionPercentCoverageChange : +44.59%
 * branchPercentCoverageChange : +38.57%
 * linePercentCoverageChange : +47.39%
 * complexityPercentCoverageChange : +20.00%
 * methodPercentCoverageChange : +50.00%
    
org.pentaho.di.trans.step.RunThread:
 * branchPercentCoverage :26.00%
 * linePercentCoverage :57.14%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :21.43%
 * instructionPercentCoverage :30.04%
    
org.pentaho.di.trans.steps.injector.Injector:
 * branchPercentCoverage :75.00%
 * instructionPercentCoverageChange : +44.68%
 * linePercentCoverageChange : +63.64%
 * complexityPercentCoverageChange : +40.00%
 * methodPercentCoverageChange : +33.33%
    
org.pentaho.di.trans.Trans.new StepListener() {...}:
 * branchPercentCoverage :37.50%
 * linePercentCoverage :44.00%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :42.86%
 * instructionPercentCoverage :31.16%
    
org.pentaho.di.trans.step.BaseStepData:
 * instructionPercentCoverageChange : +4.17%
 * linePercentCoverageChange : +7.14%
 * complexityPercentCoverageChange : +5.56%
 * methodPercentCoverageChange : +9.09%
    
org.pentaho.di.trans.TransMeta:
 * instructionPercentCoverageChange : +0.04%
 * linePercentCoverageChange : +0.10%
 * complexityPercentCoverageChange : +0.12%
 * methodPercentCoverageChange : +0.37%
    
org.pentaho.di.trans.step.StepInitThread:
 * instructionPercentCoverageChange :**-13.07%**
 * branchPercentCoverageChange :**-25.00%**
 * linePercentCoverageChange :**-6.25%**
 * complexityPercentCoverageChange :**-8.33%**
    
org.pentaho.di.trans.step.BaseStep:
 * instructionPercentCoverageChange : +1.76%
 * branchPercentCoverageChange : +3.55%
 * linePercentCoverageChange : +1.96%
 * complexityPercentCoverageChange : +2.73%
 * methodPercentCoverageChange : +2.93%
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange : +7.14%
 * complexityPercentCoverageChange : +7.69%
    
org.pentaho.di.trans.step.StepAdapter:
 * linePercentCoverage :33.33%
 * methodPercentCoverage :33.33%
 * complexityPercentCoverage :33.33%
 * instructionPercentCoverage :60.00%

**Comment by SergeyTravin** [comment]
@akhayrutdinov, The PR was updated according your notes from

**Comment by akhayrutdinov** [comment]
@SergeyTravin, to make the test be integration, you need to rename it to follow the convention, namely to end with `IT`. There is no need in moving it the the root project (those tests are not executed).

**Comment by SergeyTravin** [comment]
@akhayrutdinov,  Have you got a chance to look on it again? Thanks!

**Comment by lucboudreau** [comment]
A few comments on this PR.

 - There is a 13% drop of coverage in StepInitThread. This should have been either addressed, or a comment explaining why it can't should be present on the PR.

 - The coverage target for new files is 80%. None of the new files in this PR reach this threshold.

**Comment by pamval** [comment]
@SergeyTravin @akhayrutdinov please address Luc's concerns.

**Pull request merged**
