### PR TITLE
[PDI-18028] Kitchen export fails for Concat Fields step

### PR DESCRIPTION
**Pull request by smmribeiro**
ConcatFieldsMeta extends TextFileOutputMeta, the reason seeming to be the reuse several fields (like Separator, Enclosure, Header, Footer, etc.).
The problem (aroused by this issue) is that ConcatFields doesn't need all of those fields, specially the 'file' field (that, when persisting, has some specific handling by TextFileOutputMeta).

While the overrided methods would be enough to fix the persistence behaviour that originates the problem, setters are invoked a few times on several locations as a guarantee of the state of the field and to ensure that previously persisted ConcatFields' steps are read correctly.

@pentaho/r2d2 @bmorrise 
@pentaho/tatooine @pentaho-lmartins

### CODE REVIEW

**Comment by buildguy** [comment]
### :gear: Build finished in 1m 50s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl plugins/core/impl
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|57|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6893/1/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 34s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl plugins/core/impl
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|57|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6893/2/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 1m 43s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl plugins/core/impl
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|58|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6893/3/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
> Please write some unit tests that exercise the new code.

Unit tests added (IntelliJ reports 73% method and 60% line coverage for ConcatFieldsMeta; all newly added code is covered).

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 47s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl plugins/core/impl
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|58|0|1|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6893/4/testReport)|
|----|

:information_source:  _This is an automatic message_

**Pull request merged**
