### PR TITLE
[PDI-12814] Need to prohibit empty names when adding new users or roles

### PR DESCRIPTION
**Pull request by MikhailHubanau**
[PDI-12814](http://jira.pentaho.com/browse/PDI-12814) has UX Feedback with two requirement items.
This PR fixes issue but implements only second item of UX Feedback (first item is still need to be implemented). 
Also it should be noted that this PR implements "Dialog Button: Close" requirement (from second UX item) but org.eclipse.swt.widgets.MessageBox (which is used for dialog) does not support button name changes (always will be "OK"). So if we use current MessageBox as dialog base "Dialog Button: Close" implementation will not be visible.

### CODE REVIEW

**Comment by MikhailHubanau** [comment]
EE https://github.com/pentaho/pdi-ee-plugin/pull/287

**Comment by MikhailHubanau** [comment]
@dkincade @mbatchelor Could you please review?

**Comment by dkincade** [comment]
@mattyb149 @rmansoor @pentaho-nbaker please review or pass along to others

**Comment by MikhailHubanau** [comment]
Added.

**Pull request merged**
