### PR TITLE
[PDI-15821] java.lang.ArrayIndexOutOfBoundsException with metadata injection and microsoft excel input step

### PR DESCRIPTION
**Pull request by Advent51**
- new fix

### CODE REVIEW

**Comment by Advent51** [comment]
@mbatchelor please review.
This is the same fix, but with changed behavior of setDefault() method.
If you have any objections - please let me know.
If this is a **completely wrong** fix, please explain why.

**Comment by pamval** [comment]
@mdamour1976 @wseyler @e-cuellar please review

**Comment by Advent51** [comment]
@mdamour1976 please review

**Comment by mbatchelor** [comment]
@Advent51 - please rebase. Thanks!

**Comment by Advent51** [comment]
@mbatchelor please review

**Comment by Advent51** [comment]
@mdamour1976 @mbatchelor please review

**Pull request merged**
