### PR TITLE
[TAP-5819] Webspoon integration into Pentaho base code - pentaho-kett…

### PR DESCRIPTION
**Pull request by angel-ramoscardona**
…le/plugins/get-fields/core

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/get-fields/core
```
---
:ok_hand: All tests passed!
 
Tests run: **5**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-8146/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/get-fields/core
```
---
:ok_hand: All tests passed!
 
Tests run: **5**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-8146/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/get-fields/core
```
---
:ok_hand: All tests passed!
 
Tests run: **5**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-8146/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/get-fields/core
```
---
:ok_hand: All tests passed!
 
Tests run: **5**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-8146/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by rmansoor — APPROVED** [review]

**Pull request merged**
