### PR TITLE
[PDI-14641] - Unable to rename database connection

### PR DESCRIPTION
**Pull request by AndreyBurikhin**
@mdamour1976 please review

### CODE REVIEW

**Comment by mdamour1976** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f ui/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  ui/src/org/pentaho/di/ui/cluster/dialog/ClusterSchemaDialog.java
  ui/src/org/pentaho/di/ui/cluster/dialog/SlaveServerDialog.java
  ui/src/org/pentaho/di/ui/partition/dialog/PartitionSchemaDialog.java
  ui/src/org/pentaho/di/ui/spoon/delegates/SpoonDBDelegate.java
  ui/src/org/pentaho/di/ui/util/DialogUtils.java

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File ui/src/org/pentaho/di/ui/cluster/dialog/ClusterSchemaDialog.java
1. Message: Line has trailing spaces. at Line: 127 Column: None
2. Message: '>' is followed by whitespace. at Line: 129 Column: 58
3. Message: Line has trailing spaces. at Line: 467 Column: None
4. Message: Line has trailing spaces. at Line: 79 Column: None

File ui/src/org/pentaho/di/ui/cluster/dialog/SlaveServerDialog.java
1. Message: Avoid nested blocks. at Line: 375 Column: 5
2. Message: Avoid nested blocks. at Line: 387 Column: 5
3. Message: Line has trailing spaces. at Line: 527 Column: None
4. Message: Line has trailing spaces. at Line: 540 Column: None
5. Message: Line has trailing spaces. at Line: 80 Column: None

File ui/src/org/pentaho/di/ui/partition/dialog/PartitionSchemaDialog.java
1. Message: Line has trailing spaces. at Line: 111 Column: None
2. Message: Line has trailing spaces. at Line: 348 Column: None
3. Message: Line has trailing spaces. at Line: 81 Column: None

File ui/src/org/pentaho/di/ui/spoon/delegates/SpoonDBDelegate.java
1. Message: '(' is not followed by whitespace. at Line: 93 Column: 11
2. Message: ')' is not preceded with whitespace. at Line: 93 Column: 139

File ui/src/org/pentaho/di/ui/util/DialogUtils.java
1. Message: Line has trailing spaces. at Line: 53 Column: None


License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.di.ui.util.DialogUtils:
 * instructionPercentCoverageChange :**-2.47%**
 * branchPercentCoverageChange :**-6.94%**
 * complexityPercentCoverageChange :**-4.55%**

**Comment by AndreyBurikhin** [comment]
@mdamour1976 updated

**Comment by mdamour1976** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f ui/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  ui/src/org/pentaho/di/ui/cluster/dialog/ClusterSchemaDialog.java
  ui/src/org/pentaho/di/ui/cluster/dialog/SlaveServerDialog.java
  ui/src/org/pentaho/di/ui/partition/dialog/PartitionSchemaDialog.java
  ui/src/org/pentaho/di/ui/spoon/delegates/SpoonDBDelegate.java
  ui/src/org/pentaho/di/ui/util/DialogUtils.java
  ui/test-src/org/pentaho/di/ui/util/DialogUtilsTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File ui/src/org/pentaho/di/ui/cluster/dialog/SlaveServerDialog.java
1. Message: Line has trailing spaces. at Line: 537 Column: None









Unit test coverage change:
============
org.pentaho.di.ui.util.DialogUtils:
 * instructionPercentCoverageChange : +35.89%
 * branchPercentCoverageChange : +31.94%
 * linePercentCoverageChange : +35.29%
 * complexityPercentCoverageChange : +28.79%
 * methodPercentCoverageChange : +33.33%

**Comment by mdamour1976** [comment]
The only violation now is on lines not touched by the commit, I'm going to merge it.

**Pull request merged**
