### PR TITLE
[PDI-15704] Mail Send (transformation) step fails when receive the pa…

### PR DESCRIPTION
**Pull request by LeonardoCoelho71950**
…rameter that contains an encrypted password.

@pentaho-lmartins @ssamora 
@pentaho/tatooine 

Mail step didn't handle an encrypted password.

### CODE REVIEW

**Comment by buildguy** [comment]
### :gear: Build finished in 14m 50s with command:
```
mvn clean verify -B -e -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3532|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6870/1/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 20m 21s with command:
```
mvn clean verify -B -e -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3530|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6870/2/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by pamval** [comment]
Is there a reason for not having an unit test along with this change?

**Comment by buildguy** [comment]
### :gear: Build finished in 24m 6s with command:
```
mvn clean verify -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl engine
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 11 test(s) failed:
- **org.pentaho.di.trans.StepWithMappingMetaTest.loadMappingMeta**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.trans.StepWithMappingMetaTest.loadMappingMetaTest**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.trans.StepWithMappingMetaTest.testFileNameAsVariable**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.trans.TransMetaTest.testSetInternalEntryCurrentDirectoryWithRepository**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.trans.TransMetaTest.testLoadXml**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.trans.TransMetaTest.testTransWithOneStepIsConsideredUsed**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTest**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTestCantFindDirectory**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTestJobNotFoundInDirectory**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTestCantFindRepository**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
- **org.pentaho.di.www.ExecuteJobServletTest.testExecuteJobServletTestWithUnauthorizedUser**
```
    javassist.CannotCompileException: by java.util.zip.ZipException: invalid distance too far back
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|3539|11|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6870/4/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 10m 4s with command:
```
mvn clean verify -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3541|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6870/5/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 20m 54s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3541|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6870/6/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 20m 39s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3541|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6870/7/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 22m 5s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3541|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6870/8/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 21m 45s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl engine
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3540|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6870/9/testReport)|
|----|

:information_source:  _This is an automatic message_

**Pull request merged**
