### PR TITLE
 [PDI-15032] - Metadata Injection on all tabs of select values step is causing error - fix getters

### PR DESCRIPTION
**Pull request by AndreyBurikhin**
@mkambol please review.
I decided to stay with -2 "magic number" and just added constant for it. Of course I could replace int[] with array of objects (integers), but I think it better to stay it "as is". It worked this way before my changes, so it would work the same after them.

(I executed tests for pdi-dataservice-server-plugin and all tests from SqlTransGeneratorTest passed successfully. Let me know if other tests were broken and i didn't fix it them)

### CODE REVIEW

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/91/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMeta.java
  engine/test-src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMetaTest.java



Unit test coverage change:
============
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change : **-7.14%**
 * Complexity Change : **-7.69%**

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change : **-1.64%**
 * Line Change : **-1.94%**

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change : **-1.64%**
 * Complexity Change : **-.69%**
 * Instruction Change : **-2.43%**
 * Line Change : **-3.70%**

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Instruction Change :  + .08%

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Instruction Change : **-.07%**

org.pentaho.di.trans.steps.selectvalues.SelectValuesMeta:
 * Branch Change : **-3.21%**
 * Complexity Change : **-2.45%**
 * Instruction Change : **-1.64%**
 * Line Change : **-2.16%**

org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * Instruction Change :  + .18%

org.pentaho.di.trans.Trans:
 * Branch Change : **-.10%**
 * Complexity Change : **-.14%**
 * Instruction Change : **-.09%**
 * Line Change : **-.11%**



Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/engine/test-src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMetaTest.java

1. Message: Using a static member import should be avoided - org.pentaho.di.trans.steps.selectvalues.SelectValuesMeta.UNDEFINED. at Line: 26

**Comment by mkambol** [comment]
@AndreyBurikhin Can you address the checkstyle violation?  Thanks.

**Comment by AndreyBurikhin** [comment]
@mkambol  done. I thought that static import was allowed in tests, but seems I was wrong.

**Comment by mkambol** [comment]
I've made the same mistake.  Only certain static imports are allowed in tests-- there's a white list to allow most of the common junit/jmock static methods.

**Pull request merged**
