### PR TITLE
[PDI-14988] - Add option to disable interactive GSSAPI authentication

### PR DESCRIPTION
**Pull request by mchen-len-son**
- changed gssapi auth to be enabled depending on -D parameter
- added/fixed unit tests

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/job/entries/sftp/SFTPClient.java
  engine/test-src/org/pentaho/di/job/entries/sftp/SFTPClientTest.java



Unit test coverage change:
============
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change : **-7.14%**
 * Complexity Change : **-7.69%**

org.pentaho.di.job.entries.sftp.SFTPClient:
 * Branch Change :  + 2.65%
 * Complexity Change :  + 3.07%
 * Instruction Change :  + 1.87%
 * Line Change :  + 1.00%
 * Method Change :  + 3.31%

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.94%

org.pentaho.di.trans.step.StepMeta:
 * Instruction Change : **-.19%**
 * Line Change : **-.27%**

org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * Branch Change :  + 3.33%
 * Complexity Change :  + 1.85%
 * Instruction Change :  + .28%

org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * Branch Change : **-.53%**

**Comment by mchen-len-son** [comment]
@brosander @akhayrutdinov review please

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/job/entries/sftp/SFTPClient.java
  engine/test-src/org/pentaho/di/job/entries/sftp/SFTPClientTest.java



Unit test coverage change:
============
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change : **-7.14%**
 * Complexity Change : **-7.69%**

org.pentaho.di.job.entries.sftp.SFTPClient:
 * Branch Change :  + 2.65%
 * Complexity Change :  + 3.07%
 * Instruction Change :  + 1.87%
 * Line Change :  + 1.00%
 * Method Change :  + 3.31%

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.94%

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change :  + 1.64%
 * Complexity Change :  + .69%
 * Instruction Change :  + 2.43%
 * Line Change :  + 3.70%

org.pentaho.di.trans.steps.randomvalue.RandomValueMeta:
 * Branch Change : **-2.17%**
 * Complexity Change : **-2.17%**
 * Instruction Change : **-.15%**

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Instruction Change : **-.07%**

org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * Instruction Change :  + .18%

org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * Branch Change : **-3.33%**
 * Complexity Change : **-1.85%**
 * Instruction Change : **-.28%**

**Comment by brosander** [comment]
@mchen-len-son tests that set system properties should restore them to their original settings when done with them

**Comment by mchen-len-son** [comment]
@brosander, sure.
Added property removing to setUp and tearDown.
Thanks.

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/53/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  engine/src/org/pentaho/di/job/entries/sftp/SFTPClient.java
  engine/test-src/org/pentaho/di/job/entries/sftp/SFTPClientTest.java

Newly Broken Tests:
======================
org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeIT.testProcessRow_RowSizeEqualsCommitSize: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: Step still started expected:<Finished> but was:<Running>
	at org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeIT.processRow(SynchronizeAfterMergeIT.java:229)
	at org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeIT.testProcessRow_RowSizeEqualsCommitSize(SynchronizeAfterMergeIT.java:201)

```

Unit test coverage change:
============
org.pentaho.di.job.entries.sftp.SFTPClient:
 * Branch Change :  + 2.65%
 * Complexity Change :  + 3.07%
 * Instruction Change :  + 1.87%
 * Line Change :  + 1.00%
 * Method Change :  + 3.31%

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Instruction Change : **-.07%**

org.pentaho.di.trans.Trans:
 * Branch Change : **-.10%**
 * Complexity Change : **-.14%**
 * Instruction Change : **-.09%**
 * Line Change : **-.11%**



Integration test coverage change:
============
org.pentaho.di.trans.step.BaseStep:
 * Branch Change :  + .30%
 * Complexity Change :  + .36%
 * Instruction Change :  + .15%
 * Line Change :  + .23%
 * Method Change :  + .49%

org.pentaho.di.trans.step.BaseStepData.StepExecutionStatus:
 * Complexity Change :  + 16.67%
 * Instruction Change :  + 1.69%
 * Line Change :  + 6.25%
 * Method Change :  + 16.67%

**Comment by brosander** [comment]
Don't think test failure is related to this change, probably a race condition in org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeIT.testProcessRow_RowSizeEqualsCommitSize

**Pull request merged**
