### PR TITLE
[SP-6608] Backport of [PPP-4582] - Use of Vulnerable Component: Components/oauth_client_library_for_java (10.2 Suite)

### PR DESCRIPTION
**Pull request by singletonc**
Remove pdi-google-analytics-plugin and pentaho-googledrive-vfs-plugin from plugin assemblies

### CODE REVIEW

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[🚨 Frogbot scanned this pull request and found the below:](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>




---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

```
filename
```
at `core/src/main/java/org/pentaho/di/laf/OverlayProperties.java` (line 60)


[comment]: <> (FrogbotReviewComment)


## 🎯 Static Application Security Testing (SAST) Vulnerability
<div align='center'>

| Severity                | Finding                  |
| :---------------------: | :-----------------------------------: |
| <br>     Low | Untrusted stored value used in file paths, allowing access to unintended files |

</div>

<details>
<summary> <b>Full description</b> </summary>
<br>


### Overview
Path traversal, also known as directory traversal, is a type of
vulnerability that allows an attacker to access files or directories on a
computer or device that are outside of the intended directory.
Allowing arbitrary read access can allow the attacker to read sensitive
files, such as configuration files or sensitive data, potentially leading
data loss or even system compromise. Allowing arbitrary write access is
more severe and in most cases leads to arbitrary code execution, via
editing important system files or sensitive data.

### Vulnerable example
```java
public class path_traversaLvuln {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String DOCS_FOLDER = "/srv/www/docs";
        String docName = statement.executeQuery(query);  // Reading from DB
        Path docPath = Paths.get(DOCS_FOLDER, docName);
        File docFile = docPath.toFile();
        FileUtils.copyFile(docFile, response.getOutputStream());
    }
}
```
In this example, an attacker can, via a stored parameter, inject a back-path,
that will get anywhere in the system, using "../../".

### Remediation
```diff
public class path_traversal_safe {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String DOCS_FOLDER = "/srv/www/docs";
        String docName = statement.executeQuery(query);  // Reading from DB
        Path docPath = Paths.get(DOCS_FOLDER, docName);
+         Path normDocPath = docPath.normalize();
+         // Make sure the canonical path resides in the desired dir
+         if (normDocPath.startsWith(DOCS_FOLDER)) {
            File docFile = docPath.toFile();
            FileUtils.copyFile(docFile, response.getOutputStream());
+         }
    }
}
```
By checking that the folder name still starts with the predefined prefix, we
make sure that the attacker is not able to back-path outside of the allowed
folder.


</details>

<details>
<summary> <b>Code Flows</b> </summary>
<br>


<details>
<summary> <b>Vulnerable data flow analysis result</b> </summary>
<br>


↘️ `System.getProperty( variable, deflt )` (at core/src/main/java/org/pentaho/di/core/Const.java line 2634)

↘️ `return System.getProperty( variable, deflt );` (at core/src/main/java/org/pentaho/di/core/Const.java line 2634)

↘️ `Const.getEnvironmentVariable( "org.pentaho.di.laf.alt", null )` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 54)

↘️ `altFile` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 54)

↘️ `altFile` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 56)

↘️ `String filename` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 86)

↘️ `filename` (at core/src/main/java/org/pentaho/di/laf/OverlayPropertyHandler.java line 88)

↘️ `public class OverlayProperties extends Properties implements PropertyHandler {

  private static final long serialVersionUID = 1L;
  private String name = null;

  public OverlayProperties( String file ) throws IOException {
    load( file );
  }

  @Override
  public boolean exists( String filename ) {
    try {
      return ( getURL( filename ) != null );
    } catch ( MalformedURLException e ) {
      return false;
    }
  }

  @Override
  public boolean loadProps( String filename ) {
    try {
      return load( filename );
    } catch ( IOException e ) {
      return false;
    }
  }

  private URL getURL( String filename ) throws MalformedURLException {
    URL url;
    File file = new File( filename );
    if ( file.exists() ) {
      url = file.toURI().toURL();
    } else {
      ClassLoader classLoader = getClass().getClassLoader();
      url = classLoader.getResource( filename );
    }
    return url;
  }

  /**
   * cleanse and reload the property file
   *
   * @param filename
   * @return
   * @throws IOException
   */
  public boolean load( String filename ) throws IOException {
    URL url = getURL( filename );
    if ( url == null ) {
      return false;
    }
    clear();
    load( url.openStream() );
    return true;
  }

  public String getName() {
    return name;
  }
}` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 31)

↘️ `String file` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 36)

↘️ `file` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 37)

↘️ `String filename` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 77)

↘️ `filename` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 78)

↘️ `String filename` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 58)

↘️ `filename` (at core/src/main/java/org/pentaho/di/laf/OverlayProperties.java line 60)


</details>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

```
SYSTEM_FOLDER
```
at `plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java` (line 1483)


[comment]: <> (FrogbotReviewComment)


## 🎯 Static Application Security Testing (SAST) Vulnerability
<div align='center'>

| Severity                | Finding                  |
| :---------------------: | :-----------------------------------: |
| <br>     Low | Untrusted stored value used in file paths, allowing access to unintended files |

</div>

<details>
<summary> <b>Full description</b> </summary>
<br>


### Overview
Path traversal, also known as directory traversal, is a type of
vulnerability that allows an attacker to access files or directories on a
computer or device that are outside of the intended directory.
Allowing arbitrary read access can allow the attacker to read sensitive
files, such as configuration files or sensitive data, potentially leading
data loss or even system compromise. Allowing arbitrary write access is
more severe and in most cases leads to arbitrary code execution, via
editing important system files or sensitive data.

### Vulnerable example
```java
public class path_traversaLvuln {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String DOCS_FOLDER = "/srv/www/docs";
        String docName = statement.executeQuery(query);  // Reading from DB
        Path docPath = Paths.get(DOCS_FOLDER, docName);
        File docFile = docPath.toFile();
        FileUtils.copyFile(docFile, response.getOutputStream());
    }
}
```
In this example, an attacker can, via a stored parameter, inject a back-path,
that will get anywhere in the system, using "../../".

### Remediation
```diff
public class path_traversal_safe {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String DOCS_FOLDER = "/srv/www/docs";
        String docName = statement.executeQuery(query);  // Reading from DB
        Path docPath = Paths.get(DOCS_FOLDER, docName);
+         Path normDocPath = docPath.normalize();
+         // Make sure the canonical path resides in the desired dir
+         if (normDocPath.startsWith(DOCS_FOLDER)) {
            File docFile = docPath.toFile();
            FileUtils.copyFile(docFile, response.getOutputStream());
+         }
    }
}
```
By checking that the folder name still starts with the predefined prefix, we
make sure that the attacker is not able to back-path outside of the allowed
folder.


</details>

<details>
<summary> <b>Code Flows</b> </summary>
<br>


<details>
<summary> <b>Vulnerable data flow analysis result</b> </summary>
<br>


↘️ `System.getProperty( "file.separator" )` (at core/src/main/java/org/pentaho/di/core/Const.java line 164)

↘️ `FILE_SEPARATOR` (at core/src/main/java/org/pentaho/di/core/Const.java line 164)

↘️ `FILE_SEPARATOR` (at core/src/main/java/org/pentaho/di/core/Const.java line 3665)

↘️ `dir + FILE_SEPARATOR` (at core/src/main/java/org/pentaho/di/core/Const.java line 3665)

↘️ `dir + FILE_SEPARATOR + file` (at core/src/main/java/org/pentaho/di/core/Const.java line 3665)

↘️ `return dir + FILE_SEPARATOR + file;` (at core/src/main/java/org/pentaho/di/core/Const.java line 3665)

↘️ `Const
          .safeAppendDirectory( BasePropertyHandler.getProperty( "systemDirBase", "system/" ), "" )` (at plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java line 170)

↘️ `SYSTEM_FOLDER` (at plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java line 170)

↘️ `SYSTEM_FOLDER` (at plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java line 1483)


</details>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

```
dbDir
```
at `integration/src/it/java/org/pentaho/di/cluster/SlaveSequenceIT.java` (line 112)


[comment]: <> (FrogbotReviewComment)


## 🎯 Static Application Security Testing (SAST) Vulnerability
<div align='center'>

| Severity                | Finding                  |
| :---------------------: | :-----------------------------------: |
| <br>     Low | Untrusted stored value used in file paths, allowing access to unintended files |

</div>

<details>
<summary> <b>Full description</b> </summary>
<br>


### Overview
Path traversal, also known as directory traversal, is a type of
vulnerability that allows an attacker to access files or directories on a
computer or device that are outside of the intended directory.
Allowing arbitrary read access can allow the attacker to read sensitive
files, such as configuration files or sensitive data, potentially leading
data loss or even system compromise. Allowing arbitrary write access is
more severe and in most cases leads to arbitrary code execution, via
editing important system files or sensitive data.

### Vulnerable example
```java
public class path_traversaLvuln {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String DOCS_FOLDER = "/srv/www/docs";
        String docName = statement.executeQuery(query);  // Reading from DB
        Path docPath = Paths.get(DOCS_FOLDER, docName);
        File docFile = docPath.toFile();
        FileUtils.copyFile(docFile, response.getOutputStream());
    }
}
```
In this example, an attacker can, via a stored parameter, inject a back-path,
that will get anywhere in the system, using "../../".

### Remediation
```diff
public class path_traversal_safe {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String DOCS_FOLDER = "/srv/www/docs";
        String docName = statement.executeQuery(query);  // Reading from DB
        Path docPath = Paths.get(DOCS_FOLDER, docName);
+         Path normDocPath = docPath.normalize();
+         // Make sure the canonical path resides in the desired dir
+         if (normDocPath.startsWith(DOCS_FOLDER)) {
            File docFile = docPath.toFile();
            FileUtils.copyFile(docFile, response.getOutputStream());
+         }
    }
}
```
By checking that the folder name still starts with the predefined prefix, we
make sure that the attacker is not able to back-path outside of the allowed
folder.


</details>

<details>
<summary> <b>Code Flows</b> </summary>
<br>


<details>
<summary> <b>Vulnerable data flow analysis result</b> </summary>
<br>


↘️ `System.getProperty( "java.io.tmpdir" )` (at integration/src/it/java/org/pentaho/di/cluster/SlaveSequenceIT.java line 66)

↘️ `System.getProperty( "java.io.tmpdir" ) + "/"` (at integration/src/it/java/org/pentaho/di/cluster/SlaveSequenceIT.java line 66)

↘️ `System.getProperty( "java.io.tmpdir" ) + "/" + UUID.randomUUID().toString()` (at integration/src/it/java/org/pentaho/di/cluster/SlaveSequenceIT.java line 66)

↘️ `System.getProperty( "java.io.tmpdir" ) + "/" + UUID.randomUUID().toString() + "-slaveSeqTest-H2-DB"` (at integration/src/it/java/org/pentaho/di/cluster/SlaveSequenceIT.java line 66)

↘️ `dbDir` (at integration/src/it/java/org/pentaho/di/cluster/SlaveSequenceIT.java line 65)

↘️ `dbDir` (at integration/src/it/java/org/pentaho/di/cluster/SlaveSequenceIT.java line 112)


</details>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

```
new File( folderName + "/" + fileName + ".txt" )
```
at `integration/src/it/java/org/pentaho/di/TestUtilities.java` (line 242)


[comment]: <> (FrogbotReviewComment)


## 🎯 Static Application Security Testing (SAST) Vulnerability
<div align='center'>

| Severity                | Finding                  |
| :---------------------: | :-----------------------------------: |
| <br>     Low | Untrusted stored value used in file paths, allowing access to unintended files |

</div>

<details>
<summary> <b>Full description</b> </summary>
<br>


### Overview
Path traversal, also known as directory traversal, is a type of
vulnerability that allows an attacker to access files or directories on a
computer or device that are outside of the intended directory.
Allowing arbitrary read access can allow the attacker to read sensitive
files, such as configuration files or sensitive data, potentially leading
data loss or even system compromise. Allowing arbitrary write access is
more severe and in most cases leads to arbitrary code execution, via
editing important system files or sensitive data.

### Vulnerable example
```java
public class path_traversaLvuln {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String DOCS_FOLDER = "/srv/www/docs";
        String docName = statement.executeQuery(query);  // Reading from DB
        Path docPath = Paths.get(DOCS_FOLDER, docName);
        File docFile = docPath.toFile();
        FileUtils.copyFile(docFile, response.getOutputStream());
    }
}
```
In this example, an attacker can, via a stored parameter, inject a back-path,
that will get anywhere in the system, using "../../".

### Remediation
```diff
public class path_traversal_safe {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String DOCS_FOLDER = "/srv/www/docs";
        String docName = statement.executeQuery(query);  // Reading from DB
        Path docPath = Paths.get(DOCS_FOLDER, docName);
+         Path normDocPath = docPath.normalize();
+         // Make sure the canonical path resides in the desired dir
+         if (normDocPath.startsWith(DOCS_FOLDER)) {
            File docFile = docPath.toFile();
            FileUtils.copyFile(docFile, response.getOutputStream());
+         }
    }
}
```
By checking that the folder name still starts with the predefined prefix, we
make sure that the attacker is not able to back-path outside of the allowed
folder.


</details>

<details>
<summary> <b>Code Flows</b> </summary>
<br>


<details>
<summary> <b>Vulnerable data flow analysis result</b> </summary>
<br>


↘️ `System.getProperty( "java.io.tmpdir" )` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 213)

↘️ `System.getProperty( "java.io.tmpdir" ) + "/"` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 213)

↘️ `System.getProperty( "java.io.tmpdir" ) + "/" + folderName` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 213)

↘️ `System.getProperty( "java.io.tmpdir" ) + "/" + folderName + "_"` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 213)

↘️ `System.getProperty( "java.io.tmpdir" ) + "/" + folderName + "_" + System.currentTimeMillis()` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 213)

↘️ `absoluteFolderPath` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 212)

↘️ `absoluteFolderPath` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 216)

↘️ `TestUtilities.createTempFolder( "testLocalFileCopy_source" )` (at integration/src/it/java/org/pentaho/di/job/entries/copyfiles/CopyFilesIT.java line 64)

↘️ `sourceFolder` (at integration/src/it/java/org/pentaho/di/job/entries/copyfiles/CopyFilesIT.java line 64)

↘️ `sourceFolder` (at integration/src/it/java/org/pentaho/di/job/entries/copyfiles/CopyFilesIT.java line 72)

↘️ `String folderName` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 239)

↘️ `folderName` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 242)

↘️ `folderName + "/"` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 242)

↘️ `folderName + "/" + fileName` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 242)

↘️ `folderName + "/" + fileName + ".txt"` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 242)

↘️ `new File( folderName + "/" + fileName + ".txt" )` (at integration/src/it/java/org/pentaho/di/TestUtilities.java line 242)


</details>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Review by rmansoor — APPROVED** [review]

**Comment by rmansoor** [comment]
@smmribeiro This PR can be merged for 10.2.0.1 now

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[🚨 Frogbot scanned this pull request and found the below:](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>




---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

```
out.println( new WebResult( WebResult.STRING_ERROR, message ) )
```
at `engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java` (line 223)


[comment]: <> (FrogbotReviewComment)


## 🎯 Static Application Security Testing (SAST) Vulnerability
<div align='center'>

| Severity                | Finding                  |
| :---------------------: | :-----------------------------------: |
| <br>    High | Untrusted input is included in web page content |

</div>

<details>
<summary> <b>Full description</b> </summary>
<br>


### Overview
XSS, or Cross-Site Scripting, is a type of vulnerability that allows an attacker to
inject malicious code into a website or web application.
This can allow the attacker to steal sensitive information from users, such as their
cookies or login credentials, or to perform unauthorized actions on their behalf.

### Vulnerable example
```java
public class xss_vuln {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String username = request.getParameter("username");
        //If username exists in the db - do something and write a response
        //if it doesn't exists -
        response.getWriter().println("Unable to find user " + username);
        response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
    }
}
```
In this example, a user-provided data is injected directly into the
`response.getWriter().println` command.

### Remediation
```diff
+ import org.owasp.html.HtmlPolicyBuilder;
+ import org.owasp.html.PolicyFactory;
public class xss_safe {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String username = request.getParameter("username");
        //If username exists in the db - do something and write a response
        //if it doesn't exists -
        + PolicyFactory policy = new HtmlPolicyBuilder().toFactory();
        + String htmlResponse = policy.sanitize("Unable to find user " + username);
        + response.getWriter().println(htmlResponse);
        - response.getWriter().println("Unable to find user " + username);
        response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
    }
}
```
Using `PolicyFactory` library, we escape the user-provided data, before
getting into the `response.getWriter().println` command.


</details>

<details>
<summary> <b>Code Flows</b> </summary>
<br>


<details>
<summary> <b>Vulnerable data flow analysis result</b> </summary>
<br>


↘️ `request.getParameter( "id" )` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 159)

↘️ `id` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 159)

↘️ `id` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 221)

↘️ `String source` (at core/src/main/java/org/pentaho/di/core/Const.java line 2718)

↘️ `source` (at core/src/main/java/org/pentaho/di/core/Const.java line 2722)

↘️ `Const.NVL( id, "" )` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 221)

↘️ `"The specified transformation ["
              + transName + "] with id [" + Const.NVL( id, "" )` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 220)

↘️ `"The specified transformation ["
              + transName + "] with id [" + Const.NVL( id, "" ) + "] could not be found"` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 220)

↘️ `message` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 219)

↘️ `message` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 223)

↘️ `public class WebResult {
  private static Class<?> PKG = WebResult.class; // for i18n purposes, needed by Translator2!!

  public static final String XML_TAG = "webresult";

  public static final String STRING_OK = "OK";
  public static final String STRING_ERROR = "ERROR";

  public static final WebResult OK = new WebResult( STRING_OK );

  private String result;
  private String message;
  private String id;

  public WebResult( String result ) {
    this( result, null, null );
  }

  public WebResult( String result, String message ) {
    this( result, message, null );
  }

  public WebResult( String result, String message, String id ) {
    this.result = result;
    this.message = message;
    this.id = id;
  }

  public String getXML() {
    StringBuilder xml = new StringBuilder();

    xml.append( "<" + XML_TAG + ">" ).append( Const.CR );

    xml.append( "  " ).append( XMLHandler.addTagValue( "result", result ) );
    xml.append( "  " ).append( XMLHandler.addTagValue( "message", message ) );
    xml.append( "  " ).append( XMLHandler.addTagValue( "id", id ) );

    xml.append( "</" + XML_TAG + ">" ).append( Const.CR );

    return xml.toString();
  }

  @Override
  public String toString() {
    return getXML();
  }

  public WebResult( Node webResultNode ) {
    result = XMLHandler.getTagValue( webResultNode, "result" );
    message = XMLHandler.getTagValue( webResultNode, "message" );
    id = XMLHandler.getTagValue( webResultNode, "id" );
  }

  public String getResult() {
    return result;
  }

  public void setResult( String result ) {
    this.result = result;
  }

  public String getMessage() {
    return message;
  }

  public void setMessage( String message ) {
    this.message = message;
  }

  public static WebResult fromXMLString( String xml ) throws KettleXMLException {
    try {
      Document doc = XMLHandler.loadXMLString( xml );
      Node node = XMLHandler.getSubNode( doc, XML_TAG );

      return new WebResult( node );
    } catch ( Exception e ) {
      throw new KettleXMLException( BaseMessages.getString( PKG, "WebResult.Error.UnableCreateResult" ), e );
    }
  }

  /**
   * @return the id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   *          the id to set
   */
  public void setId( String id ) {
    this.id = id;
  }
}` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 32)

↘️ `String message` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 50)

↘️ `message` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 51)

↘️ `String message` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 54)

↘️ `message` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 56)

↘️ `this( result, message, null );` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 51)

↘️ `public class WebResult {
  private static Class<?> PKG = WebResult.class; // for i18n purposes, needed by Translator2!!

  public static final String XML_TAG = "webresult";

  public static final String STRING_OK = "OK";
  public static final String STRING_ERROR = "ERROR";

  public static final WebResult OK = new WebResult( STRING_OK );

  private String result;
  private String message;
  private String id;

  public WebResult( String result ) {
    this( result, null, null );
  }

  public WebResult( String result, String message ) {
    this( result, message, null );
  }

  public WebResult( String result, String message, String id ) {
    this.result = result;
    this.message = message;
    this.id = id;
  }

  public String getXML() {
    StringBuilder xml = new StringBuilder();

    xml.append( "<" + XML_TAG + ">" ).append( Const.CR );

    xml.append( "  " ).append( XMLHandler.addTagValue( "result", result ) );
    xml.append( "  " ).append( XMLHandler.addTagValue( "message", message ) );
    xml.append( "  " ).append( XMLHandler.addTagValue( "id", id ) );

    xml.append( "</" + XML_TAG + ">" ).append( Const.CR );

    return xml.toString();
  }

  @Override
  public String toString() {
    return getXML();
  }

  public WebResult( Node webResultNode ) {
    result = XMLHandler.getTagValue( webResultNode, "result" );
    message = XMLHandler.getTagValue( webResultNode, "message" );
    id = XMLHandler.getTagValue( webResultNode, "id" );
  }

  public String getResult() {
    return result;
  }

  public void setResult( String result ) {
    this.result = result;
  }

  public String getMessage() {
    return message;
  }

  public void setMessage( String message ) {
    this.message = message;
  }

  public static WebResult fromXMLString( String xml ) throws KettleXMLException {
    try {
      Document doc = XMLHandler.loadXMLString( xml );
      Node node = XMLHandler.getSubNode( doc, XML_TAG );

      return new WebResult( node );
    } catch ( Exception e ) {
      throw new KettleXMLException( BaseMessages.getString( PKG, "WebResult.Error.UnableCreateResult" ), e );
    }
  }

  /**
   * @return the id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   *          the id to set
   */
  public void setId( String id ) {
    this.id = id;
  }
}` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 32)

↘️ `new WebResult( WebResult.STRING_ERROR, message )` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 223)

↘️ `out.println( new WebResult( WebResult.STRING_ERROR, message ) )` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 223)


</details>

<details>
<summary> <b>Vulnerable data flow analysis result</b> </summary>
<br>


↘️ `request.getParameter( "id" )` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 159)

↘️ `id` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 159)

↘️ `id` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 221)

↘️ `T source` (at core/src/main/java/org/pentaho/di/core/Const.java line 2734)

↘️ `source` (at core/src/main/java/org/pentaho/di/core/Const.java line 2738)

↘️ `Const.NVL( id, "" )` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 221)

↘️ `"The specified transformation ["
              + transName + "] with id [" + Const.NVL( id, "" )` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 220)

↘️ `"The specified transformation ["
              + transName + "] with id [" + Const.NVL( id, "" ) + "] could not be found"` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 220)

↘️ `message` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 219)

↘️ `message` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 223)

↘️ `public class WebResult {
  private static Class<?> PKG = WebResult.class; // for i18n purposes, needed by Translator2!!

  public static final String XML_TAG = "webresult";

  public static final String STRING_OK = "OK";
  public static final String STRING_ERROR = "ERROR";

  public static final WebResult OK = new WebResult( STRING_OK );

  private String result;
  private String message;
  private String id;

  public WebResult( String result ) {
    this( result, null, null );
  }

  public WebResult( String result, String message ) {
    this( result, message, null );
  }

  public WebResult( String result, String message, String id ) {
    this.result = result;
    this.message = message;
    this.id = id;
  }

  public String getXML() {
    StringBuilder xml = new StringBuilder();

    xml.append( "<" + XML_TAG + ">" ).append( Const.CR );

    xml.append( "  " ).append( XMLHandler.addTagValue( "result", result ) );
    xml.append( "  " ).append( XMLHandler.addTagValue( "message", message ) );
    xml.append( "  " ).append( XMLHandler.addTagValue( "id", id ) );

    xml.append( "</" + XML_TAG + ">" ).append( Const.CR );

    return xml.toString();
  }

  @Override
  public String toString() {
    return getXML();
  }

  public WebResult( Node webResultNode ) {
    result = XMLHandler.getTagValue( webResultNode, "result" );
    message = XMLHandler.getTagValue( webResultNode, "message" );
    id = XMLHandler.getTagValue( webResultNode, "id" );
  }

  public String getResult() {
    return result;
  }

  public void setResult( String result ) {
    this.result = result;
  }

  public String getMessage() {
    return message;
  }

  public void setMessage( String message ) {
    this.message = message;
  }

  public static WebResult fromXMLString( String xml ) throws KettleXMLException {
    try {
      Document doc = XMLHandler.loadXMLString( xml );
      Node node = XMLHandler.getSubNode( doc, XML_TAG );

      return new WebResult( node );
    } catch ( Exception e ) {
      throw new KettleXMLException( BaseMessages.getString( PKG, "WebResult.Error.UnableCreateResult" ), e );
    }
  }

  /**
   * @return the id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   *          the id to set
   */
  public void setId( String id ) {
    this.id = id;
  }
}` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 32)

↘️ `String message` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 50)

↘️ `message` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 51)

↘️ `String message` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 54)

↘️ `message` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 56)

↘️ `this( result, message, null );` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 51)

↘️ `public class WebResult {
  private static Class<?> PKG = WebResult.class; // for i18n purposes, needed by Translator2!!

  public static final String XML_TAG = "webresult";

  public static final String STRING_OK = "OK";
  public static final String STRING_ERROR = "ERROR";

  public static final WebResult OK = new WebResult( STRING_OK );

  private String result;
  private String message;
  private String id;

  public WebResult( String result ) {
    this( result, null, null );
  }

  public WebResult( String result, String message ) {
    this( result, message, null );
  }

  public WebResult( String result, String message, String id ) {
    this.result = result;
    this.message = message;
    this.id = id;
  }

  public String getXML() {
    StringBuilder xml = new StringBuilder();

    xml.append( "<" + XML_TAG + ">" ).append( Const.CR );

    xml.append( "  " ).append( XMLHandler.addTagValue( "result", result ) );
    xml.append( "  " ).append( XMLHandler.addTagValue( "message", message ) );
    xml.append( "  " ).append( XMLHandler.addTagValue( "id", id ) );

    xml.append( "</" + XML_TAG + ">" ).append( Const.CR );

    return xml.toString();
  }

  @Override
  public String toString() {
    return getXML();
  }

  public WebResult( Node webResultNode ) {
    result = XMLHandler.getTagValue( webResultNode, "result" );
    message = XMLHandler.getTagValue( webResultNode, "message" );
    id = XMLHandler.getTagValue( webResultNode, "id" );
  }

  public String getResult() {
    return result;
  }

  public void setResult( String result ) {
    this.result = result;
  }

  public String getMessage() {
    return message;
  }

  public void setMessage( String message ) {
    this.message = message;
  }

  public static WebResult fromXMLString( String xml ) throws KettleXMLException {
    try {
      Document doc = XMLHandler.loadXMLString( xml );
      Node node = XMLHandler.getSubNode( doc, XML_TAG );

      return new WebResult( node );
    } catch ( Exception e ) {
      throw new KettleXMLException( BaseMessages.getString( PKG, "WebResult.Error.UnableCreateResult" ), e );
    }
  }

  /**
   * @return the id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   *          the id to set
   */
  public void setId( String id ) {
    this.id = id;
  }
}` (at core/src/main/java/org/pentaho/di/www/WebResult.java line 32)

↘️ `new WebResult( WebResult.STRING_ERROR, message )` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 223)

↘️ `out.println( new WebResult( WebResult.STRING_ERROR, message ) )` (at engine/src/main/java/org/pentaho/di/www/CleanupTransServlet.java line 223)


</details>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :x: Build failed in 3h 34m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl assemblies/plugins
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by rmansoor — APPROVED** [review]

**Pull request merged**
