### PR TITLE
[PDI-14653] Using export option with kitchen.sh

### PR DESCRIPTION
**Pull request by mchen-len-son**
- fixed current directory resolving when resources exporting
- added unit/integration tests

@akhayrutdinov, @brosander, review it please

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@pamval, @pedrofvteixeira, please run WM over the PR

**Comment by pedrofvteixeira** [comment]
[wingman](http://10.100.11.222:8080/job/wingman-ant/358)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/job/JobMeta.java
  engine/test-src/org/pentaho/di/job/JobExportIT.java
  engine/test-src/org/pentaho/di/job/JobMetaTest.java
  engine/test-src/org/pentaho/di/job/repo/folder/sample_job.kjb
  engine/test-src/org/pentaho/di/job/repo/folder/sample_trans.ktr


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File engine/test-src/org/pentaho/di/job/JobExportIT.java
1. Message: Using a static member import should be avoided - org.junit.Assert.assertTrue. at Line: 47 Column: None

File engine/test-src/org/pentaho/di/job/JobMetaTest.java
1. Message: Using a static member import should be avoided - org.mockito.Matchers.same. at Line: 45 Column: None
2. Message: Using a static member import should be avoided - org.mockito.Mockito.*. at Line: 46 Column: None









Unit test coverage change:
============
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange : +0.08%
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange :**-7.14%**
 * complexityPercentCoverageChange :**-7.69%**
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange :**-0.28%**
 * branchPercentCoverageChange :**-3.33%**
 * complexityPercentCoverageChange :**-1.85%**
    
org.pentaho.di.job.JobMeta:
 * instructionPercentCoverageChange : +2.31%
 * branchPercentCoverageChange : +1.16%
 * linePercentCoverageChange : +2.24%
 * complexityPercentCoverageChange : +0.22%
 * methodPercentCoverageChange : +0.70%
    
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange : +0.17%
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange :**-0.18%**
    
org.pentaho.di.resource.ResourceNamingInterface.FileNamingType:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :84.48%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-1.97%**
    
org.pentaho.di.resource.ResourceDefinition:
 * linePercentCoverage :46.15%
 * methodPercentCoverage :28.57%
 * complexityPercentCoverage :28.57%
 * instructionPercentCoverage :43.33%
    
Integration test coverage change:
============
org.pentaho.di.core.logging.JobLogTable.ID:
 * linePercentCoverage :90.91%
 * methodPercentCoverage :40.00%
 * complexityPercentCoverage :40.00%
 * instructionPercentCoverage :95.29%
    
org.pentaho.di.resource.SimpleResourceNaming.new Object() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :87.88%
    
org.pentaho.di.core.logging.ChannelLogTable:
 * instructionPercentCoverageChange : +8.64%
 * linePercentCoverageChange : +9.57%
 * complexityPercentCoverageChange : +2.63%
 * methodPercentCoverageChange : +7.14%
    
org.pentaho.di.trans.SlaveStepCopyPartitionDistribution:
 * instructionPercentCoverageChange : +12.46%
 * branchPercentCoverageChange : +10.00%
 * linePercentCoverageChange : +12.70%
 * complexityPercentCoverageChange : +5.00%
 * methodPercentCoverageChange : +10.00%
    
org.pentaho.di.repository.filerep.KettleFileRepository:
 * branchPercentCoverage :18.60%
 * linePercentCoverage :20.32%
 * methodPercentCoverage :13.86%
 * complexityPercentCoverage :11.51%
 * instructionPercentCoverage :20.54%
    
org.pentaho.di.core.logging.JobEntryLogTable.ID:
 * linePercentCoverage :90.00%
 * methodPercentCoverage :40.00%
 * complexityPercentCoverage :40.00%
 * instructionPercentCoverage :94.31%
    
org.pentaho.di.core.logging.TransLogTable:
 * instructionPercentCoverageChange : +5.14%
 * linePercentCoverageChange : +5.07%
 * complexityPercentCoverageChange : +1.22%
 * methodPercentCoverageChange : +2.50%
    
org.pentaho.di.trans.TransMeta.TransformationType:
 * instructionPercentCoverageChange : +2.38%
 * linePercentCoverageChange : +5.26%
 * complexityPercentCoverageChange : +8.33%
 * methodPercentCoverageChange : +12.50%
    
org.pentaho.di.job.entries.success.JobEntrySuccess:
 * linePercentCoverage :54.17%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :57.58%
    
org.pentaho.di.core.logging.PerformanceLogTable:
 * instructionPercentCoverageChange : +7.75%
 * linePercentCoverageChange : +8.70%
 * complexityPercentCoverageChange : +2.38%
 * methodPercentCoverageChange : +5.26%
    
org.pentaho.di.resource.ResourceDefinition:
 * linePercentCoverage :69.23%
 * methodPercentCoverage :71.43%
 * complexityPercentCoverage :71.43%
 * instructionPercentCoverage :73.33%
    
org.pentaho.di.trans.step.BaseStepMeta:
 * instructionPercentCoverageChange : +2.71%
 * linePercentCoverageChange : +3.80%
 * complexityPercentCoverageChange : +3.60%
 * methodPercentCoverageChange : +4.40%
    
org.pentaho.di.trans.step.StepPartitioningMeta:
 * instructionPercentCoverageChange : +27.55%
 * branchPercentCoverageChange : +14.71%
 * linePercentCoverageChange : +28.35%
 * complexityPercentCoverageChange : +16.13%
 * methodPercentCoverageChange : +32.14%
    
org.pentaho.di.trans.steps.writetolog.WriteToLogMeta:
 * branchPercentCoverage :14.29%
 * linePercentCoverage :30.37%
 * methodPercentCoverage :28.00%
 * complexityPercentCoverage :21.74%
 * instructionPercentCoverage :38.20%
    
org.pentaho.di.trans.steps.systemdata.SystemDataTypes:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :85.71%
 * complexityPercentCoverage :87.50%
 * instructionPercentCoverage :99.59%
    
org.pentaho.di.trans.steps.systemdata.SystemDataMeta:
 * branchPercentCoverage :21.57%
 * linePercentCoverage :31.67%
 * methodPercentCoverage :34.78%
 * complexityPercentCoverage :24.00%
 * instructionPercentCoverage :35.61%
    
org.pentaho.di.resource.SimpleResourceNaming:
 * branchPercentCoverage :32.86%
 * linePercentCoverage :41.98%
 * methodPercentCoverage :31.58%
 * complexityPercentCoverage :14.55%
 * instructionPercentCoverage :44.28%
    
org.pentaho.di.repository.filerep.KettleFileRepositoryMeta.new RepositoryCapabilities() {...}:
 * linePercentCoverage :10.00%
 * methodPercentCoverage :10.00%
 * complexityPercentCoverage :10.00%
 * instructionPercentCoverage :23.08%
    
org.pentaho.di.repository.filerep.KettleFileRepositoryMeta:
 * linePercentCoverage :24.24%
 * methodPercentCoverage :46.15%
 * complexityPercentCoverage :46.15%
 * instructionPercentCoverage :18.71%
    
org.pentaho.di.job.entries.trans.JobEntryTrans:
 * branchPercentCoverage :7.77%
 * linePercentCoverage :22.67%
 * methodPercentCoverage :27.78%
 * complexityPercentCoverage :7.35%
 * instructionPercentCoverage :22.35%
    
org.pentaho.di.core.gui.JobTracker:
 * branchPercentCoverage :6.25%
 * linePercentCoverage :12.50%
 * methodPercentCoverage :9.09%
 * complexityPercentCoverage :6.67%
 * instructionPercentCoverage :10.24%
    
org.pentaho.di.job.entries.special.JobEntrySpecial:
 * linePercentCoverage :33.33%
 * methodPercentCoverage :33.33%
 * complexityPercentCoverage :23.08%
 * instructionPercentCoverage :33.60%
    
org.pentaho.di.core.logging.JobLogTable:
 * linePercentCoverage :28.95%
 * methodPercentCoverage :20.59%
 * complexityPercentCoverage :8.97%
 * instructionPercentCoverage :55.14%
    
org.pentaho.di.resource.TopLevelResource:
 * linePercentCoverage :35.71%
 * methodPercentCoverage :14.29%
 * complexityPercentCoverage :14.29%
 * instructionPercentCoverage :36.36%
    
org.pentaho.di.repository.filerep.KettleFileRepositorySecurityProvider:
 * linePercentCoverage :9.76%
 * methodPercentCoverage :8.33%
 * complexityPercentCoverage :2.78%
 * instructionPercentCoverage :4.72%
    
org.pentaho.di.resource.ResourceNamingInterface.FileNamingType:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :75.00%
 * complexityPercentCoverage :75.00%
 * instructionPercentCoverage :91.38%
    
org.pentaho.di.core.logging.MetricsLogTable:
 * instructionPercentCoverageChange : +10.46%
 * linePercentCoverageChange : +10.59%
 * complexityPercentCoverageChange : +3.23%
 * methodPercentCoverageChange : +7.14%
    
org.pentaho.di.core.attributes.AttributesUtil:
 * instructionPercentCoverageChange : +93.79%
 * branchPercentCoverageChange : +77.78%
 * linePercentCoverageChange : +89.19%
 * complexityPercentCoverageChange : +58.33%
 * methodPercentCoverageChange : +33.33%
    
org.pentaho.di.core.changed.ChangedFlag:
 * instructionPercentCoverageChange : +4.90%
 * linePercentCoverageChange : +7.69%
 * complexityPercentCoverageChange : +8.33%
 * methodPercentCoverageChange : +12.50%
    
org.pentaho.di.job.entry.JobEntryCopy:
 * branchPercentCoverage :19.05%
 * linePercentCoverage :52.38%
 * methodPercentCoverage :36.21%
 * complexityPercentCoverage :26.58%
 * instructionPercentCoverage :53.58%
    
org.pentaho.di.job.JobHopMeta:
 * branchPercentCoverage :13.33%
 * linePercentCoverage :33.64%
 * methodPercentCoverage :17.24%
 * complexityPercentCoverage :11.36%
 * instructionPercentCoverage :47.73%
    
org.pentaho.di.core.logging.StepLogTable:
 * instructionPercentCoverageChange : +7.47%
 * linePercentCoverageChange : +8.91%
 * complexityPercentCoverageChange : +2.86%
 * methodPercentCoverageChange : +7.14%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +26.92%
 * branchPercentCoverageChange : +13.01%
 * linePercentCoverageChange : +22.37%
 * complexityPercentCoverageChange : +5.26%
 * methodPercentCoverageChange : +9.18%
    
org.pentaho.di.core.util.CurrentDirectoryResolver:
 * instructionPercentCoverageChange : +26.64%
 * branchPercentCoverageChange : +16.67%
 * linePercentCoverageChange : +32.14%
 * complexityPercentCoverageChange : +6.82%
 * methodPercentCoverageChange : +40.00%
    
org.pentaho.di.job.JobMeta:
 * branchPercentCoverage :12.87%
 * linePercentCoverage :25.79%
 * methodPercentCoverage :16.90%
 * complexityPercentCoverage :8.54%
 * instructionPercentCoverage :26.52%
    
org.pentaho.di.resource.ResourceUtil:
 * branchPercentCoverage :30.00%
 * linePercentCoverage :54.35%
 * methodPercentCoverage :60.00%
 * complexityPercentCoverage :26.67%
 * instructionPercentCoverage :42.21%
    
org.pentaho.di.trans.TransMeta:
 * instructionPercentCoverageChange : +10.98%
 * branchPercentCoverageChange : +5.83%
 * linePercentCoverageChange : +8.54%
 * complexityPercentCoverageChange : +3.20%
 * methodPercentCoverageChange : +2.23%
    
org.pentaho.di.base.AbstractMeta:
 * instructionPercentCoverageChange : +3.60%
 * branchPercentCoverageChange : +2.73%
 * linePercentCoverageChange : +3.18%
 * complexityPercentCoverageChange : +2.51%
 * methodPercentCoverageChange : +2.74%
    
org.pentaho.di.resource.SequenceResourceNaming:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :81.82%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :71.70%
    
org.pentaho.di.repository.BaseRepositoryMeta:
 * linePercentCoverage :17.07%
 * methodPercentCoverage :25.00%
 * complexityPercentCoverage :21.43%
 * instructionPercentCoverage :10.91%
    
org.pentaho.di.core.logging.BaseLogTable:
 * instructionPercentCoverageChange : +6.90%
 * branchPercentCoverageChange : +3.38%
 * linePercentCoverageChange : +5.21%
 * complexityPercentCoverageChange : +2.65%
 * methodPercentCoverageChange : +2.56%
    
org.pentaho.di.job.Job:
 * branchPercentCoverage :3.20%
 * linePercentCoverage :8.90%
 * methodPercentCoverage :14.49%
 * complexityPercentCoverage :7.60%
 * instructionPercentCoverage :7.22%
    
org.pentaho.di.job.entries.trans.JobEntryTrans.new Object() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :88.46%
    
org.pentaho.di.trans.TransHopMeta:
 * instructionPercentCoverageChange : +20.54%
 * branchPercentCoverageChange : +8.33%
 * linePercentCoverageChange : +16.22%
 * complexityPercentCoverageChange : +8.33%
 * methodPercentCoverageChange : +12.50%
    
org.pentaho.di.job.entry.JobEntryBase:
 * branchPercentCoverage :8.33%
 * linePercentCoverage :30.45%
 * methodPercentCoverage :28.00%
 * complexityPercentCoverage :25.55%
 * instructionPercentCoverage :30.03%
    
org.pentaho.di.core.logging.JobEntryLogTable:
 * branchPercentCoverage :1.52%
 * linePercentCoverage :34.62%
 * methodPercentCoverage :35.71%
 * complexityPercentCoverage :9.09%
 * instructionPercentCoverage :61.65%

**Comment by brosander** [comment]
@mchen-len-son please remove database connections from the job and trans

**Comment by mchen-len-son** [comment]
@brosander, db connection has been removed. Recheck, please.

**Pull request merged**
