### PR TITLE
[TEST] Increase code coverage

### PR DESCRIPTION
**Pull request by DFieldFL**
please review and merge @pminutillo @kurtwalker @bytekast

### CODE REVIEW

**Comment by matthewtckr** [comment]
In assertXmlOutputMeta(), this will fail on Windows-based systems, as the ZipFileMeta class uses Const.CR to generate `\r\n` for line endings.

**Comment by DFieldFL** [comment]
Would checking for `.contains` be sufficient for testing?

**Comment by matthewtckr** [comment]
You could probably just do `...</someTag>" + Const.CR;` for each line instead of the `\n`.

**Comment by lucboudreau** [comment]
Wingman in progress.
http://10.100.11.222:8080/job/wingman-ant/134/console

**Comment by DFieldFL** [comment]
@matthewtckr yes that seemed to work. I'll wait for the wingman to finish and see if there is any other errors I need to fix before committing it.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/test-src/org/pentaho/di/trans/steps/zipfile/ZipFileMetaTest.java

Checkstyle violations:
======================
File engine/test-src/org/pentaho/di/trans/steps/zipfile/ZipFileMetaTest.java
1. Message: '(' is followed by whitespace. at Line: 199 Column: 24
2. Message: ')' is preceded with whitespace. at Line: 199 Column: 32


License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange :**-0.17%**
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange :**-0.53%**
    
org.pentaho.di.trans.steps.zipfile.ZipFileData:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange : +7.14%
 * complexityPercentCoverageChange : +7.69%
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange : +0.28%
 * branchPercentCoverageChange : +3.33%
 * complexityPercentCoverageChange : +1.85%
    
org.pentaho.di.trans.steps.zipfile.ZipFileMeta:
 * branchPercentCoverage :87.50%
 * linePercentCoverage :92.13%
 * methodPercentCoverage :97.14%
 * complexityPercentCoverage :91.49%
 * instructionPercentCoverage :91.85%
    
org.pentaho.di.trans.steps.zipfile.ZipFile:
 * linePercentCoverage :1.38%
 * methodPercentCoverage :22.22%
 * complexityPercentCoverage :2.47%
 * instructionPercentCoverage :0.96%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +1.97%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/test-src/org/pentaho/di/trans/steps/zipfile/ZipFileMetaTest.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange :**-0.17%**
    
org.pentaho.di.trans.steps.zipfile.ZipFileData:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange :**-0.28%**
 * branchPercentCoverageChange :**-3.33%**
 * complexityPercentCoverageChange :**-1.85%**
    
org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * instructionPercentCoverageChange : +0.07%
    
org.pentaho.di.trans.steps.zipfile.ZipFileMeta:
 * branchPercentCoverage :87.50%
 * linePercentCoverage :92.13%
 * methodPercentCoverage :97.14%
 * complexityPercentCoverage :91.49%
 * instructionPercentCoverage :91.85%
    
org.pentaho.di.trans.steps.zipfile.ZipFile:
 * linePercentCoverage :1.38%
 * methodPercentCoverage :22.22%
 * complexityPercentCoverage :2.47%
 * instructionPercentCoverage :0.96%
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange : +0.18%

**Comment by DFieldFL** [comment]
@pminutillo @kurtwalker @bytekast @matthewtckr please reveiw

**Pull request merged**
