### PR TITLE
[SP-6306] - Backport of PPP-4610 - Use of Vulnerable Component: Components/snakeyaml:1.25 (9.4 Suite)

### PR DESCRIPTION
**Pull request by andreramos89**
@smmribeiro 
@renato-s 
@bcostahitachivantara

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,plugins/pur/core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by bcostahitachivantara — APPROVED** [review]

**Comment by buildguy** [comment]
### :x: Build failed in 40m 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,plugins/pur/core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 7 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransTest.testPDI12424ParametersFromMetaAreCopiedToTrans</b> (click to expand)</summary><p>

```

Transformation was unable to open [null]

The transformation path ram:///parameters_34f2d18e-b8ea-11ed-ac5b-e16be5fea357.ktr is invalid, and will not run successfully.


```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.avro.input.AvroInputMetaTest.testGetFields_unknownPluginForFieldType</b> (click to expand)</summary><p>

```
Expected exception: org.pentaho.di.core.exception.KettleStepException
```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testDedupeArray</b> (click to expand)</summary><p>

```
Could not load SWT library. Reasons: 
 no swt-pi-gtk-4623 in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
 no swt-pi-gtk in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
 /home/buildguy/.swt/lib/linux/x86_64/libswt-pi-gtk-4623.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
 Can't load library: /home/buildguy/.swt/lib/linux/x86_64/libswt-pi-gtk.so

```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testDedupeLines</b> (click to expand)</summary><p>

```
Could not initialize class org.eclipse.swt.widgets.Display
```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testBigIntegerNode</b> (click to expand)</summary><p>

```
Could not initialize class org.eclipse.swt.widgets.Display
```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testDedupeObject</b> (click to expand)</summary><p>

```
Could not initialize class org.eclipse.swt.widgets.Display
```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testDedupeNestedArrays</b> (click to expand)</summary><p>

```
Could not initialize class org.eclipse.swt.widgets.Display
```

</p></details>

  
Tests run: **4042**, Failures: **7**, Skipped: **8** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8832/2/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 40m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,plugins/pur/core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 7 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransTest.testPDI12424ParametersFromMetaAreCopiedToTrans</b> (click to expand)</summary><p>

```

Transformation was unable to open [null]

The transformation path ram:///parameters_113370c0-b8f7-11ed-aeb7-93837e091d62.ktr is invalid, and will not run successfully.


```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.avro.input.AvroInputMetaTest.testGetFields_unknownPluginForFieldType</b> (click to expand)</summary><p>

```
Expected exception: org.pentaho.di.core.exception.KettleStepException
```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testDedupeArray</b> (click to expand)</summary><p>

```
Could not load SWT library. Reasons: 
 no swt-pi-gtk-4623 in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
 no swt-pi-gtk in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
 /home/buildguy/.swt/lib/linux/x86_64/libswt-pi-gtk-4623.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
 Can't load library: /home/buildguy/.swt/lib/linux/x86_64/libswt-pi-gtk.so

```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testDedupeLines</b> (click to expand)</summary><p>

```
Could not initialize class org.eclipse.swt.widgets.Display
```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testBigIntegerNode</b> (click to expand)</summary><p>

```
Could not initialize class org.eclipse.swt.widgets.Display
```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testDedupeObject</b> (click to expand)</summary><p>

```
Could not initialize class org.eclipse.swt.widgets.Display
```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testDedupeNestedArrays</b> (click to expand)</summary><p>

```
Could not initialize class org.eclipse.swt.widgets.Display
```

</p></details>

  
Tests run: **4042**, Failures: **7**, Skipped: **8** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8832/3/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 39m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,plugins/pur/core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 7 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransTest.testPDI12424ParametersFromMetaAreCopiedToTrans</b> (click to expand)</summary><p>

```

Transformation was unable to open [null]

The transformation path ram:///parameters_d6620fb0-b901-11ed-ad60-5b2ce72c27a8.ktr is invalid, and will not run successfully.


```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.avro.input.AvroInputMetaTest.testGetFields_unknownPluginForFieldType</b> (click to expand)</summary><p>

```
Expected exception: org.pentaho.di.core.exception.KettleStepException
```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testDedupeArray</b> (click to expand)</summary><p>

```
Could not load SWT library. Reasons: 
 no swt-pi-gtk-4623 in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
 no swt-pi-gtk in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
 /home/buildguy/.swt/lib/linux/x86_64/libswt-pi-gtk-4623.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
 Can't load library: /home/buildguy/.swt/lib/linux/x86_64/libswt-pi-gtk.so

```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testDedupeLines</b> (click to expand)</summary><p>

```
Could not initialize class org.eclipse.swt.widgets.Display
```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testBigIntegerNode</b> (click to expand)</summary><p>

```
Could not initialize class org.eclipse.swt.widgets.Display
```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testDedupeObject</b> (click to expand)</summary><p>

```
Could not initialize class org.eclipse.swt.widgets.Display
```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.jsoninput.getfields.JsonSamplerTest.testDedupeNestedArrays</b> (click to expand)</summary><p>

```
Could not initialize class org.eclipse.swt.widgets.Display
```

</p></details>

  
Tests run: **4042**, Failures: **7**, Skipped: **8** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-8832/4/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
