### PR TITLE
[PDI-20078] - Metadata generated from "Automatic Documentation Output step for a transformation/job will contain all the unwanted connections available in the repository

### PR DESCRIPTION
**Pull request by andreramos89**
@smmribeiro 
@renato-s

### CODE REVIEW

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 27m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransMetaPrivateDbTest.onePrivate_TwoShared</b> (click to expand)</summary><p>

```
expected:<3> but was:<2>
```

</p></details>

<details><summary><b>org.pentaho.di.trans.TransMetaPrivateDbTest.onePrivate_NoShared</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **3587**, Failures: **2**, Skipped: **6** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9279/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 25m 55s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransMetaPrivateDbTest.onePrivate_TwoShared</b> (click to expand)</summary><p>

```
expected:<3> but was:<2>
```

</p></details>

<details><summary><b>org.pentaho.di.trans.TransMetaPrivateDbTest.onePrivate_NoShared</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **3587**, Failures: **2**, Skipped: **6** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9279/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
~Looks good.

**Review by renato-s — APPROVED** [review]

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 25m
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransMetaPrivateDbTest.onePrivate_TwoShared</b> (click to expand)</summary><p>

```
expected:<3> but was:<2>
```

</p></details>

<details><summary><b>org.pentaho.di.trans.TransMetaPrivateDbTest.onePrivate_NoShared</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **3587**, Failures: **2**, Skipped: **6** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9279/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 21m 16s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.trans.TransMetaPrivateDbTest.onePrivate_TwoShared</b> (click to expand)</summary><p>

```
expected:<3> but was:<2>
```

</p></details>

<details><summary><b>org.pentaho.di.trans.TransMetaPrivateDbTest.onePrivate_NoShared</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **3587**, Failures: **2**, Skipped: **6** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9279/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
