### PR TITLE
[PDI-14861] Add NULL_AS support to kettle-gpload-plugin

### PR DESCRIPTION
**Pull request by stevewillcock**
This allows a known value in an import file to be treated as NULL when data is
imported - this has some bearing on http://jira.pentaho.com/browse/PDI-8457 although that may need more work for a full resolution - this PR just adds support for the NULL_AS option, not the ESCAPE option

### CODE REVIEW

**Comment by mbatchelor** [comment]
@stevewillcock - Thanks for the contribution, but we can't merge this in until some things are fixed. 

Most importantly, you added a new variable (nullAs) that only saves/loads state from XML. But if you're using a repository, the state won't be saved or loaded. You need to add code to readRep/saveRep to persist and load this new value.

Secondly, your changes will fail our checkstyle. If you run the checkstyle ant task and review the output report, you'll find that your changes don't conform.

Thirdly, we are trying to improve the code quality and stability of our open source projects. As such, we need unit test cases to make sure we don't regress in functionality or capability. In the case of this plugin though, there are no existing test cases, so I understand not providing one. If you have the time though, we'd appreciate a unit test - even if it's just to test the round-tripping of the variables (load/save testing). That unit-test would have pointed out the issue with saveRep/loadRep not being populated with your new variable. For an example, see the testRoundTrip test in the ElasticSearchBulkMetadataTest here: https://github.com/stevewillcock/pentaho-kettle/blob/master/plugins/elasticsearch-bulk-insert/test-src/org/pentaho/di/trans/steps/elasticsearchbulk/ElasticSearchBulkMetaTest.java 

Lastly, to receive contributions, we need to have a JIRA case. Please create one at http://jira.pentaho.com, and comment it with your pull request.

Thanks again for your contribution - I would really love to merge this in once the issues are resolved!

**Comment by stevewillcock** [comment]
Great, thanks for the quick feedback - I'll take a look at those issues, including getting some round-tripping unit tests for the metadata in there (thanks for the pointer to the ElasticSearchBulkMetadataTest, that's really useful) and update the PR.

**Comment by stevewillcock** [comment]
@mbatchelor I have done some work towards resolving the issues with the PR.

* Added a unit test class based on the ElasticSearchBulkMetadataTest that you pointed me to
* Resolved the issue where the nullAs field wasn't being written to or read from the repository - the unit test did indeed fail as you mentioned at this point.
* Resolved the checkstyle issues with the new code as far as possible.
* Raised a JIRA issue http://jira.pentaho.com/browse/PDI-14861
* Rebased the commits on my fork so this PR is all on one commit

There are a couple of issues which may still need addressing.

1 - Running checkstyle generates a large number of errors around generic declarations in the code.

For example, line 65 in GPLoad.java

```
private static Class<?> PKG = GPLoadMeta.class; // for i18n purposes, needed by Translator2!! $NON-NLS-1$
```
Generates these issues:
```
'<' is not preceded with whitespace
'<' is not followed by whitespace
'?' is not preceded with whitespace
'>' is not preceded with whitespace
'?' is not followed by whitespace
```

This was an existing line in that file, so I'm not sure if this is a configuration issue with checkstyle on my setup or if it is expected? I did try putting various bits of whitespace around the  <, ?, and > but I was unable to resolve the issue.

2 -  I haven't come up with a good implementation of DatabaseMetaFieldLoadSaveValidator (as used in GPLoadMetaTest.java) - I tried creating a DatabaseMeta object but that failed as it couldn't find a database type with the given name. I think this loads database types from kettle-database-types.xml but I assume that this is not loaded in the context of the unit tests. The implementation in the PR here simply returns null which allows validateTestObject to pass.

If you could take a look when you get chance and let me know if there is anything else you need me to do to get this through that would be great :)

Thanks

Steve

**Comment by stevewillcock** [comment]
@mbatchelor Upon running the unit test again I noticed that it was failing intermittently - this was due to the encloseNumbers field not being deserialised in the xml reader. This was an issue in the existing code which was highlighted by having a unit test in place. I have updated the PR to resolve this issue and to ensure that the test will pass reliably.

I think that the code style on the PR is now in line with your requirements - the error with the angle brackets for generics is happening on code throughout the code base. As such I think that this may be ok to merge.

Let me know if I'm mistaken about the code styling though, or if there's anything else that you would like to be changed on this PR before you can merge it :)

Thanks

**Comment by mbatchelor** [comment]
Awesome, thanks! I will merge your PR now.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-gpload-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-gpload-plugin/ivy.xml
  plugins/kettle-gpload-plugin/src/org/pentaho/di/trans/steps/gpload/GPLoad.java
  plugins/kettle-gpload-plugin/src/org/pentaho/di/trans/steps/gpload/GPLoadMeta.java
  plugins/kettle-gpload-plugin/src/org/pentaho/di/trans/steps/gpload/messages/messages_en_US.properties
  plugins/kettle-gpload-plugin/src/org/pentaho/di/ui/trans/steps/gpload/GPLoadDialog.java
  plugins/kettle-gpload-plugin/test-src/org/pentaho/di/trans/steps/gpload/GPLoadMetaTest.java










Unit test coverage change:
============
org.pentaho.di.trans.steps.gpload.GPLoadMeta:
 * branchPercentCoverage :26.92%
 * linePercentCoverage :54.86%
 * methodPercentCoverage :81.43%
 * complexityPercentCoverage :54.10%
 * instructionPercentCoverage :56.11%

**Comment by stevewillcock** [comment]
```
ant -Dpentaho.coding.standards.version=1.0.1
```

Ah, this explains why I was getting the checkstyle errors on generic declarations - I wasn't passing that to the build and it was using the 1.0.3 version of the checkstyle xml config by default. Thanks for that info, very useful.

**Pull request merged**
