### PR TITLE
[PDI-19118] Database Cursor Leak of Kettle 8.3

### PR DESCRIPTION
**Pull request by sunhongxia123**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 24m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4844**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7997/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by sunhongxia123** [comment]
> **SonarQube Quality Gate:**
> [Quality Gate failed](https://sonar.orl.eng.hitachivantara.com/dashboard?id=org.pentaho.di%3Apdi&pullRequest=7997)
> 
> [Failed condition](https://sonar.orl.eng.hitachivantara.com/dashboard?id=org.pentaho.di%3Apdi&pullRequest=7997) [E](https://sonar.orl.eng.hitachivantara.com/dashboard?id=org.pentaho.di%3Apdi&pullRequest=7997) Maintainability Rating on New Code (is worse than A)
> [Failed condition](https://sonar.orl.eng.hitachivantara.com/dashboard?id=org.pentaho.di%3Apdi&pullRequest=7997) 31 New Code Smells (is greater than 0)
> 
> [See analysis details on SonarQube](https://sonar.orl.eng.hitachivantara.com/dashboard?id=org.pentaho.di%3Apdi&pullRequest=7997)

I can not open it, please confirm the URL, thank you:)

**Comment by sunhongxia123** [comment]
> **SonarQube Quality Gate:**
> [Quality Gate failed](https://sonar.orl.eng.hitachivantara.com/dashboard?id=org.pentaho.di%3Apdi&pullRequest=7997)
> 
> [Failed condition](https://sonar.orl.eng.hitachivantara.com/dashboard?id=org.pentaho.di%3Apdi&pullRequest=7997) [E](https://sonar.orl.eng.hitachivantara.com/dashboard?id=org.pentaho.di%3Apdi&pullRequest=7997) Maintainability Rating on New Code (is worse than A)
> [Failed condition](https://sonar.orl.eng.hitachivantara.com/dashboard?id=org.pentaho.di%3Apdi&pullRequest=7997) 31 New Code Smells (is greater than 0)
> 
> [See analysis details on SonarQube](https://sonar.orl.eng.hitachivantara.com/dashboard?id=org.pentaho.di%3Apdi&pullRequest=7997)

Hello, I can not open this URL, how to check this sonar issue?

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 25m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4844**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7997/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 24m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4844**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7997/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 25m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **4844**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7997/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
Thank you for your pull request, but I'm closing it as, for the 8.3 branch, they follow a different (internal) process.
When the issue is fixed on master, it'll be evaluated to see if it is suitable for backport.

**Pull request closed without merging**
