### PR TITLE
[PDI-14878] fixed the reference leak of cached objects

### PR DESCRIPTION
**Pull request by andrey-markelov**

### CODE REVIEW

**Comment by andrey-markelov** [comment]
@rmansoor @rfellows please merge

**Comment by akhayrutdinov** [comment]
@brosander, review it please

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_Links_IT.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
1. Message: File length is 2,914 lines (max allowed is 2,000). at Line: 1 Column: None
2. Message: Using a static member import should be avoided - org.pentaho.di.repository.RepositoryObjectType.JOB. at Line: 104 Column: None
3. Message: Using a static member import should be avoided - org.pentaho.di.repository.RepositoryObjectType.TRANSFORMATION. at Line: 105 Column: None
4. Message: Unused import - org.pentaho.di.core.KettleEnvironment. at Line: 25 Column: 8
5. Message: Unused import - org.pentaho.di.core.Props. at Line: 27 Column: 8
6. Message: 'switch' is not followed by whitespace. at Line: 2833 Column: 11
7. Message: 'if' is not followed by whitespace. at Line: 551 Column: 7
8. Message: Unused import - org.pentaho.di.ui.core.dialog.KettlePropertiesFileDialog. at Line: 69 Column: 8

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_Links_IT.java
1. Message: Using a static member import should be avoided - org.junit.Assert.fail. at Line: 3 Column: None


License header violations:
==========================

1. plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_Links_IT.java









Integration test coverage change:
============
org.pentaho.di.repository.pur.JobDelegate:
 * instructionPercentCoverageChange : +0.80%
 * branchPercentCoverageChange : +2.83%
 * linePercentCoverageChange : +0.77%
 * complexityPercentCoverageChange : +1.49%
    
org.pentaho.di.repository.pur.TransDelegate:
 * instructionPercentCoverageChange : +0.52%
 * branchPercentCoverageChange : +1.52%
 * linePercentCoverageChange : +0.51%
 * complexityPercentCoverageChange : +0.88%
    
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange : +0.06%
 * linePercentCoverageChange : +0.17%
 * complexityPercentCoverageChange : +0.23%
 * methodPercentCoverageChange : +0.57%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_Links_IT.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
1. Message: File length is 2,911 lines (max allowed is 2,000). at Line: 1 Column: None
2. Message: Using a static member import should be avoided - org.pentaho.di.repository.RepositoryObjectType.JOB. at Line: 20 Column: None
3. Message: Using a static member import should be avoided - org.pentaho.di.repository.RepositoryObjectType.TRANSFORMATION. at Line: 21 Column: None

File plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_Links_IT.java
1. Message: Using a static member import should be avoided - org.junit.Assert.fail. at Line: 19 Column: None










Integration test coverage change:
============
org.pentaho.di.repository.pur.JobDelegate:
 * instructionPercentCoverageChange : +0.80%
 * branchPercentCoverageChange : +2.83%
 * linePercentCoverageChange : +0.77%
 * complexityPercentCoverageChange : +1.49%
    
org.pentaho.di.repository.pur.TransDelegate:
 * instructionPercentCoverageChange : +0.52%
 * branchPercentCoverageChange : +1.52%
 * linePercentCoverageChange : +0.51%
 * complexityPercentCoverageChange : +0.88%
    
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange : +0.06%
 * linePercentCoverageChange : +0.17%
 * complexityPercentCoverageChange : +0.23%
 * methodPercentCoverageChange : +0.57%

**Comment by pamval** [comment]
@andrey-markelov please fix the code style violations

**Comment by andrey-markelov** [comment]
@pamval I suppressed the file length violation, but I could not remove the imports of static classes

**Pull request merged**
