### PR TITLE
[PDI-9137] - Wrong interpretation of bignumber in java Script step

### PR DESCRIPTION
**Pull request by akhayrutdinov**
@mattyb149, @brosander, review it please

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@brosander, do you have any other remarks?

**Comment by akhayrutdinov** [comment]
@brosander, take a look at it please

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please. This ticket has been added to the current sprint, the sprint ends on Friday

**Comment by mattyb149** [comment]
The ScriptUtils class, since it is shared by two steps in different packages, should be moved somewhere else. Otherwise if we ever move the Script step out of the engine into a plugin, the ScriptMod step will no longer compile.

**Comment by akhayrutdinov** [comment]
@mattyb149, thanks for responding!
I propose https://github.com/pentaho/pentaho-kettle/tree/master/engine/src/org/pentaho/di/core/util, do you have any dissents?

**Comment by mattyb149** [comment]
For clarity, let's call it JavascriptUtils. We'll have to take a look at all our Javascript support to see if it still runs (using Rhino) on JRE8.  The location is good with me, thanks!

**Comment by akhayrutdinov** [comment]
I've renamed it

**Pull request merged**
