### PR TITLE
[SP-2834] Backport of PDI-12590 - Write to Log Job Entry Ignores Log …

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
[SP-2834] Backport of PDI-12590 - Write to Log Job Entry Ignores Log Level Setting (6.1 Suite)

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
backport of #2774

**Comment by stanislau-strelchanka** [comment]
@mbatchelor, @matthewtckr, @pamval , @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor, @matthewtckr, @pamval , @mchen-len-son please review

**Comment by lucboudreau** [comment]
Can we add a few tests to raise coverage on JobEntryWriteToLog? Not sure if the new code is well covered. Adding a loop over the different log levels would probably fix it. Thanks!

**Comment by dkincade** [comment]
This was covered with https://github.com/pentaho/pentaho-kettle/pull/2774 ... looks safe to bring in.

**Pull request merged**
