### PR TITLE
[PDI-15203] Made the Collections.synchornizedList(...) a CopyOnWriteA…

### PR DESCRIPTION
**Pull request by ccaspanello**
…rrayList so that it is now threadsafe throughout the stack.  Also added a test fromt he Crate perspective that passes the threadsafe list into the WebServer.

@hudak Here's the pull request

### CODE REVIEW

**Comment by mbatchelor** [comment]
Cannot process PR until issues are fixed (copyright dates, CarteTest no longer broken)

**Comment by lucboudreau** [comment]
Chris, please squash your two commits and trigger Wingman afterwards.

**Comment by ccaspanello** [comment]
Thanks Luc, reopened pull request (instead of closing/creating a new one like I previously did).  I did another commit and squashed it like you said and it looks like Wingman detected the change and is running again.  This is cool! :+1:

**Comment by lucboudreau** [comment]
I'm seeing two commits in this pull request. I think the squash did not work.

**Comment by ccaspanello** [comment]
Fixed license and check style errors.

**Pull request merged**
