### PR TITLE
[TEST] Correcting 2 test classes which had ambiguous

### PR DESCRIPTION
**Pull request by mkambol**
calls to logError.

### CODE REVIEW

**Comment by mkambol** [comment]
http://10.100.11.222:8080/job/wingman-ant/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/test-src/org/pentaho/di/trans/steps/replacestring/ReplaceStringTest.java
  engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java



Unit test coverage change:
============
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.94%

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change : **-1.64%**
 * Complexity Change : **-.69%**
 * Instruction Change : **-2.43%**
 * Line Change : **-3.70%**

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Instruction Change : **-.08%**

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Instruction Change : **-.07%**

org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * Instruction Change : **-.18%**

org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * Branch Change : **-3.33%**
 * Complexity Change : **-1.85%**
 * Instruction Change : **-.28%**

org.pentaho.di.trans.Trans:
 * Branch Change : **-.10%**
 * Complexity Change : **-.14%**
 * Instruction Change : **-.09%**
 * Line Change : **-.11%**



Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java

1. Message: Using a static member import should be avoided - org.pentaho.di.core.util.Assert.assertFalse. at Line: 37
2. Message: Using a static member import should be avoided - org.pentaho.di.core.util.Assert.assertTrue. at Line: 38

**Comment by brosander** [comment]
@mkambol no idea why we need assert classes in Kettle, I know you didn't touch that part of the file but mind using junit ones?

**Comment by mkambol** [comment]
@brosander - sure, was just looking at that.  I expect it was an accidental auto-IDE thing by whoever put those asserts in.

**Comment by mkambol** [comment]
@brosander Updated PR with assert imports fixed.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/test-src/org/pentaho/di/trans/steps/replacestring/ReplaceStringTest.java
  engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java



Unit test coverage change:
============
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change :  + 7.14%
 * Complexity Change :  + 7.69%

org.pentaho.di.core.util.Assert:
 * Branch Change : **-1.56%**
 * Complexity Change : **-3.51%**
 * Instruction Change : **-3.03%**
 * Line Change : **-4.65%**
 * Method Change : **-8.00%**

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change :  + 1.64%
 * Complexity Change :  + .69%
 * Instruction Change :  + 2.43%
 * Line Change :  + 3.70%

org.pentaho.di.trans.step.StepMeta:
 * Instruction Change :  + .19%
 * Line Change :  + .27%

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Instruction Change :  + .07%

org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * Branch Change : **-3.33%**
 * Complexity Change : **-1.85%**
 * Instruction Change : **-.28%**

org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * Branch Change :  + .53%

org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * Instruction Change :  + .18%

org.pentaho.di.trans.Trans:
 * Branch Change : **-.10%**
 * Complexity Change : **-.14%**
 * Instruction Change : **-.09%**
 * Line Change : **-.11%**

**Pull request merged**
