### PR TITLE
[PDI-14921]-Fixed the failing test cases.

### PR DESCRIPTION
**Pull request by phalguni-a**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 9m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by peterrinehart — CHANGES_REQUESTED** [review]
Please update the copyright dates in the test classes.

**Comment by buildguy** [comment]
### :x: Build failed in 6m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
plugins/file-open-save-new/core,ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 47s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
core,plugins/file-open-save-new/core,ui
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by phalguni-a** [comment]
Will create a new PR

**Pull request closed without merging**
