### PR TITLE
[SP-2496] - Backport of PDI-4837 - CSV File Input - fails to populate rownum, filenameField, input row count (5.4 Suite)

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- set meta data columns on last, incomplete CSV row
- add a test
(adopted from commits 6e436e0, 268c314)

@brosander, @hudak, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2185

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@brosander, @hudak, review it please. This is a backport of #2185

**Comment by akhayrutdinov** [comment]
@pedrofvteixeira, @pamval, please start WingMan for this PR

**Comment by pamval** [comment]
wingman failed for 5.4 - review manually, please.

**Comment by akhayrutdinov** [comment]
@mtseu, @kolinus, @PavelSakoun, review it please

**Comment by akhayrutdinov** [comment]
@brosander, review it please

**Pull request merged**
