### PR TITLE
[PDI-14979] - Add new method to DatabaseInterface in Kettle Core

### PR DESCRIPTION
**Pull request by mchen-len-son**
- added new extending interface
- added general and Oracle specific implementation
- added unit tests

@deinspanjer, review it please

### CODE REVIEW

**Comment by deinspanjer** [comment]
This looks great, and I'll be happy to merge it, but I need to check with people managing the current release first to make sure when we are clear to start merging in non-release work.

**Comment by mchen-len-son** [comment]
Hi, @deinspanjer. 
Just to remind. Can't you merge it now?
Thanks.

**Comment by deinspanjer** [comment]
Yes, I can merge it now, but I had to merge a big nasty PR before it and there are now a couple of conflicts.  Could you please take a look at them and I'll merge it then?

**Comment by mchen-len-son** [comment]
@deinspanjer, I rebased the branch and squashed the commits. 
Recheck, please.

**Pull request merged**
