### PR TITLE
[PDI-17329] Add Constants : Adding an Internet Address type constant …

### PR DESCRIPTION
**Pull request by smmribeiro**
…will result in an error.

@renato-s @andreramos89

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 6m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3786**, Failures: **0**, Skipped: **9** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/vc-pdi/job/PR-9210/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 35m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **4110**, Failures: **0**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9210/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 43m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **4110**, Failures: **0**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9210/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by renato-s — APPROVED** [review]

**Pull request merged**
