### PR TITLE
[BACKLOG-11640] Update the Spoon help link to point to a page in the help system

### PR DESCRIPTION
**Pull request by davidmsantos90**
@pentaho/millenniumfalcon @pamval please review.

### CODE REVIEW

**Comment by mdamour1976** [comment]
Use a URL fragment for the documentationUrl:
documentationUrl=0D0/Pentaho_Data_Integration

Then later, simply use Const.getDocUrl( url )

**Comment by mdamour1976** [comment]
IMO, also, if we are no longer using InformationMap, that should be removed.

**Comment by mdamour1976** [comment]
This might also be helpful to update:
https://github.com/pentaho/pentaho-kettle/blob/master/core/src/org/pentaho/di/core/messages/messages_en_US.properties

**Comment by davidmsantos90** [comment]
@mdamour1976 So should we also remove the mechanism that provides local documentation altogether?

**Comment by davidmsantos90** [comment]
In BACKLOG-11645 we have this:
"Requirement Note: This link needs to be configurable via a properties file or some other "non-compile" method so customers can change where this points to if they have internal help or are OEMs."

But by using Const.BaseDocUrl we lose the ability to change this without compiling the project.

Do you know a better place to configure this?

**Comment by mdamour1976** [comment]
@davidmsantos90 Const.getDocUrl uses a properties file..  It has been accepted in the past as a "non-compile" option.  I don't know of a scenario where someone would use "different" documentation, and if they did, well, they can open the jar and change the properties file.

**Comment by davidmsantos90** [comment]
@pentaho/millenniumfalcon @mdamour1976 @pamval please review

**Comment by davidmsantos90** [comment]
@pentaho/millenniumfalcon @mdamour1976 @pamval doing the PR without changing welcome/index.html, wingman runs without any problems.

But when running with the file changed, it fails. This looks like a problem with wingman, but I'm not sure.
@lucboudreau can you also take a look at this error?

**Pull request merged**
