### PR TITLE
[SP-2641] Backport of PDI-14974 - Data Service SQL that counts distin…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
…ct null values returns incorrect value (6.1 Suite) - backport functionality

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
@brosander, @mattyb149, @mchen-len-son, please review

**Comment by brosander** [comment]
@stanislau-strelchanka please link to master pr

**Comment by brosander** [comment]
Base build failed with return code 1

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupBy.java
  engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByAggregationTest.java

Unit test coverage change:
============
org.pentaho.di.core.lifecycle.KettleLifecycleSupport:
 * Branch Change :  + 8.33%
 * Complexity Change :  + 9.09%

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.97%

org.pentaho.di.trans.step.StepMeta:
 * Instruction Change : **-.19%**
 * Line Change : **-.27%**

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Instruction Change :  + .08%

org.pentaho.di.trans.steps.memgroupby.MemoryGroupBy:
 * Branch Change :  + 35.32%
 * Complexity Change :  + 32.54%
 * Instruction Change :  + 35.07%
 * Line Change :  + 34.20%
 * Method Change :  + 23.08%

org.pentaho.di.trans.steps.memgroupby.MemoryGroupByMeta:
 * Branch Change :  + 22.50%
 * Complexity Change :  + 15.49%
 * Instruction Change :  + 12.97%
 * Line Change :  + 20.22%
 * Method Change :  + 13.79%

org.pentaho.di.trans.steps.randomvalue.RandomValueMeta:
 * Branch Change :  + 2.17%
 * Complexity Change :  + 2.17%
 * Instruction Change :  + .15%

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Instruction Change : **-.07%**

org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * Instruction Change :  + .18%

org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * Branch Change : **-.53%**

org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * Instruction Change :  + .18%

Integration test coverage change:
============
org.pentaho.di.trans.step.BaseStep:
 * Branch Change : **-.44%**
 * Complexity Change : **-.18%**
 * Instruction Change : **-.20%**
 * Line Change : **-.16%**

**Comment by stanislau-strelchanka** [comment]
@brosander, link to master pr - https://github.com/pentaho/pentaho-kettle/pull/2294

**Comment by brosander** [comment]
@stanislau-strelchanka @mkambol reviewed the master pr, he'll have more context on this

**Pull request merged**
