### PR TITLE
[BACKLOG-12327] AVG function doesn't work for data services with CSV …

### PR DESCRIPTION
**Pull request by andrei-viaryshka**
…Input step with Lazy Conversion on

### CODE REVIEW

**Comment by andrei-viaryshka** [comment]
@mkambol Could you review please?

**Comment by mkambol** [comment]
@andrei-viaryshka - I notice some of the getXXX methods still just do a straight == null check, rather than isNull().   Is there a reason only Number, BigNumber and Date needed to be changed?

**Comment by andrei-viaryshka** [comment]
@mkambol I've made changes/tests only for types that are used in other tests with lazy conversion.

**Comment by andrei-viaryshka** [comment]
@mkambol Added the change for Integer as well. It looks like lazy conversion shouldn't be an issue for other types.

**Pull request merged**
