### PR TITLE
SP-1595 - Backport of PDI-12368 - Race condition using Pentaho 5 Kettle ...

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
...SDK and KettleLogStore.getAppender().getBuffer(...) (5.2 Suite)

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@hudak 
Please review.

**Comment by dkincade** [comment]
@brosander implemented the parent fix for this ... please make sure your work is in line with his fix (details in http://jira.pentaho.com/browse/PDI-12368)

**Comment by Aliaksandr-Kastenka** [comment]
@dkincade 
It is the same as https://github.com/pentaho/pentaho-kettle/pull/931 , just in one commit, not two. Should i send pr again?

**Comment by dkincade** [comment]
Yes - and let's have @hudak review it since it reviewed the pone from @brosander 
Thanks!

**Pull request merged**
