### PR TITLE
Fix ZipOutputStream double closing for Java 8

### PR DESCRIPTION
**Pull request by AlexanderBuloichik**

### CODE REVIEW

**Comment by dkincade** [comment]
@brosander @mattyb149 @hudak @mdamour1976  please review ...

**Comment by mdamour1976** [comment]
@AlexanderBuloichik so, engine now has runtime dependency on test-src?  Unless we ship the test-src jar, this isn't going to work out so great.   :)

**Comment by AlexanderBuloichik** [comment]
@mdamour1976 Yes, sorry, wrong place for package.
I'm also not sure that package "org.pentaho.di.workarounds" is good name, but I don't see any better place for wrapper.

**Comment by mdamour1976** [comment]
Changed files:
==============
  engine/src/org/pentaho/di/job/entries/zipfile/JobEntryZipFile.java
  engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java
  engine/src/org/pentaho/di/workarounds/BufferedOutputStreamWithCloseDetection.java

Checkstyle violations:
----------------------
Errors:File engine/src/org/pentaho/di/job/entries/zipfile/JobEntryZipFile.java
1. Message: Unused import - java.io.BufferedOutputStream. at Line: 32 Column: 8File engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java
1. Message: Unused import - java.io.OutputStream. at Line: 28 Column: 8

Newly Broken Tests:
=================
Test Case Errors:
-----------------
  org.pentaho.di.www.Batch-With-Multiple-Tests.message: 
```

```org.pentaho.di.www.Batch-With-Multiple-Tests.type: 
```

```org.pentaho.di.www.Batch-With-Multiple-Tests.severity: 
```

```


Unit test coverage change:
============
org.pentaho.di.workarounds.BufferedOutputStreamWithCloseDetection:
 * branchPercentCoverage :0.00%
 * linePercentCoverage :0.00%
 * methodPercentCoverage :0.00%
 * complexityPercentCoverage :0.00%
 * instructionPercentCoverage :0.00%
    
Integration test coverage change:
============
org.pentaho.di.workarounds.BufferedOutputStreamWithCloseDetection:
 * branchPercentCoverage :0.00%
 * linePercentCoverage :0.00%
 * methodPercentCoverage :0.00%
 * complexityPercentCoverage :0.00%
 * instructionPercentCoverage :0.00%

**Comment by mdamour1976** [comment]
Changed files:
==============
  engine/src/org/pentaho/di/job/entries/zipfile/JobEntryZipFile.java
  engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java
  engine/src/org/pentaho/di/workarounds/BufferedOutputStreamWithCloseDetection.java

Checkstyle violations:
----------------------
No errors found

Newly Broken Tests:
=================
Test Case Errors:
-----------------
  org.pentaho.di.www.Batch-With-Multiple-Tests.message: 
```

```org.pentaho.di.www.Batch-With-Multiple-Tests.type: 
```

```org.pentaho.di.www.Batch-With-Multiple-Tests.severity: 
```

```


Unit test coverage change:
============
org.pentaho.di.workarounds.BufferedOutputStreamWithCloseDetection:
 * branchPercentCoverage :0.00%
 * linePercentCoverage :0.00%
 * methodPercentCoverage :0.00%
 * complexityPercentCoverage :0.00%
 * instructionPercentCoverage :0.00%
    
Integration test coverage change:
============
org.pentaho.di.workarounds.BufferedOutputStreamWithCloseDetection:
 * branchPercentCoverage :0.00%
 * linePercentCoverage :0.00%
 * methodPercentCoverage :0.00%
 * complexityPercentCoverage :0.00%
 * instructionPercentCoverage :0.00%

**Pull request merged**
