### PR TITLE
[SP-6083] Backport of PDI-19292 - ERROR messages related to LoggingRe…

### PR DESCRIPTION
**Pull request by ddiroma**
…gistry Purge keeps getting logged. (8.3 Suite)

### CODE REVIEW

**Comment by ddiroma** [comment]
@pentaho/tatooine Please approve

**Comment by buildguy** [comment]
### :x: Build failed in 2m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 1h 29m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 7 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.getxmldata.GetXMLDataMetaTest.testSaveRepOfAdditionalOutputFields</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/repository2/unified/IUnifiedRepository
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.getxmldata.GetXMLDataStepAnalyzerTest.testCreateResourceNode</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.metaverse.api.analyzer.kettle.KettleAnalyzerUtil
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.xmloutput.XMLOutputMetaTest.testCheck</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/repository2/unified/IUnifiedRepository
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.xmloutput.XMLOutputMetaTest.testReadRep</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/repository2/unified/IUnifiedRepository
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.xmloutput.XMLOutputMetaTest.testGetFields</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/repository2/unified/IUnifiedRepository
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.xmloutput.XMLOutputMetaTest.testReadRepException</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/repository2/unified/IUnifiedRepository
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.xmloutput.XMLOutputStepAnalyzerTest.testCreateResourceNode</b> (click to expand)</summary><p>

```
org/pentaho/platform/api/engine/ObjectFactoryException
```

</p></details>

  
Tests run: **4619**, Failures: **7**, Skipped: **7** &nbsp;&nbsp; [Test Results](https://wingman.pentaho.net/job/projects/job/pdi-8/job/PR-8175/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
I'm closing this PR as the issue is still not assigned a specific SP.

**Comment by ddiroma** [comment]
Master PR: https://github.com/pentaho/pentaho-kettle/pull/8144

8.3 PR: https://github.com/pentaho/pentaho-kettle/pull/8175

9.2 PR: https://github.com/pentaho/pentaho-kettle/pull/8176

9.2.0.4 PR: https://github.com/pentaho/pentaho-kettle/pull/8320

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PR.

**Pull request merged**
