### PR TITLE
[SP-3843][PDI-14442]-PDI Import scripts are executed in parallel by multiple users

### PR DESCRIPTION
**Pull request by stepanovdg**
Depends on https://github.com/pentaho/pentaho-platform/pull/3916

### CODE REVIEW

**Comment by stepanovdg** [comment]
@mchen-len-son Could you please take a look?

**Comment by stepanovdg** [comment]
After merging dependent pull-request rerun wingman.

**Comment by mchen-len-son** [comment]
@stepanovdg 
besides wingman's failure on this, I see try-catch for pur.updateFile is not backported. is this expected?

**Comment by mchen-len-son** [comment]
Could not reproduce the errors reported on a clean environment.
Looks like old platform-api is cached at Wingman's workspace.
Checked manually - everything seems to be OK.
Merging.

**Pull request merged**
