### PR TITLE
PDI-12368 - Race condition using Pentaho 5 Kettle SDK and KettleLogStore...

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
....getAppender().getBuffer(...)

### CODE REVIEW

**Comment by Aliaksandr-Kastenka** [comment]
@dkincade @mbatchelor 
Please review.

**Comment by dkincade** [comment]
@mattcasters @mattyb149 @brosander please review

**Comment by brosander** [comment]
@Aliaksandr-Kastenka are there tests for this?

**Comment by Aliaksandr-Kastenka** [comment]
@brosander 
I checked it by running the attached class from the issue:
http://jira.pentaho.com/secure/attachment/50006/RunningJobs.java
and getting an output:
...
****** Print the size of each job's buffer******************************************************
Job number 0 4478
Job number 1 4478
Job number 2 4478
************************************************************************************************
...
instead of this(attached log output):
http://jira.pentaho.com/secure/attachment/49648/esr3851.log

**Comment by brosander** [comment]
@Aliaksandr-Kastenka is this something we should either unit or integration test?

**Comment by Aliaksandr-Kastenka** [comment]
@brosander 
Please review.

**Pull request merged**
