### PR TITLE
[BACKLOG-7682] Change XMLOutput implementation to StAX

### PR DESCRIPTION
**Pull request by AlexanderBuloichik**

### CODE REVIEW

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local
2. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-xml-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-xml-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/di/core/xml/XMLHandler.java
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmloutput/XMLOutput.java
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmloutput/XMLOutputData.java
  plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/xmloutput/XMLOutputTest.java

Unit test coverage change:
============
org.pentaho.di.core.xml.XMLHandler:
 * Complexity Change :  + .17%
 * Instruction Change :  + .18%
 * Line Change :  + .24%
 * Method Change :  + .49%

org.pentaho.di.trans.steps.xmloutput.XMLOutput:
 * Complexity Change :  + 1.71%
 * Instruction Change : **-.57%**
 * Line Change : **-1.28%**
 * Method Change :  + 6.36%

License header violations:
==========================
1. Copyright year is not the current year on core/src/org/pentaho/di/core/xml/XMLHandler.java. Found 2013. Was expecting 2016

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmloutput/XMLOutput.java

1. Message: ')' is not preceded with whitespace. at Line: 261 Column: 96
2. Message: '(' is not followed by whitespace. at Line: 265 Column: 42
3. Message: ')' is not preceded with whitespace. at Line: 295 Column: 96
4. Message: '(' is not followed by whitespace. at Line: 300 Column: 42

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f core/build.xml jacoco-integration checkstyle publish-local
2. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-xml-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-xml-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  core/src/org/pentaho/di/core/xml/XMLHandler.java
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmloutput/XMLOutput.java
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmloutput/XMLOutputData.java
  plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/xmloutput/XMLOutputTest.java

Unit test coverage change:
============
org.pentaho.di.core.xml.XMLHandler:
 * Complexity Change :  + .17%
 * Instruction Change :  + .18%
 * Line Change :  + .24%
 * Method Change :  + .49%

org.pentaho.di.trans.steps.xmloutput.XMLOutput:
 * Complexity Change :  + 1.71%
 * Instruction Change : **-.57%**
 * Line Change : **-1.28%**
 * Method Change :  + 6.36%

**Comment by AlexanderBuloichik** [comment]
We can't test separate methods with StAX without creating full XML document. But it will be integration test.

**Comment by kurtwalker** [comment]
@bmorrise @AlexanderBuloichik This change broke compile in pentaho-metadata because it is using the StringBuffer version of append.  I'll go ahead and fix it since I'm in there already, but I wouldn't be surprised if it breaks some other projects as well.  Also, Can you please add some notes to the deprecation indicating what method to use instead.

**Pull request merged**
