### PR TITLE
[CLEANUP] Remove ValueMeta references

### PR DESCRIPTION
**Pull request by matthewtckr**

### CODE REVIEW

**Comment by matthewtckr** [comment]
Ignoring copyright year warning for `OpenERPObjectOutputMeta`, as it is not a Pentaho copyright header.

**Comment by matthewtckr** [comment]
Removed file that was conflicting after #2703 was merged.  Will pick that file up again in a future PR.

**Comment by lucboudreau** [comment]
I'm not surprised this build failed on Wingman. Too many changes. Please validate locally.

**Comment by matthewtckr** [comment]
Wingman broken

**Pull request merged**
