### PR TITLE
[CLEANUP] Checkstyle fixes

### PR DESCRIPTION
**Pull request by AlexanderBuloichik**

### CODE REVIEW

**Comment by mdamour1976** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/job/Job.java
  engine/src/org/pentaho/di/trans/Trans.java
  engine/src/org/pentaho/di/trans/step/StepMeta.java
  engine/src/org/pentaho/di/trans/steps/fileinput/text/BOMDetector.java
  engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInput.java
  engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputMetaInjection.java
  engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputReader.java
  engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
  engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java
  engine/src/org/pentaho/di/www/Carte.java
  engine/test-src/org/pentaho/di/job/JobMetaTest.java
  engine/test-src/org/pentaho/di/job/entries/setvariables/JobEntrySetVariablesTest.java
  engine/test-src/org/pentaho/di/trans/DatabaseImpactTest.java
  engine/test-src/org/pentaho/di/trans/step/FakeRowDistribution.java
  engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMetaTest.java
  engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java
  engine/test-src/org/pentaho/di/trans/steps/xmloutput/XMLOutputMetaTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMetaTest.java
1. Message: '&&' should be on a new line. at Line: 164 Column: 57
2. Message: '&&' should be on a new line. at Line: 165 Column: 47
3. Message: '&&' should be on a new line. at Line: 166 Column: 58
4. Message: '&&' should be on a new line. at Line: 167 Column: 51
5. Message: '&&' should be on a new line. at Line: 168 Column: 57
6. Message: '&&' should be on a new line. at Line: 169 Column: 74
7. Message: '&&' should be on a new line. at Line: 170 Column: 72
8. Message: '&&' should be on a new line. at Line: 171 Column: 74
9. Message: 'if' child have incorrect indentation level 10, expected level should be 8. at Line: 173 Column: None

File engine/test-src/org/pentaho/di/trans/steps/xmloutput/XMLOutputMetaTest.java
1. Message: 'array initialization' child have incorrect indentation level 12, expected level should be 10. at Line: 409 Column: None
2. Message: 'array initialization' child have incorrect indentation level 12, expected level should be 10. at Line: 410 Column: None
3. Message: 'array initialization' child have incorrect indentation level 12, expected level should be 10. at Line: 411 Column: None
4. Message: 'array initialization' child have incorrect indentation level 12, expected level should be 10. at Line: 412 Column: None
5. Message: 'array initialization' child have incorrect indentation level 12, expected level should be 10. at Line: 413 Column: None
6. Message: 'array initialization' child have incorrect indentation level 12, expected level should be 10. at Line: 414 Column: None
7. Message: 'array initialization' child have incorrect indentation level 12, expected level should be 10. at Line: 415 Column: None
8. Message: 'array initialization' child have incorrect indentation level 12, expected level should be 10. at Line: 416 Column: None
9. Message: 'array initialization' child have incorrect indentation level 12, expected level should be 10. at Line: 417 Column: None
10. Message: 'array initialization' child have incorrect indentation level 12, expected level should be 10. at Line: 418 Column: None


License header violations:
==========================

1. engine/src/org/pentaho/di/trans/steps/fileinput/text/BOMDetector.java

2. engine/test-src/org/pentaho/di/job/entries/setvariables/JobEntrySetVariablesTest.java








Unit test coverage change:
============
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange : +0.08%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange : +0.53%
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange :**-7.14%**
 * complexityPercentCoverageChange :**-7.69%**
    
org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * instructionPercentCoverageChange :**-0.07%**
    
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange :**-0.17%**
    
org.pentaho.di.trans.steps.randomvalue.RandomValueMeta:
 * instructionPercentCoverageChange :**-0.15%**
 * branchPercentCoverageChange :**-2.08%**
 * complexityPercentCoverageChange :**-2.13%**
    
org.pentaho.di.core.lifecycle.KettleLifecycleSupport:
 * branchPercentCoverageChange : +8.33%
 * complexityPercentCoverageChange : +9.09%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +1.97%

**Comment by AlexanderBuloichik** [comment]
@mdamour1976 Not my issues ;) Fixed.

**Comment by mdamour1976** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/job/Job.java
  engine/src/org/pentaho/di/trans/Trans.java
  engine/src/org/pentaho/di/trans/step/StepMeta.java
  engine/src/org/pentaho/di/trans/steps/fileinput/text/BOMDetector.java
  engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInput.java
  engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputMetaInjection.java
  engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputReader.java
  engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
  engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java
  engine/src/org/pentaho/di/www/Carte.java
  engine/test-src/org/pentaho/di/job/JobMetaTest.java
  engine/test-src/org/pentaho/di/job/entries/setvariables/JobEntrySetVariablesTest.java
  engine/test-src/org/pentaho/di/trans/DatabaseImpactTest.java
  engine/test-src/org/pentaho/di/trans/step/FakeRowDistribution.java
  engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMetaTest.java
  engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java
  engine/test-src/org/pentaho/di/trans/steps/xmloutput/XMLOutputMetaTest.java










Unit test coverage change:
============
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange :**-3.28%**
 * linePercentCoverageChange :**-3.95%**
    
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange :**-0.08%**
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange :**-7.14%**
 * complexityPercentCoverageChange :**-7.69%**
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange : +0.18%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange : +0.53%

**Comment by mdamour1976** [comment]
@AlexanderBuloichik looks good, will merge

**Pull request merged**
