### PR TITLE
[BACKLOG-6767] - Add warning prompt to user when metadata injection mappings are missing

### PR DESCRIPTION
**Pull request by AndreyBurikhin**
@bmorrise , @mdamour1976 please review

### CODE REVIEW

**Comment by lucboudreau** [comment]
[Wingman in progress](http://10.100.11.222:8080/job/wingman-ant/347/console)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local
3. ant -Djunit.jvmargs=-XX:PermSize=256m -f ui/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/metainject/MetaInject.java
  engine/src/org/pentaho/di/trans/steps/metainject/messages/messages_en_US.properties
  engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java
  ui/src/org/pentaho/di/ui/trans/steps/metainject/MetaInjectDialog.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java
1. Message: Using a static member import should be avoided - org.junit.Assert.assertEquals. at Line: 25 Column: None
2. Message: Unused import - org.junit.Assert.assertFalse. at Line: 26 Column: 15
3. Message: Using a static member import should be avoided - org.junit.Assert.assertFalse. at Line: 26 Column: None
4. Message: '>' is followed by whitespace. at Line: 269 Column: 31
5. Message: Using a static member import should be avoided - org.junit.Assert.assertTrue. at Line: 27 Column: None
6. Message: Using a static member import should be avoided - org.mockito.Matchers.any. at Line: 28 Column: None
7. Message: '>' is followed by whitespace. at Line: 281 Column: 91
8. Message: Using a static member import should be avoided - org.mockito.Matchers.refEq. at Line: 29 Column: None
9. Message: Using a static member import should be avoided - org.mockito.Mockito.atLeastOnce. at Line: 30 Column: None
10. Message: Using a static member import should be avoided - org.mockito.Mockito.doReturn. at Line: 31 Column: None
11. Message: Using a static member import should be avoided - org.mockito.Mockito.mock. at Line: 32 Column: None
12. Message: Using a static member import should be avoided - org.mockito.Mockito.spy. at Line: 33 Column: None
13. Message: Using a static member import should be avoided - org.mockito.Mockito.verify. at Line: 34 Column: None









Unit test coverage change:
============
org.pentaho.di.trans.steps.metainject.TargetStepAttribute:
 * instructionPercentCoverageChange :**-4.29%**
 * linePercentCoverageChange :**-4.76%**
 * complexityPercentCoverageChange :**-7.69%**
 * methodPercentCoverageChange :**-11.11%**
    
org.pentaho.di.trans.step.StepInjectionMetaEntry:
 * instructionPercentCoverageChange :**-7.41%**
 * linePercentCoverageChange :**-10.71%**
 * complexityPercentCoverageChange :**-13.33%**
 * methodPercentCoverageChange :**-14.29%**
    
org.pentaho.di.trans.steps.metainject.MetaInject:
 * instructionPercentCoverageChange :**-43.62%**
 * branchPercentCoverageChange :**-37.48%**
 * linePercentCoverageChange :**-45.76%**
 * complexityPercentCoverageChange :**-27.38%**
 * methodPercentCoverageChange :**-42.35%**
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange : +0.53%
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange :**-0.28%**
 * branchPercentCoverageChange :**-3.33%**
 * complexityPercentCoverageChange :**-1.85%**
    
org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * instructionPercentCoverageChange : +0.07%
    
org.pentaho.di.trans.TransMeta:
 * instructionPercentCoverageChange :**-0.60%**
 * branchPercentCoverageChange :**-0.35%**
 * linePercentCoverageChange :**-0.67%**
 * complexityPercentCoverageChange :**-0.47%**
 * methodPercentCoverageChange :**-1.49%**
    
org.pentaho.di.trans.steps.metainject.SourceStepField:
 * branchPercentCoverage :50.00%
 * instructionPercentCoverageChange : +53.33%
 * linePercentCoverageChange : +29.41%
 * complexityPercentCoverageChange : +18.18%
 * methodPercentCoverageChange : +28.57%
    
org.pentaho.di.trans.steps.metainject.MetaInjectMeta:
 * instructionPercentCoverageChange :**-0.62%**
 * linePercentCoverageChange :**-1.14%**
 * complexityPercentCoverageChange :**-3.41%**
 * methodPercentCoverageChange :**-5.77%**
    
org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * instructionPercentCoverageChange : +2.43%
 * branchPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +2.95%
 * complexityPercentCoverageChange : +0.69%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +0.19%
 * linePercentCoverageChange : +0.27%
    
org.pentaho.di.core.injection.bean.BeanInjectionInfo:
 * instructionPercentCoverageChange :**-3.37%**
 * branchPercentCoverageChange :**-8.33%**
 * linePercentCoverageChange :**-4.55%**
 * complexityPercentCoverageChange :**-7.69%**
 * methodPercentCoverageChange :**-14.29%**
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange : +7.14%
 * complexityPercentCoverageChange : +7.69%
    
Integration test coverage change:
============
org.pentaho.di.trans.steps.metainject.MetaInject:
 * instructionPercentCoverageChange : +0.18%
 * branchPercentCoverageChange :**-0.33%**
 * linePercentCoverageChange :**-0.79%**
 * complexityPercentCoverageChange : +0.35%
 * methodPercentCoverageChange : +0.29%

**Comment by lucboudreau** [comment]
There are a few checkstyle issues to address, as well as a significant drop in coverage for many files. Please see if this can be addressed. Thanks!

**Comment by AndreyBurikhin** [comment]
@lucboudreau  

I made some changes to the test code, add a few tests, also remove 3 tests which were useless after this commit: https://github.com/pentaho/pentaho-kettle/commit/b3c56f77aadc893ac45df714bd8a3dd4f1841aab.

As for checkstyle violations - I might be wrong but as i remember static import is allowed now (for test). Let me know if i'm wrong i'll remove static import.

**Comment by bmorrise** [comment]
@AndreyBurikhin This pull request is reporting that is contains conflicts that need to be resolved.

**Comment by AndreyBurikhin** [comment]
@bmorrise resolved

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local
3. ant -Djunit.jvmargs=-XX:PermSize=256m -f ui/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/metainject/MetaInject.java
  engine/src/org/pentaho/di/trans/steps/metainject/messages/messages_en_US.properties
  engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java
  ui/src/org/pentaho/di/ui/trans/steps/metainject/MetaInjectDialog.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java
1. Message: '>' is followed by whitespace. at Line: 241 Column: 31
2. Message: Using a static member import should be avoided - org.junit.Assert.assertEquals. at Line: 25 Column: None
3. Message: '>' is followed by whitespace. at Line: 253 Column: 91
4. Message: Using a static member import should be avoided - org.junit.Assert.assertNotNull. at Line: 26 Column: None
5. Message: Using a static member import should be avoided - org.junit.Assert.assertTrue. at Line: 27 Column: None
6. Message: Using a static member import should be avoided - org.mockito.Matchers.any. at Line: 28 Column: None
7. Message: Using a static member import should be avoided - org.mockito.Matchers.refEq. at Line: 29 Column: None
8. Message: Using a static member import should be avoided - org.mockito.Mockito.atLeastOnce. at Line: 30 Column: None
9. Message: Using a static member import should be avoided - org.mockito.Mockito.doReturn. at Line: 31 Column: None
10. Message: Using a static member import should be avoided - org.mockito.Mockito.mock. at Line: 32 Column: None
11. Message: Using a static member import should be avoided - org.mockito.Mockito.spy. at Line: 33 Column: None
12. Message: Using a static member import should be avoided - org.mockito.Mockito.verify. at Line: 34 Column: None









Unit test coverage change:
============
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange :**-0.08%**
    
org.pentaho.di.trans.steps.metainject.MetaInject:
 * instructionPercentCoverageChange : +0.05%
 * branchPercentCoverageChange : +2.64%
 * linePercentCoverageChange : +3.22%
 * complexityPercentCoverageChange : +6.58%
 * methodPercentCoverageChange : +2.65%
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange : +7.14%
 * complexityPercentCoverageChange : +7.69%
    
org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * instructionPercentCoverageChange :**-0.07%**
    
org.pentaho.di.trans.steps.metainject.SourceStepField:
 * branchPercentCoverage :50.00%
 * instructionPercentCoverageChange : +53.33%
 * linePercentCoverageChange : +29.41%
 * complexityPercentCoverageChange : +18.18%
 * methodPercentCoverageChange : +28.57%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +0.19%
 * linePercentCoverageChange : +0.27%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange : +0.53%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +1.97%
    
Integration test coverage change:
============
org.pentaho.di.trans.steps.metainject.MetaInject:
 * instructionPercentCoverageChange : +0.16%
 * branchPercentCoverageChange :**-0.33%**
 * linePercentCoverageChange :**-0.79%**
 * complexityPercentCoverageChange : +0.35%
 * methodPercentCoverageChange : +0.29%

**Comment by bmorrise** [comment]
@AndreyBurikhin Can you squash these into a single commit?

**Comment by AndreyBurikhin** [comment]
@bmorrise done.

**Pull request merged**
