### PR TITLE
[SP-5994] Backport of PPP-4590 - XML External Entity (XXE) vulnerability when reading XLSX files (8.3 Suite)

### PR DESCRIPTION
**Pull request by smmribeiro**
Cherry pick of:

- [pentaho-kettle#7817](https://github.com/pentaho/pentaho-kettle/pull/7817)
Note that '\plugins\json\core\pom.xml' was not backported as a subsequent backported development removed the affected entries
- [pentaho-kettle#7846](https://github.com/pentaho/pentaho-kettle/pull/7846)

@ssamora @bcostahitachivantara @moraesvc

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 3m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,plugins/xml
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 19s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,plugins/xml
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,plugins/xml
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,plugins/xml
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,plugins/xml
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,plugins/xml
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 3m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,plugins/xml
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 30m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine,plugins/xml
```
---
:ok_hand: All tests passed!
 
Tests run: **3706**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-8079/8/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ssamora — APPROVED** [review]

**Pull request merged**
