### PR TITLE
[BACKLOG-17671] TableView column resize

### PR DESCRIPTION
**Pull request by tgf**
TableView: allow disabling automatic column expansion for contents
ColumnsResizer: account for vscrollbar when resizing, option to refit
after manual column resize

### CODE REVIEW

**Comment by tgf** [comment]
@ddiroma please review

**Comment by roboguy** [comment]
@tgf - Is there any plan to allow user control of this behavior ? For example in the `TransPreviewDelegate` that controls the preview table .. we usually have long strings that do not fit well in this table. We would like to be able to set autoResize to false.

**Comment by tgf** [comment]
@roboguy if you mean user control from the ui, then no; it's just meant to be set when creating the table. otherwise this can be used in preview or anything else using tableview

**Comment by roboguy** [comment]
@tgf - thank you for replying.

**Pull request merged**
