### PR TITLE
[BACKLOG-29332] S3 Multipart Upload does not allow configurable part …

### PR DESCRIPTION
**Pull request by NJtwentyone**
…sizes

- created class StorageUnitConverter to handle human readible file size to byte

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 46m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **4768**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7335/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by NJtwentyone** [comment]
the sonar link doesn't show any finds

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 45m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **4768**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7335/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 45m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **4768**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7335/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
