### PR TITLE
[BACKLOG-32963] - Determine the state of deprecated ResolvableResourc…

### PR DESCRIPTION
**Pull request by cravobranco**
…e interface

* Removed deprecated ResolvableResource interface and its calls

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 29m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3633**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7228/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by cravobranco** [comment]
@pentaho/bb-8 please review

**Comment by buildguy** [comment]
### :x: Build failed in 1m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3633**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7228/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 24m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3634**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-7228/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by cravobranco** [comment]
According to @ccaspanello :

"I talk to Jake about the deprecation. It seems like this is not deprecated functionality and is the way we do things now."

=> As far pentaho-shims project is actively using the ResolvableResource  interface, I'll close the PR and resolve the Jira case.

**Pull request closed without merging**
