### PR TITLE
[PDI-14172] - Text file input Repeat doesn't work

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- applying changes from 9e3e72d9d85ce5222a44b4ebe46d4e7163057e9e to new implementation of the step

@mattyb149, @brosander, review it please. This is a fix migration from https://github.com/pentaho/pentaho-kettle/pull/1731 to the new implementation

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please.

**Comment by pamval** [comment]
@rpbouman if you can, please review

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, review it please.

**Comment by akhayrutdinov** [comment]
@dkincade, would you minding looking at this? I believe it is better to include the fix into 6.0

**Pull request merged**
