### PR TITLE
[BISERVER-15128] - Excel reports generated using newer Apache POI lib…

### PR DESCRIPTION
**Pull request by krishnaalluhitachi**
…rary leave larger files on tomcat's temp directory

### CODE REVIEW

**Comment by buildguy** [comment]
<div align='center'>

[🚨 Frogbot scanned this pull request and found the below:](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>




---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

```
db.parse( inputSource )
```
at `core/src/main/java/org/pentaho/di/core/xml/XMLHandler.java` (line 749)


[comment]: <> (FrogbotReviewComment)


## 🎯 Static Application Security Testing (SAST) Vulnerability
<div align='center'>

| Severity                | Finding                  |
| :---------------------: | :-----------------------------------: |
| <br>  Medium | XML external entities |

</div>

<details>
<summary> <b>Full description</b> </summary>
<br>


### Overview
Unsafe XXE (XML External Entity) expansion, is a type of vulnerability
that allows an attacker to access external resources, such as files or
network services using a crafted XML document. The attack can also lead to
a denial of service, due to quadratic expansion of XXE elements.

### Vulnerable example
```java
protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
    DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
    DocumentBuilder db = dbf.newDocumentBuilder();
    InputSource is = new InputSource();
    // Load the xml string into an InputSource object.
    is.setCharacterStream(new StringReader( request.getParameter("xml") ));
    // Parse it
    db.parse(is);
}
```
### Remediation
Set the following features on `DocumentBuilderFactory` to remediate XXE:
```diff
+   try {
+      dbf.setFeature("http://xml.org/sax/features/external-general-entities", false);
+   } catch (ParserConfigurationException e) { }
+   try {
+      dbf.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
+   } catch (ParserConfigurationException e) { }
+   try {
+      dbf.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
+   } catch (ParserConfigurationException e) { }
+   try {
+      dbf.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd",
+           false);
+   } catch (ParserConfigurationException e) { }
+   dbf.setXIncludeAware(false);
+   dbf.setExpandEntityReferences(false);
    DocumentBuilder db = dbf.newDocumentBuilder();
```


</details>

<details>
<summary> <b>Code Flows</b> </summary>
<br>


<details>
<summary> <b>Vulnerable data flow analysis result</b> </summary>
<br>


↘️ `inputStream.read()` (at engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java line 380)

↘️ `c` (at engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java line 380)

↘️ `xml.append( (char) c )` (at engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java line 381)

↘️ `xml.toString()` (at engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java line 384)

↘️ `XMLHandler.loadXMLString( xml.toString() )` (at engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java line 384)

↘️ `DocumentBuilder db` (at core/src/main/java/org/pentaho/di/core/xml/XMLHandler.java line 741)

↘️ `db.parse( inputSource )` (at core/src/main/java/org/pentaho/di/core/xml/XMLHandler.java line 749)


</details>

<details>
<summary> <b>Vulnerable data flow analysis result</b> </summary>
<br>


↘️ `is.read()` (at ui/src/main/java/org/pentaho/di/ui/trans/steps/scriptvalues_mod/ScriptValuesHelp.java line 92)

↘️ `c` (at ui/src/main/java/org/pentaho/di/ui/trans/steps/scriptvalues_mod/ScriptValuesHelp.java line 92)

↘️ `buffer.append( (char) c )` (at ui/src/main/java/org/pentaho/di/ui/trans/steps/scriptvalues_mod/ScriptValuesHelp.java line 93)

↘️ `buffer.toString()` (at ui/src/main/java/org/pentaho/di/ui/trans/steps/scriptvalues_mod/ScriptValuesHelp.java line 96)

↘️ `XMLHandler.loadXMLString( buffer.toString() )` (at ui/src/main/java/org/pentaho/di/ui/trans/steps/scriptvalues_mod/ScriptValuesHelp.java line 96)

↘️ `DocumentBuilder db` (at core/src/main/java/org/pentaho/di/core/xml/XMLHandler.java line 741)

↘️ `db.parse( inputSource )` (at core/src/main/java/org/pentaho/di/core/xml/XMLHandler.java line 749)


</details>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
<div align='center'>

[🚨 Frogbot scanned this pull request and found the below:](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>




---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :x: Build failed in 3h 11m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl plugins/excel/core
```
---
:ok_hand: All tests passed!
 
Tests run: **117**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9629/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by rmansoor — APPROVED** [review]

**Pull request merged**
