### PR TITLE
[PDI-12920] Comment couldn't be updated after restore previously vers…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
[PDI-12920] Comment couldn't be updated after restore previously version of transformation (job).

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
@mbatchelor @pamval @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor @pamval @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@bmorrise please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor @pamval @mchen-len-son @bmorrise please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor @pamval @mchen-len-son @bmorrise please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor @pamval @mchen-len-son @bmorrise please review

**Comment by bmorrise** [comment]
@stanislau-strelchanka The changes look good. There was a conflict with the new header, which I resolved, but it created another commit. Can you rebase your original commit with master and push it back up?

**Comment by stanislau-strelchanka** [comment]
@bmorrise  updated, thanks

**Comment by stanislau-strelchanka** [comment]
looks like it complaining on "Hitachi Vantara" in license header
@mbatchelor @pamval @mchen-len-son @bmorrise please review

**Pull request merged**
