### PR TITLE
[TEST] - more test coverage for XmlOutputMeta

### PR DESCRIPTION
**Pull request by kurtwalker**

### CODE REVIEW

**Comment by kurtwalker** [comment]
@bytekast @DFieldFL @pminutillo

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/xmloutput/XMLOutputMeta.java
  engine/test-src/org/pentaho/di/trans/steps/xmloutput/XMLOutputMetaTest.java

Checkstyle violations:
======================
File engine/test-src/org/pentaho/di/trans/steps/xmloutput/XMLOutputMetaTest.java
1. Message: array initialization child at indentation level 12 not at correct indentation, 10 at Line: 400 Column: None
2. Message: array initialization child at indentation level 12 not at correct indentation, 10 at Line: 401 Column: None
3. Message: array initialization child at indentation level 12 not at correct indentation, 10 at Line: 402 Column: None
4. Message: array initialization child at indentation level 12 not at correct indentation, 10 at Line: 403 Column: None
5. Message: array initialization child at indentation level 12 not at correct indentation, 10 at Line: 404 Column: None
6. Message: array initialization child at indentation level 12 not at correct indentation, 10 at Line: 405 Column: None
7. Message: array initialization child at indentation level 12 not at correct indentation, 10 at Line: 406 Column: None
8. Message: array initialization child at indentation level 12 not at correct indentation, 10 at Line: 407 Column: None
9. Message: array initialization child at indentation level 12 not at correct indentation, 10 at Line: 408 Column: None
10. Message: array initialization child at indentation level 12 not at correct indentation, 10 at Line: 409 Column: None


License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange :**-0.08%**
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange : +7.14%
 * complexityPercentCoverageChange : +7.69%
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange : +0.28%
 * branchPercentCoverageChange : +3.33%
 * complexityPercentCoverageChange : +1.85%
    
org.pentaho.di.core.lifecycle.KettleLifecycleSupport:
 * branchPercentCoverageChange :**-8.33%**
 * complexityPercentCoverageChange :**-9.09%**
    
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange : +0.17%
    
org.pentaho.di.trans.steps.xmloutput.XMLField:
 * instructionPercentCoverageChange : +6.98%
 * linePercentCoverageChange : +8.20%
 * complexityPercentCoverageChange : +10.00%
 * methodPercentCoverageChange : +10.00%
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange : +0.18%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +0.19%
 * linePercentCoverageChange : +0.27%
    
org.pentaho.di.trans.steps.xmloutput.XMLOutputMeta:
 * instructionPercentCoverageChange : +32.39%
 * branchPercentCoverageChange : +46.51%
 * linePercentCoverageChange : +42.66%
 * complexityPercentCoverageChange : +36.53%
 * methodPercentCoverageChange : +45.45%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-1.97%**

**Comment by lucboudreau** [comment]
Wingman found checkstyle issues in this one. Please check if they need fixing, it might also be a wingman issue.

**Comment by kurtwalker** [comment]
This is one where intellij checkstyle is reporting differently from whatever checkstyle the build is using.  I'll take this opportunity to investigate

**Pull request merged**
