### PR TITLE
[BISERVER-13110] If there are some transformations/jobs which names differs only by whitespace/underscore symbol, only transformations/jobs with underscore symbol in it's name will be restored after backup/restore operation.

### PR DESCRIPTION
**Pull request by IvanNikolaychuk**
- Change name due to [KETTLE_COMPATIBILITY_PUR_OLD_NAMING_MODE property] (https://help.pentaho.com/Documentation/5.2/0T0/040/010) value. This property is specially created for handling such situations. 
- Remove duplicates of checkAndSanitize methods all over the project
- Checkstyle applied

[Here is an IT test] (https://github.com/pentaho/pentaho-kettle/blob/master/plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java#L560) covering this method. 
It wasn't covering this case before this PR, because checkAndSanitize method was duplicated over the project several time in different variations. IT test used the only correct written variation. For now all incorrect variations are removed and all calls refer to a correct one (that is tested in a link above)

@akhayrutdinov , review it please.

@pamval, @pedrofvteixeira , could you run WM on this PR?

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@pamval, @pedrofvteixeira , could you run WM on this PR?

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/92/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  plugins/pdi-pur-plugin/src/com/pentaho/repository/importexport/PDIImportFileHandler.java
  plugins/pdi-pur-plugin/src/com/pentaho/repository/importexport/PDIImportUtil.java
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/metastore/PurRepositoryMetaStore.java



Unit test coverage change:
============
com.pentaho.repository.importexport.PDIImportUtil:
 * Complexity Change :  + 28.57%
 * Instruction Change :  + 5.96%
 * Line Change :  + 3.91%
 * Method Change :  + 5.36%

org.pentaho.di.repository.pur.metastore.PurRepositoryMetaStore:
 * Branch Change :  + 2.13%
 * Complexity Change :  + 1.04%
 * Instruction Change :  + .47%
 * Line Change :  + .58%
 * Method Change :  + .32%



Integration test coverage change:
============
org.pentaho.di.repository.pur.metastore.PurRepositoryMetaStore:
 * Branch Change :  + 1.07%
 * Complexity Change :  + 2.57%
 * Instruction Change : **-.06%**
 * Line Change :  + .16%
 * Method Change : **-.38%**



Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java

1. Message: Using a static member import should be avoided - org.pentaho.di.repository.RepositoryObjectType.JOB. at Line: 21
2. Message: Using a static member import should be avoided - org.pentaho.di.repository.RepositoryObjectType.TRANSFORMATION. at Line: 22

**Comment by IvanNikolaychuk** [comment]
@brosander, could you please review this PR? (Andrey left our teem)
A also see static imports violations in RepositoryObjectType class. They are in a lot of places in the class and I consider them to fit well is this case: removing static imports will case readability problems.

**Comment by brosander** [comment]
@IvanNikolaychuk as far as I'm aware, our direction is to follow the style guidelines, it may make sense though to add certain constant-type classes to our exception list

@lucboudreau thoughts?

**Comment by IvanNikolaychuk** [comment]
@lucboudreau what is your opinion about static imports in this case?

**Comment by lucboudreau** [comment]
That's the first time we see those as static imports. I think we can do without them for now. Please make them non-static. If you think of using them more often (and I really mean everywhere, not here and there), then please let it be known and we'll add them. Again, in this case, I don't think they are needed.

**Comment by IvanNikolaychuk** [comment]
static importes removed now.
@pamval, @pedrofvteixeira, could you please run WM?

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/15/

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  plugins/pdi-pur-plugin/src/com/pentaho/repository/importexport/PDIImportFileHandler.java
  plugins/pdi-pur-plugin/src/com/pentaho/repository/importexport/PDIImportUtil.java
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/metastore/PurRepositoryMetaStore.java



Unit test coverage change:
============
com.pentaho.repository.importexport.PDIImportUtil:
 * Complexity Change :  + 28.57%
 * Instruction Change :  + 5.96%
 * Line Change :  + 3.91%
 * Method Change :  + 5.36%

org.pentaho.di.repository.pur.metastore.PurRepositoryMetaStore:
 * Branch Change :  + 2.13%
 * Complexity Change :  + 1.04%
 * Instruction Change :  + .47%
 * Line Change :  + .58%
 * Method Change :  + .32%



Integration test coverage change:
============
org.pentaho.di.repository.pur.metastore.PurRepositoryMetaStore:
 * Branch Change :  + 1.07%
 * Complexity Change :  + 2.57%
 * Instruction Change : **-.06%**
 * Line Change :  + .16%
 * Method Change : **-.38%**

**Comment by IvanNikolaychuk** [comment]
@brosander, all checks are passing now

**Comment by IvanNikolaychuk** [comment]
@brosander, could you please review it?

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/21/

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/pdi-pur-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  plugins/pdi-pur-plugin/src/com/pentaho/repository/importexport/PDIImportFileHandler.java
  plugins/pdi-pur-plugin/src/com/pentaho/repository/importexport/PDIImportUtil.java
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/metastore/PurRepositoryMetaStore.java



Unit test coverage change:
============
com.pentaho.repository.importexport.PDIImportUtil:
 * Complexity Change :  + 28.57%
 * Instruction Change :  + 5.96%
 * Line Change :  + 3.91%
 * Method Change :  + 5.36%

org.pentaho.di.repository.pur.metastore.PurRepositoryMetaStore:
 * Branch Change :  + 2.13%
 * Complexity Change :  + 1.04%
 * Instruction Change :  + .47%
 * Line Change :  + .58%
 * Method Change :  + .32%



Integration test coverage change:
============
org.pentaho.di.repository.pur.metastore.PurRepositoryMetaStore:
 * Branch Change :  + 1.07%
 * Complexity Change :  + 2.57%
 * Instruction Change : **-.06%**
 * Line Change :  + .16%
 * Method Change : **-.38%**

**Comment by IvanNikolaychuk** [comment]
@brosander, can it be merged now? 
Thanks!

**Pull request merged**
