### PR TITLE
[PDI-15344] Date A - Date B (working days) Calculation returns incorrect

### PR DESCRIPTION
**Pull request by denisprotopopov**
values
 - DateWorkingDiff calculation now considers last day of month
 - added unit test (divided tests into separate ones by months since in case of errors some months are failing some not)

### CODE REVIEW

**Comment by denisprotopopov** [comment]
@mchen-len-son @pamval please review the changes

**Comment by mbatchelor** [comment]
Running wingman on it.

**Comment by mchen-len-son** [comment]
Run wingman on it:
http://wingman.pentaho.com:8080/job/wingman/3828

**Comment by denisprotopopov** [comment]
@mchen-len-son @pamval please review the changes

**Comment by mchen-len-son** [comment]
Double-checked locally.
The tests are passing, checkstyle is OK.
Merging.

**Pull request merged**
