### PR TITLE
[SP-6550] Backport of PDI-20109, PDI-20119 and PDI-20120

### PR DESCRIPTION
**Pull request by smmribeiro**
Original PRs:
- [pentaho-kettle#9357](https://github.com/pentaho/pentaho-kettle/pull/9357)
- [pentaho-kettle#9404](https://github.com/pentaho/pentaho-kettle/pull/9404)
- [pentaho-kettle#9406](https://github.com/pentaho/pentaho-kettle/pull/9406)

Note: for PDI-20109 the implementation had to be adapted to the 9.3 code base.

@pentaho/tatooine_dev  @rmansoor

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 5s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
no protocol: repo.orl.eng.hitachivantara.com
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by rmansoor — APPROVED** [review]

**Comment by buildguy** [comment]
### :x: Build failed in 6s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
no protocol: repo.orl.eng.hitachivantara.com
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 3s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
no protocol: repo.orl.eng.hitachivantara.com
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 5s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
no protocol: repo.orl.eng.hitachivantara.com
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 4s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
no protocol: repo.orl.eng.hitachivantara.com
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
Wingman is having some internal problems.

**Comment by buildguy** [comment]
### :x: Build failed in 26m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3890**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi-jdk11/job/PR-9417/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Pull request merged**
