### PR TITLE
[PDI-17126] Fixes regression for fields without a specified metadata …

### PR DESCRIPTION
**Pull request by pentaho-lmartins**
…length.

This fixes a regression introduced by #5496.

@bantonio82 @ricardosilva88, please review. See JIRA case for details.

### CODE REVIEW

**Comment by pentaho-lmartins** [comment]
@e-cuellar, please review.

**Comment by e-cuellar** [comment]
@pentaho-lmartins Looks good..... Could you just make sure that this doesn't cause a regression on https://jira.pentaho.com/browse/BACKLOG-24034?

Thanks.

**Comment by e-cuellar** [comment]
@pentaho-lmartins If maxlen ends up being -1 it will cause a java.lang.StringIndexOutOfBoundsException

**Comment by pentaho-lmartins** [comment]
@e-cuellar, already tested.

**Comment by pentaho-lmartins** [comment]
@e-cuellar, no `maxlen` will be either the length of the string, the length defined in the metadata of the field or the max length defined in the db dialect.

**Comment by pentaho-lmartins** [comment]
@mbatchelor, please review.

**Pull request merged**
