### PR TITLE
[PRD-5778]-JDBC connection details still remains even after removing from Options tab for MsSQL connections.JDBC connection details still remains

### PR DESCRIPTION
**Pull request by denisprotopopov**
- set using pluginId insteadof constant
 - add unit test

### CODE REVIEW

**Comment by denisprotopopov** [comment]
@pamval @mchen-len-son please review the changes

**Comment by tmorgner** [comment]
I dont think that code actually changes anything. It just takes the hardcoded plugin id "MSSQL" and replaces it with a non-hardcoded one. But the property in question is only valid for MSSQL database connections, so the code will now still work largely as before. I cannot see how it is going to fix the PRD problem.

As PRD stores the properties for connections outside of the database-meta interface, the error probably lies there instead. DatabaseMeta is only used for feeding the dialog, after that we extract all properties and set them as JDBC properties on the Driver-connection  definition. I would assume it is that code (in PRD) that does not handle the case where a property has gone away.

**Comment by denisprotopopov** [comment]
As I understand user can create 2 types of connection for MS SQL (MS SQL SERVER and MS SQL SERVER Native). They have different pluginIds.
Connection for MS SQL Server (Native) has PluginId=MSSQLNATIVE so in https://github.com/pentaho/pentaho-reporting/blob/master/designer/datasource-editor-jdbc/source/org/pentaho/reporting/ui/datasources/jdbc/ui/XulDatabaseDialog.java#L294 
We received realkey='ce' instead of 'instance' for key=MSSQLNATIVE.instance

**Comment by tmorgner** [comment]
Wow, ok, that is a connection so strange that I would not have foreseen it. I stand corrected.

**Pull request merged**
