### PR TITLE
[PDI-19906] - Google BigQuery Simba driver version 1.3.3.1004 in Pentaho

### PR DESCRIPTION
**Pull request by bcostahitachivantara**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1h 24m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **5327**, Failures: **0**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9050/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good.

**Comment by buildguy** [comment]
### :warning: Build finished in 1h 6m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 10 test(s) failed:

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_LowResourceMaxIdleTimeSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_LowResourceMaxIdleTimeSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptQueueSizeSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptQueueSizeSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptorsSetUp</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testJettyOption_AcceptorsSetUp</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsEmpty</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsEmpty</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsInvalidValue</b> (click to expand)</summary><p>

```
org/eclipse/jetty/util/component/AttributeContainerMap
```

</p></details>

<details><summary><b>org.pentaho.di.www.WebServerTest.testNoExceptionAndUsingDefaultServerValue_WhenJettyOptionSetAsInvalidValue</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **5332**, Failures: **10**, Skipped: **14** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pdi/job/PR-9050/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
These 10 unit tests that failed, are failing on master; so they are not related with the code on this PR.

**Pull request merged**
