### PR TITLE
[SP-6415] - Backport of PPP-4620 - Use of Vulnerable Component: Components/xmlrpc-client:3.1.3 (9.3 Suite)

### PR DESCRIPTION
**Pull request by andreramos89**
Original PR: https://github.com/pentaho/pentaho-kettle/pull/9003

@renato-s 
@smmribeiro 
@bcostahitachivantara

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
[FATAL] Non-readable POM /build/wingman/workspace/maintenance/wingman/builds/pentaho.pentaho-kettle.PR-9052/plugins/openerp/pom.xml: /build/wingman/workspace/maintenance/wingman/builds/pentaho.pentaho-kettle.PR-9052/plugins/openerp/pom.xml (No such file or directory) @
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
[FATAL] Non-readable POM /build/wingman/workspace/maintenance/wingman/builds/pentaho.pentaho-kettle.PR-9052/plugins/openerp/pom.xml: /build/wingman/workspace/maintenance/wingman/builds/pentaho.pentaho-kettle.PR-9052/plugins/openerp/pom.xml (No such file or directory) @
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 43s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PR.

**Comment by smmribeiro** [comment]
Wingman fails to compile this PR for 9.3, stating "[ERROR] 'dependencies.dependency.version' for org.apache.jackrabbit:jackrabbit-api:jar is missing. @ line 361, column 17".
This, most probably, is related with wingman's artifactory...
As this PR is a "simple" deletion of two modules, I'm merging it anyway.

**Pull request merged**
