### PR TITLE
[PDI-18868] - The Text File Input step does not handle line breaks correctly

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@pentaho-lmartins 
@ssamora 
@ppatricio 
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 33m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.fileinput.text.TextFileInputTest.fieldsWithLineBreaksAndNoEmptyLinesTest</b> (click to expand)</summary><p>

```
[0][1] expected:<"b[]bb"> but was:<"b[
]bb">
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.fileinput.text.TextFileInputTest.fieldsWithLineBreaksWithEmptyLinesTest</b> (click to expand)</summary><p>

```
[0][1] expected:<"b[]bb"> but was:<"b[
]bb">
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.fileinput.text.TextFileInputTest.fieldsWithLineBreaksTest</b> (click to expand)</summary><p>

```
[0][1] expected:<"b[]bb"> but was:<"b[
]bb">
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.fileinput.text.TextFileInputUtilsTest.getLineBrokenByEnclosureTest</b> (click to expand)</summary><p>

```
expected:<"firstLine[]""secondLine"> but was:<"firstLine[
]""secondLine">
```

</p></details>

  
Tests run: **3746**, Failures: **4**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7666/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3745**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7666/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 32m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.di.trans.step.mqtt.MQTTStreamSourceTest.mqttReadsBinary</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **3745**, Failures: **1**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7666/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3745**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7666/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ssamora** [comment]
changes look ok, and related cases were validated also with this change.

**Review by ssamora — APPROVED** [review]

**Pull request merged**
