### PR TITLE
[SP-2523][PDI-14413] Step Synchronize after merge - issue with mode "…

### PR DESCRIPTION
**Pull request by SergeyTravin**
…use batch update"

- batch will be executed after last row readed, independet from batch size.

Conflicts:
	engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeTest.java

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@tgf, @pamval, could you please start WM?

**Comment by pamval** [comment]
running

**Comment by SergeyTravin** [comment]
@tgf, @pamval, looks like the WM was failed. Could you please restart WM or give some information about it? Thanks!

**Comment by pamval** [comment]
It's not publishing the results. I see this in the logs:

Newly Broken Tests:
-----------------
org.pentaho.di.trans.steps.textfileinput.TextFileInputMetaLoadSaveTest.message: 
```

```
org.pentaho.di.trans.steps.textfileinput.TextFileInputMetaLoadSaveTest.type: 
```

```
org.pentaho.di.trans.steps.textfileinput.TextFileInputMetaLoadSaveTest.severity: 
```

```

**Comment by pamval** [comment]
anyway, @akhayrutdinov please review manually. thanks.

**Comment by akhayrutdinov** [comment]
sorry, don't have time for it now.
@mtseu, @kolinus, @PavelSakoun can anyone of you review it please?

**Comment by kolinus** [comment]
@pamval, could you please rerun WM on updated commit?

**Comment by pedrofvteixeira** [comment]
[wingman](http://10.100.11.222:8080/job/wingman-ant/417)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMerge.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchMockDriver.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeIT.java
  engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeTest.java










Unit test coverage change:
============
org.pentaho.di.trans.Trans:
 * instructionPercentCoverageChange :**-1.21%**
 * branchPercentCoverageChange :**-1.21%**
 * linePercentCoverageChange :**-1.14%**
 * complexityPercentCoverageChange :**-1.27%**
    
org.pentaho.di.trans.steps.randomvalue.RandomValueMeta:
 * instructionPercentCoverageChange :**-0.15%**
 * branchPercentCoverageChange :**-2.08%**
 * complexityPercentCoverageChange :**-2.13%**
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange :**-7.14%**
 * complexityPercentCoverageChange :**-7.69%**
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange :**-0.28%**
 * branchPercentCoverageChange :**-3.33%**
 * complexityPercentCoverageChange :**-1.85%**
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange :**-1.09%**
 * branchPercentCoverageChange :**-2.74%**
 * linePercentCoverageChange :**-0.53%**
 * complexityPercentCoverageChange :**-1.17%**
 * methodPercentCoverageChange :**-1.02%**
    
org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * instructionPercentCoverageChange : +0.07%
    
org.pentaho.di.trans.TransMeta:
 * instructionPercentCoverageChange :**-0.80%**
 * branchPercentCoverageChange :**-1.48%**
 * linePercentCoverageChange :**-0.74%**
 * complexityPercentCoverageChange :**-0.95%**
    
org.pentaho.di.trans.step.StepInitThread:
 * instructionPercentCoverageChange :**-13.07%**
 * branchPercentCoverageChange :**-25.00%**
 * linePercentCoverageChange :**-6.25%**
 * complexityPercentCoverageChange :**-8.33%**
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange : +0.18%
    
org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * instructionPercentCoverageChange :**-2.43%**
 * branchPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-3.70%**
 * complexityPercentCoverageChange :**-0.69%**
    
org.pentaho.di.trans.step.BaseStep:
 * instructionPercentCoverageChange :**-1.23%**
 * branchPercentCoverageChange :**-1.77%**
 * linePercentCoverageChange :**-1.53%**
 * complexityPercentCoverageChange :**-1.28%**
    
org.pentaho.di.trans.TransHopMeta:
 * instructionPercentCoverageChange :**-1.01%**
 * linePercentCoverageChange :**-1.35%**
 * complexityPercentCoverageChange :**-2.78%**
 * methodPercentCoverageChange :**-4.17%**
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +1.95%
    
Integration test coverage change:
============
org.pentaho.di.core.logging.StepLogTable.ID:
 * linePercentCoverage :90.00%
 * methodPercentCoverage :40.00%
 * complexityPercentCoverage :40.00%
 * instructionPercentCoverage :93.26%
    
org.pentaho.di.trans.steps.dummytrans.DummyTransData:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.core.auth.AuthenticationConsumerPluginType:
 * linePercentCoverage :28.00%
 * methodPercentCoverage :27.78%
 * complexityPercentCoverage :27.78%
 * instructionPercentCoverage :22.22%
    
org.pentaho.di.core.logging.ChannelLogTable:
 * linePercentCoverage :36.07%
 * methodPercentCoverage :28.57%
 * complexityPercentCoverage :10.53%
 * instructionPercentCoverage :53.32%
    
org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMerge:
 * branchPercentCoverage :42.86%
 * linePercentCoverage :52.80%
 * methodPercentCoverage :90.00%
 * complexityPercentCoverage :22.16%
 * instructionPercentCoverage :50.07%
    
org.pentaho.di.trans.steps.injector.Injector:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :90.91%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :80.00%
 * instructionPercentCoverage :68.09%
    
org.pentaho.di.core.lifecycle.KettleLifecycleSupport:
 * branchPercentCoverage :33.33%
 * linePercentCoverage :39.47%
 * methodPercentCoverage :80.00%
 * complexityPercentCoverage :36.36%
 * instructionPercentCoverage :37.74%
    
org.pentaho.di.core.plugins.KettleLifecyclePluginType:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :50.00%
 * methodPercentCoverage :25.00%
 * complexityPercentCoverage :20.00%
 * instructionPercentCoverage :45.00%
    
org.pentaho.di.core.logging.TransLogTable:
 * linePercentCoverage :17.89%
 * methodPercentCoverage :20.00%
 * complexityPercentCoverage :9.76%
 * instructionPercentCoverage :43.38%
    
org.pentaho.di.core.logging.PerformanceLogTable.ID:
 * linePercentCoverage :90.00%
 * methodPercentCoverage :40.00%
 * complexityPercentCoverage :40.00%
 * instructionPercentCoverage :93.65%
    
org.pentaho.di.trans.TransMeta.TransformationType:
 * linePercentCoverage :47.62%
 * methodPercentCoverage :37.50%
 * complexityPercentCoverage :25.00%
 * instructionPercentCoverage :53.17%
    
org.pentaho.di.core.logging.PerformanceLogTable:
 * linePercentCoverage :21.74%
 * methodPercentCoverage :26.32%
 * complexityPercentCoverage :11.90%
 * instructionPercentCoverage :52.83%
    
org.pentaho.di.core.plugins.JobEntryPluginType:
 * branchPercentCoverage :60.00%
 * linePercentCoverage :53.73%
 * methodPercentCoverage :35.00%
 * complexityPercentCoverage :33.33%
 * instructionPercentCoverage :49.06%
    
org.pentaho.di.trans.step.BaseStepMeta:
 * branchPercentCoverage :2.50%
 * linePercentCoverage :7.53%
 * methodPercentCoverage :6.59%
 * complexityPercentCoverage :5.41%
 * instructionPercentCoverage :5.25%
    
org.pentaho.di.trans.step.StepPartitioningMeta:
 * branchPercentCoverage :1.47%
 * linePercentCoverage :7.75%
 * methodPercentCoverage :10.71%
 * complexityPercentCoverage :4.84%
 * instructionPercentCoverage :9.25%
    
org.pentaho.di.core.plugins.RepositoryPluginType:
 * branchPercentCoverage :71.43%
 * linePercentCoverage :49.02%
 * methodPercentCoverage :25.00%
 * complexityPercentCoverage :30.43%
 * instructionPercentCoverage :48.58%
    
org.pentaho.di.core.plugins.ImportRulePluginType:
 * branchPercentCoverage :62.50%
 * linePercentCoverage :55.56%
 * methodPercentCoverage :23.53%
 * complexityPercentCoverage :23.81%
 * instructionPercentCoverage :59.23%
    
org.pentaho.di.core.KettleEnvironment:
 * branchPercentCoverage :22.22%
 * linePercentCoverage :67.74%
 * methodPercentCoverage :70.00%
 * complexityPercentCoverage :36.84%
 * instructionPercentCoverage :54.44%
    
org.pentaho.di.partition.PartitionSchema:
 * linePercentCoverage :5.10%
 * methodPercentCoverage :5.71%
 * complexityPercentCoverage :4.76%
 * instructionPercentCoverage :4.24%
    
org.pentaho.di.trans.steps.injector.InjectorData:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.core.plugins.PartitionerPluginType:
 * branchPercentCoverage :62.50%
 * linePercentCoverage :49.02%
 * methodPercentCoverage :23.53%
 * complexityPercentCoverage :28.00%
 * instructionPercentCoverage :51.76%
    
org.pentaho.di.trans.Trans.new ThreadFactory() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.core.plugins.LifecyclePluginType:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :50.00%
 * methodPercentCoverage :33.33%
 * complexityPercentCoverage :31.58%
 * instructionPercentCoverage :41.43%
    
org.pentaho.di.trans.step.BaseStep:
 * branchPercentCoverage :20.38%
 * linePercentCoverage :27.96%
 * methodPercentCoverage :34.63%
 * complexityPercentCoverage :17.30%
 * instructionPercentCoverage :23.93%
    
org.pentaho.di.core.attributes.metastore.EmbeddedMetaStore:
 * linePercentCoverage :7.27%
 * methodPercentCoverage :3.57%
 * complexityPercentCoverage :3.12%
 * instructionPercentCoverage :3.67%
    
org.pentaho.di.core.logging.MetricsLogTable:
 * linePercentCoverage :20.00%
 * methodPercentCoverage :28.57%
 * complexityPercentCoverage :12.90%
 * instructionPercentCoverage :50.10%
    
org.pentaho.di.core.changed.ChangedFlag:
 * linePercentCoverage :19.23%
 * methodPercentCoverage :25.00%
 * complexityPercentCoverage :16.67%
 * instructionPercentCoverage :18.63%
    
org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeMeta:
 * linePercentCoverage :12.20%
 * methodPercentCoverage :73.21%
 * complexityPercentCoverage :29.93%
 * instructionPercentCoverage :5.65%
    
org.pentaho.di.trans.step.StepMeta:
 * branchPercentCoverage :8.90%
 * linePercentCoverage :14.51%
 * methodPercentCoverage :23.47%
 * complexityPercentCoverage :14.62%
 * instructionPercentCoverage :12.69%
    
org.pentaho.di.trans.step.BaseStepData.StepExecutionStatus:
 * linePercentCoverage :87.50%
 * methodPercentCoverage :33.33%
 * complexityPercentCoverage :33.33%
 * instructionPercentCoverage :91.53%
    
org.pentaho.di.core.auth.AuthenticationProviderPluginType:
 * branchPercentCoverage :66.67%
 * linePercentCoverage :55.88%
 * methodPercentCoverage :29.41%
 * complexityPercentCoverage :30.00%
 * instructionPercentCoverage :53.52%
    
org.pentaho.di.core.logging.StepLogTable:
 * linePercentCoverage :25.74%
 * methodPercentCoverage :28.57%
 * complexityPercentCoverage :11.43%
 * instructionPercentCoverage :56.47%
    
org.pentaho.di.core.plugins.CartePluginType:
 * branchPercentCoverage :54.55%
 * linePercentCoverage :49.12%
 * methodPercentCoverage :25.00%
 * complexityPercentCoverage :25.93%
 * instructionPercentCoverage :45.34%
    
org.pentaho.di.trans.step.StepErrorMeta:
 * linePercentCoverage :12.70%
 * methodPercentCoverage :24.14%
 * complexityPercentCoverage :17.95%
 * instructionPercentCoverage :8.48%
    
org.pentaho.di.core.KettleVariablesList:
 * branchPercentCoverage :62.50%
 * linePercentCoverage :89.66%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :88.79%
    
org.pentaho.di.trans.steps.dummytrans.DummyTrans:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :83.33%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :62.75%
    
org.pentaho.di.trans.TransMeta:
 * branchPercentCoverage :3.13%
 * linePercentCoverage :6.68%
 * methodPercentCoverage :12.27%
 * complexityPercentCoverage :4.86%
 * instructionPercentCoverage :5.65%
    
org.pentaho.di.trans.step.RowDistributionPluginType:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :34.78%
 * methodPercentCoverage :22.22%
 * complexityPercentCoverage :21.05%
 * instructionPercentCoverage :31.15%
    
org.pentaho.di.trans.step.StepAdapter:
 * linePercentCoverage :33.33%
 * methodPercentCoverage :33.33%
 * complexityPercentCoverage :33.33%
 * instructionPercentCoverage :60.00%
    
org.pentaho.di.trans.steps.synchronizeaftermerge.SynchronizeAfterMergeData:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.base.AbstractMeta:
 * branchPercentCoverage :8.00%
 * linePercentCoverage :18.75%
 * methodPercentCoverage :20.42%
 * complexityPercentCoverage :13.42%
 * instructionPercentCoverage :17.88%
    
org.pentaho.di.core.logging.LogTablePluginType:
 * branchPercentCoverage :60.00%
 * linePercentCoverage :36.11%
 * methodPercentCoverage :25.00%
 * complexityPercentCoverage :28.57%
 * instructionPercentCoverage :35.43%
    
org.pentaho.di.core.compress.CompressionPluginType:
 * branchPercentCoverage :62.50%
 * linePercentCoverage :52.63%
 * methodPercentCoverage :22.22%
 * complexityPercentCoverage :22.73%
 * instructionPercentCoverage :49.68%
    
org.pentaho.di.core.lifecycle.LifecycleSupport:
 * branchPercentCoverage :16.67%
 * linePercentCoverage :19.23%
 * methodPercentCoverage :40.00%
 * complexityPercentCoverage :25.00%
 * instructionPercentCoverage :18.81%
    
org.pentaho.di.trans.steps.dummytrans.DummyTransMeta:
 * linePercentCoverage :16.67%
 * methodPercentCoverage :33.33%
 * complexityPercentCoverage :26.67%
 * instructionPercentCoverage :16.38%
    
org.pentaho.di.trans.Trans:
 * branchPercentCoverage :13.32%
 * linePercentCoverage :19.08%
 * methodPercentCoverage :26.32%
 * complexityPercentCoverage :10.86%
 * instructionPercentCoverage :17.39%
    
org.pentaho.di.core.lifecycle.KettleLifecycleSupport.new PluginTypeListener() {...}:
 * linePercentCoverage :5.88%
 * methodPercentCoverage :25.00%
 * complexityPercentCoverage :20.00%
 * instructionPercentCoverage :12.00%
    
org.pentaho.di.trans.steps.injector.InjectorMeta:
 * linePercentCoverage :12.50%
 * methodPercentCoverage :20.83%
 * complexityPercentCoverage :16.13%
 * instructionPercentCoverage :8.61%
    
org.pentaho.di.core.plugins.StepPluginType:
 * branchPercentCoverage :54.55%
 * linePercentCoverage :47.46%
 * methodPercentCoverage :23.53%
 * complexityPercentCoverage :25.00%
 * instructionPercentCoverage :44.44%
    
org.pentaho.di.core.logging.BaseLogTable:
 * branchPercentCoverage :7.43%
 * linePercentCoverage :17.73%
 * methodPercentCoverage :20.51%
 * complexityPercentCoverage :7.96%
 * instructionPercentCoverage :11.81%
    
org.pentaho.di.trans.step.RunThread:
 * branchPercentCoverage :26.00%
 * linePercentCoverage :59.26%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :21.43%
 * instructionPercentCoverage :30.04%
    
org.pentaho.di.trans.RowProducer:
 * branchPercentCoverage :75.00%
 * linePercentCoverage :61.90%
 * methodPercentCoverage :44.44%
 * complexityPercentCoverage :45.45%
 * instructionPercentCoverage :56.92%
    
org.pentaho.di.trans.Trans.new Object() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :88.46%
    
org.pentaho.di.core.KettleEnvironment.new Thread() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.di.trans.step.StepInitThread:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :59.38%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :41.67%
 * instructionPercentCoverage :47.71%
    
org.pentaho.di.trans.step.StepMetaDataCombi:
 * linePercentCoverage :50.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :42.86%
    
org.pentaho.di.core.logging.MetricsLogTable.ID:
 * linePercentCoverage :91.67%
 * methodPercentCoverage :40.00%
 * complexityPercentCoverage :40.00%
 * instructionPercentCoverage :90.24%
    
org.pentaho.di.core.logging.TransLogTable.ID:
 * linePercentCoverage :90.91%
 * methodPercentCoverage :40.00%
 * complexityPercentCoverage :40.00%
 * instructionPercentCoverage :95.08%
    
org.pentaho.di.trans.TransAdapter:
 * linePercentCoverage :25.00%
 * methodPercentCoverage :25.00%
 * complexityPercentCoverage :25.00%
 * instructionPercentCoverage :50.00%
    
org.pentaho.di.trans.TransHopMeta:
 * linePercentCoverage :13.51%
 * methodPercentCoverage :20.83%
 * complexityPercentCoverage :13.89%
 * instructionPercentCoverage :9.09%
    
org.pentaho.di.trans.SlaveStepCopyPartitionDistribution:
 * linePercentCoverage :4.62%
 * methodPercentCoverage :10.00%
 * complexityPercentCoverage :5.00%
 * instructionPercentCoverage :2.49%
    
org.pentaho.di.core.logging.ChannelLogTable.ID:
 * linePercentCoverage :88.89%
 * methodPercentCoverage :40.00%
 * complexityPercentCoverage :40.00%
 * instructionPercentCoverage :92.31%
    
org.pentaho.di.trans.Trans.new StepListener() {...}:
 * branchPercentCoverage :37.50%
 * linePercentCoverage :40.74%
 * methodPercentCoverage :66.67%
 * complexityPercentCoverage :42.86%
 * instructionPercentCoverage :31.16%
    
org.pentaho.di.trans.Trans.new StepAdapter() {...}:
 * linePercentCoverage :66.67%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :73.08%
    
org.pentaho.di.trans.step.BaseStepData:
 * linePercentCoverage :50.00%
 * methodPercentCoverage :36.36%
 * complexityPercentCoverage :22.22%
 * instructionPercentCoverage :22.22%

**Pull request merged**
