### PR TITLE
[TEST] Add clone method checks

### PR DESCRIPTION
**Pull request by matthewtckr**
Ensure when a step meta is cloned, that it contains all of the same information as XML or Repository serialization.

### CODE REVIEW

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/18/

**Comment by lucboudreau** [comment]
This wingman job failed ^^

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/20/

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman/41/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  engine/test-src/org/pentaho/di/job/entry/loadSave/LoadSaveTester.java
  engine/test-src/org/pentaho/di/trans/steps/loadsave/LoadSaveTester.java



Unit test coverage change:
============
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change : **-7.14%**
 * Complexity Change : **-7.69%**

org.pentaho.di.job.entries.abort.JobEntryAbort:
 * Complexity Change :  + 5.88%
 * Instruction Change :  + 3.14%
 * Line Change :  + 3.77%
 * Method Change :  + 6.25%

org.pentaho.di.job.entries.addresultfilenames.JobEntryAddResultFilenames:
 * Complexity Change :  + 1.69%
 * Instruction Change :  + .68%
 * Line Change :  + 1.18%
 * Method Change :  + 4.76%

org.pentaho.di.job.entries.checkfilelocked.JobEntryCheckFilesLocked:
 * Branch Change :  + 1.39%
 * Complexity Change :  + 1.75%
 * Instruction Change :  + 1.10%
 * Line Change :  + 1.85%
 * Method Change :  + 4.76%

org.pentaho.di.job.entries.connectedtorepository.JobEntryConnectedToRepository:
 * Complexity Change :  + 3.45%
 * Instruction Change :  + 1.47%
 * Line Change :  + 2.27%
 * Method Change :  + 5.26%

org.pentaho.di.job.entries.copyfiles.JobEntryCopyFiles:
 * Branch Change :  + .62%
 * Complexity Change :  + .82%
 * Instruction Change :  + .47%
 * Line Change :  + .85%
 * Method Change :  + 2.38%

org.pentaho.di.job.entries.copymoveresultfilenames.JobEntryCopyMoveResultFilenames:
 * Complexity Change :  + .85%
 * Instruction Change :  + .36%
 * Line Change :  + .58%
 * Method Change :  + 1.89%

org.pentaho.di.job.entries.createfile.JobEntryCreateFile:
 * Complexity Change :  + 3.23%
 * Instruction Change :  + 1.28%
 * Line Change :  + 1.89%
 * Method Change :  + 5.00%

org.pentaho.di.job.entries.createfolder.JobEntryCreateFolder:
 * Complexity Change :  + 3.85%
 * Instruction Change :  + 1.64%
 * Line Change :  + 2.41%
 * Method Change :  + 6.25%

org.pentaho.di.job.entries.delay.JobEntryDelay:
 * Complexity Change :  + 3.70%
 * Instruction Change :  + 1.69%
 * Line Change :  + 2.44%
 * Method Change :  + 5.56%

org.pentaho.di.job.entries.deletefile.JobEntryDeleteFile:
 * Complexity Change :  + 3.45%
 * Instruction Change :  + 1.45%
 * Line Change :  + 2.17%
 * Method Change :  + 5.56%

org.pentaho.di.job.entries.deletefiles.JobEntryDeleteFiles:
 * Branch Change :  + 1.25%
 * Complexity Change :  + 1.64%
 * Instruction Change :  + 1.06%
 * Line Change :  + 1.78%
 * Method Change :  + 4.76%

org.pentaho.di.job.entries.deletefolders.JobEntryDeleteFolders:
 * Branch Change :  + 1.02%
 * Complexity Change :  + 1.35%
 * Instruction Change :  + .92%
 * Line Change :  + 1.53%
 * Method Change :  + 4.00%

org.pentaho.di.job.entries.deleteresultfilenames.JobEntryDeleteResultFilenames:
 * Complexity Change :  + 2.78%
 * Instruction Change :  + 1.26%
 * Line Change :  + 1.96%
 * Method Change :  + 4.76%

org.pentaho.di.job.entries.dostounix.JobEntryDosToUnix:
 * Branch Change :  + .50%
 * Complexity Change :  + .73%
 * Instruction Change :  + .47%
 * Line Change :  + .80%
 * Method Change :  + 2.78%

org.pentaho.di.job.entries.filecompare.JobEntryFileCompare:
 * Complexity Change :  + 1.96%
 * Instruction Change :  + .93%
 * Line Change :  + 1.46%
 * Method Change :  + 4.76%

org.pentaho.di.job.entries.fileexists.JobEntryFileExists:
 * Complexity Change :  + 4.55%
 * Instruction Change :  + 2.08%
 * Line Change :  + 2.90%
 * Method Change :  + 6.25%

org.pentaho.di.job.entries.folderisempty.JobEntryFolderIsEmpty:
 * Complexity Change :  + 2.86%
 * Instruction Change :  + 1.26%
 * Line Change :  + 1.82%
 * Method Change :  + 4.55%

org.pentaho.di.job.entries.folderscompare.JobEntryFoldersCompare:
 * Complexity Change :  + 1.08%
 * Instruction Change :  + .44%
 * Line Change :  + .75%
 * Method Change :  + 3.33%

org.pentaho.di.job.entries.ftpput.JobEntryFTPPUT:
 * Complexity Change :  + .83%
 * Instruction Change :  + .32%
 * Line Change :  + .52%
 * Method Change :  + 1.75%

org.pentaho.di.job.entries.ftpsget.FTPSConnection:
 * Branch Change : **-1.56%**
 * Complexity Change : **-1.37%**
 * Instruction Change : **-.23%**

org.pentaho.di.job.entries.ftpsput.JobEntryFTPSPUT:
 * Complexity Change :  + 1.18%
 * Instruction Change :  + .42%
 * Line Change :  + .70%
 * Method Change :  + 2.13%

org.pentaho.di.job.entries.mailvalidator.JobEntryMailValidator:
 * Complexity Change :  + 3.12%
 * Instruction Change :  + 1.22%
 * Line Change :  + 1.82%
 * Method Change :  + 4.76%

org.pentaho.di.job.entries.movefiles.JobEntryMoveFiles:
 * Branch Change :  + .25%
 * Complexity Change :  + .37%
 * Instruction Change :  + .23%
 * Line Change :  + .41%
 * Method Change :  + 1.54%

org.pentaho.di.job.entries.msgboxinfo.JobEntryMsgBoxInfo:
 * Complexity Change :  + 4.55%
 * Instruction Change :  + 2.54%
 * Line Change :  + 3.23%
 * Method Change :  + 5.26%

org.pentaho.di.job.entries.pgpverify.JobEntryPGPVerify:
 * Complexity Change :  + 2.70%
 * Instruction Change :  + 1.28%
 * Line Change :  + 1.87%
 * Method Change :  + 4.76%

org.pentaho.di.job.entries.ping.JobEntryPing:
 * Complexity Change :  + 1.85%
 * Instruction Change :  + .68%
 * Line Change :  + 1.17%
 * Method Change :  + 4.35%

org.pentaho.di.job.entries.sendnagiospassivecheck.JobEntrySendNagiosPassiveCheck:
 * Complexity Change :  + 1.41%
 * Instruction Change :  + .61%
 * Line Change :  + .90%
 * Method Change :  + 2.50%

org.pentaho.di.job.entries.simpleeval.JobEntrySimpleEval:
 * Complexity Change :  + .43%
 * Instruction Change :  + .20%
 * Line Change :  + .32%
 * Method Change :  + 2.08%

org.pentaho.di.job.entries.snmptrap.JobEntrySNMPTrap:
 * Complexity Change :  + 1.96%
 * Instruction Change :  + .61%
 * Line Change :  + .97%
 * Method Change :  + 2.94%

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Complexity Change :  + 1.64%
 * Instruction Change :  + .82%
 * Line Change :  + 1.29%
 * Method Change :  + 3.85%

org.pentaho.di.job.entries.syslog.JobEntrySyslog:
 * Complexity Change :  + 2.94%
 * Instruction Change :  + 1.11%
 * Line Change :  + 1.64%
 * Method Change :  + 3.70%

org.pentaho.di.job.entries.talendjobexec.JobEntryTalendJobExec:
 * Complexity Change :  + 3.23%
 * Instruction Change :  + 1.15%
 * Line Change :  + 1.82%
 * Method Change :  + 4.76%

org.pentaho.di.job.entries.telnet.JobEntryTelnet:
 * Complexity Change :  + 4.17%
 * Instruction Change :  + 1.69%
 * Line Change :  + 2.50%
 * Method Change :  + 4.76%

org.pentaho.di.job.entries.unzip.JobEntryUnZip:
 * Complexity Change :  + .40%
 * Instruction Change :  + .16%
 * Line Change :  + .30%
 * Method Change :  + 1.59%

org.pentaho.di.job.entries.waitforfile.JobEntryWaitForFile:
 * Complexity Change :  + 1.54%
 * Instruction Change :  + .66%
 * Line Change :  + 1.09%
 * Method Change :  + 3.70%

org.pentaho.di.job.entries.webserviceavailable.JobEntryWebServiceAvailable:
 * Complexity Change :  + 5.00%
 * Instruction Change :  + 1.84%
 * Line Change :  + 2.63%
 * Method Change :  + 6.25%

org.pentaho.di.job.entries.writetofile.JobEntryWriteToFile:
 * Complexity Change :  + 2.44%
 * Instruction Change :  + 1.02%
 * Line Change :  + 1.53%
 * Method Change :  + 4.17%

org.pentaho.di.job.entries.writetolog.JobEntryWriteToLog:
 * Complexity Change :  + 3.12%
 * Instruction Change :  + 1.57%
 * Line Change :  + 2.41%
 * Method Change :  + 4.76%

org.pentaho.di.job.entries.zipfile.JobEntryZipFile:
 * Complexity Change :  + .52%
 * Instruction Change :  + .20%
 * Line Change :  + .35%
 * Method Change :  + 2.04%

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change :  + 1.64%
 * Complexity Change :  + .69%
 * Instruction Change :  + 2.43%
 * Line Change :  + 3.70%

org.pentaho.di.trans.step.StepMeta:
 * Instruction Change : **-.19%**
 * Line Change : **-.27%**

org.pentaho.di.trans.steps.autodoc.AutoDocMeta:
 * Complexity Change :  + 1.89%
 * Instruction Change :  + .60%
 * Line Change :  + .99%
 * Method Change :  + 2.50%

org.pentaho.di.trans.steps.changefileencoding.ChangeFileEncodingMeta:
 * Complexity Change :  + 3.12%
 * Instruction Change :  + 1.05%
 * Line Change :  + 1.63%
 * Method Change :  + 3.70%

org.pentaho.di.trans.steps.clonerow.CloneRowMeta:
 * Complexity Change :  + 2.44%
 * Instruction Change :  + .77%
 * Line Change :  + 1.47%
 * Method Change :  + 3.70%

org.pentaho.di.trans.steps.cubeinput.CubeInputMeta:
 * Complexity Change :  + 3.70%
 * Instruction Change :  + 1.60%
 * Line Change :  + 2.22%
 * Method Change :  + 4.76%

org.pentaho.di.trans.steps.cubeoutput.CubeOutputMeta:
 * Complexity Change :  + 4.55%
 * Instruction Change :  + 2.11%
 * Line Change :  + 2.90%
 * Method Change :  + 5.26%

org.pentaho.di.trans.steps.delay.DelayMeta:
 * Complexity Change :  + 3.23%
 * Instruction Change :  + 1.29%
 * Line Change :  + 2.25%
 * Method Change :  + 5.56%

org.pentaho.di.trans.steps.detectlastrow.DetectLastRowMeta:
 * Complexity Change :  + 5.26%
 * Instruction Change :  + 2.64%
 * Line Change :  + 3.70%
 * Method Change :  + 6.25%

org.pentaho.di.trans.steps.edi2xml.Edi2XmlMeta:
 * Complexity Change :  + 4.35%
 * Instruction Change :  + 1.55%
 * Line Change :  + 2.94%
 * Method Change :  + 5.88%

org.pentaho.di.trans.steps.excelinput.ExcelInputMeta:
 * Branch Change :  + .60%
 * Complexity Change :  + .51%
 * Instruction Change :  + 2.61%
 * Line Change :  + 2.30%
 * Method Change :  + .88%

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepField:
 * Complexity Change :  + 3.45%
 * Instruction Change :  + 3.65%
 * Line Change :  + 4.00%
 * Method Change :  + 3.45%

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Branch Change :  + 2.56%
 * Complexity Change :  + 1.57%
 * Instruction Change :  + 1.18%
 * Line Change :  + 1.27%
 * Method Change :  + 1.14%

org.pentaho.di.trans.steps.execprocess.ExecProcessMeta:
 * Complexity Change :  + 2.94%
 * Instruction Change :  + 1.15%
 * Line Change :  + 1.72%
 * Method Change :  + 3.85%

org.pentaho.di.trans.steps.fieldschangesequence.FieldsChangeSequenceMeta:
 * Complexity Change :  + 2.70%
 * Instruction Change :  + 3.32%
 * Line Change :  + 3.94%
 * Method Change :  + 4.35%

org.pentaho.di.trans.steps.fieldsplitter.FieldSplitterMeta:
 * Complexity Change :  + 1.67%
 * Instruction Change :  + 9.23%
 * Line Change :  + 7.11%
 * Method Change :  + 2.13%

org.pentaho.di.trans.steps.fileexists.FileExistsMeta:
 * Complexity Change :  + 3.33%
 * Instruction Change :  + 1.36%
 * Line Change :  + 2.02%
 * Method Change :  + 4.17%

org.pentaho.di.trans.steps.filelocked.FileLockedMeta:
 * Complexity Change :  + 4.17%
 * Instruction Change :  + 1.78%
 * Line Change :  + 2.60%
 * Method Change :  + 5.00%

org.pentaho.di.trans.steps.filestoresult.FilesToResultMeta:
 * Complexity Change :  + 5.56%
 * Instruction Change :  + 3.36%
 * Line Change :  + 4.88%
 * Method Change :  + 5.88%

org.pentaho.di.trans.steps.flattener.FlattenerMeta:
 * Complexity Change :  + 3.70%
 * Instruction Change :  + 1.30%
 * Line Change :  + 2.56%
 * Method Change :  + 5.56%

org.pentaho.di.trans.steps.formula.FormulaMeta:
 * Branch Change :  + 8.82%
 * Complexity Change :  + 6.06%
 * Instruction Change :  + 9.04%
 * Line Change :  + 7.69%
 * Method Change :  + 6.25%

org.pentaho.di.trans.steps.formula.FormulaMetaFunction:
 * Complexity Change :  + 4.35%
 * Instruction Change :  + 1.76%
 * Line Change :  + 2.82%
 * Method Change :  + 4.76%

org.pentaho.di.trans.steps.getfilenames.GetFileNamesMeta:
 * Complexity Change :  + 1.22%
 * Instruction Change :  + 3.87%
 * Line Change :  + 3.04%
 * Method Change :  + 1.75%

org.pentaho.di.trans.steps.getrepositorynames.GetRepositoryNamesMeta:
 * Complexity Change :  + 2.63%
 * Instruction Change :  + 6.11%
 * Line Change :  + 4.79%
 * Method Change :  + 3.70%

org.pentaho.di.trans.steps.getslavesequence.GetSlaveSequenceMeta:
 * Complexity Change :  + 4.55%
 * Instruction Change :  + 1.74%
 * Line Change :  + 2.94%
 * Method Change :  + 4.76%

org.pentaho.di.trans.steps.getsubfolders.GetSubFoldersMeta:
 * Complexity Change :  + 1.96%
 * Instruction Change :  + 3.14%
 * Line Change :  + 3.02%
 * Method Change :  + 3.03%

org.pentaho.di.trans.steps.jobexecutor.JobExecutorMeta:
 * Complexity Change :  + .57%
 * Instruction Change :  + .20%
 * Line Change :  + .38%
 * Method Change :  + .96%

org.pentaho.di.trans.steps.mergejoin.MergeJoinMeta:
 * Complexity Change :  + 2.44%
 * Instruction Change :  + 4.91%
 * Line Change :  + 5.93%
 * Method Change :  + 4.00%

org.pentaho.di.trans.steps.mysqlbulkloader.MySQLBulkLoaderMeta:
 * Complexity Change :  + 1.06%
 * Instruction Change :  + 2.19%
 * Line Change :  + 2.06%
 * Method Change :  + 1.85%

org.pentaho.di.trans.steps.normaliser.NormaliserMeta:
 * Branch Change :  + 4.76%
 * Complexity Change :  + 5.00%
 * Instruction Change :  + 3.88%
 * Line Change :  + 4.26%
 * Method Change :  + 5.26%

org.pentaho.di.trans.steps.normaliser.NormaliserMeta.NormaliserField:
 * Complexity Change :  + 4.00%
 * Instruction Change :  + 4.00%
 * Line Change :  + 4.55%
 * Method Change :  + 10.00%

org.pentaho.di.trans.steps.numberrange.NumberRangeMeta:
 * Complexity Change :  + 3.23%
 * Instruction Change :  + .95%
 * Line Change :  + 1.63%
 * Method Change :  + 4.17%

org.pentaho.di.trans.steps.olapinput.OlapInputMeta:
 * Complexity Change :  + 2.86%
 * Instruction Change :  + 1.25%
 * Line Change :  + 1.75%
 * Method Change :  + 3.57%

org.pentaho.di.trans.steps.randomccnumber.RandomCCNumberGeneratorMeta:
 * Complexity Change :  + 2.50%
 * Instruction Change :  + 5.43%
 * Line Change :  + 5.11%
 * Method Change :  + 3.57%

org.pentaho.di.trans.steps.randomvalue.RandomValueMeta:
 * Complexity Change :  + 2.17%
 * Instruction Change :  + 4.41%
 * Line Change :  + 5.13%
 * Method Change :  + 5.00%

org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * Complexity Change :  + .96%
 * Instruction Change :  + 5.96%
 * Line Change :  + 4.80%
 * Method Change :  + 2.22%

org.pentaho.di.trans.steps.reservoirsampling.ReservoirSamplingMeta:
 * Complexity Change :  + 4.35%
 * Instruction Change :  + 2.69%
 * Line Change :  + 3.85%
 * Method Change :  + 6.25%

org.pentaho.di.trans.steps.selectvalues.SelectValuesMeta:
 * Branch Change :  + 1.55%
 * Complexity Change :  + 1.47%
 * Instruction Change :  + 2.10%
 * Line Change :  + 2.36%
 * Method Change :  + 2.56%

org.pentaho.di.trans.steps.selectvalues.SelectValuesMeta.SelectField:
 * Complexity Change :  + 10.00%
 * Instruction Change :  + 9.76%
 * Line Change :  + 6.25%
 * Method Change :  + 10.00%

org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * Complexity Change :  + 2.86%
 * Instruction Change :  + 5.37%
 * Line Change :  + 5.56%
 * Method Change :  + 5.26%

org.pentaho.di.trans.steps.ssh.SSHMeta:
 * Complexity Change :  + 1.52%
 * Instruction Change :  + .55%
 * Line Change :  + .80%
 * Method Change :  + 2.00%

org.pentaho.di.trans.steps.switchcase.SwitchCaseMeta:
 * Branch Change :  + 3.85%
 * Complexity Change :  + 3.17%
 * Instruction Change :  + 3.17%
 * Line Change :  + 2.70%
 * Method Change :  + 2.70%

org.pentaho.di.trans.steps.switchcase.SwitchCaseTarget:
 * Complexity Change :  + 50.00%
 * Instruction Change :  + 50.00%
 * Line Change :  + 33.33%
 * Method Change :  + 50.00%

org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * Complexity Change :  + 1.85%
 * Instruction Change :  + .84%
 * Line Change :  + 1.29%
 * Method Change :  + 2.56%

org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * Branch Change :  + .53%

org.pentaho.di.trans.steps.textfileoutput.TextFileField:
 * Complexity Change :  + 3.23%
 * Instruction Change :  + 2.84%
 * Line Change :  + 3.28%
 * Method Change :  + 3.23%

org.pentaho.di.trans.steps.textfileoutput.TextFileOutputMeta:
 * Branch Change :  + 1.69%
 * Complexity Change :  + 1.34%
 * Instruction Change :  + 1.15%
 * Line Change :  + 1.19%
 * Method Change :  + 1.11%

org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * Complexity Change :  + 2.70%
 * Instruction Change :  + 5.25%
 * Line Change :  + 5.22%
 * Method Change :  + 3.70%

org.pentaho.di.trans.steps.uniquerowsbyhashset.UniqueRowsByHashSetMeta:
 * Complexity Change :  + 3.45%
 * Instruction Change :  + 5.16%
 * Line Change :  + 5.75%
 * Method Change :  + 4.35%

org.pentaho.di.trans.steps.univariatestats.UnivariateStatsMeta:
 * Branch Change :  + 7.14%
 * Complexity Change :  + 5.26%
 * Instruction Change :  + 6.77%
 * Line Change :  + 6.25%
 * Method Change :  + 5.88%



Integration test coverage change:
============
org.pentaho.di.trans.steps.http.HTTPMeta:
 * Complexity Change :  + 1.47%
 * Instruction Change :  + 3.97%
 * Line Change :  + 3.70%
 * Method Change :  + 1.96%

org.pentaho.di.trans.steps.httppost.HTTPPOSTMeta:
 * Complexity Change :  + 1.33%
 * Instruction Change :  + 4.08%
 * Line Change :  + 4.09%
 * Method Change :  + 1.72%

org.pentaho.di.trans.steps.rest.RestMeta:
 * Complexity Change :  + .98%
 * Instruction Change :  + 4.01%
 * Line Change :  + 3.54%
 * Method Change :  + 1.52%

**Comment by lucboudreau** [comment]
I love this PR. Well done @matthewtckr

**Pull request merged**
