### PR TITLE
[PDI-18993]:Text File Input not processing escape characters properly

### PR DESCRIPTION
**Pull request by BhargaviChevva**

### CODE REVIEW

**Comment by BhargaviChevva** [comment]
The failure in SonarQube quality check is due to high cognitive complexity in existing code. The changes made recently contribute very little to the increased cognitive complexity.

**Review by peterrinehart — CHANGES_REQUESTED** [review]
Can we get a unit test to ensure this particular problem was fixed?

**Comment by BhargaviChevva** [comment]
Added a Junit test to validate the fix

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 17m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
