### PR TITLE
[PDI-19047] - The Log timeout setting for database logging will apply…

### PR DESCRIPTION
**Pull request by tkafalas**
… to all KJBs or KTRs causing the wrong database rows to be deleted

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 30m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **4996**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7802/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **4996**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7802/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 35m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **4996**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7802/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 35m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **4996**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7802/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by angel-ramoscardona — APPROVED** [review]

**Pull request merged**
