### PR TITLE
[PDI-19357] - Incomplete logging in kettle/status page when database logging for a job/transformation is enabled.

### PR DESCRIPTION
**Pull request by renato-s**
@andreramos89 
@bcostahitachivantara 
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 8m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by pentaho-aschurman** [comment]
Team, from the point of viw of this new line in the code

`this.logBufferStartLine = KettleLogStore.getAppender().getLastBufferLineNr();`

I see now Checks or protection is the aprender is NULL or if the getLastBufferLineNr is null, or anything else un expected.
Should we add code to prevent a NullPointerException?

**Comment by pentaho-aschurman** [comment]
Team, further review....
I see changes on the JOB Class, but what about the TRANSFORMATION class?
Isn´t this Logging issue also happening with Transformations

**Comment by renato-s** [comment]
The method `KettleLogStore.getAppender()` already checks if the `KettleLogStore` has been initialized, so there should be no need for more validations.
A new commit has been made with equivalent changes for Transformations

**Comment by buildguy** [comment]
### :x: Build failed in 6m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 6m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 6m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good.

**Pull request merged**
