### PR TITLE
[BACKLOG-35955] - Copy/Paste Functionality in Folder viewer (incl. Between vfs providers)

### PR DESCRIPTION
**Pull request by addagudi**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 8m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
plugins/file-open-save-new/api,plugins/file-open-save-new/core
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by peterrinehart — CHANGES_REQUESTED** [review]
Solution looks good overall.  Please format the code per our code style standards and add the required copyright header to any new files.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 7m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
plugins/file-open-save-new/api,plugins/file-open-save-new/core
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
plugins/file-open-save-new/api,plugins/file-open-save-new/core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Pull request closed without merging**
