### PR TITLE
[SP-2637][PDI-14699] Encrypted passwords do not work in Salesforce / …

### PR DESCRIPTION
**Pull request by SergeyTravin**
…IBM WebSphere MQ steps

### CODE REVIEW

**Comment by SergeyTravin** [comment]
It is backport for https://github.com/pentaho/pentaho-kettle/pull/2380

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/salesforce/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/salesforce/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceinput/SalesforceConnection.java
  plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceinput/SalesforceConnectionIT.java
  plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceinput/SalesforceConnectionTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.salesforceinput.SalesforceConnection:
 * Branch Change :  + 4.05%
 * Complexity Change :  + 7.24%
 * Instruction Change :  + 7.67%
 * Line Change :  + 11.53%
 * Method Change :  + 16.23%

Integration test coverage change:
============
org.pentaho.di.trans.steps.salesforceinput.SalesforceConnection:
 * Branch New Coverage : 4.86%
 * Complexity New Coverage : 8.38%
 * Instruction New Coverage : 11.46%
 * Line New Coverage : 18.18%
 * Method New Coverage : 27.27%

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceinput/SalesforceConnection.java

1. Message: ',' is preceded with whitespace. at Line: 864 Column: 92
2. Message: ',' is preceded with whitespace. at Line: 872 Column: 92
3. Message: ',' is preceded with whitespace. at Line: 880 Column: 92
4. Message: ',' is preceded with whitespace. at Line: 888 Column: 92

**Comment by SergeyTravin** [comment]
The PR was updated with fix checkstyle violations

**Comment by SergeyTravin** [comment]
@bmorrise, Could you review this backport for #2380?

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/salesforce/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/salesforce/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceinput/SalesforceConnection.java
  plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceinput/SalesforceConnectionIT.java
  plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceinput/SalesforceConnectionTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.salesforceinput.SalesforceConnection:
 * Branch Change :  + 4.05%
 * Complexity Change :  + 7.24%
 * Instruction Change :  + 7.67%
 * Line Change :  + 11.53%
 * Method Change :  + 16.23%

Integration test coverage change:
============
org.pentaho.di.trans.steps.salesforceinput.SalesforceConnection:
 * Branch New Coverage : 4.86%
 * Complexity New Coverage : 8.38%
 * Instruction New Coverage : 11.46%
 * Line New Coverage : 18.18%
 * Method New Coverage : 27.27%

**Pull request merged**
