### PR TITLE
[PDI-19826] Changed the Annotated SOAP Web Service sample ktr to a valid public soap url

### PR DESCRIPTION
**Pull request by nawaz34-hitachivantara**
Removed the ktr under data-integration/samples/transformations - 'General - Annotated SOAP Web Service call - dialog.ktr' and added the new ktr under same folder with name - 'General - Annotated SOAP web service call (celsius to fahrenheit) - dialog.ktr' with valid public url which converts temperature from Celsius to Fahrenheit.

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 2s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/samples
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/samples
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/samples
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/samples
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by krishnaalluhitachi — APPROVED** [review]

**Pull request merged**
