### PR TITLE
[PDI-19140] Problems in Delete Files and Get Subfolder Names steps wh…

### PR DESCRIPTION
**Pull request by ssamora**
…en using S3

@smmribeiro @bcostahitachivantara

### CODE REVIEW

**Review by smmribeiro — APPROVED** [review]
Looks good!

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 28m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3882**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7921/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 29m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3882**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7921/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 30m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **5073**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7921/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
New changes also work for Windows.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 32m 19s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine
```
---
:ok_hand: All tests passed!
 
Tests run: **5073**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7921/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
