### PR TITLE
[BACKLOG-8583] Correct misspelling on the new dialog Login to Repository

### PR DESCRIPTION
**Pull request by ddiroma**
@bmorrise @mdamour1976

### CODE REVIEW

**Comment by mbatchelor** [comment]
Since English isn't a first language for many people, I prefer to have *no* contractions and spell things out completely. So "didn't" should become "did not" in my opinion.

**Comment by ddiroma** [comment]
@bmorrise @mdamour1976 : Please comment as the description in the jira case retains the contractions.

**Comment by ddiroma** [comment]
Furthermore, there are many other instances throughout pdi where contractions are used...too many to count.

**Comment by bmorrise** [comment]
Per UX, these messages are correct.

**Pull request merged**
