### PR TITLE
[TEST] - Add tests for UserRoleHelper

### PR DESCRIPTION
**Pull request by akhayrutdinov**
@mattyb149, @brosander, review it please. This is test for ```UserRoleHelper```. I prepared it when was dealing with PDI-12814, but didn't include into its PRs

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@mattyb149, I've updated the PR by adding guard conditions

**Comment by akhayrutdinov** [comment]
@mattyb149, review it please

**Comment by akhayrutdinov** [comment]
@mattyb149, review it please

**Comment by brosander** [comment]
Changed files:
==============
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/UserRoleHelper.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/UserRoleHelperTest.java

Checkstyle violations:
----------------------
No errors found




Unit test coverage change:
============
org.pentaho.di.repository.pur.UserRoleHelper:
 * instructionPercentCoverageChange : +15.55%
 * branchPercentCoverageChange : +20.35%
 * linePercentCoverageChange : +15.79%
 * complexityPercentCoverageChange : +11.58%
 * methodPercentCoverageChange : +11.11%
    
org.pentaho.di.repository.pur.model.EEUserInfo:
 * instructionPercentCoverageChange : +19.23%
 * linePercentCoverageChange : +27.27%
 * complexityPercentCoverageChange : +27.27%
 * methodPercentCoverageChange : +30.00%

**Pull request merged**
