### PR TITLE
[PDI-15246] Group By with include all rows option does not clean up temp files

### PR DESCRIPTION
**Pull request by IvanNikolaychuk**
- Closing streams before deleting file
- Refactoring
- Tests written

More details:

**GroupBy**
- Closing streams before deleting files.
- Logging an error if stream can't be closed
- Logging detailed message if temp file wasn't deleted. I've chosen this log level because in most cases temp file wouldn't be deleted because streams to this file are not closed (and we do log about close-stream error)
- Refactoring

**GroupByData**
- Changed name of streams, pointing that they are related to temp file only.

**GroupByMeta**
- Refactoring some field names

**GroupByTest**
- Updating to JUnit 4.0
- Added positive test for temp file deletion
- No negative test added, as in this case it would be equivalent to testing logger.

**messages**
- Added message, notifying that temp file wasn't deleting
- Refactored a message, notifying that connection to file wasn't closed. Pointing to the path of the file, where an error occurred.

### CODE REVIEW

**Comment by IvanNikolaychuk** [comment]
@wingman-pentaho, wmn?

**Comment by lucboudreau** [comment]
@wingman-pentaho Just a test.

**Comment by lucboudreau** [comment]
@wingman-pentaho Just another test. Please ignore.

**Comment by lucboudreau** [comment]
@wingman-pentaho Nothing to see here. Move on.

**Comment by lucboudreau** [comment]
@wingman-pentaho Yet another test.

**Comment by lucboudreau** [comment]
One last test.

**Comment by IvanNikolaychuk** [comment]
@brosander , could you please review this PR?

**Comment by brosander** [comment]
@IvanNikolaychuk I'm ok with static imports in tests (especially asserts) but please use the junit packages

**Comment by lucboudreau** [comment]
@IvanNikolaychuk @brosander If you use ``org.junit.Assert.X``, these warnings will go away. See rule AvoidStaticImport [here](http://sonar.pentaho.com:9000/api/qualityprofiles/export?language=java&name=Pentaho&exporterKey=checkstyle).

We're also in the process of making a few changes to those rules. The static imports will be allowed in the next version.

**Comment by IvanNikolaychuk** [comment]
@brosander, sure, this importes were brought by mistake. 
Updated.

**Comment by IvanNikolaychuk** [comment]
@brosander, can it be merged now?

**Pull request merged**
