### PR TITLE
[PDI-19445] - Json Parser syntax not working

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@smmribeiro 
@andreramos89 
@renato-s

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,plugins/json/core
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good.

**Comment by buildguy** [comment]
### :x: Build failed in 6m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,plugins/json/core
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 19m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,plugins/json/core
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
