### PR TITLE
[PDI-14948] Transformation with Metadata Injection runs endlessly if no input is received by Injection Step

### PR DESCRIPTION
**Pull request by IvanNikolaychuk**
- When starting threads, check if transformation has any step to run, and finish it, if it has no steps.
- Test written
- Checkstyle applied

### CODE REVIEW

**Comment by pamval** [comment]
Are we able to understand the impacts of this change? This touches the base class for the Transformation and changes its behavior.

**Comment by pamval** [comment]
@kurtwalker @mdamour1976 @e-cuellar @tkafalas @tgf (and everyone else at R2D2), can you please review this?

**Comment by kurtwalker** [comment]
Change was originally my suggestion.  I think it's safe, but I was worried about use cases I may have been unaware of.  Suggest thorough regression test

**Comment by IvanNikolaychuk** [comment]
@pamval, @kurtwalker, well, initially it's Kurt who suggested this fix.
I did some regression testing and covered some cases that I'm aware of, contacted to testers that work with PDI closely and asked my dev-colleagues about this changes.
It looks safe for me, but I would also prefer this to be reviewed by as much devs as possible.

**Comment by IvanNikolaychuk** [comment]
@AndreyBurikhin , @mchen-len-son , could you please take a look at this PR?

**Comment by IvanNikolaychuk** [comment]
@mdamour1976 @e-cuellar @tkafalas @tgf @bmorrise @wseyler, could you please review this PR?

**Comment by mdamour1976** [comment]
@IvanNikolaychuk I think it looks safe enough, but I'm wondering about that wingman newly failed case.  I'm not sure how that is related.  Can that part be validated independent of wingman?

**Comment by IvanNikolaychuk** [comment]
@mdamour1976, agree, don't see any correlation between changes and this PR. TextFileInputMetaLoadSaveTest passes localy for me either.
Thanks for review!

**Pull request merged**
