### PR TITLE
[SP-1776] Regression of PDI-13633: Database Connections with JNDI mix up...

### PR DESCRIPTION
**Pull request by ivanpogodin**
... JNDI name with Connection name (5.3 Suite)
@mattyb149, @brosander, review it please

### CODE REVIEW

**Comment by mattyb149** [comment]
Needs unit and/or integration tests

**Comment by brosander** [comment]
@ivanpogodin if we're going to make DatabaseUtil a singleton, we should make the constructor private to prevent accidentally having orphan instances used elsewhere in the codebase

**Comment by ivanpogodin** [comment]
@mattyb149, @brosander, review it please

**Comment by brosander** [comment]
@ivanpogodin where is connectUsingNamedDataSource called? do we still need this method? are there expected impacts from removing it?

**Comment by ivanpogodin** [comment]
I agree, we can remove private connectUsingNamedDataSource.
I kept it because it's the only point where rg.pentaho.di.core.database.DataSourceProviderFactory used.
As I see, removing connectUsingNamedDataSource makes [platform]PlatformKettleDataSourceProvider unused. As well as [kettle]DataSourceProviderFactory. And probably some other classes.
I haven't decided to remove them. The impact is too risky. This is a larger task - to remove classes or change datasource lookup algorithm.

**Comment by ivanpogodin** [comment]
see also fix https://github.com/pentaho/pentaho-kettle/pull/1264

**Pull request merged**
