### PR TITLE
PDI-4055 UI: Ctrl+C for copying marked log entries does copy the tran…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
PDI-4055 UI: Ctrl+C for copying marked log entries does copy the transformation XML and not the part of the marked log - check focused control

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
@brosander, @mattyb149, @mchen-len-son, please review

**Comment by stanislau-strelchanka** [comment]
@brosander, @mattyb149, @mchen-len-son, could you please check it manually, there are no tests or style problems on my environment. Thanks.

**Comment by pamval** [comment]
@mchen-len-son please get this one

**Comment by mchen-len-son** [comment]
Built locally, tests are passing, checkstyle is OK
Also re-tested the fix.

Merging.

**Pull request merged**
