### PR TITLE
[CLEANUP] javadoc: namedcluster saved in embedded metastore

### PR DESCRIPTION
**Pull request by DFieldFL**

### CODE REVIEW

**Comment by DFieldFL** [comment]
@pentaho/ackbar @tkafalas

**Comment by DFieldFL** [comment]
I can't reproduce the test error locally.

**Comment by pavel-sakun** [comment]
AFAIR the test is failing like this for years

**Comment by tmcsantos** [comment]
The failure happens when the system is on high load, failing any test with timeouts.

**Pull request merged**
