### PR TITLE
[SP-2156] - Backporting test to repair it

### PR DESCRIPTION
**Pull request by akhayrutdinov**
@mattyb149, @brosander, review it please. This fixed failed test in kettle-engine-5.4
/cc @pamval

### CODE REVIEW

**Comment by brosander** [comment]
@akhayrutdinov running tests now, what about org.pentaho.di.core.database.DatabaseConnectingTest.connect_GroupIsEqual_InParallel?

**Comment by akhayrutdinov** [comment]
@brosander, there is a flaw in synchronization inside `Database`. It fixed it here: https://github.com/pentaho/pentaho-kettle/pull/1507.

However, it affects not only the test, but also the production class. Do you want me to backport it?

**Comment by brosander** [comment]
backport of JobMetaTest change in https://github.com/pentaho/pentaho-kettle/pull/1855

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; ant -f engine/build.xml clean-all resolve jacoco checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo "no publish local to remove"

Changed files:
==============
  engine/test-src/org/pentaho/di/job/JobMetaTest.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found




Newly Fixed Tests:
-----------------
org.pentaho.di.job.JobMetaTest.testLookupRepositoryReferences: java.lang.RuntimeException
```
java.lang.RuntimeException
	at org.pentaho.di.job.JobMetaTest.testLookupRepositoryReferences(JobMetaTest.java:67)

```



Unit test coverage change:
============
org.pentaho.di.trans.Trans:
 * instructionPercentCoverageChange : +0.09%
 * branchPercentCoverageChange : +0.10%
 * linePercentCoverageChange : +0.12%
 * complexityPercentCoverageChange : +0.14%
    
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange : +0.17%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange :**-0.53%**
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange : +0.28%
 * branchPercentCoverageChange : +3.33%
 * complexityPercentCoverageChange : +1.85%
    
org.pentaho.di.job.JobMeta:
 * instructionPercentCoverageChange : +0.73%
 * branchPercentCoverageChange : +0.74%
 * linePercentCoverageChange : +0.86%
 * complexityPercentCoverageChange : +0.25%
    
org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * instructionPercentCoverageChange : +0.07%
    
org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * instructionPercentCoverageChange : +2.43%
 * branchPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +2.95%
 * complexityPercentCoverageChange : +0.69%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-1.97%**

**Comment by pamval** [comment]
@brosander are we good for merging ?

**Comment by brosander** [comment]
@akhayrutdinov please port to 6.0 branch as well

**Pull request merged**
