### PR TITLE
[BAD-201] Create and Document Spark samples

### PR DESCRIPTION
**Pull request by pavel-sakun**
Sample job for spark submit job entry

### CODE REVIEW

**Comment by pavel-sakun** [comment]
@mattyb149

**Comment by mattyb149** [comment]
Is our Spark entry only supported on a CDH shim? I thought we could point to a vanilla Apache Spark instance? If so, we should probably remove/change the references in the notes to CDH or Cloudera

**Comment by pavel-sakun** [comment]
For 5.4 we claim support for spark running on cloudera 5.3 in yarn mode only

**Comment by mattyb149** [comment]
Ok just checking :)

**Pull request merged**
