### PR TITLE
[PDI-16258] Hidden folders show for business user "Suzy" from Spoon

### PR DESCRIPTION
**Pull request by AliaksandrShuhayeu**
[PDI-16258] Hidden folders show for business user "Suzy" from Spoon
only admins can see hidden files in pentaho repository via spoon explorer
@mbatchelor Could you please review and merge it?

### CODE REVIEW

**Comment by kolinus** [comment]
@pedrofvteixeira  @pamval @mdamour1976  could you please take a look

**Comment by pamval** [comment]
@AliaksandrShuhayeu what are the downstream impacts of this change? Can we try to figure that out? We're changing the UserInfo class and IUser interface and I'm not sure about the impacts on PDI Plugins. Can you try to build some of the PDI plugins agains these changes?

**Comment by AliaksandrShuhayeu** [comment]
@pamval I builded all PDI plugins successfully without errors against these changes. But I sent one more PR without impacting on PDI Plugins and custom plugins. https://github.com/pentaho/pentaho-kettle/pull/4189

**Comment by pamval** [comment]
Closed in favor of #4189

**Pull request closed without merging**
