### PR TITLE
[PDI-17993] Fix inconsistent file type filters in JSON Output dialog

### PR DESCRIPTION
**Pull request by cdeptula**

### CODE REVIEW

**Comment by buildguy** [comment]
### :gear: Build finished in 3m 19s with command:
```
mvn clean verify -B -e -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|79|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/5/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 26s with command:
```
mvn clean verify -B -e -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|79|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/6/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 31s with command:
```
mvn clean verify -B -e -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|79|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/7/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 54s with command:
```
mvn clean verify -B -e -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|79|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/8/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 5m 43s with command:
```
mvn clean verify -f pom.xml -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -U -Dmaven-surefire-plugin.argLine=-XX:MaxRAMPercentage=90.0 -Dmaven-failsafe-plugin.argLine=-XX:MaxRAMPercentage=90.0 -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|79|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/10/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 41s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|79|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/11/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 48s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|79|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/12/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 3m 22s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|79|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/14/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 54s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|79|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/15/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 54s with command:
```
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd -Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|79|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/16/testReport)|
|----|

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 3m with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|79|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/18/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 48s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/19/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 56s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/20/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 4m 30s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/21/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 5s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/22/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 4s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/23/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 3m 29s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/24/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 2m 52s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -P !assemblies -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/25/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 4m 13s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/26/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 3m 45s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/27/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 4m 2s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/28/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 5m 7s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/29/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 4m 44s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/30/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 4m 7s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/31/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 4m 6s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl plugins/json/core
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|80|0|0|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/32/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 1s
Build command:
```console
mvn clean deploy -B -e -Daudit -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **80**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/33/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **80**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/35/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 5m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **80**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/36/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **80**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/37/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 44s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **80**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/38/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 5m
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **80**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/39/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **80**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/40/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 14m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **80**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/41/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **80**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/42/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **80**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/44/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl plugins/json/core
```
---
:ok_hand: All tests passed!
 
Tests run: **80**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6327/45/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
Pull request 6327 : Not mergeable at 2667acc501a62ade0bda1742a6ee803efea17692+bed542c90ddc38c0185475dedce0c5d32fd31f40 (NOT_MERGEABLE)
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by cseverino789** [comment]
Addressed by the new VFS Browser Dialog.

**Pull request closed without merging**
