### PR TITLE
[SP-3010] - Backport of PDI-15679 - ArrayIndexOutOfBoundsException wi…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
[SP-3010] - Backport of PDI-15679 - ArrayIndexOutOfBoundsException with Metadata Injection for Split Rows Step (7.0 Suite)

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
backport of #3128

**Comment by stanislau-strelchanka** [comment]
@mbatchelor, @matthewtckr, @pamval , @mchen-len-son please review

**Comment by mchen-len-son** [comment]
broken test looks unrelated to the changes. ran wingman again

**Comment by mchen-len-son** [comment]
@stanislau-strelchanka can you please check if that failing test is caused by the changes or not?

**Pull request merged**
