### PR TITLE
[PDI-14343] - Timestamp for jobs in DI repository continuously displays the same value for different versions

### PR DESCRIPTION
**Pull request by akhayrutdinov**
- improve PurRepository
  - remove code duplication in ```saveTrans0()``` and ```saveJob0()```
  - add java docs for ```saveKettleEntity()```
  - fix checkstyle violations
- re-organize tests
  - delete revision-related tests from ```PurRepositoryIT```
  - introduce ```PurRepository_Revisions_I```T and implement revision-related test cases there

@mattyb149, @brosander, review it please. The problem described in the ticket has been already fixed. This PR eliminates code duplication and brushes up tests

### CODE REVIEW

**Comment by brosander** [comment]
Changed files:
==============
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_Revisions_IT.java

Checkstyle violations:
----------------------
Errors:File plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java1. Message: File length is 2,868 lines (max allowed is 2,000). at Line: 1 Column: None




Unit test coverage change:
============
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange : +0.29%
 * branchPercentCoverageChange : +0.32%
 * linePercentCoverageChange : +0.29%
 * complexityPercentCoverageChange : +0.21%
 * methodPercentCoverageChange :-0.06%
    
Integration test coverage change:
============
org.pentaho.di.repository.pur.PurObjectRevision:
 * instructionPercentCoverageChange :-14.67%
 * branchPercentCoverageChange :-12.50%
 * linePercentCoverageChange :-6.25%
 * complexityPercentCoverageChange :-10.00%
 * methodPercentCoverageChange :-16.67%
    
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange : +3.19%
 * branchPercentCoverageChange : +5.62%
 * linePercentCoverageChange : +2.59%
 * complexityPercentCoverageChange : +3.69%
 * methodPercentCoverageChange : +1.37%

**Comment by brosander** [comment]
@akhayrutdinov it looks like we lost a decent amount of coverage on PurObjectRevision

**Comment by brosander** [comment]
@akhayrutdinov don't worry about the num lines violation for now, PurRepository has been too long for a long time

**Comment by akhayrutdinov** [comment]
@brosander, do you think ```PurObjectRevision``` is worth be worried about? It is a simple container of data w/o any logic inside

**Comment by akhayrutdinov** [comment]
@brosander, I see why did it happen. Let me update tests with usage of the class

**Comment by akhayrutdinov** [comment]
@brosander, I've updated the PR. Take a look at it once again please

**Comment by bkemper-pentaho** [comment]
Than it should be really easy to write tests for.   Since I think it's worth worrying about (as I feel about all of our code).....

It's only not worth worrying about if you're not worried about whether it works.   And the answer to that one is pretty obvious... since we all better care if our products work.



Bob Kemper
Executive Vice President of Engineering
Pentaho, a Hitachi Data Systems company.
5950 Hazeltine National Dr.
Suite 340
Orlando, FL 32822
(407)-965-4019

[cid:5F6A7A1B-12F2-427C-AFBD-13DBB14A36EC]

**Comment by brosander** [comment]
Changed files:
==============
  plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java
  plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_Revisions_IT.java

Checkstyle violations:
----------------------
Errors:File plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java1. Message: File length is 2,868 lines (max allowed is 2,000). at Line: 1 Column: None


Unit test coverage change:
============
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange : +0.29%
 * branchPercentCoverageChange : +0.32%
 * linePercentCoverageChange : +0.29%
 * complexityPercentCoverageChange : +0.21%
 * methodPercentCoverageChange :<span style="color: red">-0.06%</span>

Integration test coverage change:
============
org.pentaho.di.repository.pur.PurRepository:
 * instructionPercentCoverageChange : +3.19%
 * branchPercentCoverageChange : +5.62%
 * linePercentCoverageChange : +2.59%
 * complexityPercentCoverageChange : +3.69%
 * methodPercentCoverageChange : +1.37%

**Pull request merged**
