### PR TITLE
[BACKLOG-8568] - Added code to handle long repository names, tested, …

### PR DESCRIPTION
**Pull request by wseyler**
…ran checkstyles @mdamour1976 @bmorrise

### CODE REVIEW

**Comment by lucboudreau** [comment]
Something weird with wingman here. No build commands were run. I'll look into it.

**Comment by lucboudreau** [comment]
@wseyler Hey Bill, got any clue why this would fail? We're running this on Java 8; does it work locally with the exact same build command?

**Comment by pentaho-nbaker** [comment]
Probably multiple XML parsers (Xerces) on the classpath, one winning out over the other in different environments. The AbstractMethodError is probably due to an older version being active.

**Comment by wseyler** [comment]
I don't get this failure locally.

**Comment by wseyler** [comment]
I'm running java 8 and it fails for me too.  I have no idea why.  Tried debugging and got very strange results that didn't lead me anywhere.  Any help would be appreciated.

**Comment by lucboudreau** [comment]
Looking at the logs I see two xerces dependencies. From the looks of the version numbers, I suspect they aren't compatible.

```
Mon Jul 25 22:35:03 EDT 2016 - stdout - head: [WARNING] Artifact xerces:xerces:jar:1.4.0 (...snip...)
Mon Jul 25 22:35:03 EDT 2016 - stdout - head: [WARNING] Artifact xerces:xmlParserAPIs:jar:2.6.2 (...snip...)
```

**Comment by lucboudreau** [comment]
This will probably fix it. Thanks @tgf !

https://github.com/pentaho/pentaho-kettle/pull/2729

**Pull request merged**
