### PR TITLE
[PPP-3487] Classes are dynamically modified by the build process to i…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
…nject Version information

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
dependent prs

https://github.com/pentaho/pentaho-mongolap/pull/116
https://github.com/pentaho/pentaho-splunk-plugin/pull/32
https://github.com/pentaho/pentaho-platform-plugin-mobile/pull/53
https://github.com/pentaho/pdi-jms-plugin/pull/40
https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/64
https://github.com/pentaho/pdi-google-docs-plugin/pull/22
https://github.com/pentaho/pentaho-r-plugin/pull/53
https://github.com/pentaho/pentaho-ee-chart-plugin/pull/6

https://github.com/pentaho/pentaho-yarn-kettle-plugin/pull/286
https://github.com/pentaho/pdi-monitoring-plugin/pull/74
https://github.com/pentaho/pentaho-data-refinery/pull/85
https://github.com/pentaho/pentaho-platform-plugin-geo/pull/189

**Comment by stanislau-strelchanka** [comment]
@mbatchelor @mchen-len-son @cjboyden please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor @mchen-len-son @cjboyden please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor @mchen-len-son @cjboyden @pamval  please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor @mchen-len-son @cjboyden @pamval please review

**Comment by stanislau-strelchanka** [comment]
@mbatchelor @mchen-len-son @cjboyden @pamval please review

**Comment by mbatchelor** [comment]
Move to maven happening tomorrow. Closing this PR.

**Pull request closed without merging**
