### PR TITLE
[PPP-4490] We should not allow anonymous access to executeJob and exe…

### PR DESCRIPTION
**Pull request by smmribeiro**
…cuteTrans

@pentaho-lmartins @ssamora @ppatricio @bcostahitachivantara

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 25m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,plugins/pur/core
```
---
:ok_hand: All tests passed!
 
Tests run: **4413**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7383/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 42m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,plugins/pur/core
```
---
:ok_hand: All tests passed!
 
Tests run: **4835**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7383/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 44m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,plugins/pur/core
```
---
:ok_hand: All tests passed!
 
Tests run: **4835**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7383/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 50m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,engine,plugins/pur/core
```
---
:ok_hand: All tests passed!
 
Tests run: **4835**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7383/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
To be reformulated.

**Pull request closed without merging**
