### PR TITLE
[BACKLOG-6425] -Changed layout for trans an job run dialogs.

### PR DESCRIPTION
**Pull request by wseyler**
Changed to match OSX mock.  Rank checkstyles. @bmorrise

### CODE REVIEW

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f ui/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f ui/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  ui/src/org/pentaho/di/ui/core/dialog/ConfigurationDialog.java
  ui/src/org/pentaho/di/ui/job/dialog/JobExecutionConfigurationDialog.java
  ui/src/org/pentaho/di/ui/trans/dialog/TransExecutionConfigurationDialog.java

null

null

**Comment by bmorrise** [comment]
Can we get some of these commits squashed?

**Comment by mdamour1976** [comment]
Not just squashed, but merge commits are forbidden.

**Comment by mdamour1976** [comment]
git fetch upstream
git checkout master
git reset --hard upstream/master
git checkout -b bill-dev-squashed
git remote add bill https://github.com/wseyler/pentaho-kettle.git
git fetch bill
git cherry-pick e3e057ad42b6cb913075e9c4311dec227408b57e
git cherry-pick f83c9dc44789ada0e02dcfda6348e0dd8d95d6b2
git cherry-pick 4a3a08401f8cba63dfcc8a929fe43f4408b3d192
git cherry-pick a8d4a9af04d886432a0d0b126995cf8d09155777
git rebase -i 7c9d97db61ff08c11af90824337858361bf995be
git push origin bill-dev-squashed

**Pull request merged**
