### PR TITLE
[BACKLOG-2444] - including a larger warning image

### PR DESCRIPTION
**Pull request by kurtwalker**

### CODE REVIEW

**Comment by kurtwalker** [comment]
@bytekast @tgf @pamval please review

**Comment by bytekast** [comment]
@kurtwalker - please merge this into the future develop branch as well

**Comment by kurtwalker** [comment]
won't Nick's auto scripts do that?

**Comment by bytekast** [comment]
@kurtwalker - yes but I don't know when the next time it will run. This might break the data-refinery project in the future develop branch.. we might want to do a pre-emptive strike

**Comment by kurtwalker** [comment]
ok, are we just cherry-picking?

**Comment by bytekast** [comment]
i think that’s okay for now.

**Pull request merged**
