### PR TITLE
[PDI-17007] Issues with Carte Jobs API startJob endpoint in Pentaho REST API

### PR DESCRIPTION
**Pull request by ssamora**
@pentaho-lmartins

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 28m 44s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3727**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7585/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 32m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3727**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7585/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 48m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **4909**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7585/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ssamora** [comment]
PR recreated in https://github.com/pentaho/pentaho-kettle/pull/7636 due to merging conflicts after 9.1 code freeze

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3732**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7585/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 30m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 17 test(s) failed:

<details><summary><b>org.pentaho.di.cluster.SlaveServerTest.org.pentaho.di.cluster.SlaveServerTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.shared.SharedObjectsTest.org.pentaho.di.shared.SharedObjectsTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.www.CarteTest.callStopCarteRestService</b> (click to expand)</summary><p>

```
"No Carte Server found at localhost:8080
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.salesforce.SalesforceConnectionTest.org.pentaho.di.trans.steps.salesforce.SalesforceConnectionTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.salesforce.SalesforceMetaTest.org.pentaho.di.trans.steps.salesforce.SalesforceMetaTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.salesforce.SalesforceStepTest.org.pentaho.di.trans.steps.salesforce.SalesforceStepTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.salesforcedelete.SalesforceDeleteMetaTest.org.pentaho.di.trans.steps.salesforcedelete.SalesforceDeleteMetaTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.salesforceinput.SalesforceInputMetaTest.org.pentaho.di.trans.steps.salesforceinput.SalesforceInputMetaTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.salesforceinsert.PDI_10836_Test.org.pentaho.di.trans.steps.salesforceinsert.PDI_10836_Test</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.salesforceinsert.SalesforceInsertMetaTest.org.pentaho.di.trans.steps.salesforceinsert.SalesforceInsertMetaTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.salesforceinsert.SalesforceInsertTest.org.pentaho.di.trans.steps.salesforceinsert.SalesforceInsertTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.salesforceupdate.SalesforceUpdateMetaTest.org.pentaho.di.trans.steps.salesforceupdate.SalesforceUpdateMetaTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.salesforceupdate.SalesforceUpdateTest.org.pentaho.di.trans.steps.salesforceupdate.SalesforceUpdateTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.salesforceupsert.SalesforceUpsertMetaTest.org.pentaho.di.trans.steps.salesforceupsert.SalesforceUpsertMetaTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.salesforceupsert.SalesforceUpsertTest.org.pentaho.di.trans.steps.salesforceupsert.SalesforceUpsertTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.salesforceinput.SalesforceInputDialogTest.org.pentaho.di.ui.trans.steps.salesforceinput.SalesforceInputDialogTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

<details><summary><b>org.pentaho.di.ui.trans.steps.salesforceinput.SalesforceInputMetaInjectionTest.org.pentaho.di.ui.trans.steps.salesforceinput.SalesforceInputMetaInjectionTest</b> (click to expand)</summary><p>

```

Unable to find plugin with ID 'Kettle'.  If this is a test, make sure kettle-core tests jar is a dependency.  If this is live make sure a kettle-password-encoder-plugins.xml exits in the classpath

```

</p></details>

  
Tests run: **3669**, Failures: **17**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7585/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 19s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3732**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7585/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]

**Review by ppatricio — APPROVED** [review]

**Pull request merged**
