### PR TITLE
[PDI-14699] Encrypted passwords do not work in Salesforce / IBM WebSp…

### PR DESCRIPTION
**Pull request by SergeyTravin**
…here MQ steps

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@pamval, @pedrofvteixeira , could you run WM on this PR?

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/93/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/salesforce/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/salesforce/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceinput/SalesforceConnection.java
  plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceinput/SalesforceConnectionIT.java
  plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceinput/SalesforceConnectionTest.java



Unit test coverage change:
============
org.pentaho.di.trans.steps.salesforceinput.SalesforceConnection:
 * Branch Change :  + 4.05%
 * Complexity Change :  + 7.24%
 * Instruction Change :  + 7.67%
 * Line Change :  + 11.12%
 * Method Change :  + 16.23%



Integration test coverage change:
============
org.pentaho.di.trans.steps.salesforceinput.SalesforceConnection:
 * Branch New Coverage : 4.86%
 * Complexity New Coverage : 8.38%
 * Instruction New Coverage : 11.46%
 * Line New Coverage : 17.54%
 * Method New Coverage : 27.27%

**Comment by SergeyTravin** [comment]
@bmorrise, The wingman did not found any problem. Could you please review it?

**Pull request merged**
