### PR TITLE
[PDI-13260] - Excel-Input Step does not save all properties

### PR DESCRIPTION
**Pull request by aliakseihaidukou**
save sizeFieldName attribute

@mbatchelor please review

### CODE REVIEW

**Comment by dkincade** [comment]
@brosander @mattyb149 @hudak

**Comment by hudak** [comment]
Unit Tests?
Consider using the [LoadSaveTester](https://github.com/pentaho/pentaho-kettle/blob/master/engine/test-src/org/pentaho/di/trans/steps/loadsave/LoadSaveTester.java) to verify that all properties survive the round trip

**Comment by aliakseihaidukou** [comment]
@hudak is this test OK for you?

**Comment by hudak** [comment]
@aliakseihaidukou looks, good. Thank you!

**Pull request merged**
