### PR TITLE
[PDI-18387] - Fields defined in "Key(s) to look up the values" goes missing in the Delete Step

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@pentaho-lmartins 
@ssamora 
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 27m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3848**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7812/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ssamora** [comment]
Correction seems fine. Can you address the Sonar issue please ? It relates with multiple use of the String literal ""key_field" 
And by changing that one to a variable, i would say that we could do the same to the other literals, like "key_name", "key_condition" etc..

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3848**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7812/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 29m 16s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl engine
```
---
:ok_hand: All tests passed!
 
Tests run: **3848**, Failures: **0**, Skipped: **7** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/pdi/job/PR-7812/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ssamora — APPROVED** [review]

**Pull request merged**
