### PR TITLE
[BACKLOG-20859] Run MQTT Step in AEL/Spark

### PR DESCRIPTION
**Pull request by DFieldFL**
Move retrieving the Resource Dependencies to Base Stream Meta.
Put libraries in the appropriate spots for AEL/Spark.

### CODE REVIEW

**Comment by DFieldFL** [comment]
@pentaho/ackbar please review

**Comment by kurtwalker** [comment]
why are the mqtt libs are needed in kettle?

**Comment by mkambol** [comment]
@DFieldFL Can these dependencies be loaded in OSGi rather than putting them in lib?  Looks like mqttv3 is a bundle.

**Comment by DFieldFL** [comment]
Ran into the same problem as Kafka where spark can't see the libs. I'd be willing to discuss this further.

**Pull request merged**
