### PR TITLE
[TEST] LoadSaveTests

### PR DESCRIPTION
**Pull request by matthewtckr**
Get Subfolders
Get Sequence ID from Slave
Row Normalizer

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMeta.java
  engine/test-src/org/pentaho/di/trans/steps/getrepositorynames/GetRepositoryNamesMetaTest.java
  engine/test-src/org/pentaho/di/trans/steps/getslavesequence/GetSlaveSequenceMetaTest.java
  engine/test-src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMetaTest.java
  engine/test-src/org/pentaho/di/trans/steps/normalizer/NormalizerMetaTest.java

Checkstyle violations:
======================
File engine/test-src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMetaTest.java
1. Message: Line has trailing spaces. at Line: 42 Column: None


License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange : +0.17%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange :**-0.53%**
    
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * branchPercentCoverageChange :**-7.14%**
 * complexityPercentCoverageChange :**-7.69%**
    
org.pentaho.di.trans.steps.normaliser.NormaliserMeta:
 * branchPercentCoverage :21.05%
 * linePercentCoverage :40.29%
 * methodPercentCoverage :60.87%
 * complexityPercentCoverage :42.86%
 * instructionPercentCoverage :38.27%
    
org.pentaho.di.trans.steps.getrepositorynames.ObjectTypeSelection:
 * linePercentCoverage :46.15%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :28.57%
 * instructionPercentCoverage :54.29%
    
org.pentaho.di.trans.steps.getsubfolders.GetSubFoldersMeta:
 * branchPercentCoverage :34.21%
 * linePercentCoverage :45.50%
 * methodPercentCoverage :69.70%
 * complexityPercentCoverage :55.77%
 * instructionPercentCoverage :45.97%
    
org.pentaho.di.trans.steps.getslavesequence.GetSlaveSequenceMeta:
 * linePercentCoverage :61.54%
 * methodPercentCoverage :71.43%
 * complexityPercentCoverage :68.18%
 * instructionPercentCoverage :55.90%
    
org.pentaho.di.trans.steps.getrepositorynames.GetRepositoryNamesMeta:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :51.55%
 * methodPercentCoverage :77.78%
 * complexityPercentCoverage :67.57%
 * instructionPercentCoverage :55.22%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-1.97%**

**Comment by matthewtckr** [comment]
Fixed checkstyle issue.  Added additional tests to GetSubFoldersMetaTest

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMeta.java
  engine/test-src/org/pentaho/di/trans/steps/getrepositorynames/GetRepositoryNamesMetaTest.java
  engine/test-src/org/pentaho/di/trans/steps/getslavesequence/GetSlaveSequenceMetaTest.java
  engine/test-src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMetaTest.java
  engine/test-src/org/pentaho/di/trans/steps/normalizer/NormalizerMetaTest.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found


Newly Broken Tests:
-----------------
org.pentaho.di.trans.steps.getrepositorynames.GetRepositoryNamesMetaTest.testRoundTrip: java.lang.RuntimeException
```
java.lang.RuntimeException: Error validating object_type
	at org.pentaho.di.trans.steps.loadsave.LoadSaveTester.validateLoadedMeta(LoadSaveTester.java:159)
	at org.pentaho.di.trans.steps.loadsave.LoadSaveTester.testXmlRoundTrip(LoadSaveTester.java:173)
	at org.pentaho.di.trans.steps.getrepositorynames.GetRepositoryNamesMetaTest.testRoundTrip(GetRepositoryNamesMetaTest.java:75)
Caused by: org.pentaho.di.core.exception.KettleException: 
Attribute object_type started with value Jobs ended with value All

	at org.pentaho.di.trans.steps.loadsave.LoadSaveTester.validateLoadedMeta(LoadSaveTester.java:155)

```





Unit test coverage change:
============
org.pentaho.di.trans.steps.getsubfolders.GetSubFoldersMeta:
 * branchPercentCoverage :39.47%
 * linePercentCoverage :68.25%
 * methodPercentCoverage :72.73%
 * complexityPercentCoverage :59.62%
 * instructionPercentCoverage :63.69%
    
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange : +0.08%
    
org.pentaho.di.trans.steps.getrepositorynames.ObjectTypeSelection:
 * linePercentCoverage :46.15%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :28.57%
 * instructionPercentCoverage :54.29%
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange : +0.18%
    
org.pentaho.di.trans.steps.normaliser.NormaliserMeta:
 * branchPercentCoverage :21.05%
 * linePercentCoverage :40.29%
 * methodPercentCoverage :60.87%
 * complexityPercentCoverage :42.86%
 * instructionPercentCoverage :38.27%
    
org.pentaho.di.core.lifecycle.KettleLifecycleSupport:
 * branchPercentCoverageChange : +8.33%
 * complexityPercentCoverageChange : +9.09%
    
org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * instructionPercentCoverageChange : +0.07%
    
org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * instructionPercentCoverageChange : +0.17%
    
org.pentaho.di.job.entries.ftpsget.FTPSConnection:
 * instructionPercentCoverageChange :**-0.23%**
 * branchPercentCoverageChange :**-1.56%**
 * complexityPercentCoverageChange :**-1.37%**
    
org.pentaho.di.trans.steps.getslavesequence.GetSlaveSequenceMeta:
 * linePercentCoverage :61.54%
 * methodPercentCoverage :71.43%
 * complexityPercentCoverage :68.18%
 * instructionPercentCoverage :55.90%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange :**-0.19%**
 * linePercentCoverageChange :**-0.27%**
    
org.pentaho.di.trans.steps.getrepositorynames.GetRepositoryNamesMeta:
 * branchPercentCoverage :50.00%
 * linePercentCoverage :51.55%
 * methodPercentCoverage :77.78%
 * complexityPercentCoverage :67.57%
 * instructionPercentCoverage :55.22%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange : +1.64%
 * linePercentCoverageChange : +1.97%
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange : +0.28%
 * branchPercentCoverageChange : +3.33%
 * complexityPercentCoverageChange : +1.85%

**Comment by matthewtckr** [comment]
I've removed GetRepositoryNamesMetaTest, as the Meta class does not read in the Object Type setting correctly.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMeta.java
  engine/test-src/org/pentaho/di/trans/steps/getslavesequence/GetSlaveSequenceMetaTest.java
  engine/test-src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMetaTest.java
  engine/test-src/org/pentaho/di/trans/steps/normalizer/NormalizerMetaTest.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.di.trans.steps.getsubfolders.GetSubFoldersMeta:
 * branchPercentCoverage :39.47%
 * linePercentCoverage :68.25%
 * methodPercentCoverage :72.73%
 * complexityPercentCoverage :59.62%
 * instructionPercentCoverage :63.69%
    
org.pentaho.di.trans.steps.textfileinput.TextFileInputMeta:
 * branchPercentCoverageChange :**-0.53%**
    
org.pentaho.di.trans.steps.normaliser.NormaliserMeta:
 * branchPercentCoverage :21.05%
 * linePercentCoverage :40.29%
 * methodPercentCoverage :60.87%
 * complexityPercentCoverage :42.86%
 * instructionPercentCoverage :38.27%
    
org.pentaho.di.trans.steps.replacestring.ReplaceStringMeta:
 * instructionPercentCoverageChange :**-0.07%**
    
org.pentaho.di.job.entries.ftpsget.FTPSConnection:
 * instructionPercentCoverageChange :**-0.23%**
 * branchPercentCoverageChange :**-1.56%**
 * complexityPercentCoverageChange :**-1.37%**
    
org.pentaho.di.trans.steps.getslavesequence.GetSlaveSequenceMeta:
 * linePercentCoverage :61.54%
 * methodPercentCoverage :71.43%
 * complexityPercentCoverage :68.18%
 * instructionPercentCoverage :55.90%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange :**-0.19%**
 * linePercentCoverageChange :**-0.27%**
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-1.97%**
    
org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * instructionPercentCoverageChange :**-0.28%**
 * branchPercentCoverageChange :**-3.33%**
 * complexityPercentCoverageChange :**-1.85%**

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMeta.java
  engine/test-src/org/pentaho/di/trans/steps/getslavesequence/GetSlaveSequenceMetaTest.java
  engine/test-src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMetaTest.java
  engine/test-src/org/pentaho/di/trans/steps/normalizer/NormalizerMetaTest.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found








Unit test coverage change:
============
org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * instructionPercentCoverageChange :**-0.08%**
    
org.pentaho.di.trans.steps.sortedmerge.SortedMergeMeta:
 * instructionPercentCoverageChange : +0.18%
    
org.pentaho.di.trans.steps.normaliser.NormaliserMeta:
 * branchPercentCoverage :21.05%
 * linePercentCoverage :40.29%
 * methodPercentCoverage :60.87%
 * complexityPercentCoverage :42.86%
 * instructionPercentCoverage :38.27%
    
org.pentaho.di.trans.steps.getsubfolders.GetSubFoldersMeta:
 * branchPercentCoverage :39.47%
 * linePercentCoverage :68.25%
 * methodPercentCoverage :72.73%
 * complexityPercentCoverage :59.62%
 * instructionPercentCoverage :63.69%
    
org.pentaho.di.trans.steps.getslavesequence.GetSlaveSequenceMeta:
 * linePercentCoverage :61.54%
 * methodPercentCoverage :71.43%
 * complexityPercentCoverage :68.18%
 * instructionPercentCoverage :55.90%
    
org.pentaho.di.trans.step.StepMeta:
 * instructionPercentCoverageChange : +0.19%
 * linePercentCoverageChange : +0.27%
    
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * instructionPercentCoverageChange :**-1.64%**
 * linePercentCoverageChange :**-1.97%**

**Pull request merged**
