### PR TITLE
[BACKLOG-5732] Add MDI support to XML Join

### PR DESCRIPTION
**Pull request by e-cuellar**

### CODE REVIEW

**Comment by e-cuellar** [comment]
@mdamour1976 Please Sir!

**Comment by mdamour1976** [comment]
@bmorrise

**Comment by bmorrise** [comment]
Running wingman: http://10.100.11.222:8080/job/wingman-ant/391/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-xml-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmljoin/XMLJoinMeta.java
  plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/xmljoin/XMLJoinMetaInjectionTest.java










Unit test coverage change:
============
org.pentaho.di.trans.steps.xmljoin.XMLJoinMeta:
 * instructionPercentCoverageChange : +4.29%
 * linePercentCoverageChange : +8.18%
 * complexityPercentCoverageChange : +21.43%
 * methodPercentCoverageChange : +33.33%

**Pull request merged**
