### PR TITLE
[BACKLOG-31101] Improve UX for adding parameters to the Transformatio…

### PR DESCRIPTION
**Pull request by ddiroma**
…n job entry

### CODE REVIEW

**Comment by buildguy** [comment]
### :gear: Build finished in 20m 43s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl engine,ui
```
### :warning: Failed Tests
---
#### :cloud_with_lightning_and_rain: 7 test(s) failed:
- **org.pentaho.di.ui.job.entries.job.JobEntryJobDialogTest.testEntryName**
```
    Could not load SWT library. Reasons: 
 no swt-pi-gtk-4623 in java.library.path
 no swt-pi-gtk in java.library.path
 Can't load library: /home/buildguy/.swt/lib/linux/x86_64/libswt-pi-gtk-4623.so
 Can't load library: /home/buildguy/.swt/lib/linux/x86_64/libswt-pi-gtk.so
 /home/buildguy/.swt/lib/linux/x86_64/libswt-pi-gtk-4623.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

```
- **org.pentaho.di.ui.job.entries.job.JobEntryJobDialogTest.testSetChanged_OK**
```
    Could not initialize class org.pentaho.di.ui.util.ParameterTableHelper
```
- **org.pentaho.di.ui.job.entries.job.JobEntryJobDialogTest.testSpecificationMethod_ConnectedRepositoryByName**
```
    Could not initialize class org.pentaho.di.ui.util.ParameterTableHelper
```
- **org.pentaho.di.ui.job.entries.job.JobEntryJobDialogTest.testSpecificationMethod_ConnectedFilename**
```
    Could not initialize class org.pentaho.di.ui.util.ParameterTableHelper
```
- **org.pentaho.di.ui.job.entries.job.JobEntryJobDialogTest.testSpecificationMethod_ConnectedFilenameZip**
```
    Could not initialize class org.pentaho.di.ui.util.ParameterTableHelper
```
- **org.pentaho.di.ui.job.entries.job.JobEntryJobDialogTest.testSpecificationMethod_ConnectedFilenameHDFS**
```
    Could not initialize class org.pentaho.di.ui.util.ParameterTableHelper
```
- **org.pentaho.di.ui.job.entries.job.JobEntryJobDialogTest.testSpecificationMethod_NotConnectedFilename**
```
    Could not initialize class org.pentaho.di.ui.util.ParameterTableHelper
```
  ---

|Total|Failed|Skipped|
|---|---|---|
|3579|7|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6994/1/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :gear: Build finished in 20m 42s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl engine,ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3579|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6994/2/testReport)|
|----|


:information_source:  _This is an automatic message_

**Comment by ddiroma** [comment]
@bmorrise @cseverino789

**Comment by buildguy** [comment]
### :gear: Build finished in 20m 31s with command:
```console
mvn clean verify -B -e -Daether.connector.resumeDownloads=false -amd \
-Daudit -pl engine,ui
```
:ok_hand: All tests passed!
 ---

|Total|Failed|Skipped|
|---|---|---|
|3579|0|7|

|[Details](http://wingman2.pentaho.net/job/projects/job/pdi/job/PR-6994/3/testReport)|
|----|


:information_source:  _This is an automatic message_

**Pull request merged**
