### PR TITLE
[BACKLOG-5733] - Add MDI support to XML Add - type conversion + fix error message

### PR DESCRIPTION
**Pull request by AndreyBurikhin**
@bmorrise please review

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-xml-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/addxml/AddXML.java
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/addxml/XMLField.java










Unit test coverage change:
============
org.pentaho.di.trans.steps.addxml.XMLField:
 * instructionPercentCoverageChange :**-12.29%**
 * linePercentCoverageChange :**-10.94%**
 * complexityPercentCoverageChange :**-25.00%**
 * methodPercentCoverageChange :**-25.00%**
    
org.pentaho.di.trans.steps.addxml.AddXML:
 * instructionPercentCoverageChange :**-0.09%**
 * linePercentCoverageChange : +0.41%

**Comment by bmorrise** [comment]
@AndreyBurikhin I see that were was a significant decrease in unit test coverage in XMLField. Can we add additional testing?

**Comment by AndreyBurikhin** [comment]
@bmorrise updated (load/save test was added).

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-xml-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/addxml/AddXML.java
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/addxml/XMLField.java
  plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/addxml/AddXMLMetaInjectionTest.java
  plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/addxml/AddXMLMetaTest.java










Unit test coverage change:
============
org.pentaho.di.trans.steps.addxml.AddXMLMeta:
 * branchPercentCoverage :35.71%
 * instructionPercentCoverageChange : +65.10%
 * linePercentCoverageChange : +59.07%
 * complexityPercentCoverageChange : +40.00%
 * methodPercentCoverageChange : +46.15%
    
org.pentaho.di.trans.steps.addxml.AddXML:
 * instructionPercentCoverageChange :**-0.09%**
 * linePercentCoverageChange : +0.41%
    
org.pentaho.di.trans.steps.addxml.XMLField:
 * instructionPercentCoverageChange : +30.17%
 * linePercentCoverageChange : +40.62%
 * complexityPercentCoverageChange : +40.62%
 * methodPercentCoverageChange : +40.62%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-xml-plugin/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-xml-plugin/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/addxml/AddXML.java
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/addxml/XMLField.java
  plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/addxml/AddXMLMetaInjectionTest.java
  plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/addxml/AddXMLMetaTest.java



Unit test coverage change:
============
org.pentaho.di.trans.steps.addxml.AddXML:
 * Instruction Change : **-.09%**
 * Line Change :  + .41%

org.pentaho.di.trans.steps.addxml.AddXMLMeta:
 * Branch Change :  + 35.71%
 * Complexity Change :  + 40.00%
 * Instruction Change :  + 65.10%
 * Line Change :  + 59.07%
 * Method Change :  + 46.15%

org.pentaho.di.trans.steps.addxml.XMLField:
 * Complexity Change :  + 40.62%
 * Instruction Change :  + 30.17%
 * Line Change :  + 40.62%
 * Method Change :  + 40.62%

**Pull request merged**
