### PR TITLE
[BACKLOG-7186] - Metadata Injection for Metadata Injection step

### PR DESCRIPTION
**Pull request by AndreyBurikhin**
@bmorrise please review

### CODE REVIEW

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/38/

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/40/

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman/49/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/metainject/MetaInject.java
  engine/src/org/pentaho/di/trans/steps/metainject/MetaInjectMapping.java
  engine/src/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java
  engine/src/org/pentaho/di/trans/steps/metainject/MetaInjectOutputField.java
  engine/src/org/pentaho/di/trans/steps/metainject/messages/messages_en_US.properties
  engine/test-src/org/pentaho/di/core/injection/BaseMetadataInjectionTest.java
  engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectMetaInjectionTest.java
  engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectMetaTest.java



Unit test coverage change:
============
org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.94%

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change :  + 1.64%
 * Complexity Change :  + .69%
 * Instruction Change :  + 2.43%
 * Line Change :  + 3.70%

org.pentaho.di.trans.step.StepMeta:
 * Instruction Change :  + .19%
 * Line Change :  + .27%

org.pentaho.di.trans.steps.metainject.MetaInject:
 * Instruction Change :  + .09%
 * Line Change :  + .13%

org.pentaho.di.trans.steps.metainject.MetaInjectMapping:
 * Complexity New Coverage : 100.00%
 * Instruction New Coverage : 100.00%
 * Line New Coverage : 100.00%
 * Method New Coverage : 100.00%

org.pentaho.di.trans.steps.metainject.MetaInjectMeta:
 * Branch Change :  + 6.72%
 * Complexity Change :  + 11.93%
 * Instruction Change :  + 5.79%
 * Line Change :  + 7.67%
 * Method Change :  + 21.41%

org.pentaho.di.trans.steps.metainject.MetaInjectOutputField:
 * Complexity Change :  + 33.33%
 * Instruction Change :  + 20.00%
 * Line Change :  + 22.73%
 * Method Change :  + 33.33%

org.pentaho.di.trans.steps.metainject.MetaInjectOutputField.DataTypeConverter:
 * Complexity New Coverage : 50.00%
 * Instruction New Coverage : 50.00%
 * Line New Coverage : 50.00%
 * Method New Coverage : 50.00%

org.pentaho.di.trans.steps.randomvalue.RandomValueMeta:
 * Branch Change : **-2.17%**
 * Complexity Change : **-2.17%**
 * Instruction Change : **-.15%**

org.pentaho.di.trans.steps.uniquerows.UniqueRowsMeta:
 * Instruction Change :  + .18%



Integration test coverage change:
============
org.pentaho.di.trans.steps.metainject.MetaInject:
 * Instruction Change :  + .07%
 * Line Change :  + .10%

org.pentaho.di.trans.steps.metainject.MetaInjectMeta:
 * Branch Change : **-.32%**
 * Complexity Change : **-1.81%**
 * Instruction Change : **-1.16%**
 * Line Change : **-1.12%**
 * Method Change : **-1.92%**



Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectMetaTest.java

1. Message: '>' is followed by whitespace. at Line: 116 Column: 91

**Comment by AndreyBurikhin** [comment]
@bmorrise the violation was fixed.

**Pull request merged**
