### PR TITLE
[BACKLOG-7185] As an ETL Developer, I want Merge Join to offer Metadata Injection

### PR DESCRIPTION
**Pull request by AlexanderBuloichik**

### CODE REVIEW

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman/9/

**Comment by lucboudreau** [comment]
Head build failed with return code 1

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman/11/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f engine/build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  engine/src/org/pentaho/di/trans/steps/mergejoin/MergeJoinMeta.java
  engine/test-src/org/pentaho/di/trans/steps/mergejoin/MergeJoinMetaInjectionStep.java



Unit test coverage change:
============
org.pentaho.di.core.auth.core.impl.DefaultAuthenticationConsumerFactory:
 * Branch Change :  + 7.14%
 * Complexity Change :  + 7.69%

org.pentaho.di.job.entries.sql.JobEntrySQL:
 * Instruction Change :  + 1.64%
 * Line Change :  + 1.94%

org.pentaho.di.repository.kdr.KettleDatabaseRepositoryCreationHelper:
 * Branch Change : **-1.64%**
 * Complexity Change : **-.69%**
 * Instruction Change : **-2.43%**
 * Line Change : **-3.70%**

org.pentaho.di.trans.steps.excelwriter.ExcelWriterStepMeta:
 * Instruction Change : **-.08%**

org.pentaho.di.trans.steps.symmetriccrypto.symmetriccryptotrans.SymmetricCryptoTransMeta:
 * Branch Change :  + 3.33%
 * Complexity Change :  + 1.85%
 * Instruction Change :  + .28%

org.pentaho.di.trans.Trans:
 * Branch Change : **-.10%**
 * Complexity Change : **-.14%**
 * Instruction Change : **-.09%**
 * Line Change : **-.11%**



Integration test coverage change:
============
org.pentaho.di.trans.step.BaseStep:
 * Branch Change :  + .30%
 * Complexity Change :  + .18%
 * Instruction Change :  + .13%
 * Line Change :  + .08%

**Comment by lucboudreau** [comment]
Are you sure the build picked up this new test class? It does not end with wither of Test or IT, so I think the test won't be run.

**Comment by bmorrise** [comment]
@AlexanderBuloichik Can you rename your test class per Luc's comment?

**Pull request merged**
