### PR TITLE
[PDI-16436]- Issues with 3 steps when exporting - importing in an EE repository

### PR DESCRIPTION
**Pull request by ArtsiomYurhevich**
Issues with several steps during exporting - importing in an EE repository : directories are not updated properly. 
-Removed hardcoded step name checks (like stepMeta.isMapping() or stepMeta.isTransformation() ) which identify whether we should update step inner directories or not 
-Added interface which means that a step has directory(ies) to another transformations(jobs)
Affected by the issue steps : JobEntryJob, JobEntryTrans, Mapping, SimpleMapping, SingleThreader, TransExecutor, JobExecutor, Metainject, Pentaho MapReduce

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@pamval @mbatchelor can you please take a look?
thanks.

**Comment by mchen-len-son** [comment]
@pamval @mbatchelor can you please take a look?
thanks.

**Comment by mbatchelor** [comment]
Please rebase this PR.

**Comment by ArtsiomYurhevich** [comment]
PDI-16436 will only be merged after code freeze (and branching happens)

**Comment by ArtsiomYurhevich** [comment]
@mbatchelor Could you please take a look?

**Comment by mchen-len-son** [comment]
@bmorrise @pamval @mbatchelor can you please take a look?
thanks

**Comment by mchen-len-son** [comment]
@bmorrise @pamval @mbatchelor can you please take a look?
thanks

**Comment by ArtsiomYurhevich** [comment]
@pamval @mbatchelor Could you please take a look?

**Pull request merged**
