### PR TITLE
[PDI-14441] Fixed issue with ignore empty file on get xml data step

### PR DESCRIPTION
**Pull request by bmorrise**

### CODE REVIEW

**Comment by bmorrise** [comment]
Running wingman: http://10.100.11.222:8080/job/wingman-ant/396/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f plugins/kettle-xml-plugin/build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/getxmldata/GetXMLData.java










Unit test coverage change:
============
org.pentaho.di.trans.steps.getxmldata.GetXMLData:
 * instructionPercentCoverageChange :**-0.39%**
 * branchPercentCoverageChange :**-0.37%**
 * linePercentCoverageChange :**-0.20%**
 * complexityPercentCoverageChange :**-0.17%**

**Comment by bmorrise** [comment]
@mdamour1976

**Comment by lucboudreau** [comment]
No tests?

**Pull request merged**
