### PR TITLE
[PDI-16891]-Incorrect remainder in division of numbers in Calculator step

### PR DESCRIPTION
**Pull request by denisprotopopov**
- fixed. now source values convert to the target data type before calculation

### CODE REVIEW

**Comment by denisprotopopov** [comment]
@bmorrise @pamval @mbatchelor please review the changes

**Comment by denisprotopopov** [comment]
@mbatchelor this error existed before my changes

**Comment by mbatchelor** [comment]
Re-running Wingman on this PR.

**Comment by denisprotopopov** [comment]
@bmorrise @pamval @mbatchelor please review the changes

**Comment by denisprotopopov** [comment]
@bmorrise @pamval @mbatchelor please review the changes

**Comment by denisprotopopov** [comment]
@bmorrise @pamval @mbatchelor please review the changes

**Pull request merged**
