### PR TITLE
[PDI-8934]-BaseStep rowListeners - Thread Safety Issue. Removed synch…

### PR DESCRIPTION
**Pull request by ArtsiomYurhevich**
…ronized blocks and changed implementation of step listeners to CopOnWriteArrayList

### CODE REVIEW

**Comment by ArtsiomYurhevich** [comment]
@mbatchelor , @pamval Could you please take a look?

**Comment by pamval** [comment]
Maybe there was a discussion about this case that I missed, but the changes here do not follow the suggestions by @mbatchelor  on the jira case.

Not particularly happy about using CopyOnWriteArrayList since it's not clear to me how many writes we have on that list compared to reads. Who writes to that list?

**Comment by ArtsiomYurhevich** [comment]
@pamval Adding row listeners is usually performed only during initialization/preparing stage of  trans/job execution and then during execution stage we only read from the collection. So, I think, CopyOnWriteArrayList is appropriate for this purposes

**Comment by ArtsiomYurhevich** [comment]
@pamval The changes do not exactly follow the description of the issue because the issue was created long ago in 2012

**Comment by pamval** [comment]
@mbatchelor please review this change.

**Comment by mbatchelor** [comment]
I searched the code for mutations of the row listeners list (who calls either addRowListener or removeRowListener) and as far as I can see, the CopyOnWriteArrayList should not be a performance burden on normal execution. It does run the risk of making tests run slower though because we have a *huge* amount of unit and integration tests that rely on the row listeners for validating results. That said, any case we avoid any kind of synchronization without impacting usual runtime performance is a win.

**Pull request merged**
